---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-cluster
  namespace: flux-system
spec:
  interval: ${flux_gitrepo_interval:=10m0s}
  ref:
    branch: ${flux_cluster_branch:=develop}
  secretRef:
    name: ${flux_cluster_repo_secret_name:=github-read-flux-cluster}
  timeout: 60s
  url: ${flux_cluster_repo_url:=https://github.com/lukasfriedhoff/flux-cluster.git}
