---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-apps
  namespace: flux-system
spec:
  interval: ${flux_gitrepo_interval:=10m0s}
  ref:
    branch: ${flux_apps_branch:=develop}
  secretRef:
    name: ${flux_apps_repo_secret_name:=github-read-flux-apps}
  url: ${flux_apps_repo_url:=https://github.com/lukasfriedhoff/flux-apps.git}
