apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: logday
  namespace: flux-system
spec:
  interval: ${flux_gitrepo_interval:=10m0s}
  suspend: ${logday_repo_suspend:=true}
  ref:
    branch: ${logday_branch:=develop}
  secretRef:
    name: ${logday_repo_secret_name:=github-read-logday-disabled}
  url: https://github.com/lukasfriedhoff/logDay.git
