apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-replica-policy
  namespace: flux-system
spec:
  interval: ${flux_kustomization_default_interval:=1h0m0s}
  path: ./overlays/staging-3vm/longhorn-replica-policy
  prune: true
  retryInterval: ${flux_kustomization_default_retry_interval:=10m0s}
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  timeout: 10m0s
  wait: true
