apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-config
  namespace: authelia
data:
  configuration.yaml: |
    server:
      address: 'tcp://0.0.0.0:9091'

    log:
      level: info

    theme: dark
    default_redirection_url: https://nextcloud.h4xx.io

    jwt_secret: 'file:/secrets/jwt_secret'

    authentication_backend:
      file:
        path: /config/users_database.yml

    access_control:
      default_policy: deny
      rules:
        - domain: 'auth.h4xx.io'
          policy: bypass
        - domain: '*.h4xx.io'
          policy: two_factor

    session:
      name: authelia_session
      same_site: lax
      secret: 'file:/secrets/session_secret'
      expiration: 1h
      inactivity: 15m
      domain: h4xx.io

    storage:
      encryption_key: 'file:/secrets/storage_encryption_key'
      local:
        path: /config/db.sqlite3

    notifier:
      filesystem:
        filename: /config/notification.txt

  users_database.yml: |
    users:
      admin:
        password: "$argon2id$v=19$m=65536,t=1,p=4$c2FsdHNhbHQ$w7omX3vBXL9esSwSxEt3G5UpiRaY1oWXcnZ6+QcmGeM"
        displayname: "Admin"
        email: admin@lab.h4xx.io
        groups:
          - admins
