apiVersion: v1
kind: ConfigMap
metadata:
  name: base-config
  namespace: flux-system
data:
  ceph_csi_suspend: "true"
  longhorn_suspend: "false"
  longhorn_default_replica_count: "1"
  longhorn_storage_minimal_available_percentage: "10"
  longhorn_storage_over_provisioning_percentage: "200"
  longhorn_storage_reserved_percentage_for_default_disk: "10"
  longhorn_ssd_storage_reserved_bytes: "0"
  longhorn_backup_target: ""
  longhorn_backup_target_credential_secret_name: ""
  default_storage_class_name: longhorn-ssd-rwo-1r
  default_sts_storage_class_name: longhorn-ssd-rwo-1r
  s3_storage_class_name: longhorn-ssd-rwo-1r
  attic_storage_class_name: longhorn-ssd-rwo-1r
  attic_postgres_storage_class_name: longhorn-ssd-rwo-1r
  nix_remote_builder_storage_class_name: longhorn-ssd-rwo-1r
  valkey_storage_class_name: longhorn-ssd-rwo-1r
  nextcloud_app_storage_class_name: longhorn-ssd-rwx-1r
  nextcloud_data_storage_class_name: longhorn-ssd-rwx-1r
  immich_ml_cache_storage_class_name: longhorn-ssd-rwo-1r
  immich_uploads_storage_class_name: longhorn-ssd-rwo-1r
  immich_postgres_storage_class_name: longhorn-ssd-rwo-1r
  immich_redis_storage_class_name: longhorn-ssd-rwo-1r
  immich_photos_ml_cache_storage_class_name: longhorn-ssd-rwo-1r
  immich_photos_uploads_storage_class_name: longhorn-ssd-rwo-1r
  immich_photos_postgres_storage_class_name: longhorn-ssd-rwo-1r
  immich_photos_redis_storage_class_name: longhorn-ssd-rwo-1r
  matrix_postgres_storage_class_name: longhorn-ssd-rwo-1r
  matrix_synapse_data_storage_class_name: longhorn-ssd-rwo-1r
  matrix_synapse_media_storage_class_name: longhorn-ssd-rwo-1r
  matrix_bridge_storage_class_name: longhorn-ssd-rwo-1r
  arr_config_storage_class_name: longhorn-ssd-rwo-1r
  arr_media_storage_class_name: longhorn-ssd-rwx-1r
  arr_downloads_storage_class_name: longhorn-ssd-rwx-1r
  moonlight_config_storage_class_name: longhorn-ssd-rwo-1r
  monitoring_storage_class_name: longhorn-ssd-rwo-1r
  logday_repo_secret_name: github-read-logday-homelab
  logday_repo_suspend: "false"
