apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets.yaml
  - ../../base/
patches:
  - path: cluster-patch.yaml
  - target:
      kind: Kustomization
      name: kustomizations
    patch: |-
      - op: replace
        path: /spec/path
        value: ./overlays/homelab/kustomizations/
