apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - collabora.yaml
  - ceph-csi.yaml
  - cert-manager.yaml
  - cnpg-system.yaml
  - nextcloud.yaml
  - traefik.yaml
  - authelia.yaml
  - cloudflared.yaml
  - external-dns.yaml
  - reloader.yaml
  - monitoring.yaml
