apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - immich.yaml
  - immich-photos.yaml
  - matrix.yaml
  - collabora.yaml
  - ceph-csi.yaml
  - longhorn-system.yaml
  - cert-manager.yaml
  - cnpg-system.yaml
  - nextcloud.yaml
  - traefik.yaml
  - authelia.yaml
  - cloudflared.yaml
  - external-dns.yaml
  - reloader.yaml
  - monitoring.yaml
  - media.yaml
  - logday.yaml
  - object-storage.yaml
  - nix-cache.yaml
  - status-dashboard.yaml
