apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infra/ceph-csi.yaml
  - infra/longhorn.yaml
  - infra/longhorn-recurringjobs.yaml
  - infra/s3.yaml
  - infra/nix-cache.yaml
  - infra/attic.yaml
  - infra/nix-remote-builder.yaml
  - infra/status-dashboard.yaml
  - infra/cert-manager.yaml
  - infra/cnpg.yaml
  - infra/letsencrypt-issuer.yaml
  - infra/valkey.yaml
  - infra/nextcloud.yaml
  - infra/immich.yaml
  - infra/immich-photos.yaml
  - infra/matrix.yaml
  - infra/media.yaml
  - infra/moonlight-web.yaml
  - infra/collabora.yaml
  - infra/traefik.yaml
  - infra/traefik-resources.yaml
  - infra/coredns.yaml
  - infra/cloudflared.yaml
  - infra/external-dns.yaml
  - infra/authelia.yaml
  - infra/logday.yaml
  - infra/reloader.yaml
  - infra/monitoring.yaml
