apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infra/twofauth.yaml
  - infra/ceph-csi.yaml
  - infra/cert-manager.yaml
  - infra/cnpg.yaml
  - infra/letsencrypt-issuer.yaml
  - infra/valkey.yaml
  - infra/nextcloud.yaml
  - infra/collabora.yaml
  - infra/traefik.yaml
  - infra/coredns.yaml
  - infra/cloudflared.yaml
  - infra/external-dns.yaml
  - infra/authelia.yaml
  - infra/reloader.yaml
  - infra/monitoring.yaml
