apiVersion: v1
kind: Secret
metadata:
    name: attic-postgres-backup-credentials
    namespace: nix-cache
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:TOwVh4znZsituBwGHmUHDFDokYFXYC+dpTFIPQ==,iv:pz5dZVWFatylmXq7nCzAp73oT5HT230gjWkmfRgOnOA=,tag:FCQOUEqnqywZvDv6aBS0Jw==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:+mnmbNho9UyQdfPejqm7j95IOBajNYpAaj7WccEq0TKpW0NbFwgSbBWO0pBbkDbdqIdanMejh6U=,iv:YCTf73ExPrjMNOpMjbSqTkg8rkXvI4cefaWxINoS6gY=,tag:2zLx4ofj+tUdK3ZC1EHlZg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Ewx7zl3xhblQjv1hqHt7mSarmhneR0/6G0X7cYt71pZu2k0QhF/ukdbE2ZpnHNDBRvsPlReALpE=,iv:o3rwlqKqL+qZYA5IpU1bjjrlBXonJA91WYBwy8xvT3U=,tag:RJJrPc9A0J/PqV9v86q9eA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeFdZcnIxUTU5N1c2aThO
            M1UxU3lxNHU2MkRscEsxd0RMT0lrUEY1VFVvCk9pVURZZUVHc1RodFd2Qnk3S0Fk
            ZzBiMDBVUVhndlZ1a3ZoYVYxUkxRaDQKLS0tIGMrMiszNDFhUVROWnBGdkRvTHQy
            UnpWTE14UjZYSlZ3cGV2TC8yckJ6eW8KYZyDZiWYTUy6yvn+gPVpYXM54HKahzqN
            afJzwOz4WZib/JJUU2A/5Kv44yh4pGOX7mH8aERIWAD+RZphSYpI+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYS9FdXB3QlpXNWQyNWNQ
            SnptQUM1a2UrZnB2Q2ZFUmxvODNIOFlGSG5rClQwU3ZqVlFzd2JVTUtBR3ZndjRq
            dzdyMDA1dEJERXhEVTR2NSt0T1BiRFkKLS0tICtZSmZIN2RCT3V5bTZJUW5PdGc5
            NjhKc2xVb21uNmFGdnhrZ1BJWGRBeHMKjI/MInqrciQrWtxIelyMoa/SGmh6LT2z
            bVsHQ5xNFww74deHv7Gkssu74l/e/LefXgo63OzMqL0guPIYReNNiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-06T21:42:20Z"
    mac: ENC[AES256_GCM,data:QFLqL8UYtE7rEzdQiZ3Uw7CdwLo8ZOKCtl7PjYzTSNfEvYWC/H7XT4EeVIa9v6DYF6CZoe9RHrtj2DMZE38tNJYiAuHVC0IQ1B1ZmOPwp4EGiC06HFN8qHeZsUL0a88TG6KT4r7VLpzCjMIPUrQHO5c9zAkC1B+dHvNMDdZsPuc=,iv:T1JCeSnGIJFnoifnys8BQogj8vYe8sWEo+K+NiwLbAs=,tag:BoYdZQ2pavPNm8qheQz6Ag==,type:str]
    version: 3.13.1
