apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-credentials-staging
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:TywZ3SrEN2vEoyM3QWeJ/S2LQ2pzazTk+jvQXw8csuupD5TAxtemjNOi8HmCmZ1dvDhYYx+GJSzdjZNVL7xhDSsB3BcenyL3oyF2Gk/AM/+v0C0+ZcOGabmjyz3GjJgMtxYcpvmO0NGZKVekUvR2Mv0BpApggOTyX6+hUUIYA6Yvtl9s9t0EtDE7Ik8CLULPdxxKJ3RsOtxakRVu/Egn+ngpiWE2zPrb2JJPKLssecnQv3R9,iv:s8TT/k7VOEEkLPKiBzjPqzoKhTZkfQnxIFQc8AWPZnQ=,tag:6RtThiDBpiGqcPgizDsHcg==,type:str]
    credentials.json: ENC[AES256_GCM,data:6so9675tehtVck7ZlaYNz9pcCpSMAiMUy4gpFB+HayR5iiTi8nJzHNDQC8ZN6X3DiBVWuX0CtzzsiFu5a9LuUHz8kP766VIp9RowKDLBtn3m0gNFeTFzS8d6N5Nmrc0G/L+FqXoPErRwd8QLE1CuZUqLqlJdqnq6IdbsAGWw1QJfINoUqVpQAjSFj6OMQKPmQaCrK3/Ij3NWlJkWXQzZtjiegaGtt99A4VA8470DP24=,iv:b5fEj1TOgGSE6l8ljvv+7KXGb9DSk0Ta+VE9fhmdYIc=,tag:hNg2tjkAElgS8hxLDlhXKQ==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYnZ0L25KaHBpS1gzNDVC
            STM1aG5qdXo3NTQyWGoyanhCS2hiUEg2eW5jCmZ1MWs5Q0dza0hGQ2hHZE1mZGdF
            ZEhJTXYwNGVuVjJRQ0xDVnNTbTVlOTgKLS0tIFlreHJQWkRhNTlNd1FCNEk5ZTgw
            b3FKV1d1cmlOWWI3ZEM2VEhkc3BNZk0KBA4LvTEsUHW1hfEb9XfB9umf6+XyKiYD
            ekriZsghHyNNDpf8WJpVpG4Q0Ph/as2LleGCy2qi5dA52foK5sjE2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T22:53:58Z"
    mac: ENC[AES256_GCM,data:6zF5gVIiZkxUTPKqTxli5Yq5Pb7a+PfseQgc/lH8DZiUQumDDGtw8fDv1VPrz+FgftZK1j/QHRtuZgc2ZrRRZx0fpbXfwwqRykHagJoLaYayJJDSAL+rUsTOuoQLyNr++pXQYtp3o3DxCdqc9MqDzCGj3wYquGsmU7IEFkwciRM=,iv:J9ObTpwNydpk+lwQy0oxBxNR/NlW5X9mVruPtoVzuAQ=,tag:Y4EqlEdY+iNy1J+Hd1XTJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
