apiVersion: v1
kind: Secret
metadata:
    name: github-read-logday-staging
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:s5YkLka7U5Swh1wttzA=,iv:WQEO2ORImxH5zWb86O+jZ3RFyuPPbdTrDStYjQRIo9g=,tag:4thozZuN/Zl9lNrxHAABOg==,type:str]
    password: ENC[AES256_GCM,data:v3Ypl1OFTdxJ0ttChNZqRRBERPW9UjUGPw8dqC0s/QQsbgRphTzj4w==,iv:sIogC8sz8cgIXxJjOVcl3RQ8FAV/CJaDOfz/Q2DLbok=,tag:tjy478HaCpYjYowBTLSDgQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTVJoU3krbzh1MWJnNTg2
            MFc0V1BGdzRsUkJGa3BHNndSZjhFaHNPbVU4CmFKcnlUK05lNEdJYUlTWFF0Ujlx
            Y1V3TzRabDdrNHR2VDN5NWFMTmNHQjAKLS0tIDV2bUxyaTRweVRMY0dVbm0xV251
            bTFQa1czTTgzeXR5aFpiN3J5Zi96VFUK4RylYntuW5h2OIETZ1dhOKNt17lqAHwM
            NZWhuyMx+MuUsfWNZdkj5wY7q5CuaNE6Qd1BzfysywpSv47HsOjUsw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSS2VJVWJiYTJlQ0FTMXJi
            cnJaOW5qYU5vTjBSMnVZUmpqVC9QY1lhK0FBCnh0dEgweDZmdFlvK0VXZjRPSDJp
            QUtqQk9TN1piS0FDekh5UmF6bnlOQ3MKLS0tIDZpVjlyTDc1bHhNaWgrMFNMTU9X
            S2N1cUwzaG5BcUY4U3V3Ujc5bjdvR0kKSMY7XBYvt8x4b6nkHq7WG9EYj4847Dic
            oYs2K0o6TJAF9L3y2Wwf+rnc4lfb0bkFsSQbGMfm2rq2k4CHobXvgg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T13:07:53Z"
    mac: ENC[AES256_GCM,data:+bsfOGR0Sb9OnYXDNJRrSxYhz8aPMNRzTvOOEm8bnU5okbAchxN34Uqvg4nPJPn2FyGGvwZOw2y95zh1rvDvFRRNg3s8k5ThKKXAFMj0JipDioFARviKe5CKJU8tUnYBmDzz1tfX/s49W/YKsYZvO4ABCsD6EzmS/NqfzP9nQUY=,iv:d7Kum3X8q/uiycHVphG74kPMa2ziwuyqrFVTEjBOW0o=,tag:3WMm+S4GJa/KSShP4Ile0g==,type:str]
    version: 3.13.0
