apiVersion: v1
kind: Secret
metadata:
    name: github-read-github-staging
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:HZjEwVHDHkm+uMYhRig=,iv:kHTZ2uH4fn04yTbvfGiTyRqW3LajWB4nCPQdvl+nOZ0=,tag:MqohRsY09CNeRoiqHwn0PQ==,type:str]
    password: ENC[AES256_GCM,data:KAh7Vdq6FVUQoCHhbyOjFJhmx0otsQkiGHdgX3795oysdTTnbXqLpZn50YAM35amt0SGDk7TppFZJBmONijWWNfh7az9e5wBDSAbsfztln2n9G6dKVUVW4gwDKdC,iv:kgRvjOL8F7nyhpR5Hxqh/Ib3JXlRgwa3Wa+RClxPJH0=,tag:ChWdxpiCeM+RdF7S9boEmQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcUtSZVB6dDJGU2NKdk5O
            NFN2K0xnbDlhaG81TUt3d1R3ajRUNVZMVXlNClFCUWM2aWpTdWRTY2hWeURjSU9B
            K0ZWSjZoS1BFcFVOVXh3K3UxbUhGb2MKLS0tIFE5Q0o3dlNSZjZNc1dLcWpDc3Zy
            V2lzQWJSOUg2Mytmamh4QnlpRjh2YTQKevh5i3ClR1UkSDcQyB/9wrsrQunGcXvG
            qMz56G3KDqO0dOvkg4GQHfKtqj4wtV1w7vSR4Al0KmSP/djg/+gp6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjQUF1TmNSY003ZXBWRVdN
            WFRFbzVMZG1YTkhodnM5MExHOU8xYVd4dTNFCnErUjVlWlp6WnMwT0RONzhCMXlX
            ZDV6NlY2UkR4eS9BbWhMU05JU1VmOEkKLS0tIHFVaEdQUW5pMU9VTXFOWTZUWmFR
            OGU1UXNXSWNYd0VWeEpRNmVRZ0g3aTQKJQ7jcr4D/vW3JzsBj9gkxFiclr4/sgi5
            WWzl7ZIofC+X/Lig6HeA85ZwM+n4Ba3LBWlqaf9PqvZZF+vcIe92RA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T16:33:56Z"
    mac: ENC[AES256_GCM,data:jwq1TfGHjluiKkr4/GNg0p1RtlGtjCCWlqCnDJNbO18jS8/nvqjit31cSzxEkfmtTbfxINZgq3ZAVF2yBjLAE6yPyOkiZbGVZ1UtFFXkQvcsf07Y1fWSdgf/MwurjisI/W/LUnV6azzJN/nvrldj71bvS1C5S+eZ7shepPUV4uE=,iv:2A4FYjeqpyw1ibFL9WWehIQ+q1XN5d0guclXIpBWspE=,tag:MZjAHwtXiH+2JOJCyfhgwQ==,type:str]
    version: 3.13.1
