apiVersion: v1
kind: Secret
metadata:
    name: ${hydra_admin_secret_name}
    namespace: ${hydra_namespace}
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:E6+2g9a2B4SrkNrxRXwCmCwNcAB93wCIABo62Hb8PEmo9JFx3SQuG74=,iv:WfV9vJc2xq+GZMPT8r6YrqtZnl6e1MCdO1fhnvR3WUU=,tag:fm6jBqHrpAQttECln+Zlmg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUWx2NU5pMkwyTkV1aith
            Rk9JN2d3OCtuN2lBaTJvQ1JjQTdwSWRnaFhvCk0wWTBhY1pmcXNTSFRnUnMybWR3
            UlBjN0FGaDEwSkRUcmppQ2dOYzlFVTQKLS0tIDNtMEJ6MVpwVzUzempvbVVvTlRa
            anh6anNlbXZ3NzU3bGUwSzNHMnBNS0UKZx6EHsLqfLa443WKWEfH+GnZjpUgHofz
            pk7IfVEd1RasBFFXuzwdkcwvcs2U77n9tfPpkYwXWt+rJUqRACZoYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4K1BVdm1WZDVWaW9xLzdR
            VDBMTHFHRmxsK2RMei9DcmV6T2FTcWovOGw0CmFROXV5VUlpUVBzUmVxUWdxVS96
            NDVnMlBuZ2pFa1pRdjBkRnFUT1Ftb2cKLS0tIFN6WloxcFJKZE51QnAxREtyUHlU
            ZGJWdzdnRUtWT2lXRFp0NXJQQUFrSm8KDBxtPsPHBrJno7lcs/qZ1/jR6f6ld5nT
            rocfAi3TwpCXR90sZoFnZP7WcrIEaP3nx9rVT3Sqg6ohOwtEWcg3+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T11:20:34Z"
    mac: ENC[AES256_GCM,data:gjI1niMu25AzENcIeSeHWlFS67vfKCQEAkD7hSlL32SjefoAsoT1rZR8cwHU8MfG8O9zF+v7HMqO/W3hBIn7Elp/c5mOXoqxD9Odztr3zZVS62CLslwWBXorzcNfuc1QL7o7Kw2lZXgVBOmBeKhzMUNAeCV0WENt0mDJLgbKFZQ=,iv:w1Cbydqw9Ij5sGPrPIcsnvkj1EqKtdxVgFP5qC+K3n8=,tag:dyyIA66Z15ZwBSzBx4Qpdw==,type:str]
    version: 3.13.1
