apiVersion: v1
kind: Secret
metadata:
    name: ${hydra_attic_upload_secret_name}
    namespace: ${hydra_namespace}
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:tPFNhpEj2+evQonbbZMyXwjGMb63coODtJl0QFf9Bi3TXhBbeioXvclOml4+F0CbkNFVadSdkFdvMdJq1CQAzeUiUoi9P3DT6OHMPfl/hhT4Cywzau8/heWv/ztl7qdi0Cyt6B60yZmWjFgQpKjGD0511dBQozPt5NyD/6fvZYGsBTJ8KRkHVcZoFT+8OC5uaOkVqONYuBM0b5ga6r+4D7uczUZiUOLVfzN99USg6JYnCYC7Gs5uE3wtPgMvRj5uYZdiTh1mgigDVrlHkomR6DfP5yeRfVumqXNmiWNQT3auJnf0bRrA+lW7YGUY1EEM0eR49ySYDf3s4A5sc/6BHQCnE8lxuhqLMK5x1vTw9d+F1VaLap0P7NGoYue97KzNOvan+ixzJw+UfJS5YzYsG/En8+Sed62s9pneORhJ/Ik73/spkKol1gpFxmSBohd34kkgh789M+GEtSKtBYg4OKGl5wpH1l/JTZw5uMliTgUfgCCW3mqhWT66NriCR6/71IJ7nV848IWvSaPogXMYJEqX0A7NWEucm9Z4XYwWNId8ie219kbiGB3gLHv84YIJnVsKTnvBZTCCHyrOfliYJ+sMk0KEJ4yKuatTh5jUouIgIT3zov89L7jxK8Q3LMWyyE51GfM1jORUR0upcxLnqUQ0GLN3AIX4P0sYqDAS6LMleNLomOrKoCrFQWvj2KWBpd+WoI+L0ABjHaK9om8K4FyVRy3kHToSzXweQGisGmxCAEN+p54+eYXsT5DqmdH1ZxJAY4Bfq2j+SGcKMUkr5VFdBvViMpfcnXe23yDzTHipq86csHdNQPUxD+c0nSmIz/moVghkIvt3+48f2y1hiZEhOwUF2PdY0+1THHEBC0Yz+YZtxbNm7SFMSx/9IOBXhQzVkqxstNOhwRtWVkRFJKZNhAMv08K4HeAx7o0RWlgZ4qwB0Hiihx15qvMdqJxkxvMA2ifj/yvx9bdqDeMcPIwp16MD0GmRhW94LeUxqtHH6KLZ9VJxtNAVHkOdH9jUoq4IBJIe/mBL1lXaLEHQHmN2cM8UaHe1jAJXGbUGHmDaQWA+T4+aFXEE5NAZ0bwCJd/QDZPpGiCpQEH73A+lWWxjZ6PdUenIJFVbHGpDWeVqJPZSXSteIKMwZN/QpNs6YhE51LIC1j8prRcyYa4fDqY=,iv:RVgzQhdGXR00FqmA/6qXcJ61YdyS2BcQIl0ELFAqSw0=,tag:jRl3FUC4QNfyD3welIqKPA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWlNuQkR4K3hHeER3eTk5
            ajQwY3IvS0Y5dGNJSzJUVWxBN0hpNmlDbDNNClRsVDlQL2laM2ljRnE5bWVrZEZq
            YURMNUgxSVNDY094NlFYd3Jid1Y5WncKLS0tIGRsOGhYRkFuTTNvN0M5aWhSQ1Ay
            UFMwOEVJRG1kZlEzZEh3UFg5cGJ1SXMKJoXCU1GfFGJxwB3PEMOTUVw+bE5gwUKq
            g87tC3DZmioIGpUjIGeHHUkHI/JpXp7UTSF+Paa350O/Xb60gRr+lg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1K2IrOTBoYytobThHeDBO
            a1ppNEt2NVIrbjN6S2VlRHlCNmR5azQxZ0dvCmpGQmRDd1MrczBnREdNNVJQYnBF
            dGVHS1Bzd0dsZnVxZDVlWDFNMFV5L1UKLS0tIDFvNlRCaXNFaEF0VzdwNUV3amVK
            cGRmaFpkODg4ZkJKSUNzbzlnWEJQK00KMClnoHTS/WKKyyKdPXLNjvsK63dwSg28
            bZC3A/jiSA+Oq4gAc2XfIqjTQ7dWEIxLQUF60CucdLIJ5j3/QBzVBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T22:35:21Z"
    mac: ENC[AES256_GCM,data:uwlxkWZaqqp6+7aYuF1bF77E6zUBsoWeu3DmK8YqPKMkfWuof7MUkDMoBIB1Jpz6yE23/CuGH2hrojtG3g63/QW7J+lJvaaR0KQ+HMDaARTiuEFxYlW3CDwT6ZAVKUSEUuF7MdZi7I7nsiR6ZQ72e85n+fCTgDQ1DVksQb5ppUY=,iv:19rRctAnLWWd7fV8gS2GmEZMl5AZrSElP+OF6hhqmRc=,tag:VidmeaFORJMS1F408+mrsA==,type:str]
    version: 3.13.1
