apiVersion: v1
kind: Secret
metadata:
    name: immich-postgres-app
    namespace: immich
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:+vfVJeTB,iv:dcQ0UCdmX2X2ZXUUGwSpd4EzF2JZSf6qSpuU28r1v9Q=,tag:iHNF7PhSJMsb54HBia5dTA==,type:str]
    password: ENC[AES256_GCM,data:aPL+HXlHCwm9AF+44U/5ouq579d/9oMr6q7BttH1yfP/KI0QaE1WZgE5lCOMqV4H,iv:4XUbJ5J9lAOy9RkclBDgas6Rb1tgwOHgHdQV7laf35s=,tag:maUTqIRDSzoCsee/MFWWDA==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByS2ZtUTlGejQwaHJpOUdo
            YlVLRkpVQ3A1NzVEOHl4Y0ZVckppMmgxTUVnCmsxV210UGIxWS9nSm1hSzROUXBE
            SzZXQmt5d0V5TGVWblp5eDFFbWVXMVkKLS0tIC8vNWdBdFhRQXIvcmZrVm5zdDhB
            TzJxZTJ6d2N2eHluZ2k0RE13VlQvZWcKleiUj6iaqmyXQH/6yX3SIUa3XPQwOigf
            tHJZU79V+lt2v/Y/WAU1mWvpYXZ5n4i3WOpByjGW3eRO9ey5Jdj3Mg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZT0hFanpRcTJ1a2hwSlBm
            d2ZmdzM1L2RRVmpvdGlnbXRGRE5WMjQ0T1Q0CkZyTGkvNFg0OGxHaVJzdzJPekVD
            Yk4ycFhyUHJyYXYyY0ZJaWVmdk1RZnMKLS0tIDZFbTU4U053dUg4V3lCSDkzZ3Fs
            UTlkUkdJYzdScHdWL3kxbW4wMjBBb2cKFnq+M9ETo98g0zwLG+NR9wX0SAoTOY2V
            9vjhYzQ3xrrp25d7lpKGAXQznhmRywWIWj9U78Aoyk4XIs1ySlzMTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T13:18:28Z"
    mac: ENC[AES256_GCM,data:EMIW815kJrEKwMgjUISpQCa3s/uXImTpalAieOMbmsB91TUrb2oszSO55aCnR3nzOs6kTXLBav5JLF5B38hnhxv09j4aF4ce5sFpY5+L0PoWivQAYpe3BADxeL2sUITMNWVLgsxtePGwhlsO37k4iGsDLV5H+DRrWqJsD/ij16U=,iv:EwBYiikeEIfOYtGwG1suk7krWhz5TELyUb/v+CY1XdM=,tag:iTiuOlh5Ad4UCDx2t88+Ag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
