apiVersion: v1
kind: Secret
metadata:
    name: immich-photos-postgres-app
    namespace: immich-photos
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:2GEaTynA,iv:QJwrzXJfv0Np2qQ1qHtm+G8r/LP2HbSoY9jT33Ynuok=,tag:gm7ZYBjXY+ULyScwpKevRw==,type:str]
    password: ENC[AES256_GCM,data:IQwGFlz57QstoMjwwVDkligd+uYroCbUXdzuRXVWxeEAkeSS3/QW6wzTp+3T9un6,iv:0fUi+oQ0Vpp8JLkJOWH6enhFOJzzdRQOjA8G9/Cxndc=,tag:a+6yjqm5n3DiqvZp42NjVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4b0xXaFF5NDI3emkvNmZj
            MXUyKzYvOER6NnVNYndCME50NGJPSmhNNUM0CkFnM08xNVREV1R6Q3h4djR1a0Jh
            Unk4L2hSVTlSMk43RlhKQkQyamdSUVUKLS0tIG9VVGJLM0s4Q3NXMnlCVzByRVhX
            dTVabFhKdjJMTU00aDh1VzB2MDBFWWMKroAxSUt2DIcvjIsQMp90HomyZzyvkq+K
            RhY2UBU2Jd0Go3pz2f55aCsfjPYMMM3OptNK0voW1HCUUaPwusr9Yg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRkNFQnh5b2QrS1JiNXhC
            U1VlUkFmQ2VlYkxxQi9pU3FTcjByS1lsWlZjCmlzTUlDZmNWYndDb3JJTk0vOEJW
            bThDL2lRRG04VjN6YkhVbUZVNUxaazgKLS0tIEl5ckJIMVluL2tOV3QzZlRIV2JE
            RXcrRVFuUFJ6alBrVTdvUUwvZG5ieUUKTquoCL1viDrSVpMZBoOyxGU2HbcRUmmi
            dRG54e5YA0heQajFavX/+vmeBSWc41FPdlaV95xsdbh4mhYO4ZsxGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-21T21:01:01Z"
    mac: ENC[AES256_GCM,data:Dq1L4cL8iQVQAruIu9hiEqn40mIA818cj8hBan4dXjAECznTEwkKby0HMWyDZOM98OnqVDS+7TNa2R0pag5ZTtCekXVlxcqI5ouSdLP9mzgFDKi8Y8hxTLTjmgbnjDp9gyvHtIJjwS2vZtQ95SPVExjWo5pH5od7nIZIIJ3IPnk=,iv:V43ZwJJ/zNMfmBkW0SA+Zm9akDPO5Jal647pn5ZgrOE=,tag:j8hfN0Y6jhRCQFoMiL2KOA==,type:str]
    version: 3.13.0
