apiVersion: v1
kind: Secret
metadata:
    name: immich-postgres-app
    namespace: immich
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:+vfVJeTB,iv:dcQ0UCdmX2X2ZXUUGwSpd4EzF2JZSf6qSpuU28r1v9Q=,tag:iHNF7PhSJMsb54HBia5dTA==,type:str]
    password: ENC[AES256_GCM,data:aPL+HXlHCwm9AF+44U/5ouq579d/9oMr6q7BttH1yfP/KI0QaE1WZgE5lCOMqV4H,iv:4XUbJ5J9lAOy9RkclBDgas6Rb1tgwOHgHdQV7laf35s=,tag:maUTqIRDSzoCsee/MFWWDA==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwaHFzOWN4OElzQjEvMmZh
            TW00cGc3ZTZva0dtYk5MSlFyUHVUZEJIekF3CitUcWJoUDNSeW5xVDIrS25zMk8r
            WTlvblY3RzFzZEJkSmdGL0lKcVFUTm8KLS0tIEZ6TnVzWS9YYy9EVzRsQ2lMSzdz
            M0I4NEFVM0R6UjBMbFd6cjlPaHI5U28KdeK7SEp0PPzi2zfVjHj8xm0mlszsMlkh
            kqN8txgzSHECNWRtpKCu9cTHIw//fh+jCg9aEyiS7P5d3xfn290Pzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T13:18:28Z"
    mac: ENC[AES256_GCM,data:EMIW815kJrEKwMgjUISpQCa3s/uXImTpalAieOMbmsB91TUrb2oszSO55aCnR3nzOs6kTXLBav5JLF5B38hnhxv09j4aF4ce5sFpY5+L0PoWivQAYpe3BADxeL2sUITMNWVLgsxtePGwhlsO37k4iGsDLV5H+DRrWqJsD/ij16U=,iv:EwBYiikeEIfOYtGwG1suk7krWhz5TELyUb/v+CY1XdM=,tag:iTiuOlh5Ad4UCDx2t88+Ag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
