apiVersion: v1
kind: Secret
metadata:
    name: immich-photos-postgres-backup-credentials
    namespace: immich-photos
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:m2ZLFdIYD6TwxVxqq7U+O2V5MC79YuajkXbzhg==,iv:cXIVp3djzWypCkhYuipnDxMUzInSCJk7jgtxkkeSHZY=,tag:cHrrQsu4TubYvGB1wStbsQ==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:OWaJvKVMBx0JIf3m39hE6RVxkgtt+Rb1qD7EXMISIIy+u2GEGyGMLhviyCmC0dQSonrwY2TUBZs=,iv:5lW4bbW9C7YWfY5fuqNykQk0xxd7xLdclm4BSzTDYls=,tag:REoICxpsVcCuryW+ZIyENQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Ic44cp7pzmh8GXGJuL27hjK4TQJtB1VMRMW2ltxrsYG9CfdW9Dd4b5xBtmOfSNKPhK2RbD2ONU8=,iv:wTFsH+VZTaNIFpol7rqmXo5APewgbsD2tiRjcLAa21U=,tag:+kN2sL7XDorGhEj1ci2vSg==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRHkrMGQrNCtOTUhMeTN1
            T0pvcVJrZXVVT0JhR21LY250c0JqR1QvVFRnCnJ2ekhZeHRzeEFnaThiN1NkSzhy
            OTdGZUIyN29WYlBpUDgzQnJSa1ZrTzQKLS0tIFQ0NGhaWVpkMmwyVVoxNnhLQlhs
            YVdMdjFHV2ExbXZUNS84RURzS0hFeW8Kbg3Eu23YKONLmFsh8nTEcTPx9enLTs9p
            aQq5kF+WavdIO2T5HspXjvXd2C5IgbkKIKTi3TlC0JwnV3MnuDLLyA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bnl5UHU4RU1nT0xPNXFv
            TXhhMWVBR3c4VWloMGExZ0lMendlQXhYUzBVCnRpbmFvbDVacmdveUZCcEJ4ZVhv
            S0ZSc1UzR1dsNnpSd2xTL3B3RGpzd1kKLS0tIGZkZ0RibFVwUEc5Yi8zNDFJQVRq
            NDg1ZndyS214WGhkTlROUGRkZkpraGMKp6rsfZiMEedNx/MM/zgUhMZLxUH7NKRh
            x63puO2/QrBM/VdEVvIXncBF0a20WeQwZR4tTjPGJYleHF6D5klsPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T21:46:20Z"
    mac: ENC[AES256_GCM,data:9vSTtMObwBkaUpN2dbh99L5OEbmdJVxTVRjaWNomLqc64PTpZLDAYhCHhcHfLwEiZK7IJdxaYTHhk4kmPcypAYtZPhUwDhGBt0m+BzYTeCzwnETVs+if3BosxKpUxzaLkbluBbIbnJRudLsWDIVQPZi6AeHVkEJ3Nl99zxrNMhI=,iv:ZddVetL0utxM9wAUZZ88C1EHB3R0qqHluQ/kNztk89Q=,tag:WxEn1J68yAZl+4DQJwgGuw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
