apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-e2e-auth
    namespace: media
type: Opaque
stringData:
    api_key: ENC[AES256_GCM,data:ITXYMKUq4qns84fUv0mL67FGhVVnUKWBLBQB4UBxml4+T7blKZVdrQ==,iv:026r/txFE2OmvpnGl8S4k9E7gqmJXjLmjuvOgi2IW/g=,tag:mRMhhsNofwiqFtDZEXBUXg==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBma3orWllUTkdDWkVteGVO
            d1BRQmVQYnFEL09IT0c3bkg0OHArR0hEL1Z3CnJ4VW82bVk3ZHNYdlh1Nzdudi84
            b2d4aEZYN3JJdUhkenkvdlkwaFhhUjgKLS0tIE1haWVkUXBuc0o0V2lOc3ZQNXpS
            VldtR1dmU2IrS0FFSlF0ZWRXK2UyRmMK7G9EzLU5CoQ6i9RDZD9mKD+FUFj1lHF+
            7wXtizSQiyg84j+YSYYIHS64a8Ia5Ne5K39zb4LAQ7f95WHdzyIkvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T21:09:13Z"
    mac: ENC[AES256_GCM,data:apYFGpxmG3q7Au/2AdeYj0hS2V+nlI52gJo0hOlF+vky5ajDPeFcgjp2emIDqUSmL/8ykmhLjUyHMUR8ARcKwm7BQn3BooekjfSi5gtILIUPrph5O3pCkc4O8pcXgJmWXGfYTqYUvsTOvLHj+TkEy6sOp5qoEked6bTfRUgPCVk=,iv:5I/RGMPVdiHx/g6/fcOu1eHl9OXh1owxLVTCLUZkjeY=,tag:KO8E7J9Ua7FVrziBrf6iPA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
