apiVersion: v1
kind: Secret
metadata:
    name: jellyseerr-e2e-auth
    namespace: media
type: Opaque
stringData:
    mode: ENC[AES256_GCM,data:1rSkDiM=,iv:/ED0ygsF5yx0HtElRCqRQqu8yal1Ih91ViIdlNLTPOE=,tag:NmG/B74j7x2T0KunOqkvrA==,type:str]
    email: ENC[AES256_GCM,data:tiWx7Pc0sY3zq6KFkGucxf8ge9w2WnLWF16pi6Ya,iv:jRkboW6A7zWPEmxjwVFBLUxYgWrtgqx5QBNjtrITffg=,tag:JWrJqGQSrwaUecQOg2340g==,type:str]
    username: ENC[AES256_GCM,data:3ce19y0GBqBTEYVJGh0=,iv:Lrs3Cfkqbeo964SdtrwA95xy4kqiEoxCEID/Yef0l3A=,tag:u/XJ+V5y2bSlESvtdh3QZQ==,type:str]
    password: ENC[AES256_GCM,data:HusC4hPX38WXCVuMlKMtmTsmFu5ttHNfAw6nU/+HKvs=,iv:XA24h1dnKaLEHFFtgyjhoAiN62nfohViyw/hDYY+fNQ=,tag:Fu0A4aWT4cb5VPWYj9j6bA==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcXBkOGVhL2RTYVFtcS9s
            SE1CTHFQOElPWEY4Q3p0L0pJRlNPM2ZFazJZCjB4UHo5YzBlL0ppN2xkVWEvcU5i
            aTZncWpobmVHeE5uS1RqczlGYWhFb0EKLS0tIHpJKy84MXYvQi9STGxxaTVKd2Fn
            OWRHT3o4Rkg1N0VxY01oaDJ6WFVURDQKvgRAJpRnPrPNOoVVlBRiLyfEhK/XoRgi
            2ZGZDF0jn8BzYJvK2n7Bv+yip1v3Ek8VieOCYRWRa9gSdezHvvTzIQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMXRjc0hOUlN5VVMxeHRR
            cHJKekRucjZ6R3YveFI3WmQwdXhnbG1jdTFBCkpRUXo2MnZFRVZydDd1N3Jhd0la
            ZFp1M3BDWTJmVVN2bENyNUJEbWcrdUEKLS0tIGk5NHJ4TzVkeDluZnJQcjR4T1cr
            VEZLSDBBbDdMYW8rMXhRZThEN2VCWGcK4/27OA60cL050ddWx17x93lst+gMnYRf
            03duSt8vDIl/Btmvfo5fl3Ciu8Hbcu2AfzfqsPfzO61u8+xaSgCpcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T12:30:23Z"
    mac: ENC[AES256_GCM,data:JbfW7R2NBYaEKNdT+CuahFCyiVCjnUQMUtfdTi+e/OM6KxgtYfIrJs/+Xer6+pxeYHyZrMf/jOTffOjhHI4EOBuCUkcj2gBjfwb0zGTIxryhYQDxiRvbwctLBKe8NLrGGWl9hGGCSYIHrpZXm4Zas/VBAOP3aQiwosIdkxrhL+M=,iv:hoISN0z33T4uV/3lrvIPZ31WmyGjrgD0/VAOhr8YYJA=,tag:x56Pogbdo/4y9vDzpy61og==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
