apiVersion: v1
kind: Secret
metadata:
    name: jellyseerr-e2e-auth
    namespace: media
type: Opaque
stringData:
    mode: ENC[AES256_GCM,data:i90vP0g=,iv:h5Axa9c8HplQRK6RmSQXkZhoVUiXLEkMMaJFkyqeiRE=,tag:PDa1y+bZBick/H5yIAl9gQ==,type:str]
    email: ENC[AES256_GCM,data:ENqLV9QTtJGa1U/6tL07rDtakZfhW/vnlGC4mTfH,iv:XZ/daO220RAk8Glfhpg/iKSvSz+L2FUhXPjlsYB1coI=,tag:DOvyl3Rl/yw7XVxG118Lcw==,type:str]
    username: ENC[AES256_GCM,data:CU5sW077n01DLgtAxtI=,iv:ulLFtkp0+KbZ4AktgsxWWuhM7+jd3M91icX0IagD5kE=,tag:LauKi6baWpf91lPj07VZWQ==,type:str]
    password: ENC[AES256_GCM,data:xrm9TAThsBBP23ng4V+4fjwOmwwjq/Lmfm7mukhEAus=,iv:UxQ+qZ5sbd8z4XJo2OZ4NQ8zLnVL9HoANhZim3aJ5Qc=,tag:GDyd43cK+fkdWAFC2BCstg==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxY29JaGJxWDFhOVhSWUtl
            azgxSVNDV3JuN2ZHaFFLUkl1L3R6WkNXVlZFCndqaEZEOTBrN0pNMnM1M1FQSzB4
            clNpT3VRcG5GbC96L1hYM0V5MHN0emcKLS0tIFU4NGJrRnF3cW9LRjUzVmRXdSts
            clpLUHM5VXdIdzVHSDJJVGFMcWFWUkkKtRAHVOpOg1iqc8NXl0fSwj5z+XScFmv5
            QZicpF+SCfh0oJ4gpLqgAVY748fsOOA5Mt2k6jR5z9giMAYg5gqMPA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbkovVUlrT0pjc3U1ZEZw
            L1hxajhQVjA5TGJjVUlkUWUzam51ZzZYWW13CitJeXUxZFpCUmd1c2dma3Y1RlhD
            K3MyalN2OVlpVUF0OThDbDljcEl6OXcKLS0tIGVzQ0I1UUlCV0s5eVVMRE9qeFAr
            UVJOUTJiTjBHeEJYclMya3pENGNTajgKfIZbtv71WDd4WvnQ/QiIkUp9e+bWuB5M
            yVCQ4gfhSLTX1yfOCYxDkPa/XLW2YiWj6lOYg/Tc6td6Zj0IIXnzmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T07:22:21Z"
    mac: ENC[AES256_GCM,data:7aO+wPM7vA0xVqxakL5Eom7Sn52873O5+synB3EnItAKvjj5hz74skwt38azECp+hvGQNsAU5yEj1Kie2+JVKhw3uaRDVM366oYACnaeKmNRLgmNACtIwGGxbBCXH6IQ1VmaEotEXOfOrLtKOslYznr48woAf8mR5DE8M2A+ZAo=,iv:2iiiwotNIe1lHNsI7wxX4qQ70epMKxSeFel7Ve2aTKE=,tag:OORVNDbsMD1vfHsokYcvaw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
