apiVersion: v1
kind: Secret
metadata:
    name: jellyseerr-e2e-auth
    namespace: media
type: Opaque
stringData:
    mode: ENC[AES256_GCM,data:i90vP0g=,iv:h5Axa9c8HplQRK6RmSQXkZhoVUiXLEkMMaJFkyqeiRE=,tag:PDa1y+bZBick/H5yIAl9gQ==,type:str]
    email: ENC[AES256_GCM,data:ENqLV9QTtJGa1U/6tL07rDtakZfhW/vnlGC4mTfH,iv:XZ/daO220RAk8Glfhpg/iKSvSz+L2FUhXPjlsYB1coI=,tag:DOvyl3Rl/yw7XVxG118Lcw==,type:str]
    username: ENC[AES256_GCM,data:CU5sW077n01DLgtAxtI=,iv:ulLFtkp0+KbZ4AktgsxWWuhM7+jd3M91icX0IagD5kE=,tag:LauKi6baWpf91lPj07VZWQ==,type:str]
    password: ENC[AES256_GCM,data:xrm9TAThsBBP23ng4V+4fjwOmwwjq/Lmfm7mukhEAus=,iv:UxQ+qZ5sbd8z4XJo2OZ4NQ8zLnVL9HoANhZim3aJ5Qc=,tag:GDyd43cK+fkdWAFC2BCstg==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cDJXTUlhVWtDVlA4MnN1
            YnpYWlBnVTllR2VsUk00WWRSK0lzdGRaWUMwCnFBUjFRTFpXblNpZnJ1aFE1aU5J
            cDBhWlZMUUFqSnhHbWpWbVJQa3JqUjgKLS0tIG02UWljWnFaQk5EMm5ONUk0RnZk
            bi9oUTNwOGhDZDdOM3hCd3MrMnZqODQKUoDX8vdbeY/iQ8bQsEUqwTFT7mJGUDrK
            v83moK8XoVqtVs/WMZIamSc0rMtWiX26M7x+3lpXdwOVQfdsVDoF1g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16aayps2sfharjkjdl2rj3al4uwd2r4hyep0kwc2ek7ka4gj9leaqxmwvsa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSTFjSGVZTkdGNUJDY0pG
            cEloRGNNTGN5TWx4aEhWbElXazhHRVlaNndFClZRMlVvN0dNRWpQT1Z0UndqZVdK
            QUZxWlIxT2xZR0hDaGVCT0VHMzNHUWMKLS0tIDhoUmp0VzZ4REJmdm9BNjZsWU5x
            R3NDZVE2M2xpYjlLRDFpY1I0MnRZREUK+ND1+e+a3DQBPd8Si9LU+6QsYGZtLbIG
            K2jucIIwscrF5sNsnOCk7ra80enuWXvUSzOW06iZ8ub3Lng6aZPQlQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age192f9zz83ht9pkq6a7jp8w0azggzqtxw5nnjrx9lgefu3euqz4f9srs2wcz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndGM4UDBFSDVEVWcrN3lu
            VWtJY3JXSmlFNGFOZHdGZkF4RXI1elRzRmxFCm9pRGRKNStvY25JcUxWWi9lbFc0
            SWxkejRTQ295YVZPQ0NYcFpROUJpakEKLS0tIFNnRGp0Tm9vSUxqTGQzSnFYck5j
            VkdFdFlJM1JPNVZ5R0RZelZFTmJlNkEKDWafJ08mDf1/DU7PBuY8prnh7DG5heY3
            ZFEKC89WroDTHG9lkwbR0slIng/cIDJYBSFKgPrX7lZqjiv3pHb4QQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r773stmmugvqk568s7c0y6s0umjsxn4f92arxdqqluv0h3euw58ssk63my
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIK2RLNWlzRlJ1ZkFRbUww
            RGlHazdXUmIrdzE1V2dTSzB3YW5PRmFXeWhZCjVVMlk4MWltSllkcE8yU2xFVlJw
            OXV1RHFzUXBOVzRSWGQ0V3NKY2h0djgKLS0tIG0yRE9XUmJwR0hybFJCMHBVY2xP
            bFlFdFJYeURWSjVwRjJ0L1NVUjFVZW8KGF7rSQUWSrry5my31gr6+mznHbkGFDEN
            GcNKfktaZWzefJAnIaewBRxiujFjNOf1lZNuwnR0XN5p/FEaW+4qIA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16aayps2sfharjkjdl2rj3al4uwd2r4hyep0kwc2ek7ka4gj9leaqxmwvsa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKaUN1YTFheklsbVY5czVa
            VEE5U0RnYlM0MEFXSUxERkVqRFdqTXdSNDJvClFQODFvNzVYSFF6dUlwcmxLY1hz
            REhMVzJKWjVtRXZYZFdBZ3VOUFI2UHcKLS0tIFRIQlBGdW9EU2VVdHN2bUpLdU9R
            R0VIYnZqUzlsWlhLQnJML2xzaFNUR3cK73ufpYfM3Q6v9BtHWQI2v8aNIjHId1s9
            +LbGOnnrUE6ur7VCaz4GwWtP0ufGUKM724QGe5wnFmD08f1TeKyevg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age192f9zz83ht9pkq6a7jp8w0azggzqtxw5nnjrx9lgefu3euqz4f9srs2wcz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByc0QwVlp4Yll1MVJFeUN4
            cFo0NDVyZU1WODNXaXBXZE5zVUpKYnUxRGlFCit3ZzBoa2xjM2t4cEM1RXk2a3pG
            L1R5Slo5LzdoeGtFcDdjNTNWZ04zbE0KLS0tIDA4SmNtUEVPRGVuMWIrYzJkMjhh
            eVNKdzRnV0E4ZUt0MFE2YmwrMkFaVlUKpF7aYZTwemEBtDHPrcZfczRLkxam2AHm
            nAcoaFANsy4mFEhkRamukYpxtD+U35eb7Zq0cikNH60U8LUQypcrvg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r773stmmugvqk568s7c0y6s0umjsxn4f92arxdqqluv0h3euw58ssk63my
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5R2dkR1JSa29tOXNMWU90
            T24rVDg0Lzl2R2I2amxKTVEyU0hYUEJUOUdNCkl4N0V4aEdaay84dmJyL2krS0Fn
            L0JkS3BTM0g1R2Y2elZ3NFJHUVdPNncKLS0tIFZsdzdYVkxzSlNJMkdnTzcvK010
            bTNSNEJJL2ZRbXdEeGhXSGVrcmFmUFEKIqZKtjtrQiunOykD4UMJA6hOOw1Ud3cp
            oIgKF8/jJzqA35pfRIhFO5qpVrSremr+pLivK91TQuf959eqQxqLSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T07:22:21Z"
    mac: ENC[AES256_GCM,data:7aO+wPM7vA0xVqxakL5Eom7Sn52873O5+synB3EnItAKvjj5hz74skwt38azECp+hvGQNsAU5yEj1Kie2+JVKhw3uaRDVM366oYACnaeKmNRLgmNACtIwGGxbBCXH6IQ1VmaEotEXOfOrLtKOslYznr48woAf8mR5DE8M2A+ZAo=,iv:2iiiwotNIe1lHNsI7wxX4qQ70epMKxSeFel7Ve2aTKE=,tag:OORVNDbsMD1vfHsokYcvaw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
