apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-e2e-auth
    namespace: media
type: Opaque
stringData:
    api_key: ENC[AES256_GCM,data:ITXYMKUq4qns84fUv0mL67FGhVVnUKWBLBQB4UBxml4+T7blKZVdrQ==,iv:026r/txFE2OmvpnGl8S4k9E7gqmJXjLmjuvOgi2IW/g=,tag:mRMhhsNofwiqFtDZEXBUXg==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbTRHR2F6Y1k4OVpqQ2l3
            b3plQWxCZmhON3IrbC9tRWNvZUxBenRQVGw0CldTWW55U01La2FMcmttYlhvQ0tO
            ZUJtcWJLQTBvMFRZVWljY0NuS0doOEUKLS0tIHVzUmVWRlB5bFNqV2c3RVNNUmt5
            SnlwdkhzbXFQcXdheHMwL0RlRTNqZjgKPc/aSS5pQ5tieJe7IuzV7bk2A5NyD1aj
            2KqjiLB9TNPMcz7xBc6N6M8KX2UH0Vo/Tu269+Otg/yiALFsAsVSVA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NUdyeDVlK1lINXdFVHQz
            YTBrUkhic0NhdVd6NVkxR3BKdVIrd0RtV0VJCkRMbklnRVN2UDJSRXdBZmV4OHFE
            bERyVlhiRTJzWjA0dXl3TWlvT3hlV3MKLS0tIHZKekoxWTZsTnl2Q3pPeGNLSlZM
            RDNncTM4ZG1tNnJ3RFRKdEtiL0E3d0UK2ZwXEkyTs0AFbc2ldxzJdunfgD9zx55n
            QY0POF4/7dRqi0VSs/nb8ZyONXk0K4PSHj9DH947AHcskMWyOIGnkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T21:09:13Z"
    mac: ENC[AES256_GCM,data:apYFGpxmG3q7Au/2AdeYj0hS2V+nlI52gJo0hOlF+vky5ajDPeFcgjp2emIDqUSmL/8ykmhLjUyHMUR8ARcKwm7BQn3BooekjfSi5gtILIUPrph5O3pCkc4O8pcXgJmWXGfYTqYUvsTOvLHj+TkEy6sOp5qoEked6bTfRUgPCVk=,iv:5I/RGMPVdiHx/g6/fcOu1eHl9OXh1owxLVTCLUZkjeY=,tag:KO8E7J9Ua7FVrziBrf6iPA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
