apiVersion: v1
kind: Secret
metadata:
    name: logday-ghcr-pull-testing
    namespace: logday
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:fPqOiRQ4uz5ooqvgkY80P8x1e7gDqT8O6tG1XlYKjYSTNP3ZG2woCR9FDHxBVdv9G1xWC5oGsSMy4IIK/u9NIRSdU8MIkld+4RervpooxX1H4fDk8rhouQtDDQMMRfT/glTGp+fDvXe1J1pbOsgWGf4LpmmDf9nT+tye30WwXiviqwgWlu8GQ48zLtQnrvGsLySLXkqpYCaaQuTNlOgxpI3Y7kxylqLrHshAuJdre08wnf+jxquTDotpd1VmxunwqAMsA++ZXlNtYFIreBQZ40Y8pJTU3yJKP8EHrAtpL1N9tp4Ssf0+kK9QCQ==,iv:tWKcrctP5mMB5uij1S+6/cikixz1/rLN8KRMmjqU2KU=,tag:xpF+pLm9TWl8g9PpFUyyyw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSHdHWHdsQkpGM3N0SWVB
            TWx6UndmNjZzRi81SFZYazZLNjFsM1BRYzNrClJaUW1zSUt2TFMyZktxdm9RRmxt
            YTVGNFpNazNvQ0Zab05XZmhYbzM5RHMKLS0tIGQ1KzEyVWhESmI1MEZkNUJBL3VD
            T25MWnRzeHVBYy91NytONWJ5WENiY2MKoxsseBOMUTTZBz7IpWuU78UAQBqlZp+M
            YdougrCznaD2+EWlF8Fghp2aeUTS6pFXYhVx9GPAusbITD/EDK22kg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTml6WHRtTkJzaG9SQW1J
            TlFuYWpwQUxxVnlTT0pxWVdhQ2tXWHFrMEhFClRVT0FNOWo2YzdjSXh4L0xpekJm
            THVVN25zbktwNDZ4aHl6Wk00K0prQncKLS0tIDFUS3k5WjhkVStuTWtQWU1NeHkz
            aG5XNUtWdnI2Tkgxcm5ubCt0K1l5d1kKE7NrpyliP7XRZHpWCdi+DMcSSxWu5sr6
            0ZX6ykWJ/xqNXc53laagCPDCjcfEfDASOGJuJhCuM7M0shlbIbmwTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T15:56:08Z"
    mac: ENC[AES256_GCM,data:N02o/Tap4mWK1HXg9oi7EpG/jTchSuk5hx5OJvmwlQB2APixYGurZyuc/sS1f4m8SneFgMFM6K2f7j+d3J3ecxzzcAQm+FdXiGPO0jproyJvMwaX7wQgDxBi3jJF6GpTeb7j6bt64JZ1QMb9zPWzVBheM6mwbCAFMBcb2MrvbEk=,iv:WFFllADuSz747c80k+u4TqMixE+2IvhW3NmScArDxlo=,tag:gtRjjEe6FfSTzFVX+ibO+w==,type:str]
    version: 3.13.0
