apiVersion: v1
kind: Secret
metadata:
    name: matrix-postgres-backup-credentials
    namespace: matrix
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data://ktku33XJFTtgF+pX8NcoCjVdcAg44pPaO3/g==,iv:Ijk/E1A93IWMgLWZu0nF+hByL8BvsTkp7ubNxwqsN8A=,tag:gOpfH0vcu+p4Osgk6Lt43Q==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:QOpro97z5D7WoMmGxpGZtKYku3RwFTg/rpQhL4obDPgHIvsZO8ZUOb5Jai7Zb1JgZMMB1ZZeMZo=,iv:R2VvWsOevdCqG+WUJFB+EhwR9/w9MJO/FU/n3EkVrPA=,tag:SFWEWB40m6UhJPmGCMdxCA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:47ykK6dvSJqUOCWZiua+TBBhozJO7jDHEpkS877JQoHcqEPNZ2agWJNSmsDbSHUZe1Q49JAmxWg=,iv:DF4+5KXzakyjy/u8obr6iYvtlG88UvCOvlwNnJgphbE=,tag:ZJ+VrJyJi6vHn/7MLUTOQQ==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bFZlSUYrei9kNnZYSlh6
            cHVWZkZZeEJ3Umdrejk2aDE5TVdsNVAzVVRNCmVDRDRTQ1B6NHlFTkZySUYyK2l0
            WS9wR2NOeExUZGhXZUhsVGhtODB5bjAKLS0tIFdvMW1tRFB2d1M3QSt4VkRGUmRv
            NHBrQmdDSld3ZW41N3JYZ0c0ajdFa28K/VggDf8IlFOk9HzzoL4pzgZyYNPYnRDK
            z/csEd7CZq24BA/dPGR0i19jpuJR7VNKCm5mbitdWk+r5ICqki8/NA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T21:46:20Z"
    mac: ENC[AES256_GCM,data:LIJxKW/E3TbUVRw7uGNF4K1Qf/Y31My3vmWCbxxbymsda75YmSQ52CY1VaxsqW3Qt31+GIglXKKy6hbhj8WGHb1MWy+cdclMrygRnCjI7fNL9h8qBOsjSRtMhOmyg1braPFB9FiUWOfkJZfMtD+tPyyZYRDExO6w6OOJp0MII4s=,iv:iaMh0ZmpldTbSnxlK64Mj7Wajux0pRiPPP7IHaJB7Ms=,tag:AVhhVvoV9dWh9AJhMD4puw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
