apiVersion: v1
kind: Secret
metadata:
    name: matrix-mas-postgres-app
    namespace: matrix
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:mKPG,iv:yQnUWDHFUO1KdZr/obkQOZowXu+cQ0HcPNisvDHlpp8=,tag:vlmeLi1hTTxTXiR57uwN8A==,type:str]
    password: ENC[AES256_GCM,data:Dmv7YW5cowuK3rJgfYWdTPXwsp1Ww096I+uzAxN+adi9d2K5JDorYuoy6fnV3serB2iVPWZQ8e03TgKCFkiRIQ==,iv:y1hAciuwQzddRLjgVxZ0prADPtnR77hBkyZfXjXaY4I=,tag:MtO4f6r3fClYUfBI+QUiJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSGVxeTZNTGtORWZLdFdv
            OTJ6Yk1WNm90TjJqc09UdWVncjlOb0o0cFFrCk9QL2kyd1NwSlFqYThYTmM4K1lx
            MERNQmtYenRDd0xYYkE5Q2h6bTdaL2MKLS0tIHBZZ1VFcm5idUc2KzQwdEc3VWZC
            TlQrczE2clltS05mYVRRVk5XUHo5MFUKJ/EiPUbScNhw11LSXEK//bmvKSsz9THM
            zvteSg/qye6ZQ+tLPtvHH2Hh5HSSZs4bbLMffvz9OTN6ml1dxNrL1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcFlwSXJrZ25Za25iQ2dp
            WjRUUDFIWHJrS3dCYWlUTVFXWXFGMktXS0ZFCnR5dDE2Sml0N0VlSVFoUG1lMHJl
            dkx2Sy9sTm1OZnBTazNVZFBORnBNQTgKLS0tIGM4ZHlKSjhYd3JDM1dRR2hOTEJR
            NVBRdVQyL05LK08vUjhFcm5BT255eG8KOM1BZTdLNhCftFIUg4jXYl6rYOE0yKAO
            B41EozLsil57f27sq8mOP/4sWOm/Ra/NpGQVKlAJHS/bjxEXkItbyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-02T10:36:47Z"
    mac: ENC[AES256_GCM,data:T44Ubjf5lWFKE/eqVTjOhGF3mv5rYF7QekfFQLx/ZNnK0L+Ul8VWgIAsFqLcqE9J/dW6EbRHd8FWWam/67bNuu5T+MAn+agezmCGRF8OG+hKd+rroDdW8brLXS1xFBomcJfSw1D5y0HWLbzv19q/o47jnkEu66vD5VZf1l4rPC0=,iv:JnY0/iWQmOviELRwjGWt5U/lDatEEsDAOiDbchlscm8=,tag:JLivhxWFGc95ySbfYiE/1w==,type:str]
    version: 3.13.2
