apiVersion: v1
kind: Secret
metadata:
    name: matrix-postgres-backup-credentials
    namespace: matrix
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data://ktku33XJFTtgF+pX8NcoCjVdcAg44pPaO3/g==,iv:Ijk/E1A93IWMgLWZu0nF+hByL8BvsTkp7ubNxwqsN8A=,tag:gOpfH0vcu+p4Osgk6Lt43Q==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:QOpro97z5D7WoMmGxpGZtKYku3RwFTg/rpQhL4obDPgHIvsZO8ZUOb5Jai7Zb1JgZMMB1ZZeMZo=,iv:R2VvWsOevdCqG+WUJFB+EhwR9/w9MJO/FU/n3EkVrPA=,tag:SFWEWB40m6UhJPmGCMdxCA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:47ykK6dvSJqUOCWZiua+TBBhozJO7jDHEpkS877JQoHcqEPNZ2agWJNSmsDbSHUZe1Q49JAmxWg=,iv:DF4+5KXzakyjy/u8obr6iYvtlG88UvCOvlwNnJgphbE=,tag:ZJ+VrJyJi6vHn/7MLUTOQQ==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQ01Nb2x4ZUt1V2FudlQ4
            aHVaWnlvTDRqeCs1WWFTWjR6a1pHeTExa3pvCkNldlREOFgrUE1WaGVCTUF3ZUpI
            YWpqckhWZmt3K3V2OTNHY1JYMmMzUGcKLS0tIFVYTWF2ZkU5ZnJoaFVKMzBNcVp6
            empPRW9ncjJTWEZ2VHRVVWNkTjhrem8KHBjRI51hK9Fi2QxLK4fT2SLDI6VhKQ85
            nsRxgGXGRdWeU/FHK5JIInKGs0D+iM86K2qwEzJC1eYuFDon37JTbQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dVZMeGhoODQ3K3FtQ3BZ
            NTlzbERsOElJQXcrbzJlUnY2dEVXcUNETmxzCjM2MzJ4bEEvQi8ya3FqTUZvQWgx
            M3Z0SHR0dy83ZGN0cDVwUUZteEpoVUEKLS0tIC92RkpucHU0SDBUazYrYzRUVzZy
            UTlLM2NSVlE4V2k0WkFZenJqd0NZYlkKKnR0axBTB62hNw2izmd9/H7/dgGA14PC
            4zYAODea7MOj8WC80qejETkmgLneVXMWCwD0JPudhFm9YHe0v+9+RA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T21:46:20Z"
    mac: ENC[AES256_GCM,data:LIJxKW/E3TbUVRw7uGNF4K1Qf/Y31My3vmWCbxxbymsda75YmSQ52CY1VaxsqW3Qt31+GIglXKKy6hbhj8WGHb1MWy+cdclMrygRnCjI7fNL9h8qBOsjSRtMhOmyg1braPFB9FiUWOfkJZfMtD+tPyyZYRDExO6w6OOJp0MII4s=,iv:iaMh0ZmpldTbSnxlK64Mj7Wajux0pRiPPP7IHaJB7Ms=,tag:AVhhVvoV9dWh9AJhMD4puw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
