apiVersion: v1
kind: Secret
metadata:
    name: synapsedb-app
    namespace: matrix
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:0u+SMRtbng==,iv:O2hwTcZ7QTYACFEBtM9CK5ejUAgueWBiLGL4a1p2pSI=,tag:rCWrihQZ/yAQCx7XmSEjEQ==,type:str]
    password: ENC[AES256_GCM,data:lC2s/n0jJp8ngE5A14Fx,iv:4mcCAnB+v03OziZFwtMSHv6VfSDZehT1IHCfbhxTxZM=,tag:8rN/NmCeTHRCGufy5uYLqA==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NDRGeld2V2MwZjMwNE5v
            Nk5wYmJQTGhHVWVPVG1ybU0wZFY4THdmQWlZCitEVmRkRHl0Sm41V0FrUTlHTGkv
            UUpDM1FIOGNBUnlCMCsrQnNlVnZaWk0KLS0tIDREUnQzYUljaXdmQ1VtYnpFclcv
            ZnNaY3krdE5ReG9JcEQyZlFCQnRBUncKaya69xOa4T2FyMaP1x+ax+YzJ5Xqbjsr
            lXceS+7f8bPT7bZPq4bH2c0o4QsWNPvr1Dy/GCBtGxWziOK3ge7Mrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T13:18:28Z"
    mac: ENC[AES256_GCM,data:iHFA8Ilw+k8wgZ65oUhzO8awt2I+CJ14WEpDhxvbUro0jFhgz5SUt8Qgr4/tHBVkU7JpxgxNKWly1ziHdsqOetw2LEf3f8czfsc+ZBN0z5oapD9li4xWyTnPzeTo/vOEYHIfCvGl3DMCYXnltlAjzmT2cuE3zT0tTgFtRJZKsPk=,iv:DKNEtnzMGQJQKPvbexiOovurrC8SZ0P0lzsu6GE5/Do=,tag:PLmtTRoQHYdZxhB/ZPCY7A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: whatsappdb-app
    namespace: matrix
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:f2kghDJAHduwAzUggXkt,iv:Z6w+l1wAmjwJQfaH2zMidv623rIm3CNRYSpmFI8rbRE=,tag:lgG3TfrWCf4fIFTT378dwQ==,type:str]
    password: ENC[AES256_GCM,data:kUfdVBh0+Lp5rYteZyfHkw==,iv:TWFJJjvLaocs7fMAz226SvraDT5OmuMJbPz19C4x310=,tag:ya5dyXF9hELI4D0rbihgFA==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NDRGeld2V2MwZjMwNE5v
            Nk5wYmJQTGhHVWVPVG1ybU0wZFY4THdmQWlZCitEVmRkRHl0Sm41V0FrUTlHTGkv
            UUpDM1FIOGNBUnlCMCsrQnNlVnZaWk0KLS0tIDREUnQzYUljaXdmQ1VtYnpFclcv
            ZnNaY3krdE5ReG9JcEQyZlFCQnRBUncKaya69xOa4T2FyMaP1x+ax+YzJ5Xqbjsr
            lXceS+7f8bPT7bZPq4bH2c0o4QsWNPvr1Dy/GCBtGxWziOK3ge7Mrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T13:18:28Z"
    mac: ENC[AES256_GCM,data:iHFA8Ilw+k8wgZ65oUhzO8awt2I+CJ14WEpDhxvbUro0jFhgz5SUt8Qgr4/tHBVkU7JpxgxNKWly1ziHdsqOetw2LEf3f8czfsc+ZBN0z5oapD9li4xWyTnPzeTo/vOEYHIfCvGl3DMCYXnltlAjzmT2cuE3zT0tTgFtRJZKsPk=,iv:DKNEtnzMGQJQKPvbexiOovurrC8SZ0P0lzsu6GE5/Do=,tag:PLmtTRoQHYdZxhB/ZPCY7A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: wadb-app
    namespace: matrix
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:/HmSrpfsUXHbzZV4ZsT1,iv:62qRZESfGgut4vS/cNFO6jpjxRZUxbdBsSnAGOP0TPw=,tag:BB+aVuSKnThfmIGZRUXAtQ==,type:str]
    password: ENC[AES256_GCM,data:7jxI8AXxk4vKNG7kvpPjhg==,iv:2mfMyBJ40sJ/4cgCyiHYA+h9gCXr/XsQ/39JGmOqzCs=,tag:LoISbXRz5UDbbMsPfXA8lw==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NDRGeld2V2MwZjMwNE5v
            Nk5wYmJQTGhHVWVPVG1ybU0wZFY4THdmQWlZCitEVmRkRHl0Sm41V0FrUTlHTGkv
            UUpDM1FIOGNBUnlCMCsrQnNlVnZaWk0KLS0tIDREUnQzYUljaXdmQ1VtYnpFclcv
            ZnNaY3krdE5ReG9JcEQyZlFCQnRBUncKaya69xOa4T2FyMaP1x+ax+YzJ5Xqbjsr
            lXceS+7f8bPT7bZPq4bH2c0o4QsWNPvr1Dy/GCBtGxWziOK3ge7Mrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T13:18:28Z"
    mac: ENC[AES256_GCM,data:iHFA8Ilw+k8wgZ65oUhzO8awt2I+CJ14WEpDhxvbUro0jFhgz5SUt8Qgr4/tHBVkU7JpxgxNKWly1ziHdsqOetw2LEf3f8czfsc+ZBN0z5oapD9li4xWyTnPzeTo/vOEYHIfCvGl3DMCYXnltlAjzmT2cuE3zT0tTgFtRJZKsPk=,iv:DKNEtnzMGQJQKPvbexiOovurrC8SZ0P0lzsu6GE5/Do=,tag:PLmtTRoQHYdZxhB/ZPCY7A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: telegramdb-app
    namespace: matrix
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:VeKhwaATLobSDWNB1wX9,iv:782tfiha8AXXWHBs78XrnXbEdmT4Iero8KcbJYkoxQ0=,tag:uEcS7x5nQ+chXgX4t46n6A==,type:str]
    password: ENC[AES256_GCM,data:TxYfbO8jTuljQIEiCZgWzg==,iv:PjJZg33zxKqo/FtnngFXjNwDbALLr3gC8hA25DN/5r4=,tag:0cj/huizUEAVUhyyOHonDw==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NDRGeld2V2MwZjMwNE5v
            Nk5wYmJQTGhHVWVPVG1ybU0wZFY4THdmQWlZCitEVmRkRHl0Sm41V0FrUTlHTGkv
            UUpDM1FIOGNBUnlCMCsrQnNlVnZaWk0KLS0tIDREUnQzYUljaXdmQ1VtYnpFclcv
            ZnNaY3krdE5ReG9JcEQyZlFCQnRBUncKaya69xOa4T2FyMaP1x+ax+YzJ5Xqbjsr
            lXceS+7f8bPT7bZPq4bH2c0o4QsWNPvr1Dy/GCBtGxWziOK3ge7Mrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T13:18:28Z"
    mac: ENC[AES256_GCM,data:iHFA8Ilw+k8wgZ65oUhzO8awt2I+CJ14WEpDhxvbUro0jFhgz5SUt8Qgr4/tHBVkU7JpxgxNKWly1ziHdsqOetw2LEf3f8czfsc+ZBN0z5oapD9li4xWyTnPzeTo/vOEYHIfCvGl3DMCYXnltlAjzmT2cuE3zT0tTgFtRJZKsPk=,iv:DKNEtnzMGQJQKPvbexiOovurrC8SZ0P0lzsu6GE5/Do=,tag:PLmtTRoQHYdZxhB/ZPCY7A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: signaldbprivate-app
    namespace: matrix
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:kYgyj6uEryfU6noS8g==,iv:oIPD1eWE8a99CRxnzYGKtGfW1s0XZsNM+vhY5mJif2w=,tag:nuAxU/DM69N42aoEeTZOKQ==,type:str]
    password: ENC[AES256_GCM,data:OItrDFuz/pqZW1+TQxw=,iv:Hy/XR9QbsNzbywSv9hcXLxAkypbNpCxhc2UYRuODwms=,tag:P1yxOuUiWATsb9OST0PVeQ==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NDRGeld2V2MwZjMwNE5v
            Nk5wYmJQTGhHVWVPVG1ybU0wZFY4THdmQWlZCitEVmRkRHl0Sm41V0FrUTlHTGkv
            UUpDM1FIOGNBUnlCMCsrQnNlVnZaWk0KLS0tIDREUnQzYUljaXdmQ1VtYnpFclcv
            ZnNaY3krdE5ReG9JcEQyZlFCQnRBUncKaya69xOa4T2FyMaP1x+ax+YzJ5Xqbjsr
            lXceS+7f8bPT7bZPq4bH2c0o4QsWNPvr1Dy/GCBtGxWziOK3ge7Mrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T13:18:28Z"
    mac: ENC[AES256_GCM,data:iHFA8Ilw+k8wgZ65oUhzO8awt2I+CJ14WEpDhxvbUro0jFhgz5SUt8Qgr4/tHBVkU7JpxgxNKWly1ziHdsqOetw2LEf3f8czfsc+ZBN0z5oapD9li4xWyTnPzeTo/vOEYHIfCvGl3DMCYXnltlAjzmT2cuE3zT0tTgFtRJZKsPk=,iv:DKNEtnzMGQJQKPvbexiOovurrC8SZ0P0lzsu6GE5/Do=,tag:PLmtTRoQHYdZxhB/ZPCY7A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
