apiVersion: v1
kind: Secret
metadata:
    name: media-protonvpn
    namespace: media
stringData:
    wireguard_private_key: ENC[AES256_GCM,data:TT0sQiU2TXVUpZnB68fCX9SdZG4WPFGZLhoyjgPBliFbVM1wGlVzcLXVmRU=,iv:yXd6zFHaxYvA7J/+Pj1tWIPvMNOZU0Q3DFCji0HN7RI=,tag:dld85KRlJSnLXHrp8/wu+g==,type:str]
    wireguard_addresses: ENC[AES256_GCM,data:ROxPGMwjHTwPyUscq5FxlxVDvpHeHEey9yFk9+TC,iv:+fYzqrSw9h7S8hKMA4wtMHGdD+3ugKjZij4LfND7Cxw=,tag:t1D8ltVesTJnNWhKOVXShA==,type:str]
    wireguard_dns: ENC[AES256_GCM,data:xPbap/ct2E+8sAs8buOTUkBCO+FhZGY=,iv:OXwYEgRCtaYSSVc7jlcN5Ll4/S4hD+KE48PMSon3Gew=,tag:fcujvwJgscxizxIVH3UoQA==,type:str]
    wireguard_public_key: ENC[AES256_GCM,data:PA02Qxz6UowSHQvHijRp7TW4gNVsNpXhYLye0o6uWBoplMAtkF+BmoUiB7g=,iv:QwGY6gAYamdxM7SKBOV6IyvFLnvcJ128AOv+ZK4O9As=,tag:C99yrqlN7kyZVl81Po/XmA==,type:str]
    wireguard_allowed_ips: ENC[AES256_GCM,data:QPjtEdwK5ZNaTKg6lXs=,iv:B6ZhKtLlYLD5ELUjcFUiiht8eqCWdLD4qruxgsJrS0U=,tag:1K+zouDCziS3/XvI7jdjQg==,type:str]
    wireguard_endpoint_ip: ENC[AES256_GCM,data:aWNRfyECcHT2oTw9Ulw=,iv:JpQdE5dDJJEvozxM0rYu7zyVprdC1yB2nS34GZJj5do=,tag:Wfa0Ty0Gg+cVLQNAWHQFyQ==,type:str]
    wireguard_endpoint_port: ENC[AES256_GCM,data:Oi/3oMM=,iv:e7qHCNm9U5mBSrtmlFVGA+lB5Kshg1iPkMqhz+7BcF8=,tag:DQ2lt7XjsMpojPcB8KMfWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSVN4anpzVmxCYnZuN2Zs
            Q3hzZDdua3E4ZkZtWHpNcmpqb0ZqdmtFRFcwCjlxcGhNWGxlY3pRRXM0aStMZ2Vh
            d09wOGFkcnA3SVVFek5wQXY2ZlhLamcKLS0tIFZkRzhwaGNmandKTjVOcUlXeFRJ
            TmlqcEVITGdsc2p2aHBjVEdBU05tbnMKgK638Jmh4ddCCHShV0ttSCKq1wdPb1u0
            APBA/KNaJ0SuIC+pob2ZCIDPRLoi2K84/0QwbLVZPVOcMiHYerQkZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SmRyMytENkd1ZGdreHNj
            NlVIa1BUUnlTK05KUjl2Z2Q0dWZUMXVOc1ZnClMvQnB0OXA3NWF2MFBzQkNIT01E
            Z29vU282K0Z3LzhLS2IyL1A5cC96dzAKLS0tIEpFSFBNaXhMOTVqYkNnRno3bllz
            TkM1QWplT3BIc0RyR3QzS0hUVjhGRWcKHyxCAXcsWqS5So5GH/6otZg4q9eOyHr5
            S97mnB0e9UBbEBaHtlDJzi7/R8U/VWQlWL/rHfHJWZcO2NjdsfO4dA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T19:36:21Z"
    mac: ENC[AES256_GCM,data:ct5Ps+JsRH4b1/d7o1f7CuRISNBCLUVIFg3FBg0q7vjC+OXfZwstN0K3g05+ckNxCKBjI63mWVvS58SS82qevwbbsOEhBclmSs6mgO27pn21eo7undZ/wlz48fZX/JGa5074/yMoRakRDCN4UN+wtFtkxAXt9geUioszBS7/tOk=,iv:TPRNJbMEvZTxXqcEAvEUIvbVXZh5g2qtkP0EqCK0qTg=,tag:EeHUNni5KB0m33Ia75+Kpg==,type:str]
    version: 3.13.0
