apiVersion: v1
kind: Secret
metadata:
    name: media-protonvpn
    namespace: media
stringData:
    wireguard_private_key: ENC[AES256_GCM,data:mp13NpXf0yZGGFyb49kiV/XWZVoSduVb3w8+0XIFzvBL0amOw86wKgV0soE=,iv:o/VYMsUBcaViZZm5r0VFuj9brk7fCRw6Y+/w8+GyfFo=,tag:ApjFQu2UswnZZStaX8Pr/A==,type:str]
    wireguard_addresses: ENC[AES256_GCM,data:xYZtMEpXTnv4nWA/l0BchFrrQQaSZImdMbb53yGr,iv:D9b8YRQfCiaHXp7iRlJEjzR043NMjYio4pjTrIz0nmQ=,tag:ufEGQJlQq14ddHPGieMzgg==,type:str]
    wireguard_dns: ENC[AES256_GCM,data:ietdTDkFRWOMcBxYXFus1xKSL6+Rj20=,iv:bfX18Mg5Wi7NbHEG8ySSzHwA+sQyF8+g/R7tlogB4/I=,tag:9vcaTJJCfglMTQlNNIhd+Q==,type:str]
    wireguard_public_key: ENC[AES256_GCM,data:T75P0XRJ3ldpGfcK6dJFq5zp7N4jXmv09WqXPT/bAHOaGTnw+UVodXqxKdo=,iv:o9srR7RyW16gGP5iGcRNv1Jyw6ICkvdOSm6wXENbUao=,tag:1pZS0cjzZZXXUALXP8Rd2Q==,type:str]
    wireguard_allowed_ips: ENC[AES256_GCM,data:+UjoKA28KiW2aAGriuo=,iv:0N4NMv6W3k6ul2R7CJo/6gGTDpyVqO/2aeIHSq2K8eg=,tag:yHijKhszXbuqBdI6YhnRiA==,type:str]
    wireguard_endpoint_ip: ENC[AES256_GCM,data:jCSZIq8LCTtbsp5bSjo=,iv:/PJg03QOR/64EnIaGBa9TxH9+xdjxCh12ju1BxE5bj8=,tag:2Y9sBGaOyUbjplIhh19dRw==,type:str]
    wireguard_endpoint_port: ENC[AES256_GCM,data:b/6CU8U=,iv:xt3pc+R8Et8F2z0jv+F79rIY96Vl/+c00gcmgPoBRMg=,tag:Sssx4Z7AMUFzz4Ex9ToYTA==,type:str]
    wireguard_pf_up_command: ENC[AES256_GCM,data:ZswMce1zpulkhZWBP4XvENY8ALbx/ep2ysLIB/WzVtLsXksN6cBiONe2udek5d7YSASKE/Y/Skhxau8yp910W9kqO6qgQCsKZ0CbYHGhxL8wbx2jgB2RMXLyFi7G/RvGqRjNHpGKJYJp1MbWb8eOybRTWv4ntJlOmSFHYAxCn5aDSvCGo9tvunoCvK7SqpbpfNfM9ZBkLJSuTteZ58OJRn7ufjjATcy0hCkbKxsI7slA8pq90fQv2RUMJkAihFh4lJDQ6/wxWgQtgZXSEwhcnE3d5MWUAN64tOaOikUQY+hLHXN9,iv:ofdfSdJrJKtxSKwQmCEFSmaBOJoH+Nma7bqCpGpQ7z8=,tag:Qi5c6yMAKNZpXK+bYfJmYA==,type:str]
    wireguard_pf_down_command: ENC[AES256_GCM,data:K1nPtkb0MmKIqekaxJ4fgPmz/THPfDX8Vm9xnFch+U+U4wYXXVSsMX7BD6vUpqgQ5aVkuV9vifDjzZd6irQMWSw3LZ8hZGIw8FRiS2LD9XNbwh3v7ccAwse52KZeGxYKEbsHjRMXheLx0YjZdLcAeNI7aBE9gJLpHbe6y4t9LOIA+nZpT5qyyB6Qh9061DwMnTzhNoEC8wou6bqxkO9rviL1p1XFyqZ18g==,iv:O14XOSJ9vMIfHKrWom4rQP1KWklbNlXiRUi59z6cFp8=,tag:9zwFaiMuJEv+CDJ6m4PS6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMktOTHVoZ09tWkQ4eXlz
            RTRJMzZwa0NXU1RmWFYxZjhIODNtVVBxblVFCjdGMS9pWFhaYzFEdUV5N2RuckpX
            NDdrMFZaNVJLWjg3NktoYkFFSy91TzQKLS0tIFEzSUZ1b1IwR1NwSmt4dXY0RUVQ
            NjBHeTB2Q3c0dWdKbVJlZGM1M1RESTgKjKdjkvhnsNIq37k6l5m9VGdrtfoAHUHv
            wXuQi9pu9GqmsJNNmdrL8mV3xVIhp7jM9hp/cCpvDhjs3968DzwZ2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTjc2dTNUYWxlZE4yYkpI
            dy9sVkM4YmExS2FsVEdMZTlGUUtYY2RtaWhRCnF2VkZ3R3hCK0x4T2tGMVE0UXJ5
            R0VmaEtFaGthYUpsSmlYeVhPR3UvQmcKLS0tIHB3cEZWb0VnVkwzc1NTejZZU3Zt
            YThjMi9nRlAyRkxmYVdzZFJ2MnN6RGcKz26qJWCEA+3I5GkDTImOyVNekzFm6icC
            RGoamQwwCj5To7ZB3HFgCgWlIWiX+lug+dV1bfvvUEu9oObf4F2v3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T19:54:08Z"
    mac: ENC[AES256_GCM,data:R6NzrjMxUNAelSC9YDueZHabfEGTYzHLF48GvAUS7xSVuydQRjiGCnx68kTFHK4CUP2wQuh8oV6MER6Mc+JD1zqEV4+xSDoPCwQR3dqftKvCMB6X2xyFt3/kU8BwMAzj08N1SktBDWCT1WMaorEQCgd23s4glmRvX/BNHIJCVg0=,iv:ogCmc8mdLFA8Sg0fAikkHJ+DSAJTKF9CuKalopBn2JQ=,tag:FU6pGLyZwzL/1BUqN/AoZw==,type:str]
    version: 3.13.0
