apiVersion: v1
kind: Secret
metadata:
    name: media-protonvpn
    namespace: media
stringData:
    wireguard_private_key: ENC[AES256_GCM,data:WKyZfxIgOHOH05YcANiszcePiAKuiGWkhqoS0aSh5hLdFKvDS690jxiKkq8=,iv:OTdXxBO/AYyeqierWsClWEuJ23J+KAPT9GMZkO3d3cw=,tag:DMXzdbF5WuMpY8dzxdx8eQ==,type:str]
    wireguard_addresses: ENC[AES256_GCM,data:x7uLIsi0T41ah12Oct79ry+eE/ZJh1nFIexjKGGh,iv:Qc+i/TyWbhP5dKSduDdT2nF4eU+coqX1w8SG70XBTaE=,tag:18Pby8AO1xLH7mIo0opyPQ==,type:str]
    wireguard_dns: ENC[AES256_GCM,data:w5lGhHjBxd2exLJ+T7Q=,iv:PjD4N4Wwkee55rYeSTvLJ0BWp30WvIa5R2z3cIRYXmg=,tag:mSnDr5brJ5qgCtlR1pakCQ==,type:str]
    wireguard_public_key: ENC[AES256_GCM,data:3obEF8D0yE454bIUaBjl8V8YAI/ujcodBBbqlty1NehjrgBh4anQ4GYu3Po=,iv:ULjJr5ugPy9UHcWwXKHukzvHBLklO8UY+gE1ja/fD28=,tag:DB7j+7iki/IkNzvM+qkztQ==,type:str]
    wireguard_allowed_ips: ENC[AES256_GCM,data:wEIZey0Q+4c3rxk70yo=,iv:JwMFK0q0gdek2UVW5qot7xsV0JuINbMHgXKPlsVTYIo=,tag:hk6ygX+l2MbSJhIy7vS3og==,type:str]
    wireguard_endpoint_ip: ENC[AES256_GCM,data:X//F5TW7FXJIwgFsoVY=,iv:so5KI2Ydispw17M+7jbbb/dPKzl9oZEgD3k+f/oSlkM=,tag:2uubw6uN2vWXJIotSddAQw==,type:str]
    wireguard_endpoint_port: ENC[AES256_GCM,data:5C2wWqU=,iv:nKtROf4UPDrbbyOmUM1LQZcClzKBT1eoGVpLqwH8YIg=,tag:ne048+r6UaAyGDmpoyFodg==,type:str]
    wireguard_pf_up_command: ENC[AES256_GCM,data:Mw0wdbPabGh13G5+7cqQtGBXpGz9ZGp43hWAKa1iPMorn/xegc6mLwjr/Hej735RlWbljxWBPrhITts2lX+KeaqoqqOpFuhyHFR9lZKxbiV36SQsU9CP5xhbCjfoEAVdeXWHn3svhANL5h/0n73Oej/dmCXchlb0JodvJ1DDnfZfZho0WBWgLcAcfW19xHfML2TKLNFn7pp8+C/X2VVCEXkO8bIrmK2a0E9Azwf1QiBb4tSXXuU8kh+7SSRX2jCwfqfnXb2hyh73Aooy2lhKjCmOXvK222+M5Mk2DXpvoMmTSZhK,iv:R5BhTlZmn+VZR+0LE9yj57LGsbTuG4E2ZIkcKUh9KN0=,tag:5jAxGoQkvDlz+G5E8ircRQ==,type:str]
    wireguard_pf_down_command: ENC[AES256_GCM,data:A499mOpilG3bZLKRJqR6dR2+U//qD/zz3GPRPDjNQHTtl1YkI5rGB9U7DWP1inHep0UTGHWbFY/ZNstH2khODotKQDEuKPKSR8e5TSwx4qZ+gHx37wUZQ4UkCLTOUCOcHaGIlA4Bk4I+cKWqK0M1ib0+6hDHsOl3ee+A1rTm2MjM6Zs9pTwpkIR37+AUS8lVvWjCn4SfFTL4IGrCMF6g5Wsz95M/nBPdgQ==,iv:DP4s93vQvVHoDL+hqAZXb4K2C25Ku5G5Gof2eG+DdaE=,tag:HeLz6+sEXBnPhiEWmN1JRg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYnd5eTIrQjVXRUlmam14
            MXRnV0ZKNlVlaFVIV2ZvVjdYMnQ4TTF5N2xnCm1vYWhLSkFkVU1ISHZHNFJXZmQ5
            TE45VjFZRHNxREpOTHpaU3RHWXdxaEUKLS0tIEZCaHYzR0ZiS3RmUmJYdUJPTGFJ
            bnY1L0duV0hxeFlTcWo1UVdrbnVtQncKHPqDrABasZDEBhd5IUK+eSXzqnYLZxbk
            fPquerpIYLonSiDTTO9JmXnJZKKLvbPRwmmVks3lRnPhvMvjYxirhg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4U3QrcXpxMkJUc2t5WGlC
            bU4wQjFnNyt5Y2ttY2c0cWRDWUpvaXkvS3dVCk9QY2ZZV2gyODVvTE9CUU93RUdW
            UjlpeVFKNk5IbWd1LzVCdzRGZ1duZVUKLS0tIHpVZVNLa3N2OFAvY2hoWmQxWUdR
            bXdSN3dhMzJkOFlXaW8vL3BDa1RhSk0KP3a7w+SofzsV/B+iKFxRBtH3UDIJGGc5
            cvwCHKFdMURaFG7Ut+JzV5IbnTA/R+espafFuMx6udUU9Rqw6GbJPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T07:51:31Z"
    mac: ENC[AES256_GCM,data:+FCkn0eWjNdjSKuOlu4X37rgDOnab0cqAEPhol7Hkx0SpNagvWypK2Jxp1/wjlNIYZpqYEXBAWheofjQQPiKk6EH+I9OE26lyrLMPJ1hBqGVFut8oAF32AG5tiCXcMYDrpavNMlyXze7S2C9Nqpha+iNrSRYLZ+KZ4eVMMNn/h8=,iv:dsyPGFEXySF7UZxI3EDB4brLp/PZWlo3MwY6XaYZyM8=,tag:7Ci7/Tw6Fsv6mw2UnSVWdw==,type:str]
    version: 3.13.1
