apiVersion: v1
kind: Secret
metadata:
    name: media-protonvpn
    namespace: media
stringData:
    wireguard_private_key: ENC[AES256_GCM,data:Sp3nGe2ut15gTkCcWPcc+g86pP97A3a8jTBQCdu5vANm3mSMkND+Eq824xY=,iv:qNkKoffAFgrg/RkJUTGjfqgl3Y0HGUFUPHbiI+tcJno=,tag:X6HFisJQ1skj/nO19QJhQA==,type:str]
    wireguard_addresses: ENC[AES256_GCM,data:Ovl7mpRVW172jVb/4xDHDACEuGjh63wTvxaRTTPM,iv:KRQOXQ2WZKX0Y8damRAdlO0H5L67b9vIFlBeWZgMJX4=,tag:SPasCYOOSFAjMqVaF5qz4w==,type:str]
    wireguard_dns: ENC[AES256_GCM,data:VqTb0BInrPaRK1dV/Ck17KHg7GRc048=,iv:WQ6NXMw4+r0GsD1iU/w1OQ/ugUuVXhmyM64/Dr244yk=,tag:1+3qVNePP5gohIL3gNRdiA==,type:str]
    wireguard_public_key: ENC[AES256_GCM,data:7NgJzQZuMpfeVaZGsKYaFjR2pRfp2U8EieWdVcps0YULTirq/vQzcaiYcm0=,iv:0ejOcbi94occJieguc7/r1j80lAflthD+1I/8K+SR4k=,tag:UAj1m2Zy7+1ISpHxHIfpYw==,type:str]
    wireguard_allowed_ips: ENC[AES256_GCM,data:dubSDAT0mUykTPZX6ko=,iv:/qlhz+An7ksA5HJvpbFAA++mU/YXP4f+XfjqCkwxMDM=,tag:JDh8lUbLwrlnbPFP922KPQ==,type:str]
    wireguard_endpoint_ip: ENC[AES256_GCM,data:hsLYwfrkTR+y61eYS0o=,iv:wXHOvlcysFRnrnkNx1GfK8cWJCiVQVKAssNMU6c7dYQ=,tag:l6dyW2WG+pS7odUEIYufVw==,type:str]
    wireguard_endpoint_port: ENC[AES256_GCM,data:3Myoau0=,iv:mG9WtkHKrolJKgE7H2efLrm4HhQX+BFKH3L2ARw2qcI=,tag:4zUKclM8+cIgtQOWujLT2g==,type:str]
    wireguard_pf_up_command: ENC[AES256_GCM,data:eewLsrXQ7FiZG5JYF6J9uSBlXJ0nVxbmmcO+CJShDw2N0lIZdqCHxEW2YBKicCaGVT0K1vIG+J2TVpb4SHMV0Ql564AD+3PPuOhqZtf2Uo2G2i4eNxiNJPSrX9FjJUeM+V21Bc/Cs8rm6NMvmZXkZMPGEkgeUh3RnbYrM/sKMTllcwyw4Cql3wDNnspLFIS1cMpfi1yzCePci0EXkGWfNGkT3+mERB3weo2eGkynd6l+LV+e7T2zu48xlu0PoRSRjDrRMjX8QZs6w7pnttVXdzwFsSm7fX5G56GbPLzwD2Y0q8k0,iv:omKZre29wX0QNecwY+CBh87FjvCXKTgUvw4I78G7mRw=,tag:dwmwz4pko4yLVUsDgMNnog==,type:str]
    wireguard_pf_down_command: ENC[AES256_GCM,data:7qdzIq0o8Tbg3IOkKGHHDxwU385gXMzfeYAJvUJWdzItNiu0oSVvPIYSCydeY4emQc0hBuk1nXnyAhhcPx4VKtOHhw6VuJzTssoeFeaSOkBbi9ZToPKriNBVhiY61chxhY72rfP+EH512xIOXrVRmKNDKhMDtzIpDshBqbK25garkSjx4tr2DSYXjGJxp9V1l6CiJRNIPy1UNRDqCJJh6BK9GHYqXfqiBA==,iv:QQhxBUdYlRMLL7mqgSNK+JBHUpJI5JgCNWkmw0DvpJ0=,tag:smY8y2iK22q8GhYgLvj4dA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Y3I3Mzg0dGRKcC9GOWxr
            OCswVmdLTDVTVGR5Z1dyZkRqamRqcThSN0ZNCnp0ZERMVDFqY2NBcHFRUEVOYzFH
            NmRmWFpVRTJVb2UrQ1Q4eWxCT1dWaEUKLS0tIHIxOE02T0ROSnp2YXZxSUdEK08y
            VThjOVE0SUNCeitHYmE2ODRYeUcyWk0KxBqMOD+Ldhfbqf1MXsqhbtgstZcMGcjz
            plIXfuoqoHeGBlyr+C0UxXnIbGdN5rrOS+iCyczHzNUcaXq5V+cRNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZFlaYmxNaEQzK1g0T21k
            WlJ6b1NVc2g3ZmZpVlVmbXhDQVpEVTNYdkU0ClJWTTRrMm1GbXpFV3Q5UDFERlBX
            cHBWNjlSdkFpZkpRbXYzMWlvMDhiS1UKLS0tIEZ6d2ZqTDJWSExSK2ZYa1U5R0pp
            QUIvZlZxcmlVV0xJcCtPOW5FQjlEWG8KdoUC0frUJkEOlhOnY/Fa68eVhKqK3LpO
            2owFy6/gCgSFhWRuD+nY2f4Bz4y07I4FkBexp/TJ+y0oO7Fw/q3sDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T19:46:45Z"
    mac: ENC[AES256_GCM,data:3Te8tBuUnPw0u+4F1F2N3NrK2hTqPKu9edXRn3KVlaTMXmaZc/SwkA/WM9MqcgtG9qu+Gdv2vqtyYoY5e9ww6X52KWivZjhh8GNJ2s9HAVo4+wEpzlJoiKGWfSpEdq2AXeRFow24XYsf90QqjmfpZ9VL5zuOumw/QdT7FILCtIM=,iv:aTqetaCOmX1bFOx1GZNoIew7cBe059z1aYf2pVaE+Ig=,tag:CMieOa7z1/nQKM57j+zrdw==,type:str]
    version: 3.13.0
