apiVersion: v1
kind: Secret
metadata:
    name: mimir-values
    namespace: monitoring
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:KCK2wD+6bUa+zocbGe5ckWi1nK1okAUL7WwpfR4jlW0cvmCa8e/UnZhcApZ2A/9roE8yFZHeTkcXOjvhKtLt6eDivZyU8weiLslArLPNrB7hdHru7Uk4Qs2dI07mgaevarb/edPzTGHIgfmCHyJijxXtjDEZv3kUphyuSiT6KWT2yQLwSRKcaRNc3CcYUvVv0VcLkcs7oGJPgs+x+Jm5najSye9smQ0ivcPaPAzUAKBhMl/LBHPNBM6hRnJ8o5XQbaZ4iawjiOaHVBqegHDSbDWYcP7ypEXGhUWF3MR4Wa88LfIoORWa5XelQEpJNhfQPEi5rB4WwpXBtSvg/z24XZtZcYJsoq1ke8IUzRvN8UOwNWrc0roeqYKVoDZWFWVCjQDzAq9q1EWiaimPJcC23tbctMoaIjpgqpfzLObiBkP/clCMtB2taXZ0cMFn3MtJmFBsygZT8xsHT88ifETd47dhXbWOB3YiERPiQrjWSS7QKXX4y5TlndvTHutLQZOl5Cq2ZiWBvYh9potQOSF7RkJrU8x/6BMR/6jSFeNIgEZM9aZNV2ylOv1ZMk+x6y8fO+hc7WE+evk1kFjLpPUtAhyv3DNrb99VgrSLbAD4FZFInKLcejsL1IkKWauHa3zr2EBjsNwXZlBi2dTdF3VFMG2mkjX1UrNPrw1Quc+o0a8sLzmybAI1qqnFhDTcHkVR8LSZ7jKNF2W31tGbQTa9WDiEiCz9R0124V1p9n42SdVp0nBvfEoKsBdJL3qdHQvuc2Ty5drsDJpdxxLyAByd6hyeKX+TKyL9QdxC4cOGz9dnGBFLD87Y4K0u4vMecuz3LoVQ8i1p/fux/snWoGVd5CkS5WGzTxpgenRgCgakFpO0StJeWIGZCVue4QAzB7qTW8f0T3Of50UkmqXcXPMGBTCU1Ul7i0xq4ZzDj4r5Pr1pIgEXurhXFKqH/6uLR96B1ATv4Lp/CpXfLsAowQX7H4BYKYw=,iv:JasHDG+si5it+A0SaPiNuA389MInPmb5D5j6H2hLuQ4=,tag:nYXoz0vCOIW+AXGr5Mk+Qw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldzJlNWE5OG13WU8wK01R
            NjcxTTBXa0ZDRlZJbktCUzdHWm1ZNXhnWGhnCmYrVVFVRWc5SnBZeEF6SVhQN3ZI
            aFh4Q0lFVVhNd2tpdW0rMUJMaldVcGsKLS0tIDFET0s0ZU92UVJHNTNSMjVwNlBh
            SFArc0laSzdwNU45VENZQ1NndFhsVGMKnF4APssJLmkhWhY2YGqfTcSMZ8+nVpJY
            eSLs1g/qDsav6dqctm18Ls6RO+gHqjXqx/HzZn5zP9ky0HFgxidw4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTVdOcEc3ZWhzQmNtUHhF
            cy8xTU1laytNcVAxS1B0ZjdjRDBHSkNzVVY4CkVFN1o2TEhwWG9oUzcyTWRBVGk2
            a1hjSTdKcUZjcHdQY29yTW1XVDZ1TUUKLS0tIHFablZlQ3VPWEZpWkQzcnNydFMz
            QWtQeE5MR3JFQjFvZlZiMXNVNEFuNHcKtrjrZrvMgwAFBfGvQOxb0mYDj8EeJfOW
            EVUpceEOdRc+aDV2slxTGlFIf3CuZaDhcyehGrsCOshk/LTsX1CXxw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T13:03:03Z"
    mac: ENC[AES256_GCM,data:A/dC9zF8kgFpwDbYk4Ors3z8IqywTT5gfW1ejpvb4SRu4+h3oFX2mWdhifuzuGqVvYQvRYIMlOkRWY9ctW3+jq3j/LdnlJi/srrI10TsMdQlTnpQ16Api6GorDwbtkpFa6V+U9KlGBJRRl7HxV82cX/ir7HzOVLOEPeJHkt7s5g=,iv:y+tWEZgvELK8u3GHQGjGfZytqNLIL0kujb/Z/WYNdxA=,tag:PeO/GfWkLCazsgtEhoV1eg==,type:str]
    version: 3.13.1
