apiVersion: v1
kind: Secret
metadata:
    name: monitoring-s3-values
    namespace: monitoring
type: Opaque
stringData:
    loki.yaml: ENC[AES256_GCM,data:txwXRHD6r1f1RL2X3zk3WcTItxjanCBkEapKlRCQ0OzUedr6GOGqNCwU0XL18kY3+igd2CT0d2bgFK3gbswvyt1rosJ6LfP/q5wfaP5nNdhJYGyBbGdK1X/oyFrSpq+03GD2HVocqzkZO8OY7a8dbzQ/y8SmFtstnxNy8Ozp/SxS+bIaCbBTHEE=,iv:XzLMF38fT1I03t12lZVwP7vIT0k9YfcWE5T58g7VJW8=,tag:ZVXgQgFoVYwe8If42MjpPQ==,type:str]
    mimir.yaml: ENC[AES256_GCM,data:r/MQUjx0eTamnRhdZVWh+6qzsYCA1AbNC7vYElf4U8GEooAbOUP1jL6c6cX6dxY9/ES6v1lsq67PwAw0at3NSJXAkm2GtfDSgu9iBje0te0kSAlEL2hey8PhCfi8J7QKmz9aa2EMt7aWCR4xiOPcaxk0+bnMQbr9Vfv7up0el7KBDBqlzZEUS+DOpUnuuUk5sh+NjbAq/+VTn7XmGGkcASEousuWwPqE1gOPhUlleQ/2jaLqqSF5Bbsh1rZ/lAQk7EcP0zQJMHonxxEisn6fyNALqcYunyljixzfAXLjxzoOr3W/KUWZDETo5gKbgkg9WzP86D23+7jx3YgJa3Mt2doEZb7MELqofu9XNe0DY+JlEjZkdqAwuS2WNmGCzz8uUIYzcjYDdSCljJUZsvVedt39JzZjN6qTjAbqelKJRMB1VsEIunoxig4jluN5r2dE2F54eG4UQ/nvBrs55tbg8PRVNruXuab/1ffu/GzCEoDSz3RV3sM424x27UiKeUllQh0Q3kBZgc2Pn3uccDq2ghwyfVtNp/D2MrXE4Lu3gsTMkJ2yUuIKw+cSUo+tYfZYbRDOarbzUNlbLATsuF6rmmeq078eUNOX6Zf5fGpZRVRlGY6dR7mEmb6zDbRd7z/tBQjH0bi8rwC35dKzska0It/lMH6Sqs9snEJXGpzbvGXqtgWzgkJHo1p5W8dEhTrAHXzzQbW4uefcJTOZYT0wpG+hY4CSLbJ6W2c1WyPPyxebeUdGAR5HhXGSEHH92qlvoMiY3Eu3u9rC6ec9OT9jMpPRsBrk44HX0gravO0SuIzSP7yW1JSYNgGULFtCB6N7m14F1LcOs+LalqfxJjavdmdDHjWR,iv:YljBX78LKltCz59JCN8fcJupjU5VeL80nkuQeK8kegA=,tag:FNwlFXQqBj4cHSMndCbq1g==,type:str]
    tempo.yaml: ENC[AES256_GCM,data:KIYSFN+GaxlCycXvP5D96UbqqR9ZZYugEqAV4nBPwsWCp6D2C0S/cO0/fJvZleFHu32MErm2c3Zv/JzsU4o0eqTlAqIhNWrVEw5ds95lAnnzckjlhDGiLI0qpFzBv1uITsKJ44KC7/NvXc76hmDIpsu/1fmamRzkxgUfenlIhbKmFBHk,iv:13wuVAeD7P7kvRN6dstvR3kGqorf0RxJXrAY3zff0OE=,tag:DzD3toq5pmIltcLlCL5iYg==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MTAzbEREZTljTVZVWUJj
            THlFZSt3K25BMEx1THRXaGl1VlhBcFhHVXhrCjZRbmQ2V1M0ZnYwUWZQTElJV3ls
            YkVuKzV4dlE0THdubWR1aE1GaG42WjgKLS0tIDg0NlRjajU5ZmdTeUhhcVZzb25B
            Mm42ZHdvQ1YyanJlRWE2V0JRVW9PRkEK71738TjFJG+OvpMbh29ooDilIO7R/GpO
            6gO0Qa/TfVG4c2AZV1usx2B0GXtJjy2R+Cm7q1kZUMjWE6bvV9Df7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T08:56:39Z"
    mac: ENC[AES256_GCM,data:9E8+mZe4jwz1p2eiiRpoW00B5ojFmYZ6tmMLF2HtVr1yIzB0fA3z0mD74B0kuIh9oep0Q4mR//o4VTaeNgPTHf+R6ctWbshKNOL34LamdcOqj5CY4MRZ6nVzAzUEKsCaDIuWNUowhhsyb0lpDQ6apfYbE4ySs59exe+JOawQiFg=,iv:tkNndBBCLXm9wnS9pKAWILYrnu134VCRBuYjBdQolDE=,tag:QESnbAlhegG052Z50h9xFQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
