apiVersion: v1
kind: Secret
metadata:
    name: monitoring-s3-values
    namespace: monitoring
type: Opaque
stringData:
    loki.yaml: ENC[AES256_GCM,data:C7EfU5E1thEyvl9zx90iF35A3uhKiAVNqHo3NnVPMHjm5TxbiZbQiDNyeUYIn00mYrm4nMfONBQ1g0+VuDqPlHr22Cq5XArOx7dyOsrn0RmQNSki2DESfAgBGvSt5UWgA6tsgKPPgJK+DVdjdLDxWt4WVpYBNcQtOIKhFFYGq0EHt6ROXE6nTQ==,iv:/1UQjK2ByPB/ymay2R7bZFuEJFx3304wx5VOO3BmIO0=,tag:QMwAcoj5fyHrD881SGM3Cw==,type:str]
    mimir.yaml: ENC[AES256_GCM,data:iBs+Qs4jd5y2G4CGMIdXfjiWJVl8vBS9p8439PtnTW4OdajWOnWeJ4QFKCZDbw313FVkARJcTnrpEwzyrj3rL+zLcsf9BrBMKTHIDhehGXn8jhsKg107YXFzCCuzokfQ0mTiY1BBpJueM09I4TNCprdAfomQlti6/vCvHnzvlpme149qaz2u6YYOafeuXx8J/vGNORYUzKPW7DDYBpLsnOYwsQrsQ478NoUwe9UnSdSGMvzm/VCg+YGzAEWLXDhtBopUcDwnUt6tx01pcexfieNC5s7rP4EBhvQnw+uVpb8nHqoMwppdotrm2O2lz3mDaDuK7PatpnmaAgkXNO7Rei+9ITYMWY+K3mUgaa1mGgtEAk89wuXz8CtNSRCPdaNhpr33CVnDq/RubSZF4JOjvsQ3KMlTgunHUZ0KcRrQgqqtynUJrPoMRANpwUZ5xrGl8S9V+2cPgzEHE8dlhujDrAvNeAWqILVHs8qkKVrNosZLLItRxN/FUmmhIcvq376BPmyzG6jDRjVRF9GsJGfboFLgndfMpuxYz9SH1Aab4jC7ldVRg7+Tbi9XInP48tYtGH1E9c60y8hk8H5O1vnrd2nuRs1J9PjD6SWianHU6m/9bbXPeIro6PsxsRpRp7tJ0oyAL16s5zazwEgwzUuMBRprZV0PFHObYOdr4d+DYXSN+geQT4uQdnbUkTr81x2uMsGde7aeRNwzPMX3u48EoM8VYBcWIdT1rhkB2R7kdfOkhE6yC5F0R6iTCcMYprh1qdvOsvpgubnbHqN5M2BFBSILVO+4NG5Ufhj2QDMR2AOfCJ4S+IHzVHmL0wdqHVkG+QqMrzZzYXAHpr0q57BNxvERciU=,iv:l9s8r/gcUYZTOM+Y1q4RXIpYFPhKJn9uq1XmaQ0r9CU=,tag:p9sQO98vGnsPu+7kuDdLQA==,type:str]
    tempo.yaml: ENC[AES256_GCM,data:Cf9JhMAk8wf24NVcV0DeTs570NDDdMk8Zko7P3yToDhjBHmPVUMYFPFDXVZcOvws7+t08nDxuNiWlykVii+qVIa0ZsYaQ6epjuGdjlSIxbhVEhhO5PhR9CEoAY5IVaTES7gGw+J7t5+pkQeeiprluDAhZ0DoJKqt6iMTLi7ZpZP5jDE=,iv:WTKeVC/8dlGh5Dsytv+MvNw8gX0p8nXU6wTCRJgQVVk=,tag:daXfE3rg1lFYeiMVMORsiA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Ky82bmNLTVEyUXR0MjRt
            K2s4WVlqMmgzTE8zeXZsTzR6MUN4T3dDRW5rCnhBRFZpZlFETUdzN1ZERGtlUU5R
            TmtPZTdwUlpDdjRsL2FyU1FjNTNuTjQKLS0tIEIxaUxuWSt6REpLdThERUtYQWpi
            VWdNMlYrTkxodGlqUithVVhCTjJqaHcKanUkyXhbQv2f4veQd8PIBxA+B+iqjXVO
            vD2gOLwhCragF/+OpT2y0sskmbbFNl/J9rvrjz5GsW4PM1PbfaZkEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNenVHU2N6cnZPaFluYUR5
            SW5ialA5K2RNdTNHUlYrWndGYW5rWTh4aHlNCjlnTVc4cTIwbEZxSnRrUm1ZY2Jx
            Q00zUGYzVTR6dVpaZGNoZytzYlFaQU0KLS0tIHNhU0F4TE1XZkZ6aCtmLzlOZGxs
            R2JkZWJxd1JYT2FQZTZIQ05LOUl5ZVEKqeJOT08ndWiOtXIKeGdgQGyvWhNdWyJ/
            lhvps5rM2ASPnBFFf54PXa2b0r4cqphBQMf5uG7z+Jo/DcGGz82TsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T13:03:03Z"
    mac: ENC[AES256_GCM,data:PbPhh8oG2oGog6pKLVgQkIpbfEWbTOljcQZEVN94Y5JepY8j/9/64XJw/CkmGQYY1hJ1lPwhsrWezC1nNCHQiahfjOgWBroMV7BbLB7FZl7KeLnJzoUoq1zMcaiFVFRnvoGvruOIPH+MsQTtN3hheAm/rxVNRaRP45SLr+XHd34=,iv:KsYY45x3AzL3u0+1NRhVeQsdSftoCwZw5C9fyk193n0=,tag:OVrTLFZMIXv9fQ81kw5OUA==,type:str]
    version: 3.13.1
