apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-postgres-backup-credentials
    namespace: nextcloud
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:fC0qpbiKrjai04BuqWz/fuEJv+QKCd/xWnJKVQ==,iv:1OwZgrs+BQVyqkEAq18UaKDLvbATcTnnh8vhVGPzdSA=,tag:0EQmi5aJmgFOBs7/0q0g9w==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:41g1h5MugKCvWnnIOllIc6n1t77m5A9T3mdk38lDqF0CrTIVTrBs56nPe23Lhtae2ir3PMQ1kV8=,iv:qPsOiNflTLWj2lkku70/qd7twOObgaPO/JcnLcKI9vw=,tag:WHxLyjtiwFGt39I169bRug==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:lPHPsxybXYi/DAwVpMADmk/jsVHzRWCY3/w0SLPFu+OITTgpyQDZbc/tnj05eUtpgOhiFFNVkxA=,iv:uJVz77senFAZlnnztQbgXT2FeJr86xY3BzEJC11X0e0=,tag:1Fj0uyszTteOlkWe5dJeOw==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYnIza01YNW82amR4d3k4
            QUV6U3E0WWZoVU9RZHU3b1RzdWRlWVF2M3o4CkdXd0JIQzVRaXlRSDIzZU84RGpC
            M2ZnMVFMMUhHYWxmYU1jMG1Vd2lqa0UKLS0tIFVrbE9UbkhNOEVPYkRnd3c5aGJq
            aWthak4wVEg2YjE2aTd1amUyTndiV2sK9XX8pclsDUCwhR9VpfOAd3g8fRCdhBNY
            r9wKZTZBGEABO9kzWa9IbJaoW7vrGRF9OvZC9M2KkH/Rp4sg53k7wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T21:46:20Z"
    mac: ENC[AES256_GCM,data:pm9JriSfA1yZ1SxABobOpQ8vRhv4NL+V/fVhD84vdISEhSffdXVS0ZKrTokXpLUO11PfYDAXF7yghEBW/eiId6MWrOOwIwpoAnjHTgGwrJz9dzHh2tNdt7e2lp5Mi9HPH4PJbyscqtzlWXNO8BU0q3LPUHbvp4xAWslxCiXoVu8=,iv:B/yW0wbySeP2D+Vd6A7xUSiPh/b2O4JUVWbilBy/Icc=,tag:tqiBr83/9FlbY8nqN+8MGQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
