apiVersion: v1
kind: Secret
metadata:
    name: ${nix_remote_builder_hostkey_secret_name}
    namespace: ${nix_remote_builder_namespace}
type: Opaque
stringData:
    ssh_host_ed25519_key: ENC[AES256_GCM,data:fdUEGJe/FBlrC3EauuCxqnMbjV5dfJj0DIMOcs9/DPnBhWArS6SY1hmdYNnNfIHtdRCGV3nUtwt74WEOJb1NzZxD95FAcirTmh6TnrgcP40RlZAFLeVfa10xhuR9EYKz3nDRtug6tUQygHHqdLoAs1qEY6tXA+18Kklq1YT531DonqcyA0DiwgukaayjGBaOFfM333+2c01Dh09Jw8aKPq+7/FXLe5rRuDYax400v6C2PY23P699NAy/2BHRPsFiOqSbQby5sqLZX/0GbklGpWjwlv94LRANq54OGK3l4fZ16C5kJ6bsp/7G4Kaytprqz7FKPRsfX/TRdP83Cgnu2ZP8A4f6eHmmg3eOkfj/8IERwgD8wXtH3ard0U/tFOXNAUcHhwg/y6eEN4lPZ42sM1M2aaE4d9EsQfes8gUPYaeula5H4si+lVo1Oii+vQ0PNm2RCdFw8SADJgD7P7z8Ns2gexGBpTcO4axk9KsOPdmEsLgHFzSqVZV2359ME2fMHmAsbAdKKlbxOl4NuCyd5ZYHqnzBR0UDcTF7,iv:q9xbpAa+bUzHQgAMhciED4NQ+xiaxjLMWcqA4roHPzk=,tag:d26gOPzoVuaYXprraS23Aw==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4OHFGZFJjMUN5RHhCSGRr
            N0JsdGo1RjVmZnNEL1gvVDhvNzF3TTZOeFg4Cmp0SzhMdnNsZ2x5OGxHWEtQQmVL
            Z2ZPK1piNkh1NXJzYXVZRnBhWTZKZFUKLS0tIHJ3cnNEY0ROdXg5STczRit0OTBv
            ZzR3eTV1cVQzbTU0YXJZYW5RRG1sRE0KHq+gOXmPQlGIddE5Bqj3dUM1inrlNwq2
            WYR8m16flyri+d81JS+8Ulmq9Y+0h3SXkMLSJscQd+TgkUly5Rc6lg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaEYzN2dhN0J1TFpQWEI5
            MHVlblhVbWw3TzQwQ2pTUy9kRDVpS2owNFFjCkFoa2lZTHZKUUx6RFJ6aFRKTWEy
            U1dYSWRXZ25NeTB0NWV6dW0xSG50Q0kKLS0tIDlkMGtGcTZveHBpSGZBeU13Z3E0
            UDJ2SE9hTytWZE4wcGMvb3FGTEkyUjgKK1KcjBHARKOSuANuDdzGSp42wAB+ttyp
            pMV31v9RBT9TcAsUnMo0Bhc/I2veN4+WtmHoh+zv+jb+IgpdRwLHyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T14:57:45Z"
    mac: ENC[AES256_GCM,data:D09E9srycvZBQj/bu1cFJ0eM6qJbsu0gVEOlsNBNgKwmz3zqulVIhj2fv3JCgWu461VgvWXcry+TQ763jPKBae1GICRg9y4L9G26Xmr9mmE+fBFiLS70kkAuhce/7FhAMvfsK9UF2Xq6Bwl9VNx433dduK2kPXkQDTJkRiUJMwQ=,iv:Qn/TCGOWKdWZbM9mfO9RPgeGmMg0qjZDvoy6IbfnewA=,tag:6PHSBkGtxh8AR0pQqdfxYw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
