apiVersion: v1
kind: Secret
metadata:
    name: s3-monitoring-credentials
    namespace: object-storage
type: Opaque
stringData:
    accessKey: ENC[AES256_GCM,data:GrDeMSGs515k7NtwdVDaoMnTNGM=,iv:iLYofhJe6nSny79AlMpvFNVu3sNviXrwZ1MLOCMa7VE=,tag:2fJhbq6p5+XpilZ3dLKVUw==,type:str]
    secretKey: ENC[AES256_GCM,data:fR+Cok2TjymQrdZMyfU26FbV0VmMHkpXvQT0COVrlg8Xc2XxTu5g/9KzLnPysYmF,iv:qEVWBetj5KI5S+niz+LFOg9IyS6EkSXEms+6GTGh/yw=,tag:+tBeOTmDmOYGU4LO0majYA==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRclZJdk1DVGllRDNZTno4
            Q3kxdzIzK0NqdFlSeDR2ZlREL0wxUG1mclQwCmJ5ZldNaHU1YnhQckRYb2dQeHRu
            SHZpNFJwdmtXZDF6bzZPS1FtY0U4akUKLS0tIHZ4RXZnSXNkS0lTcXJKS1huOTdx
            VW82ZzIwemZzVnRVdkhlUFBwbnphZzQKhI8i5D2r9aglzAPH80kri0mzIYAD8kYb
            htwF0+0S1avsOxeP3z36Uvk/gqCluaWa8TfsW9yhl4A+F7ckpBPHZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T08:56:39Z"
    mac: ENC[AES256_GCM,data:ZxKrgHi7uPp0L9eSNaTBugfP05s/vpCaoMnbNu1INo2AMseWzXr43UdihIAVHCNnnVrc4ZcBxMX3scfTAft7nwccSLAOu4w43VQf+CkgVwdqZAM3C9uBnKDrIYKjUpYrc8aquqEP+ihnTQTnSbF36T0jonRXCZ0NTt1LC8ATjBk=,iv:BPTqaByorAekffgLLcBCegTfm5FoVkhLPquRD+qIlJ4=,tag:BSsDVEls1ZI6M24rzV0GWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
