apiVersion: v1
kind: Secret
metadata:
    name: s3-monitoring-credentials
    namespace: object-storage
type: Opaque
stringData:
    accessKey: ENC[AES256_GCM,data:GrDeMSGs515k7NtwdVDaoMnTNGM=,iv:iLYofhJe6nSny79AlMpvFNVu3sNviXrwZ1MLOCMa7VE=,tag:2fJhbq6p5+XpilZ3dLKVUw==,type:str]
    secretKey: ENC[AES256_GCM,data:fR+Cok2TjymQrdZMyfU26FbV0VmMHkpXvQT0COVrlg8Xc2XxTu5g/9KzLnPysYmF,iv:qEVWBetj5KI5S+niz+LFOg9IyS6EkSXEms+6GTGh/yw=,tag:+tBeOTmDmOYGU4LO0majYA==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNDNZN0VTendEdnRFRmtv
            aHl3enJ4NlJLTkluS29mSzN1YWtQdGkwWVFzClEyVHRMMWxISm4zSEpmOExJR2xH
            OWpUTW5JNGZxODFDaEJXY01nT0t3VlEKLS0tIHdHbXRNbXNlWExnQmVVOXV1UE42
            MDZlR3ZOazZmNXFPSy9WUDBSMUo0UWcK35zyFIcQyQ0O6uRjPjIKRNTblApAMAkN
            lUSx3dwLvBvMg1QV7exRWHZWx2FvWDpmaCu4MZYu3sfISVWIQZHXFQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZ29hT3lhZVFubVZHY3Na
            SFM0cjhpTTFUNS8vMkFvOUs1VEpEQ3F0QjA4CmprTm55b09tL0lQVHltVFJGMEFh
            b3ZBRkJ0TmJlSCtSN3dsRXA5Uld6dzAKLS0tIGhWd3dWZW83dHczQlZUcnh1YzNB
            eklIQlJMYTg3TVJUZnRRdjVLdHhLcm8KYrqMmC5OUs6LRi3/i95t6ltP5ebtrfXe
            /bkuKJlfAbTeD7ONmzDMxTqnIBfDXxvHgsc1U7ZRm25S42dPSFzcrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T08:56:39Z"
    mac: ENC[AES256_GCM,data:ZxKrgHi7uPp0L9eSNaTBugfP05s/vpCaoMnbNu1INo2AMseWzXr43UdihIAVHCNnnVrc4ZcBxMX3scfTAft7nwccSLAOu4w43VQf+CkgVwdqZAM3C9uBnKDrIYKjUpYrc8aquqEP+ihnTQTnSbF36T0jonRXCZ0NTt1LC8ATjBk=,iv:BPTqaByorAekffgLLcBCegTfm5FoVkhLPquRD+qIlJ4=,tag:BSsDVEls1ZI6M24rzV0GWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
