apiVersion: v1
kind: Secret
metadata:
    name: s3-root
    namespace: object-storage
type: Opaque
stringData:
    rootUser: ENC[AES256_GCM,data:mupjM91o,iv:vVVxcpoCWfFfVHV8u4mWGhM7/YLex6gB6m+ekUV73Sk=,tag:zt2e/WOocHAPnn5zLm61HQ==,type:str]
    rootPassword: ENC[AES256_GCM,data:Jd25j62sTUOwcpaxuGrZoB8XotqLAHgZAFnSXnYlde9GsDmCi+IkBQ3LFZw2W490,iv:wzUHqHMux+AKHA1F9QW6DzD5Z22C4/a/oj+5mDrhxtE=,tag:b5lc1NQGzf9ojim05LcMYw==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjeFhtUm9NYnJvazZSekdG
            SGI0NDJWdEgzdnk4UGhFSVoycDlWTzJnVjNZCmVqOGpaaWU1WU1zNVp6RWxpaWxR
            VVdEajJXbHFsalI0TWM4NVRLNHc3ZEEKLS0tIFhVRzgvTWZVZEdabDY5UGUyZFQ0
            UW1pZ01UY1ppS0VZZ0hnK2VpQ3pFSEUK3TZlGIhrbEtmYm6VvaFZlCgL4G/WyUET
            YKQdrdWYVbFm5VWeoEvNUN+0Pfa+GrtpNvYGpJfaX6fLoCLvUDQvwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T08:56:39Z"
    mac: ENC[AES256_GCM,data:fve/ef2QJYQHRjZuK81dtXplBcqrFxapsQSg+5ZEJYFOHobi9gmDPGGyTW8W/Q1q1yp0RDbKqDn/bXAK9yixFt13231YFkj3CyqiZl5x8dbCi5gM/LN9A+Wakf9xDaWV6JHmxQIbuX+/HvSt1hIKA3WOxOyK6ncahBTd48VAp5k=,iv:2mHOW9jU5a2I6JtnGegx8/srRK79OwWotaannDwhXyE=,tag:9EifwaFFn2GEhAEPQ/u9ng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
