apiVersion: v1
kind: Secret
metadata:
    name: tempo-values
    namespace: monitoring
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:DEIYHGUdmNKZM7HxAP0zxJpNnNpvoiWH31IOjXjlGYVrRWstBjizOw0SM+ABq6FbX+AVZEA8y58pqaowR4wHJftJLsqjgebP8qbdx7oP1jCxraehgLto68XDhrmIV/S1YsvsqJrCDBQgOZ9hikL0doqqml84xTTgXsLCAypwmE6ZoR4=,iv:d1CLU9Yx/jGKo7eQ/+lPsOfh8EptqGz84GQORljpDHY=,tag:BgCaKwBEdCap0xID8GsXSg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aGo3ZWdiWGJ2NnoxVGdo
            eTVZSlk0UDh2WFQ2bWhzVDVETnFzUWxHNDNNCk95UGQrbVFFWUwrVE1lUjhQK2ZI
            U2xSRXRNZVlqUy81bVRTMTRDZDY2S00KLS0tIDRVZkpQVFRHbW1JSGpDSWVmelBr
            dE45SXVPWUYzMFdIdDMwWms1L2FPOXMKm7fnusqeatE+aNvbrb3bHSnQM8Lvrv+A
            9eUqmX1IjL9tenRsoGsyTSKefx5zoKkG3C2kP4TAqGoUAbOWHGZYeQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSHdzYlg4ckpsN3RwemRT
            MXBzSTFFcC93N0xMaGQ0eHNvcE9ESzE0NkFzCkhyOFJpaUtKYWpXT3RkaDhNY0tU
            Nnp3RjFzd3JqQi9TbjNCZy84TkJITHcKLS0tIFc2NGsydUljMnFYQjl1d0NXQnFU
            dlRIWGRSeC85eElrdUR0c1k2NHpNUzgK8IR0ZcLWkwh68fRQtegluAR3Iv/2Y1Dk
            TTWUEXnpJGNQb1oquXzIlbloGRbGZqtzVkG/ubCQQDXV4SSXMIz4JQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T13:03:03Z"
    mac: ENC[AES256_GCM,data:BA2BtL2sRISUhhjvve2NcT80nDp336/aPP543//zxXyLzU1EYThSkaryNTZVawu0Hy7HgciohM9yB1rEq6QCJkzNKUZ/cBHAj6iPO17Lul9wBL3IjT523qUKDvo5y+oNNf0EStUC+bGVphX/ih4Jnyz3OJyNd9qRi+JE1mbwmJM=,iv:Mg7gseubNqAwgdeXe1U1GjqyulI1LHuYGu/s4hwUIQc=,tag:7L+rUzF8cIuUtWT0EhkZaw==,type:str]
    version: 3.13.1
