apiVersion: v1
kind: Secret
metadata:
    name: arr-api-keys-testing
    namespace: media
type: Opaque
stringData:
    sonarr_api_key: ENC[AES256_GCM,data:v17/Q8oLVbuR606rUtwMEzR40ZkGoK5gjXtMPojQ0dU=,iv:XE5YVfmdi9e+Va5CR53j9wESmQuiLoRNjRgtKCeeDl4=,tag:vIEWqeEK2CZTiCS2RzpGWg==,type:str]
    radarr_api_key: ENC[AES256_GCM,data:pC8mIznPB4eSdl8WPiktarYAIkl18DKnn0kDnKJaQUM=,iv:FFmx/YoLb2abVvjokOHZ03RM99+D2vfnUUZRyQl5lWc=,tag:/Uu50LNRf1rcbag+u7REVg==,type:str]
    lidarr_api_key: ENC[AES256_GCM,data:xp7ZSXMVWtNQIVYRO9bmNUZEy+8EiRDmIU3fa0uNmVE=,iv:AUaJ7aURqGvJ9sEjHHJjK9d0soAishjkrvlkxyMgDhM=,tag:ilG3KXrIx0EUSV4G+6phkA==,type:str]
    readarr_api_key: ENC[AES256_GCM,data:PRpQXfvTYlRqyJvNsJtjSbrLmDOv3vkV0OVff6UJaOY=,iv:6GTVrcH8HFj3bMpuLJIOjZNuBGPRJNDbDSazjR+cJcA=,tag:bEPn7FFVteqAiR+oJkW8tg==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMUFIQjlTZ1RrdlNIeDVZ
            eDdKanZYQ1hNQ3VsMTBSTUJjbFdRUU9QRTNjCkhqTGoxeDJoSk5EbGo5ZTAvMEQx
            NmlHcSt1eHlHVEZTOUJQTFVkWkNReFUKLS0tIFlxZW5lM2FpZmRzYVRERjdNZS9K
            T2V3TGJ6bCtjWTJhNkVpK1V5bkZxQTAKf3h+djlOnRCuWEiSYaNk7BVVBY86pM6l
            CS3NRSv7Ge5bYoPmKS7A2pRoQN8hgNc9zBrwegXbKIqiH/ZMMBNy3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T21:13:17Z"
    mac: ENC[AES256_GCM,data:bqPD/Q8AY84M5SxA5MdhC5TT+FLKYHLkZQNxYLhi2kB5b4LaaGfb66n0XvX33KrFF5NLY/KBu7GZ4eZgbiHm3VL7F/ZoMEDWmuxwJYxtCn2pJgAKvhw1RtgWItuvOiB+OLpjSKUUIkIArCVHlq+wzKQCgENgHROhZBZnmOrFOBw=,iv:QAoodA/i6icKEcIcqNXkhoI3PfYeAMJ+Duzk04GbEvk=,tag:kbrpwW+b8+OebXx+Er7rEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
