apiVersion: v1
kind: Secret
metadata:
    name: arr-api-keys-testing
    namespace: media
type: Opaque
stringData:
    sonarr_api_key: ENC[AES256_GCM,data:v17/Q8oLVbuR606rUtwMEzR40ZkGoK5gjXtMPojQ0dU=,iv:XE5YVfmdi9e+Va5CR53j9wESmQuiLoRNjRgtKCeeDl4=,tag:vIEWqeEK2CZTiCS2RzpGWg==,type:str]
    radarr_api_key: ENC[AES256_GCM,data:pC8mIznPB4eSdl8WPiktarYAIkl18DKnn0kDnKJaQUM=,iv:FFmx/YoLb2abVvjokOHZ03RM99+D2vfnUUZRyQl5lWc=,tag:/Uu50LNRf1rcbag+u7REVg==,type:str]
    lidarr_api_key: ENC[AES256_GCM,data:xp7ZSXMVWtNQIVYRO9bmNUZEy+8EiRDmIU3fa0uNmVE=,iv:AUaJ7aURqGvJ9sEjHHJjK9d0soAishjkrvlkxyMgDhM=,tag:ilG3KXrIx0EUSV4G+6phkA==,type:str]
    readarr_api_key: ENC[AES256_GCM,data:PRpQXfvTYlRqyJvNsJtjSbrLmDOv3vkV0OVff6UJaOY=,iv:6GTVrcH8HFj3bMpuLJIOjZNuBGPRJNDbDSazjR+cJcA=,tag:bEPn7FFVteqAiR+oJkW8tg==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcUNJV2UyMG5RUjVBUVpN
            cHpnNjRlRFRabjJybjcwTDFXTnl0eHhnbUJRCkZIWkdRMEZrbHJGcjdTYVRBR2RL
            N0pNamJ4TEdEbGNIdFNqcThlWTI3RTAKLS0tIEdTWkpMVEpoMmhYYTVXbUV2ZFE2
            SVBReWNtc3RKQnpSTkxiNy9pMFkwQUkKy1qKif3mn0nWfRhDOPsrs5yLF9FDiCQp
            FIwqEAC2GEb0SP/0fpWwuPAD1Tp/NkTUV+WncYPzKuyxEZwZz3s7tw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aXJSOWRzeFVuVUpjM256
            NmIzSTF2enF6WThUWGlhaW9iQ3hKRmtJblhBCkdyTGFKa2tWc3VSazBuVUFiYlI5
            ck1nekg0SDk4anh1NldERkFGakNLdXMKLS0tIDJrWW9TQWI5elZNVis5dnREV3Jv
            ZjIyVEVoZ29xODRIOUJBbGVTZ0dxbXMK4nhafGkqqgLEU3OOYxXxj608x2vx/JMb
            tEPt/tiQTpsfhKfpHGcqnPoa5nDX62Fe668/e60lmHM5QWwWVdbDkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T21:13:17Z"
    mac: ENC[AES256_GCM,data:bqPD/Q8AY84M5SxA5MdhC5TT+FLKYHLkZQNxYLhi2kB5b4LaaGfb66n0XvX33KrFF5NLY/KBu7GZ4eZgbiHm3VL7F/ZoMEDWmuxwJYxtCn2pJgAKvhw1RtgWItuvOiB+OLpjSKUUIkIArCVHlq+wzKQCgENgHROhZBZnmOrFOBw=,iv:QAoodA/i6icKEcIcqNXkhoI3PfYeAMJ+Duzk04GbEvk=,tag:kbrpwW+b8+OebXx+Er7rEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
