apiVersion: v1
kind: Secret
metadata:
    name: arr-api-keys
    namespace: media
stringData:
    sonarr_api_key: ENC[AES256_GCM,data:qii+Pt2sA+N+ROkii37X4O65gJYXfm5/4Y074K+ihRM=,iv:6s7gbP+2zzIem7eL1sERYrddYVSo91UOmTF+UujSSBk=,tag:pvphp098Oc/V/cq4A0JKUA==,type:str]
    radarr_api_key: ENC[AES256_GCM,data:FiYRqXi9tBIc1jCVWWkMTmbpfCSOAv2opwfzsxXeKnI=,iv:yoMlNXLPoLFNvqVfFPwVS/PUO5Kn5q0zu2G79Dsc9ws=,tag:N2zkhHImOlmTK4k70rxXNA==,type:str]
    lidarr_api_key: ENC[AES256_GCM,data:pKjTxQ5Df3EhppcHEss6rW3HUiCI2200aleJ+x4NPj8=,iv:K+sIjOc2zWpEn2BGHZRbUWkQmHcVIRa0BwVaK574ABU=,tag:TF4ORbjMDBraIiMBTDMyDw==,type:str]
    readarr_api_key: ENC[AES256_GCM,data:U17eO62o21leKhLGzmXASl2YWSXZhmQcnxOpX7VgX7Q=,iv:bBK9sx/7hri1D3Rwth9yabAz25h0QeIiIibxScyVIcA=,tag:xj2DPF8PS7M0akadYAFWnA==,type:str]
    prowlarr_api_key: ENC[AES256_GCM,data:YY43jM62lUKQoDZxHkqJnfScFwN1Z/oFIfwfBx+fW8w=,iv:r4OYWeS+4/er5WZ1MaeriYp+15ToSP39Ka1k8L8vuww=,tag:4RvtCeu0IQ9+VpWzME/g8Q==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YjhUanBQOXoyVHI5Z3I4
            R3crejZMbGVVclZvSWhUMk5uWE5sem5uTENZCndzbHA0RHdrVE9SbDR1ZlVoQWJr
            Z0cvTTJEZjVkV0xyZUNuQVBuQ0xqNTgKLS0tIHg4UVZHMXdKVndLMFREL3J4N1Bv
            eDZ2ZDl5RE9iYXJ3TEloaGNNbmhOSVkK0x6cN/kcua1aGzhmIxLy5cw3d+/KhAzF
            P857IbSrNqDCWvU7TSBoJOftbQoRAlxkZtNHBx3hdiKhn5dZgD859A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T13:29:05Z"
    mac: ENC[AES256_GCM,data:Jisj8taTFlHVJd2lJa37mFyeXAgMYa0iYizd5hRuap8XUIYh/peZ+wHRRxypvDMoBfGaqCYjhv9B8BydJSJstdPOpQf+t2HUeEV6B7+8KP1crgE7qklONZUlI/zAnxPJXMiOd7rxQxDoX+1I70KVPqfcbuehJXC+jIx85c4qgNA=,iv:EQV7mLkV8gDFPvofNtwGTn5ddiMCN0Kefu2QaPwOb0I=,tag:FNUvdN4oS6jgZwSaLHDZ2Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
