apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-credentials-testing
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:2gDgGdKNFE3XH0V+e49VNkwguS3FXOKNRPkSgxiQvxXqxXGKtFSizbvUu2rDEGKcCbtJePrXgoc87rPDr4jaRsK7Yhgzj+V96gjxaP7GK6aIqMZmsywCicz3OuqFi1K/77tOX45aBelvksPGR5DJpfnH5ZPn6fGt+NZOPs8T1M50E2VTasJU59Jom8yAA7wudI8xV5m0cudEalywarPKh2Ix9md2NWWyFZHnJ1U+da0g0PXL,iv:1LclJYYswYJGodcK6oCX3kq1ShBnhBRQgdZ3JBE1fck=,tag:IDUZKT9OjZz+9dCNj/7Z2w==,type:str]
    credentials.json: ENC[AES256_GCM,data:7pElEslhlY+o11DEl1mWsvVAAYQC7l1xesvKAVlIoi6pz4wqNg717cEaCZ6bc9TwtQkCwkGljmzebEQVT8V8sibK+W2S35gtAM1dz/HG4jfNTI77RqqFowjF8eo2C15nD5niuLj7/JI65T85/XTYjA5Y/5a2HVlzrzW/N36cnkrYmcsSbfnl848x9GgGaTRBrsuyNbzVT/yiILnY1FwvcdRxd9FQftmrh898jQcJvg==,iv:IS7yiLyh97s9oV5YQ5RaBvrxJey0yykc6G2GCuogCUo=,tag:TTcgwC1Z4fnVuQT8xfL37Q==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTk5PejBhcERZeFRBcERm
            dGx3blVUZnJYVDBpekxUbDBWU3dmSUMwL2dVCmhSWFlyeUJNc1EyUzh5VlpYbnBG
            V2dPa0s0aDlxWmdJSjV4YTc0eFJxVm8KLS0tIHV2RFZlSGU4bng2aTN3bEVvUmVX
            QzlhSy9pVXBqK1ZQRm9Qc2hsVFVadFkKYCD2SK+fauDr+K66NFgC5UYpmh80x7By
            Pbt7BXwIwJZo8Z6LgL+ltaLyusQ9gMuMTDINa30N4cq5ozoqg5SkQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T12:48:52Z"
    mac: ENC[AES256_GCM,data:FXZqZA4SXqPmHmOss/dqqKItUAeoItRJkiwyqIuMGVrCJWaI+6PdITeVACTK4CY7czrRzOvral2UiaeRuKQf+KA5fGxVnQmZSFNp8DGekNryJr8d48OJtt+10gQ0YNEEjt0/FCYbQBHx22fM3SvHYWf7dnZDilKdsy2Sl5dmTjI=,iv:AnC8LXbZYql3EHXkjx2unPOzsq6rquFDWh1NQ8gTYF4=,tag:77+4CWuSVkL34ti8zARV4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
