apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-credentials-testing
    namespace: cloudflared
stringData:
    token: ENC[AES256_GCM,data:4wKwAWdevYsklCIHjFAm6WWt5AJ/qNrppvv07jqfZEDwJgxrh3MoNUr/9WF5hbMhK+JGQKnqbK2CHTJcT4Vt44nHWDtcoK+/rWjxgb27XULwwIa9oKnaZGz4gAi1gJbQU7YOzNdfkjVd68mTGEwuMIXaaZSVzuDKhGZjBD+YPxki/71tCz1GwfCtSn0a97L3s/ewJmZ9dNDXlZ1vK+Z9GCqb7TqcquYvfrRM+mTcoMCXv7WYoRKiDw==,iv:3vB/UhyJjlNhDZnob00CIKBX4BFBJceXnMIzSR25v1c=,tag:cbSgkVi2VpuNswO3xttB1w==,type:str]
    credentials.json: ENC[AES256_GCM,data:56hWhPbY6N9u80fqBbRE/voeBiXdHgfZ4YcmFoEqIG54jlK7KcE9mG6M3dmAdww/q8L1kCR1xHGokSGh/oDjb9Wbot+kaaYXKFDa9dMXNUw/lrpHT+NihnYBH0uynE70EjN4cbmd12kjDX0R7oXbuCO/8hu7GhBVx/jQE8WTvkzIGhbMe1n0Ss9oqWYZlCcsRg5Gq4HLR+RCYDbQMtc7sL0NJlMs,iv:r7zmuYWOPapX7FxrJIRahc0wOm7MOu9pKSXSNt+rMfM=,tag:qQPdSSTvcvhpisCeQ7WWQA==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscGN0NFU4OTNkY3NNQnN1
            VTVNZ3hHRXlRQ2ltOVg5MXN6cTJjZDN5aFJFCktMRDVBQUZ6bHBrUnZITElsQmdS
            dXFpVnNXMjNZbnpLMzJycWZ4bE5ZL1UKLS0tIExNdGF0Z1RueHpKT1lHU2dlR1NQ
            RHBselV0bExNVS9zN09kUnhrMURvVmcKRZSaHgWio9lmhCDqpyJ7bMqftgWQMb9T
            WqSjE3naXOzlx2yeH7U86JuFDbaoo4u3XZiCCEeKqzpkWEkiIhV1wQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T08:13:54Z"
    mac: ENC[AES256_GCM,data:mtT9FvJOrFPuMFW9sJj3BBl9sKQajxoLII1IqvnIKLLRa+PBb3MOiQ0ZA/CCanzfStFCYwNkMMco6on0Z/VnfbEEgnmoNngSsNqckGOoDdDZo8407L7Bh6zSZfQKYus5cBCy52x7bL6A8w8FM2oCQhwyLAj5J+DelwJxYlbN5Og=,iv:jyLqYMnwrLyry1leVVKNq01cU4XwKeT0gjElbhmW5hM=,tag:XVy86z8OS8t+qSm79CZjqQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
