apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin
    namespace: forgejo
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:72MBm8+W,iv:2xiPWX8zGhVn2QZF17wB6i7THJ2Bx1DqGsgHUk2POZo=,tag:+BH2HN3vZliw0+CtFlYwRA==,type:str]
    password: ENC[AES256_GCM,data:61xrYBWf0k7I2anBVdhT1+NJHRuWFAQjGnvWGNBkL4w=,iv:JXnD/zz80oFvX3V9NOQ6AiARzhTl2xp0oIkXFs3TtF0=,tag:Lm0x7Rj5q3qxYih3m03lKQ==,type:str]
    email: ENC[AES256_GCM,data:5rOjimAQwVKQ2R+HMhY=,iv:1efwoqu6U3voliQx7oKT0+aPvHMB5gJgSIuIpx3lMVE=,tag:R9AlpEg++r2z9+TJKBQlnQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dEpJbm9RYVJicGNCa2lv
            MmRuVHhqaTRUSS9icExBN2hTNTBwcWtBWTBNCmpnWi82Z3NLVndZTGJjTmU2Mkxv
            UDNSTkpUaXpKcklMVDQrM1c5Q3RVZjAKLS0tIGtXa1BtS2xlVmZ2SnlpaTZjT3RT
            c1JjZEtDRmc0b0NIWXdpZGlSR2RPR1UK2alXvFEjM1owIxHiDCMlag+DGMANe82c
            lsOujAGgRu3XqsE1Ca442z48skhbByAd4me6WgcV3GA6AzJGa9AiBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NSswWnM2bEVGaEE3VGRQ
            a1lZbXBRbHlJd3FPaVVvWlptK045a0J2d1dFCnRzL3J3c0g5d1dDQjlzVXlxdis4
            ZTlWMDdqbU9oZDU1WE53T0FyRndOK0EKLS0tIGFRcjhpcjk2ZXdia3VJM29vMnIr
            Lzkwdm5NeXpScHRmektXNkNvTnlNUDAKc5/5Pw7VbQjzEFCw/TVRZwsTmGYsnSJQ
            YHXTczRC3KVpSyKqtPgcK1l1utn/q9HJtQPl8mhYrpSozE7NFqOiGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-08T14:49:02Z"
    mac: ENC[AES256_GCM,data:8JY7WhCmzeHE/cx43jB8zy4UysCUeXfex00/JTqiJsNK8CsxUpu+QBSvHsulVl9dLXx/16VTqM+wZlg24A1Hg+ExLMBnPvCnZGjzMAiX5ec7xTbcQLKe8jpK0iE+/pzuVf5ZuWMrjVTcMZDmeGRmL4vVH8L6Rdt4yKfh+Z33N8M=,iv:8JgqiyPgHNYuyDP0K/6Uh1SCyj843ocvTUK7XbIWH6w=,tag:wuEO/U7JBiKBwZERU5ywmQ==,type:str]
    version: 3.13.1
