apiVersion: v1
kind: Secret
metadata:
    name: github-read-logday-testing
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:kGToBhnDl1gaotLDgj4=,iv:3hBKmBZwuzsRr91LHMxDcOU8Gx0Vi5X/B9ZuV145EUw=,tag:4TfZmgEPmhMg1EGExJDiXA==,type:str]
    password: ENC[AES256_GCM,data:poX5MglGE3LtwfQM0fLl9lqBKPwnmb/wWeNIcFHYD4hYqTRqORAGwg==,iv:+8LVqfT22kWC+gZagSXAg2pYkdi7XTiLQ+x+lBVkwf4=,tag:2w9fMX4PnkgQnPMzHipx4g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucXRVWnVvTzJzL0FzeWFR
            ZmVwVG9lb3FBNDByb2h3WmxkNDVvWkJKZlU4CmRjNmNXZEpUaWVjMUFwTUpGUXUx
            ZXgwUWloUzJydFEvZ1JrSGJ4SzVXTEUKLS0tIDlVR2MzaldTOEVyWVZaeWYwWkRr
            a2xwVUdsN1ZncTV1eTBrdS9YRzdsNmsKmhTMDHPGMdXK5f6Jp5Duh993yTOLhM+P
            N7Gaj0O4D89yzEbj+dUYaptTcIgKLUszvQjMC7Lrm7w6RWdtY3Y+Bw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGK0E1WDZjZkFhZVZoRU5D
            WWdPWlNwQU9hNkhad3ZReXBwdmNtZzFPNjNrCmZLOUtuOEVZdDRocWRRYm4za0hy
            dHlOc3kzZER3LytCKzNpVjVHUG5zR0kKLS0tIFNER0pSTndpdjBRbHl3MWtERmJV
            Rjc5cS85Q0pFZUtWd2xOSHo1OVgxWlEKdYaoe7oJ6anni7NUO9yKMW/sQsGyWNyi
            lJBadxKp6quVrVaAhFoM6nohEUE9J1ikGeynPO4++SO7lewRN1VdHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T15:56:08Z"
    mac: ENC[AES256_GCM,data:LxiYHxH40T6afustQRSzvFWVhWTHo0DUbHArZwFisDZSszHknwwt3nTOOF9xxmhUXLuY2uX3RzmjRgwabYVxZL/52gGn+2fzqRLuYVJoH1WsrKgtucIwp/1Hd1W2TRVTQdLo9514+hOj3xkBK+vqYP154eRctNlvDW23pl+uZ1E=,iv:IKQ4GexRJHb/RZU7PsSV6lpTp/JzJJDustlNaOsDK6I=,tag:QdQBZ82ZMT65FM5gpYl7/A==,type:str]
    version: 3.13.0
