apiVersion: v1
kind: Secret
metadata:
    name: github-read-github-testing
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:1TMwzx0l81GNK04iC9M=,iv:Qy8Vqs9PfvoyVYf+iLDHeWUgr1c2u+BSqE+X/EvEBNQ=,tag:rQou4PWPWpNNsh9GIgGAVw==,type:str]
    password: ENC[AES256_GCM,data:sfDNS7JlttsYjmH/AGYh+RTfqEla1FCu6cNarftwWl78XFNh+quEbXrgbGltddaurXohC96UHcEx8Iu6DIC3oBny2CX0h7vPtroWe9E2Q4M3oYE3wa+p+8KJQK/+,iv:ptJhDX5oYGkA5glcY4Mpi4xP457RDpMEIZ4bgstyJII=,tag:gnL5HG8Rk4q+qNpJ6iCLcQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbUVWV1k5R05uR3Q1N0dr
            OEozNkZ0eXFHcDFuQTJWRzlWSU9uNzVFTlgwCk9zZ21Oa0NIY1ZycFlVM3pOcEpH
            NEpUS2g3QkxHOTdUY1hZNkRNVmlUU0kKLS0tIEgwSlB2V2VlMVQ1VkxiYm9mS1pW
            ekg1dk5ybjVNcmxZbjM3OG1MWmNOMkkKHe9r1Io0+eEP2JGOtl8KHqVzQHKWa4eW
            SKGtsROEYmNGz/DO5tZYgGx+vR8O0hoaUKEXuVS5d1m3ViYCrQCeKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBub1R6bWJlejlXR1Iyb21i
            QXM5RFZQSldwWEJmcUQrVVh3K1VuTFQyWmlJCkgwaERhbnZSVVB0a2NqSjV6Z2pi
            YWtNNHYvTzkyeEN0U0VieTRzNW94MEUKLS0tIDFwQlZWbWpLQWVIR0NtU3NJV09p
            c1hpMDZROXZLT3lBcll0Sm11ZGtvcG8KSIIlB1ut+mJo5qzmT28QdAuW6F2cko9J
            FeE1ff8FpAc1omRwpO3nfMlhSHqMRJn4fpBrFf/vZSUkd/ffjMt4Ww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T18:49:24Z"
    mac: ENC[AES256_GCM,data:axGhSUUrCErXXq7BhX6CUprid6OURJIWotdzvAaGV6bT9BiwqFYuKDAHO91DY4f5o1TDT8/p7YRPZRvSXQc0+Ju1ZlY2cgGg/RA/p2BTrnqmow74QGrubFx1nml9NWd40OLnX4q1uMVVxRLwd4QEl3YCzv0y0PGD4ZM0ImrzJtg=,iv:fJ++OxfjPNKBnL4vetDhZkmppEcyYzlLTRfrhlDlJJI=,tag:NHMe65Ad23VphlTuueH9xQ==,type:str]
    version: 3.13.1
