apiVersion: v1
kind: Secret
metadata:
    name: github-read-logday-testing
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:cYj57f163SocQ8/PB7E=,iv:BZ2ta/gl3sUtbHVWHxm2QnlHZQzKS+bqdJzYoYTKC24=,tag:hCvtmLhnejJZhjaeLoOh0w==,type:str]
    password: ENC[AES256_GCM,data:fGyzcZ3J1OJUHoF3y+VqMlsT9TicsVrPL3Dm8oEr3QzvVTD08GUC3w==,iv:bgXn6NrqPiYuNShKfVunAOIRAD1VcI6Ox6w5DJ+QHgw=,tag:SrISqnUpMVGSsNDWMyeFoQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDS0s5NkdnNjkvS1g2Rm9Q
            Q3lJQU9wUjZxdVZQWmI0Z1N5aC9MOGlxMUZvCnRGN3YzWXVTVlVEUkdwcW14c1B1
            ZmpSbEU1eS8ydjU4RlhtQzVzRDZjUWsKLS0tIGJPM1NhNnY2ZnprcFNRL2tVZ0lP
            R1NyaTRKeDFTQUhHamx1YU9sSWkveVEKqzsqWNPTY1p54kX7WwJfj6y/Ja6ZsAuT
            jNke9l9DSTlTtTLDKDCMFUbje1fb/sMV5kC+DWZUFwPgaNm0yzpKvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZzJIWXhmcFN1eC83ZVNo
            N1FhY3d3UUI2R0VDZzF4MUlEWk5qcUFJMnhFClBkbUxaLzByK0pWNWs1UXZHVnp1
            cGZCU04xK0poYjVOcVZrM1F1S2RiajQKLS0tIDlYTHNkRGNqL3E2TDBhK1h0ckhm
            R013U2xrRUYvdTgvS2c3RjEyOXJCUVkKb0MeJRR6k65Jr8CsRF0YWoNfiyZFsPze
            C+i3vPIGBH9WAetQRANhEsZZ8b95if6ReM6Nf+wBzso7shaNBqacEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T13:07:53Z"
    mac: ENC[AES256_GCM,data:zUi7g4hsvHw/6p+vpzDdoDR4M1nI7q2IaIoLCo/Wgs1KX2e972EwcRNBqQeJPHxAQY7z65nxXXmSKOOEKVVe6QGEHmAadomMQurAezksDFqu1D7EtidtlcLCW5nRrX3mMCDCq2v9l2HbTLV7s+l/DqGv9F4pZCz/oLtkNdqJK5o=,iv:d63A4QH9hShKf/nxCN7A1bE04LF2zFqIVq3xHJc22kE=,tag:kM2m9bXIowOcnhPbWXJj/g==,type:str]
    version: 3.13.0
