apiVersion: v1
kind: Secret
metadata:
    name: github-read-logday-testing
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:qV68+gxouKdh6ATjyJk=,iv:/IEkk2UWfxj7jS+qCuTNjvwFSqEjDo+ohjjGkrsyVRI=,tag:7zGK/wCsjBrijnItmRraQA==,type:str]
    password: ENC[AES256_GCM,data:2JDk6G4cCCF+bLWbonLrLr0M46vNJBnDpDKnvcsje8UdfHLs9MkW/FFpcIS9Npd5gWUU4AuCujxFHeK3hRitUCAFQ0F0VCM937C286sS5bK6nx4ibzNERm8IXra0,iv:UXI6F2qjk385v8ZReeS0cDum+Yw32R6AIAF7pL4YEcg=,tag:+cKfcEl8jvN0K/XjXShklA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDYzRUbTFlUmN3b3g0SGtn
            V1V6dDJBaXBKWDdkaWptN2NhdnR3V2ZJSGpRCjNTL2daMFpTUys5TWYrVzRNY2hO
            dC9oT1g4WkhabTBkbjZsZ0paS2FoODAKLS0tIFIzWUxWamRoWEJMN0pDRUFhRmg4
            UlFqNnVSK0EyK2FKVGhhNXdwcjRBM2sK6uAAI81Z05KfPwq2QFNJBxYZSlJvh02J
            VqmuyJPaPZ44e7WMGLKk144Ndet1iec7QM7VJRv6S9ppsFG9bVbOPg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTGZMbnVnMi8wTTdvdXhi
            MS9maGV0M1ZSR21jTzRqQVYvUW9haDZiNlV3CmdxbnpnbWxmQnpaM3MyelU3ejRB
            NlZFRjBndm9YV2Npc2s3Rm9CR0QyVzQKLS0tIDFwYnYxQmhIV054enB3MS9lVURr
            YVlCRUNGUHBBODMwK1paMUs4b28wTjAKt2vKEhUCgfZoR7Hh1ErgYRrWjOoZ+kVf
            +pUhjBGersfzpTS29tJu9tQLG3C4mnNJK4h9I8cow50Ywpd/3n6fVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T15:26:33Z"
    mac: ENC[AES256_GCM,data:aMVKyfeEiX/4yLxNzE/r9gwJw3DhH2k1AFE41d6OP9uo84zmZXqXlIqmC3p5AacHCAKmcrU90wYDHRXg4xJ8kPZaBTk8q6IF2H6wFsl7WxySd1m0Nt/JjbmpTTCwG9J5jme1QlPGSE9ruN3lT+ub2X+NCBkIumvrlsBlzwqM5/s=,iv:zJRa9/SVVRFJaXXbkLbMiB4DM7xH9esoCof+uunxwlE=,tag:3x7YTdI2ZJbX9nocrMNE4A==,type:str]
    version: 3.13.0
