apiVersion: v1
kind: Secret
metadata:
    name: immich-postgres-backup-credentials
    namespace: immich
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:1WAjWT/SLWM=,iv:vjBk8lQUIaHrTavgw443vl6t2Z9kifqjnCIWe07pw98=,tag:JGwzQPuReaTBoK9LfB2Mtw==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:BsQssnS9CRvtl8Fh7pB4L4PU9C3/Gn3XeYCXVww/QE5Wl6KAbkEa+dH1Fi31sg4dQ+r56du86tLaWfq5fEXhlw==,iv:F1mYfH6He7ui8RkMfhQGjynLvzFaBStf7dZXYwA0A1g=,tag:g/S9X9wsOfgt/oSX/RkstQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:+i8XnFpDnWRMUL1zzND2mBwn24lLIb/WB5Hw0a8R0HiRELjqIiOTelemfWTir2LxzMZ8hmzpbqpw5Nq11+lSQg==,iv:Z0NZnDCc90lVxAKGZV0wRe/7NuLgJHg6gAtEwjfg7Go=,tag:+KFhm/lg6Z+DU2Loifqpog==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySzY2TFVxRktHcHVtbFZO
            L3FIdWRsa2s3cEVVeFR1ZEVyZnhmYlZxTW1zCjMzaDBXK2hHQjFOSlR4bWtXMGtY
            cUx6Qk9tQi9EQlJtYS8reGxzcU42Mm8KLS0tIGQwT3FsczJhYktBUlYvTWlRSzlQ
            YnF6MWtlSlVCcUFWYzZYNHRjTDI0UkUKDUo6ALmTYFJb6Y/eP7h5AIN3nLNAI2lo
            Iwv3irm8yGCHNu4WakylmfsrqhRV3esAxgZuIJyUF8ceUy4Ihh5dFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T08:12:17Z"
    mac: ENC[AES256_GCM,data:68QHn2+GLQoK/cj7MmubV1SO3ieKnXYiueZaKB0/VqutsCzT/UzLpFr1wCYFJaYOon5+L+N/3TAu7pQq1iQSCYKtKpELuO/Pf0HZ2hJlxIncIg90H/1/0/Qjuw9NqX2oov/xdXp1y1nMukgvUlfx7DJOKNCknGrXqY+dRyabXH0=,iv:kK4mjIw6zFHm2+qFKjN2SD5dEjzl/8L/lSoCklPGwjs=,tag:3it0NYwlHjARs78K0Eogbg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
