apiVersion: v1
kind: Secret
metadata:
    name: immich-photos-secrets
    namespace: immich-photos
type: Opaque
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:FIloLEyt,iv:B5Mr53O0+L0eaUDLwqMCu8n0sqpBLIElKkvhDLiXXQY=,tag:zn6KTLLH7d8EDKZM+Srf8w==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:Fxxhni0l,iv:aCr0fQ6dFwOZZttgTaLaZGdjJxVvLYiXaT0RhAD5qZE=,tag:MgodBlw5l7ec/L5BxJNbJg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:9mboHc7aiotCJIt/qTpsuaLJKOzwOnFaEwXlcUlk98JiRu1NWw+mWWWXxxz0JNkt,iv:9e33J+VL/epsU8MskmMTfmHTNmeFF21XitOF5jpNzP8=,tag:F3085Sdd8DwD5eCqekGyYg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:59ZLvYlHyLe59PQaCb/VrWsRqVCaUF0KCcB90yvbWEBWJgzazZ1mkCmfGLdUrh2r,iv:Spct5O8rYPHeq0MA+hFSzbfcyGss08rr5RC7HhcFcuY=,tag:j4AJIO9YhwqXc2dWW6JZFw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:mLxuhytWJ4FKHe+2rGSbgAMuNPtvJXOS9FBqbFbuiz5kqJZbhUp7G4SLUIQQh6goD/NsW4VMHkbLe+40KjAmlQ==,iv:VnGx9ZcIaq3tTsACioWGScNpNYzdOFhbiREExm1DRco=,tag:NihPbeoa6hYE9bAuf9Kzog==,type:str]
    IMMICH_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:2HfHuLn+2tNI1+sxjt5LctSBwn8wSc1uppRxNindQwRnKkyPuz5xcn9gr306lelH,iv:21+OOAQP4QEmLjLA2Z6QxfFCXDlpyaA4by4NIc7b3xM=,tag:rPNS76CjwXD6rZM+jt3Qpg==,type:str]
    IMMICH_ADMIN_EMAIL: ENC[AES256_GCM,data:HTdtpSyjufvPoTwhPf93X+78EQqsJOnNHPOSuw==,iv:TERmTXjDizip5f20hDCeUXLbWxry497+l9QzpKzbyDk=,tag:NePlXl35r+BBmgNbTpMboQ==,type:str]
    IMMICH_ADMIN_PASSWORD: ENC[AES256_GCM,data:4o+ODZ1LWLE=,iv:iqEIV83IGU72GEOBtdZPhiV+mQVZrd1Hud9f8k9WxXM=,tag:XCktCr3kdAb/v2UCCNPlSg==,type:str]
    IMMICH_ADMIN_NAME: ENC[AES256_GCM,data:aR+BpeZcJ/kPTkTtotlL,iv:UTrrcX286vdvb/YIMRRB8PJSKKv1e0X5yMQoqELIJ3U=,tag:T03JgxsVQ2oMCqUjXJP1eQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4U1lhYVl3bEZiUGJaQzV3
            dXhBM3FyVkkrcUU5YlBSbVN3aDNjL1lhYUhjCjh4QlhONElUMWZwZjZGZmttOHhl
            YkNpRzZiV0grK1owVnMwRE04bStqYzgKLS0tIGVkTmw1eUpVMHMwSVYvamttUkgz
            eHpDTTRMendWUVR4cy9MN3hGaWJncW8KZijIRyHP+93sYI0I2Bgae5sbt/BUDnpD
            gxYp/9J4Apuppfxa8vd3ZlpV5CaFEdAHCZY6mdOq47XctoGFC/Lh6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZTFkdzgwS3pxMXZVMUVM
            SXpmSUNhbUorOVA2Rkc3cktTUkpTN1g3VkhrCktPS3hqYVp6UWJWeC9vY0VZbmxE
            M0dVWmFncStFN29kYUQzcE5WK21jdGcKLS0tIHhQSnRkT3lvekZ6WGREZk1PMGEz
            dUlNSi9jSVcxaVRMWVE5OVpmb245YmsKMpwTflyBtqoSlGQ2/+IOG4viKQxqVIhv
            XB0lQt6n/GPab/5PrCiHZJaFy+RKyccaa3D3DI8GppMbQwWr+B3yhA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-21T21:01:01Z"
    mac: ENC[AES256_GCM,data:5tNcJxWGTZAbVciIVM/c6w7U2AfjsNtXxfWVr9vBaF1tmyf2+OBz+ZQAxqkOx/cI93f9L6UIDdxqlvZf3DWLkMPct8LoYo7t523sGvn7NXdLbjziLCnccZAs+Ubj6aAVuqW4ARQtzsvs2EHY1FGprNkdbGoMHOCorHxEbnx3nxw=,iv:QrBkcSLA6zuOZisHSgclANtBURtex+6hm2NeBMndILI=,tag:oadKHOx1Y+rzhSHaXsA5bw==,type:str]
    version: 3.13.0
