apiVersion: v1
kind: Secret
metadata:
    name: immich-secrets
    namespace: immich
type: Opaque
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:eHaZNskw,iv:g/uE6MPODq6MCP4Azeg5FhnjYUqE9p6axuKwYDoMxRE=,tag:X73lHDxy7n7Yij+Z4Vk5CQ==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:cB2Hz0Zo,iv:txPaEKXB8bskSH/Q/nCuh1BJi3GSVDdGZxhXKvV70RA=,tag:GsJuKjkhPflCuIhc1+pqNA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:1Ko1oml5NOquhOWlh4dvdekUmBM9kdgondBrH9xwiZoNypx2EWMA+GkZ9zsMHg2G,iv:1lYI/oTohCleRXQ20AeEEFOXlh+D0J48G7FVxZ+tNu0=,tag:y0GPELHnv5Fbk3ABg3YYcQ==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:vEFvtigJGxGogrfmlipy3WoaiQlro3FLcBnCFuoxz5pHvY0KZGlGmIf+3V6hFrdw,iv:9AOCAGQt5rtsDGyVTuGhFV/R/Sk3SU0GgDowPh+4vp4=,tag:x0+kUfBE43+3KpshwhmKTg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:+Jf55/FKyzq1TrvX7mvqKBvKIMKbdKXTg88cMXLmeglkQlbABrdTLC4XViv/1I0BRV8+JDx/Ih2Z8ZR0zJnm3A==,iv:F/wrMhQRkcsi87Oa8kZEc1GfIE4/fdUXp5YtSR7LeJY=,tag:n3jQTw1K6mEl5hYZCh81SQ==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMN1hXTVFsMDN1U3NWNmdJ
            bFBVOG4xNGxTbHVNVlYwMGkzSjlSaGM2L1RBCkdZVTVXUE9lbGIrUzE5ck1kU0I1
            cHlHWVVwelBuNUhaV3Q2OEdnY2tSNWMKLS0tIDJJQmRkRG9KVmtMRUpWWmFTMmpG
            WWpGVmhPbEVYQXNRajEybW00d25Hb1kKMPAnIZbKLFmr5JaBUM3sljQ6IC/kZuGH
            qocWCxbe2+4lRVXnB3cD5hS1oyaUtDTY+iWBbD5Eq1eCH25ngsydsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T22:15:57Z"
    mac: ENC[AES256_GCM,data:Bl8ra7LkW+PGqN0thugGxAQYfgvv+5jRUcZNfoGLVRA1319kQv7g0XcOaxjqbbAyPauRsewlWRUzj41l5TX+mvT1xkxfdjDWFyS4VgvxndFV6iBZMgfMb09iME7VJk2qRpds8RXhS94rdAxe7yUzyhuRz8WtblpTFmZZza+ibDw=,iv:6ZXmg+PrJPIMX9DcyM/Nkl9mIY+OIKpmqFX9zaszlHU=,tag:zrz4MyLg+ak8zYAfpHKEZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
