apiVersion: v1
kind: Secret
metadata:
    name: immich-postgres-app
    namespace: immich
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:+vfVJeTB,iv:dcQ0UCdmX2X2ZXUUGwSpd4EzF2JZSf6qSpuU28r1v9Q=,tag:iHNF7PhSJMsb54HBia5dTA==,type:str]
    password: ENC[AES256_GCM,data:aPL+HXlHCwm9AF+44U/5ouq579d/9oMr6q7BttH1yfP/KI0QaE1WZgE5lCOMqV4H,iv:4XUbJ5J9lAOy9RkclBDgas6Rb1tgwOHgHdQV7laf35s=,tag:maUTqIRDSzoCsee/MFWWDA==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4OUdkaFJ5QnFIbGtRYmVt
            dUtNQjBnbDBsL0pqWUVDVDZWVFNUZzR1RmpjCkZZU3FML0Vtcm9Lb1IzRGtFdE1H
            ejQ1V0xFK0tvZVlHcTd6aHdnT0hKK3MKLS0tIGdGTGxqZGgrSVl1c25ERVlLb0ND
            Nm1yUy9KMWVKeGxqNGM1NzhIdHRER1UK3KNcTbzCn+aVUxV4KXuRNPIyJ3o7jMkI
            DZk3qSF0jBLm9qECZQDAcSJoiKxn6w0tMnSR8UAEpvkprSg2UMOWqw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhejEzeGc3Y1BxRG51U1lR
            S1Vvc0Q4VkcydzcvaE1WR2dCcnoreGJxZFdnClZUK1JseU5jUE9PZFp5ODBuVlky
            ZDZhSzVLU1Nacm9qeGFaWUgzckVHU2sKLS0tIGljVjVWQUMvYVpxZXJxaElaWTBB
            RDRlM2NOaUJ6RFRLZUZkSENERTBER2sKqUu/Hg2Q8dVbHr962/Qt+9dSARpYlLjP
            8Kq90cQMIrvg79fRYMjMYb4qCwpvP0itlxJXVEPAd+fyy3Amk0I24w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T13:18:28Z"
    mac: ENC[AES256_GCM,data:EMIW815kJrEKwMgjUISpQCa3s/uXImTpalAieOMbmsB91TUrb2oszSO55aCnR3nzOs6kTXLBav5JLF5B38hnhxv09j4aF4ce5sFpY5+L0PoWivQAYpe3BADxeL2sUITMNWVLgsxtePGwhlsO37k4iGsDLV5H+DRrWqJsD/ij16U=,iv:EwBYiikeEIfOYtGwG1suk7krWhz5TELyUb/v+CY1XdM=,tag:iTiuOlh5Ad4UCDx2t88+Ag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
