apiVersion: v1
kind: Secret
metadata:
    name: immich-photos-postgres-backup-credentials
    namespace: immich-photos
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:r7rC84k9c4Vm4AoW3dKyhTSFH05e4hSJkn8tRQ==,iv:CvEZhMjtjJaP7pM7wsyy0fAu8kD+R6pQ2XVAALs+MeI=,tag:rLXg8Mz3CzHI6wAA3Naf+g==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:lsgl0KKnz8MMf4dIO3Yk4VTbEoc0m9psOGWvSud63TQbfINIwkeAhmGzXJXTMLYaZ1BfxYp3jiQ=,iv:6Fi3GtB7ByS51y7dJ5LMi4JsmBRd9UAR1NJiKcmMeRE=,tag:3wjZ02S8tEiuap90Y6XLAw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:O/xp7CTGosMJEXEfCD1E6+ZZp9FqvbsUYaIR9u4/jLQ10j3qRXCQ/S01SN7pzLjDun0RM4Y9pGs=,iv:olInPs+g+FrhXU/QVeFSqXYsg0UgRCMCVQAzsRK/hbk=,tag:2sFP5pthT4CbJ+irpjNvtw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUlo1bUdydDJ4cmV4Ympx
            S3N5dVpsNUVmZUwrSmkrZ0JGVVRJRlBmWlNzCmhSWVZ0MlVyOHl5d29rejg0akhi
            SHRvdXdIZTdzWnN4Mkg4WnRJOE9iK3cKLS0tIE5KU3FqekVwVGxoODl1ZEZTOWlT
            d3FwYmxFUzM0RDFPWERKTnVNV3pzMW8KDXLFTISAmKr7A4Bnh6rBb9nRNRbirSpe
            QSLuO8Av6rai5DvxBntWCga+nYErohbaXPM+FBkM3L2sX2IVBqWhzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUnRZRzlpWTlZTDlwekJ5
            dG84dy81ZG9jeE5kNXRqRG4wTStpK2czcnd3CjlkTXdlUnpHQnN6TEJ5YVcwUkhU
            dUxIOWxkUWpnYit1Q01NUGVvQytVcVEKLS0tIDlCU3BZVGdURW1DVXBDY0cycTV4
            TDdvNTZrbFljOVNGMGh0UmNkaTVoWmMKIfiWhWb8N/iPxi4qQLqOuH2ZKFlFXQcd
            Fdd+Pq+VWp2AMSdE1cVjSNVt3zz7QD+w/HKV+jUPKj6Zc3yOzvD2MQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-21T21:01:01Z"
    mac: ENC[AES256_GCM,data:8jd3q1/FybiZcGMUMX29/bPTL1uVx6B7kNDxoIov6exFRzArwthZ80K8CYN42DuXgEAWit4zLcAKX45Jw1C/SKPmnxbV40ljESCpHe3z2fZl5djMHJEDux/vQh/aHlMHf7wfxelvRif9RzHa/KibGoA29DXhteMdy79vyUxAvpY=,iv:W37yr7UnA2244YfXz+xQTsAaxaOxEJz7zDEaMo1qfJw=,tag:gW/dfp8t6Uew92p4a9+57Q==,type:str]
    version: 3.13.0
