apiVersion: v1
kind: Secret
metadata:
    name: immich-secrets
    namespace: immich
type: Opaque
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:KZa/3+fZ,iv:D5WM6Mr4uUmUjHXDYBavxVslWf0yCg1dX5xcC5T1Lyo=,tag:zoAJ2p9nS8A0cfXDHs39eQ==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:6cuMSvNh,iv:D1ZjKG1zp+g2PLj8E+f6Gzd4ic/v4WMMLEhTVi9ikmk=,tag:T6rk5YmRq+qWRzo71Nvevw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:OClOTMgnIh0lJe6LQjZcfunJUF7164B1GZUKtpVXzXs0zbPjGF2+6vnK/5U3sIfm,iv:ku/wVOH6lquY8dE13JB7K9brf864eUfEMAYjO2iJu2k=,tag:EXNg5G+Rn8DghKWQO7maSw==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:S0a3At1KTy2XmxEggJ3Wud905j0rhwuGqzj5hLWbkxuKdFP9MVmfznROaZpOC4UE,iv:gUmsSrhglmU2c5BCFYuT2SrPN4PUIngHuR2E2dnP9oM=,tag:S0zHUHT1o0i7RyRD1m7x7Q==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:8/Ea62v3rD4uEFFqhP2jvvh705tla896/TlrOKrw2a0Aro5flz84k2LkQaNa+2iFc+Ln/yJ4oEGlCTIBO1B8Zw==,iv:DOyZTX8I2+8s+VfI0ICtNdo1wj6137ig+QL91zgJSw4=,tag:6GswK12dryg8wnDyhSx0SA==,type:str]
    IMMICH_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:JJnMmYiyeqe4H52ScB806tIrp6PRVC8e2CsrzaLhLOlu6ULsoYqC+t0MK7VU/DDN,iv:wFaiSM/vn/3UErLDZakblGgF2Yv/Le4lp4CbaLDmsLc=,tag:zXNx5rQoKtnA8aZ9dP7lUg==,type:str]
    IMMICH_ADMIN_EMAIL: ENC[AES256_GCM,data:sCd98GKaJA438w1foQxvreS6e+gQPH7HOJf8bg==,iv:mzFznnPHGuUBqZZGRYndJwuofYRE1vjlS+p4VCCRu4s=,tag:2WEyH/oHSZKP5YR54BbkrQ==,type:str]
    IMMICH_ADMIN_PASSWORD: ENC[AES256_GCM,data:ciNv6ZHoPtA=,iv:FSIQhIRe/L6RRoJl1ilG9EEKUzkHKCpIash08wr9NOA=,tag:qOOyARbNGX6dudIKvwJz4g==,type:str]
    IMMICH_ADMIN_NAME: ENC[AES256_GCM,data:m9oS7WdK9V78AT1PWVCy,iv:MfLPwAG+4UG+sXp46HQCzOlpuq5evfim8zBfiU2Y/IY=,tag:xxErq0A17nxBPajETtBUUA==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5a2Rpd09OOVV3dFJnWGF1
            MjRSeHR2WE5lelBCRXBpdHVBNTBiaXRDSXh3CksxS0FYUGdmRHNTSTlCTlU5TTNm
            T01QTER0WmVDaDlUTzQzS3psVlAwMm8KLS0tIFBwV25iSS84WGMvaC9NMzB6TFVZ
            MmZaVk1wejFuaGVIdzNrbjV6WkRmODAKMYpJhQIjAsZBaX37Npxf94UHAjRMXONn
            oJApbwYul+KyFT12fNpaZgdqLC/Bq9sSMAH/KficK1/mWLR6c9cBew==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTFU1eEFFVi9KK3o5ZHdm
            S2J4Wi9Dd2ZZRVNZQXNXL01DOXM3bW9xb1RnCkpVdCs1ZVdOZDQwa1Q3N2tMQ2V4
            SEgyRjNaWVB4Um5kMktRNG5VcnZiNHMKLS0tIEJZRE9hdm5jQ2JKbHIvS0NZQUNE
            YWNPaVhvcXNYK3J5cStFb2VQL1BYQXcKn7VHJFKhhpJPKJuJXvUF/09lNyKB5qX+
            Bo+3J6zuiQNVsYIIFdATEDwYAyIvRRRY1Ttb0vbZNF10KMPk+e1XUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T07:38:58Z"
    mac: ENC[AES256_GCM,data:0VKtJVKlBqdGcRkJD/JyPI4Mfev8IVg5ZmqMMlpMWQPTHg31ulRXuCB5NNnBMNV86aR3BQpf80XLv7s9+fmhmW5LakxvViwJca+iituvXHL2FgEec4KlJh0AaHtW0RUTlQSiqg2ZpMQd+3adTNxGCJUq8n6XY/9QqHgbr5DR7sw=,iv:fp0rc5/V0TH9+H/mySEILpah13Srt/iqry2dUuGtKEk=,tag:ZZsAGVMmz5ufyfGaWF97gQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
