apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-e2e-auth
    namespace: media
type: Opaque
stringData:
    api_key: ENC[AES256_GCM,data:ITXYMKUq4qns84fUv0mL67FGhVVnUKWBLBQB4UBxml4+T7blKZVdrQ==,iv:026r/txFE2OmvpnGl8S4k9E7gqmJXjLmjuvOgi2IW/g=,tag:mRMhhsNofwiqFtDZEXBUXg==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3QmxnT2VDdFkyNUc4MmNa
            VWlJbXZtSHpVZ3RrZnU5NWwwODd2VzNteVFnCitGWmVTTVlEU2lDU0R4dXRhZnV0
            SlBpK3BBZS9QdkU4OThpS2dQVHNWQ1kKLS0tICtHWGpUdzQ2R0lQQTJYMGdYcDU5
            OUpCZnFhYk9yQ2ZCekFjTG8zQWFDSDgK1jBd/T6AIRN1OX2VrfWEqPhHbG8TyXcj
            F/Cn21xkvnMo3DnhY57kwkQtczz/NR/vjdfxW4SHx/K7RSoBdfq94Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5aGFWMDdkdFhMN2pGb0th
            Z3FuZ3F2ZXlpZjBpNjh0eGNkZFlIWW5JNkdJClVOeWFCdE9oWW5YOU83VTB2ZUlB
            M094dklPVjJQQk83NjNqUmtQNkpkVW8KLS0tIG9EaDlxdVBkRk03bllGbXFVK0cr
            aFBudTZkdDcwNXhUMVNTNG5sU3cwaGMKQcwU6AdqGgx4f+soeHd98rTL1jg2dULF
            wXCSMByESWUvEwV3m0FoDfbsIl6jmPu5WBSIAMvhNtxlJdpE9gpj2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T21:09:13Z"
    mac: ENC[AES256_GCM,data:apYFGpxmG3q7Au/2AdeYj0hS2V+nlI52gJo0hOlF+vky5ajDPeFcgjp2emIDqUSmL/8ykmhLjUyHMUR8ARcKwm7BQn3BooekjfSi5gtILIUPrph5O3pCkc4O8pcXgJmWXGfYTqYUvsTOvLHj+TkEy6sOp5qoEked6bTfRUgPCVk=,iv:5I/RGMPVdiHx/g6/fcOu1eHl9OXh1owxLVTCLUZkjeY=,tag:KO8E7J9Ua7FVrziBrf6iPA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
