apiVersion: v1
kind: Secret
metadata:
    name: jellyseerr-e2e-auth
    namespace: media
type: Opaque
stringData:
    mode: ENC[AES256_GCM,data:4NbEdOI=,iv:1QCrd3WKItEMS3l0KxY2XkkSIGRwNySWiGDNOrVEPeg=,tag:mFljr0+kttV364JudsIHgQ==,type:str]
    email: ENC[AES256_GCM,data:/LEtr9fYWN19h3YzAXc+2t4VjcBtAiJVI8GzrjtJoiSfV0TfJNs1yPAGXAEn,iv:jwNOyyr/TCPHcXbgfCfvp6B5z/ELDaHNPmXIwLiX8ms=,tag:qrK8iadQcXJqk+3KG0qFyg==,type:str]
    username: ENC[AES256_GCM,data:dw3d2A/k7TWejFbignM=,iv:Z4RjmmgXvTjGAVS31WOWMrQfTPSZ78ZVLyTrcsmM9+U=,tag:IgAxu0GKRsILqZxxtRImPQ==,type:str]
    password: ENC[AES256_GCM,data:2ZudLOtiYLZItwzx5LcWBpjWhOVIaw3Lc5AopEn/MY8=,iv:4qLGpzDecq6+gHsF4DjWELrgTw4S2gWCVbD6GHNToOI=,tag:QgOOCQF4jKiZjvs+BxXraQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3eHpFMGVXbWxDOUtWR2NM
            d1U2MXhNOG9sR0pjTVlRRm1Zc2FONktQUUIwCnVtSERMUER6dVFTWElUazYzTEpH
            K01Cam96ODFYRGpjcjZRQm5yYW13WU0KLS0tIERlTUl6d0tFVGtHbmtvQ2ZTYzRZ
            MjlycEVqQWJ6dk96TGRTUkxMU0liM0EKp5Wd6S7CeUStAHZBucSSiDco9c0ZgbX6
            SzwkO3kLLXcEN3uunJp5q5VD1822pffhS4sT35bGktZVh7YNFxpOOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoM1Uvbi9ON1hCQVJiOFp0
            UUNMYlVneTBTVmJETWVrRTVySi9UcER2Z0FZCm5OV1ZxdXpqNHNmMHNINkQrZ3dz
            Um82MjFjSlJodTBoU1JlUHVRM0pGY3MKLS0tIE9KV2FlNUQ4OEZJUE1HTXBqdkg0
            Tzc5dGhuWlk5MmFLaDFIWkVBNHRUck0KKaSK6IJ+aXk5LiplJdg2Qh3kkRoaoIR/
            KUKX0wiRoAaQ6SyHYCghpcYugAw+CoKceKgdYGmcDVe/y1BB/gew5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T14:48:04Z"
    mac: ENC[AES256_GCM,data:FtVZ9iPxt5s8LgsDgpoWp4H+fWR18kyEhtLjVAu8vOW7sbKHbKv/5gVCj/NkGbDP1DfY0HBRV4O+x3cM2DU5MQ7bvXvqaJhEEsPoVkB9dVXfLlh8wqi8HkMiAZDXDpeKpvkz+6BX+ZodLyaEPsJ1zXrAqR1zeyZkme+GvbSCVt4=,iv:rNBQLxha4qlCEiR5pQXQVgPUNQylvopnG8TZ/3tHksY=,tag:EkaLi34FZm9kqeswZyfWMg==,type:str]
    version: 3.13.0
