apiVersion: v1
kind: Secret
metadata:
    name: jellyseerr-e2e-auth
    namespace: media
type: Opaque
stringData:
    mode: ENC[AES256_GCM,data:eHusZYM=,iv:h5Axa9c8HplQRK6RmSQXkZhoVUiXLEkMMaJFkyqeiRE=,tag:OwLXCPAP3dgxaI/27o/uTA==,type:str]
    email: ENC[AES256_GCM,data:cA/GAzIrUCO5AHhzP7Z9XmbTmoqezSx+qNic+PAx,iv:XZ/daO220RAk8Glfhpg/iKSvSz+L2FUhXPjlsYB1coI=,tag:x8oM/nrKqp9icy6uivSPzQ==,type:str]
    username: ENC[AES256_GCM,data:yfNJgQmqEag5vRzIVOc=,iv:ulLFtkp0+KbZ4AktgsxWWuhM7+jd3M91icX0IagD5kE=,tag:4dnyLGN7RZ1YfN+JB2vKOQ==,type:str]
    password: ENC[AES256_GCM,data:CgMupnszNCdmkLf2/sYmgcc2Had8gVibo+x6El0zPjs=,iv:UxQ+qZ5sbd8z4XJo2OZ4NQ8zLnVL9HoANhZim3aJ5Qc=,tag:K2+X+OyuD+RU1Rm+EAylQg==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NW9TWXprQi9tRE1LL2JH
            aW1zVUNOYjVZWG1LZ2cwRXVDaTRSTm9vT21jCm9MN2dCWEJMMVpCK1dxY3EwaGJ5
            VHZMbXZycGR1d3N3NEtKRWF5RHplSkkKLS0tIDRTYUtIT0VKMkFJWFBobzBZb2R1
            VkpZd1pxTm5HelJmbFJtNEsvelBGY2cKnbICdOLp3DTH+TDKh4G8fpV3qn+nOZy2
            VSdbIzTMpUG7oDo5PfVy7O7Ia4k0SxISk7d9ZrngtDGw55ED/XGMAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T20:43:09Z"
    mac: ENC[AES256_GCM,data:ZoMamK5e0g2bQf675AGmVQH+KD0IAle3gLihjwTFxXFTxgl43/17gfs9asNmG46BETlgynTsu6oRTFxN2TqbCGWhRUqBHDgiZK7ZC0T5bg9cZ9NqLHxbZqJ2ElMp+f7Dh7nEl91dDpsgRmUdPQlmkSSvNR4ngm3ov1mJKs7FcHE=,iv:Zk0l+wEJmqbOtGvzeCKjCyEC4CSp6bTYq0bfQx3FABU=,tag:OMb4iMCb716j5NgnBq/wIw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
