apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../homelab/secrets
  - cloudflare-tunnel-credentials-testing.yaml
patches:
  - path: authelia-users-testing.yaml
    target:
      kind: Secret
      name: authelia-users
      namespace: authelia
