apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../homelab/secrets
  - s3-root.yaml
  - s3-monitoring-credentials.yaml
  - monitoring-s3-values.yaml
  - cloudflare-tunnel-credentials-testing.yaml
  - immich-secrets.yaml
  - matrix-db.yaml
  - matrix-synapse-config.yaml
  - matrix-whatsapp-config.yaml
  - matrix-wa-config.yaml
  - matrix-telegram-config.yaml
  - matrix-signal-config.yaml
