apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../homelab/secrets
  - cloudflare-tunnel-credentials-testing.yaml
patches:
  - path: arr-api-keys-patch.yaml
  - path: recyclarr-secrets-patch.yaml
