apiVersion: v1
kind: Secret
metadata:
    name: logday-postgres-backup-credentials
    namespace: logday
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ES+Uo2kiTVeL+4J8szUaMyIkbt6XC2Nrfy0KDQ==,iv:h5cV6/mFpAF2XGyMyiALRJLiy4XNEMV08JzSK1c3DNg=,tag:pS6EACUWY1H9SL8nt2wKcg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:7sqHXxOfNClkbXnhJU0LpoMSE3J1xkjggLvasBVtoZupC6hVKfY8Hwv89T2LPFLXF1RvZ+5TmqY=,iv:BjayQGT0oLDEM8s4CPymxVHdLTsy01Knsxpjt24ULgs=,tag:Tc39nNQlEMJwtjGt7V0ssg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:JGXa2Q5NRsd8HLBWZMTCpUA+jLa9XcHQVVqNnNUaB9MpacS3lZX+TuHmU+gNWKUORFNVnhpFdqw=,iv:zg08HaJDzBeiQf1qSX6dQBlcBTbz8HsUzyEv1x0KOC8=,tag:IvhzPlqBY8oQ9H6OYNR6yw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0R201b2t4MWx0bUcvcW80
            Z0dOTEdCTkEwVUtCWEF2WkNhNU1YTDhkZUM0CjZqN1BBbWtiaGZJdTNjZ1lhNjhk
            eTF2SFk4dHUrZy91MkRhR254cmdLSzgKLS0tIE9lazNJSHdSWFNjS2dDRDlrbXQz
            dE1XVVlXKzh0V0NVRndKdnVKeGtxbFEKjnyZL6W92Bs539vFskHIZAkpI3el2PKv
            J7fLSJP5g5PiOpe3gvF8A5nS8I5Dvi2r0ty06ZBTGq8UJ4PVZEzjQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRWJ1Q0p3S2hiVkE1bVhw
            dmhaNEtlSGtNdDlYaGJJQkxDRWZHc3FpeFRvCmhHYTBiYTV5cWxZZEtBbXJpbktX
            RUxwc3h5dW9qdSs0TFNxL1VPWDBYek0KLS0tIGsveWhnVmJqUTJ2SVUxOWVmdklD
            L1lObmtFd0JQaXpTQkh4UWdacmtudDgKlcbero1zk2v399ASpf0i2oiNbhpkLl/9
            6W9sS/JsWJK3iP4/VIcimDm9V+maPVfSUb33lhEeFVIJudV3ASiOig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-06T21:42:20Z"
    mac: ENC[AES256_GCM,data:6Tqn0Aumlos3a4WRBCuZUvzLXeZlVX8kdZw48HEz3vBIiYQtm/4eihjixQoApZWmQsifATP8FMRRlci+Ua+KfjxdTQxuNu8bPUQWlpKnI9gn/cu7IUzNjfqYoNStLcwVZSthCE8pUeqw1RCGk8WLp+FSvtPy6v9fJZHLg2eTP+I=,iv:jYAkXuyJ3ovWegMhbYG+GKobBvOKY856chxMmSreeYo=,tag:+Mas7rlyH4JgVhZjL4ZlFg==,type:str]
    version: 3.13.1
