apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup-target
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:I4Eqk7EL8s3cgQFyl9Bq44xob7E=,iv:eu84+I7q2EzzuGUtU31tiQhfrMrNqbLDvhJhXHILuy8=,tag:nWqtupAJart+DCfJOQ09Hg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:6/mJcgqEGQGGj7lAgIOqpWexMg3Lug1XDnTBZx2UlaPu6PjgMxUqzg==,iv:Z3tufuCM7RPdHAkQhthv2rnCbbhidVaa4zpltj/1rjo=,tag:SoEvEQf3Sv9Cnit636RX3A==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:Q9ljItEcXRw8mmkRLq3bDb7ynIOBl0g=,iv:9hHXazvzJF8C9H1KTt0W7OCNcvHes+dkIzikRz2g/RY=,tag:TlK6d/pBkFMBmZwLuSSn+Q==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbjM5MERkNUUrMFpOcE9k
            NGptTUhpOVZlVFljaFppbFlzWWJ2RWkyVjNnCll1OHpxc3d3b0poSDNkNWY1ZDVW
            L0M0RW5oalMzYmM2ci96YXF5K0NUaDAKLS0tIGhReWtPUFZ5YmdxSytidjhHWTRR
            WUZPY3k0WDRtNEp1eTBieHJ1TnB2OVkK4vmKvqKeWikRZWFJ0KnRzD8ybt3jPfXG
            0a62qtCksTmLpqgcAOiayI02zI0aUzTr8YE6eAPKblBxXwvVC0Pj6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T08:12:14Z"
    mac: ENC[AES256_GCM,data:FBX0LW63VhchLsTYE3JArHM5ILn1zOi6b5za6uEVXdpvv/azSPootwQm8Wl8otxa7bAmFpZaNl/Q978m5/9bue7272kI+WKJPA+cUSrSTvjlKDEq0/YIFhJkI9kQg3GTQUJZWVumRXQhVo9w3Rd4ODnjZuHwuJwumgF/xoPB1s0=,iv:pMChWoL7FmskpkrtuyRLibainzSFkyad0j7n9r+HL3M=,tag:UpKFJq0b7BnLWWy26kiJXw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
