apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup-target
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:1wGf+k3Sr0nmtgx9RadDNSr6SGk=,iv:raf22cemf0BvVXADU0g82iYHy8Lwmcg5+y5Sv0mgT9Q=,tag:DBmqblUOdqDPM3frwjBkQA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:iasmYo/hfZBNFDIQqbYTDDhUjT0DGplq4Xb8DEgFsDkT1xZ3nOV7zA==,iv:S+kxIwdWhjBMPQdFVlVut6PJCbVk5Y6sW9KDtV8fJdk=,tag:50waqYjyO6w/LtsFVXuSAQ==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:L+CZ3KtUJ2y7gT5MtWW/wzFnwaNNIv0=,iv:8edroIWdZitcAKu3Y8rymH8zQGMie+9SxunR2jE599k=,tag:9g4C4y1RoL7nIdtLLKTYrA==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZDhLM3NFcXQwTTg5ZzY4
            d0xENVRqa0dDZHpIRDJ2dFE3TDFXS3RRdkVZCmlHaEF4SlpZY29FcmtFZU9GZjdC
            K2g0VklGYVFvMkRsNzRhc2lNbW9kdzgKLS0tIEV3SURSTlM1SEtsVmtTTXhTclo3
            NDJpZkNibDMwYlluTXFxNlAzSTNLV2cKpaXxUx+BuZ2h8qpqLc4zcswrlG3X8isf
            ZaUqA+YrNUwJOZA9opUKLFmzMHJ/OBflltlPxFrKkfmtQnnGdNZSkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T07:38:26Z"
    mac: ENC[AES256_GCM,data:42FeKY+pwX51SVgan9lKLj3x+8ioDAciJxLhSFlEyrswGp0FxdxNwGVT7VPgvtNFCsWk3sheepHXeFsFKoiwjiv2QoLSURpozWxBlz81QGtJ9h4gYrIokpRz8WD9lBRz4NewhEwsLPeERAp8Q4M47eND9XdOVxQHWkh0GslCYb0=,iv:i1IXnEM4M9ATVCbDuZcpom14v2H0lLJ1+WUnfk9I1Gc=,tag:gYpiwm5OC1R+TGPf0MG2SQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
