apiVersion: v1
kind: Secret
metadata:
    name: matrix-postgres-backup-credentials
    namespace: matrix
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:KCFR7hSgt7I=,iv:qJZWKLvZ+bmLpK6QVoQI9rHtf8D0PPppepPrMR5KezE=,tag:cnnvTsKw6SIIuUfRku9iSg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:+G3qLQwpZxi6Ide0vQ+GCCIZSIjSL7jcPN01DOOWaTfWHUKQdldRSgy5BJJ7IwCkiztPHdxhwfn9tdkfXfC3MA==,iv:NOSkCT3NZ4ulsYtl36Ajs57S2lkiqFnRSmdtiKkpd78=,tag:ZPnXgE0N7KPVfD0qK4Zo0g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:JkOd8yo6jie84JwQYGOloYMHJnqIYCtqaRiVQprZqf5GVfFwd2oQumQjDR9wuur82tVcrEigb232UgROyRpmNA==,iv:nUha+IZHA1UxTytbaDsbbLFlKMwQuC68MIlrwnGrV+o=,tag:oe1VKkwkJ/BgznLWZr8k8g==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLV2k3Qk1kaWxpZUtHNWpH
            L25rYkpaSzhsdGlXUlpGMEZmMVhMOHBQZ0NRCktFb0ZiaG5mSXBjay9WcTB6SEJo
            czBHL1pxZmVIeFd1STlGd1dnc2crNlkKLS0tIElva2lKSStDSGcrZ3hmWDloeGc2
            RE9waklkcy9MOGp6QTdSQXc2OTQ4bWsKbCp3UvUnKUtd1XVDW/yjM8/sB7Ym1nBp
            JoDN5XEjg8a1b2nzq6RiAU3K2qUai79K2E4+4a4FXBMyJl9xDHs9bA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T08:12:17Z"
    mac: ENC[AES256_GCM,data:Z8HQtWeZUUEI4Vmti5b9MGTWRwAGSzjBWqda9v9Ubec+ES1AOm0hPu279Mbia3hznLD4NXdIR6tMZYREUh5Ao2nkt1wV7xjpA3eyNCg6uQqHabwRy+suXDbs8rwpVuRSntMdYp41k6uBLoOL/UM1T83I+1tDprj66LtJRAabh04=,iv:GVXAe4M4mpAAs5bwDm9rVoOMW9PEr43UphbybgAXFnM=,tag:GihdQtBuIqmooeL5G66h9w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
