apiVersion: v1
kind: Secret
metadata:
    name: matrix-postgres-backup-credentials
    namespace: matrix
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data://ktku33XJFTtgF+pX8NcoCjVdcAg44pPaO3/g==,iv:Ijk/E1A93IWMgLWZu0nF+hByL8BvsTkp7ubNxwqsN8A=,tag:gOpfH0vcu+p4Osgk6Lt43Q==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:QOpro97z5D7WoMmGxpGZtKYku3RwFTg/rpQhL4obDPgHIvsZO8ZUOb5Jai7Zb1JgZMMB1ZZeMZo=,iv:R2VvWsOevdCqG+WUJFB+EhwR9/w9MJO/FU/n3EkVrPA=,tag:SFWEWB40m6UhJPmGCMdxCA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:47ykK6dvSJqUOCWZiua+TBBhozJO7jDHEpkS877JQoHcqEPNZ2agWJNSmsDbSHUZe1Q49JAmxWg=,iv:DF4+5KXzakyjy/u8obr6iYvtlG88UvCOvlwNnJgphbE=,tag:ZJ+VrJyJi6vHn/7MLUTOQQ==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3N3RZNkNuanNxN1A3VVR4
            bXZDanh3VUhFdEU3MUU1bmhXSWYvVEpLdWtzClVSOXpaL29TUVFKUGowaTlKUVBw
            bWFLeDdOaVhINjZDd2JYNUJHclVhNXcKLS0tIGY2RnVxWmVZd1VJWnhzbWNJRml1
            OHozY1JPb1V3UkJZZGM5cWcvMVZEMlkKghL2LwjNkUdb9qX50nuoDWZSQbb+yuom
            apL/1IQN+NMkK8HO0K9iq/eeMkANGj/mkUAXafTv6v2vnc473t45vQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFK2JnU3o5OHBZUlZIMXRS
            Z0ZwNFlsRWJMT29ReUM2SGxIbVZKS0NKbVFVCmc5OThtV1ZJeXFxam94UTMvUmY1
            RHgrTnd2K0J0NVp0UHg4cVRHTXl5QlUKLS0tIFRkczJzWEZkYW0remlEaURROGNp
            aWUyMms0VDlXWEFSdE1ibzhvV0RwalEKCaF44x6jEt+siZqETN8Oiue2gW92sFQy
            A+EH12e9nb5mnAY5r3N6Ay5nNhWtoLWxkcORtvCjzpxgqT/QZzOYBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T21:46:20Z"
    mac: ENC[AES256_GCM,data:LIJxKW/E3TbUVRw7uGNF4K1Qf/Y31My3vmWCbxxbymsda75YmSQ52CY1VaxsqW3Qt31+GIglXKKy6hbhj8WGHb1MWy+cdclMrygRnCjI7fNL9h8qBOsjSRtMhOmyg1braPFB9FiUWOfkJZfMtD+tPyyZYRDExO6w6OOJp0MII4s=,iv:iaMh0ZmpldTbSnxlK64Mj7Wajux0pRiPPP7IHaJB7Ms=,tag:AVhhVvoV9dWh9AJhMD4puw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
