apiVersion: v1
kind: Secret
metadata:
    name: matrix-mas-postgres-app
    namespace: matrix
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:kn+N,iv:fIQE0Ukx8vC80IL3i7hZT+nV2MOC15+pXFhgSQAUbp8=,tag:JM88Ux36Wtdhjl6ZxrBZNQ==,type:str]
    password: ENC[AES256_GCM,data:ZkCKhGkzfC23nssM7OumylCaPYM069LY5ve42/pCgUVkGWAEO8eLeLNX++Nz6Y5thKfI6vr5UC2rgleHum9ReA83927IP66mkhbP8JLHYFoi5xDhHAwiuFksqHa7hDtx,iv:d/8WVYolEGzcgyid6b6gOs46S8/bv1irOlZtsv7aZAQ=,tag:NrefzAhp4rhmWQ9ZkX2Tfw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWFFsSXA3VXJWVW1GOG9I
            T2s3NmRKQzVkQ0tybTNWb3RCL2pyQUgwUWswClY4UUpxYXRqV2xxaTFpMWdKSkNH
            OGhGdWRVZ2I0ZlRWTmZCUFN5U21XOVEKLS0tIDdudFlpbzkybVBlR3NQRGRtb041
            bTRkRzhIK3F1S3d0YVhOMVU3UjJ6YUUKDAKggAjgU1x5BdapzsPsHdQn71ZDR/Pf
            +wFAIuzmjxK6JK+fM/MGfPC2GnlAzO+7AORn9s5yPpgTrNkp0WUxpQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRW5ILzJCeWtvZ2ZWQm16
            OVc0c1FUYmFERkUrQVorVkVtNDJpV3A2Wmc0CktzbkVjcWd3MCsxMFpKUEdIM21v
            ek5lejdEM015d2FRTDdDNDlaeGNEbWcKLS0tIDVkb0NvNWhpdU1DOVFpYVh6aThu
            T0YyVThaSDh5ZTU3ZkZqVUZMdlJSeTQKFQl6bCrhuD9aOU4yrkFoBXASvcLXgMiH
            gnFkrCRvEXtyic9nMNc9KN2nGoLIaxjJrtCFQpc7IssEXfXQyVTmsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-02T09:15:44Z"
    mac: ENC[AES256_GCM,data:TJXqhQimdStjFkv3YPlEUnMaJrDJ7uG4nLxQD8WEWLy4totPsFyKo+LAN4fUiIQ7Sn8jeJDkEyqsby1xlNf4Y/lJ5+kEk6qUWr+XfA2GNzGi7mEXl7JWL2P4CoN6Mi3Pa2dkqpusAZJ4jWVTF83qTUZ4cq3DxJx9G49wRhlaO+k=,iv:eMyc068ecuvnfFoB0BUN20y3tcKQVvUyb/o/WUQ1OJg=,tag:U8GNR3wpgmiKsk2rGz0LCw==,type:str]
    version: 3.13.2
