apiVersion: v1
kind: Secret
metadata:
    name: media-protonvpn
    namespace: media
stringData:
    wireguard_private_key: ENC[AES256_GCM,data:XTYkg/YMqkzmCUnnLos5KKP3SvCl3GY0qU4JFFF5nqZIrpmkGGIeRKE2OBQ=,iv:jaQ8wxn8HO8BUWoT5G5Y50S2K5/GLTxLL4byq6R95Og=,tag:NyEZ7piikL2DRIIPiAn6lA==,type:str]
    wireguard_addresses: ENC[AES256_GCM,data:ufKNHrhig2hUvVzBApRWQhbBFubWhLpO1MytobWs,iv:4RXjMoPLGsZ5iDukAehQFnrLnhKKMQ7f7t8EWc1mr9c=,tag:XsEtQbUJbk3zXHE8Guql9w==,type:str]
    wireguard_dns: ENC[AES256_GCM,data:B38se8cQens=,iv:f0PNKaRkCBJe81aYx2WF7JWY/H2IumPKRBXjDlAkHgE=,tag:n9LHkgBwo13RqawyiIV7YQ==,type:str]
    wireguard_public_key: ENC[AES256_GCM,data:TnJG6llDW4p7oNwCXCfpNPQbWIcf4WPCgHJ8ILjnKP2kE+SblOro8yOKIRY=,iv:gNlTXcXdUqjG4a379jJ0yxnoo4Ma1s8RzUjsZQ3oUHM=,tag:jz2VedaGP82HVomIObtdcw==,type:str]
    wireguard_allowed_ips: ENC[AES256_GCM,data:Eg8nTzrxkcJvyVaDnHA=,iv:QerWyot+vvem8NnepLZHgpxlgQL7dpGXqEpwa8W0nGA=,tag:fAsxOExZ5dkQ2Mg3EWtlgQ==,type:str]
    wireguard_endpoint_ip: ENC[AES256_GCM,data:UMGsv1GAo6xMShgxy3k=,iv:yUfWvOTZ+W/Tqun/bPtmUmtnVlFcm8OJrVL91GR83CQ=,tag:HpL14WAZr2rjuOZysz4Uhg==,type:str]
    wireguard_endpoint_port: ENC[AES256_GCM,data:HZU8rB8=,iv:sedfREjjE7hOv3N3qvLvfJhppnnVg+W1u+FlDinyuKg=,tag:DGGoHOjbePBhFWTLo9lR2g==,type:str]
    wireguard_pf_up_command: ENC[AES256_GCM,data:WOumtqf0m66uz3rOS9lEAvZ0Z9urYr/BWZhY5AFSSSdlTcwTbNKK1s9fwEEyNW/JE5gGi30F3QnaePsckvIy/NaITJ1ir79Y3bHGfTjyWFZpP06beTCAOotExSsa6A+o1bJ6Cx8DreDr0uD54JsiqGweNu2WknQVx0UnQXUh5egY14d5wWybMjjr/vmzJpMbQ0KlIrILxNevU51F3ZEmlb7Fg03qoR0tkxJZES3RrBF4GKRgpac21TMXkYbWUd/39tYV9nS5hWf+QDiEoGg9A0Jed2HVVBwimvPyClqA2xVOwAij,iv:/nO0g4VbWN60X84R6Drx87XoxNRWZXpN+4rMrmXo8Q0=,tag:LLoUBjxxOLZ1wEwPu5Rg5A==,type:str]
    wireguard_pf_down_command: ENC[AES256_GCM,data:hO1kE8N10veIvL6Izx7iDCM2FF+T4DDwELSpPuVNyKKISQzrfPOaI078WMa4i2EMmu2wM9EspGRTXWCdSGej3CMfDOXIGiH97V+FU6p1DtZsI/8jGmfnmPq8N6i5zzOAVRVLHIiEFGHkvzlugmss7/QCQQIQqyVZyIi2K+IpXDsaYF7gayqH9xjUGYghLniQIXp7rr4+Tnx9edoOM0g8+fNQnDSLesBBwQ==,iv:PkI3UHQlGHD6LFC+EuLwLkMxfsK/FVnyxiM9xRgN99I=,tag:zdQRVI9lirXTI1gYytTGRw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdHpPcXVCaDNWcCtYdDFx
            NCtPNTlOWURZamJsWDVrNjVvMC9Xb0d6RTNRCkx2ZjNrKy9PUFhMcVRUUy9zdjBm
            TWtRVUhVOHk0WG9mZ1ltYWlzanBGa3cKLS0tIFpadDIwODZLQWNYWFNhMmpVSjNS
            U1hoM3BnZ1pTYzdFVis0TEVjUlA2NEEKcJ1RKPbJLTIbQdAJbB7tf3xmni1KxMC2
            d/+cY22a14fyVezI7iM8zOtxXc3lc31LqhqS1KVE0QK5E3z0v6nXhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WENaaGlORTVlSnd6Rmt0
            dE5qUmZJcUJpTGNKbjRtNWJJQmRqbU85bFZBCmVEVkVEMTU0bnNEMG1GeUxVQ1RB
            SFZBa2Q3b2RpbGdtd2QzRXF2d0xrajQKLS0tIGxGUm8zdVRxdkNjc0pVcGMrWENN
            YmZ4enRjRVdmbjUxdGNyb1YvQkYwUjAKw+wkyyGxhpJIDUaOpBXsi1CWVInO5jBO
            LBcBxG1X1xYW0zXreallXf/GJnpWD3VT+Dt+9zFt7hYWdx73aag2bg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T15:30:57Z"
    mac: ENC[AES256_GCM,data:JM65bHVdU2VJKhYAuqqJCK+W7OLxSti1sxYGFeX3bcjpPTQ6C/BSiAFz1XYxbvw/uZBNd/gC4csVXnNs0Ixy++TbIre1icdPANBCtBEiV/M38vGD2HlZgLFhIw2lIkm4KZhsGQiHEmRW01mwnxNC8i0PhDWKmLdMvoiv9q5pneQ=,iv:DPN9QHrCdWvTx+OFag4Se+CJ/JX7zONYCj9g/d1KQv8=,tag:VK/zUdCSb5TMwCpHe9Edsw==,type:str]
    version: 3.13.0
