apiVersion: v1
kind: Secret
metadata:
    name: media-protonvpn
    namespace: media
stringData:
    wireguard_private_key: ENC[AES256_GCM,data:JJ6iwSw85EFjn9QwqARG1tp0TgBrXfctJy5kiU3C5qoq5BIbosAfOSSUz+M=,iv:cLa6umwGsTlO23Wt5yJ6JMyIGAIA7CFvsiwfD+4eawg=,tag:sLnlE4i58fkCXpspLqfpUQ==,type:str]
    wireguard_addresses: ENC[AES256_GCM,data:ufKNHrhig2hUvVzBApRWQhbBFubWhLpO1MytobWs,iv:4RXjMoPLGsZ5iDukAehQFnrLnhKKMQ7f7t8EWc1mr9c=,tag:XsEtQbUJbk3zXHE8Guql9w==,type:str]
    wireguard_dns: ENC[AES256_GCM,data:bUm4xYJPVfl8YuD87Ig=,iv:4iiUx5KexO+UvkMzp4LkS34NcPPpUcc+rASmVRa+mXs=,tag:d7l8BH2Tb6f0Bu4foNkS0A==,type:str]
    wireguard_public_key: ENC[AES256_GCM,data:nrAlnNRopxpsZGf/49uDkNmoxKNzKA1e2yOOiuT7EYy4Su3qHxQRkGgznNs=,iv:5D61wxQ8pQrRf/oqb4qWxlTJuuPrlTaDNBgPlyfk040=,tag:CN1kElVJ+Xl6cuhxoaZOrA==,type:str]
    wireguard_allowed_ips: ENC[AES256_GCM,data:Eg8nTzrxkcJvyVaDnHA=,iv:QerWyot+vvem8NnepLZHgpxlgQL7dpGXqEpwa8W0nGA=,tag:fAsxOExZ5dkQ2Mg3EWtlgQ==,type:str]
    wireguard_endpoint_ip: ENC[AES256_GCM,data:/M2G0eOwcrhT8nOWG7mY,iv:l7dj3LshWyvDzxCDqdl+uMzYliPuaJNQeixiyqQuow0=,tag:LaBZaUJAZHsgyDXAPw6NnA==,type:str]
    wireguard_endpoint_port: ENC[AES256_GCM,data:HZU8rB8=,iv:sedfREjjE7hOv3N3qvLvfJhppnnVg+W1u+FlDinyuKg=,tag:DGGoHOjbePBhFWTLo9lR2g==,type:str]
    wireguard_pf_up_command: ENC[AES256_GCM,data:twgZ8gW1Sa0vAqP3Vgvp/h2TnoNM/YLnr6bIFTdMOtBULiJNGOht5jCrugcwrxLLQDHbTH8lwx9EHLIDBstQN+B31QovS4+RCAnrmLmNY/AF4vmpOr3NGneGagyUno+I52F2IxfrH3VdTgQH21MC9qC8HeUextw3Wz8o3EjrGiMlloxtpLxtIaPSd8OptJvegw7HjyioRdpyrfQXsYg5mj974H4W0TPgi4TJCHssHqh6Pz+iX16phi58NiiV0VeTQRYYgu9d1yT8TV+/mE6ssSkzPOHAMAPuBObp7ZQ9Ozp0JlP8jb+nG44LI3wxv2O04Lk8bRvbrq5jD6gRRje3k4qbTqOFxqk=,iv:2U9eQPq+ThO3hOc3ONeiYit3OnFBPwIEziE6caOsy24=,tag:90t8EizROTnoVNkFsxrhRQ==,type:str]
    wireguard_pf_down_command: ENC[AES256_GCM,data:L0GMfOu3AoH/PXCnQvthd0fkCtz307Ves3sGbBD1yGRVUzrtgOVx/a1dHzkbZyNh3yPTXufMdrXwQdBSiJwb/8QJgUvTIVJ8CYl5DEsvfqb4QhktxII5OBMke9y9+ZIgdtX3x0HpXDFOmaaRfIUf/zQikQu5QMKbcsxd/vbz+56yjOlypZ0N8JSzFev/7LENM/6HA1sgnYsVb+E6YeMYywpoPWv/9NXX61rAih2F2m6IV9u617vG+GZSVkK+tjjZHLmc/hs27uZZ746j,iv:+xqMynTsFd3KVPIgqxFxQBQbx3TOR5k/iYgvBVG7C7M=,tag:CVy8F62MjDLPlKqlOLObhg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdHpPcXVCaDNWcCtYdDFx
            NCtPNTlOWURZamJsWDVrNjVvMC9Xb0d6RTNRCkx2ZjNrKy9PUFhMcVRUUy9zdjBm
            TWtRVUhVOHk0WG9mZ1ltYWlzanBGa3cKLS0tIFpadDIwODZLQWNYWFNhMmpVSjNS
            U1hoM3BnZ1pTYzdFVis0TEVjUlA2NEEKcJ1RKPbJLTIbQdAJbB7tf3xmni1KxMC2
            d/+cY22a14fyVezI7iM8zOtxXc3lc31LqhqS1KVE0QK5E3z0v6nXhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WENaaGlORTVlSnd6Rmt0
            dE5qUmZJcUJpTGNKbjRtNWJJQmRqbU85bFZBCmVEVkVEMTU0bnNEMG1GeUxVQ1RB
            SFZBa2Q3b2RpbGdtd2QzRXF2d0xrajQKLS0tIGxGUm8zdVRxdkNjc0pVcGMrWENN
            YmZ4enRjRVdmbjUxdGNyb1YvQkYwUjAKw+wkyyGxhpJIDUaOpBXsi1CWVInO5jBO
            LBcBxG1X1xYW0zXreallXf/GJnpWD3VT+Dt+9zFt7hYWdx73aag2bg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T04:58:43Z"
    mac: ENC[AES256_GCM,data:32SSA04hKN21A39kWd/4ZPFcrJRsLnT1w8OIlZ4jYi8M2xkkqVbOSeWjuwzEU6Ehnqn7oUVGI9Z67pd36U45qYtbdg+lfJyYZSWBkkVbs638PRoHFqwzrvi/GMRUX0SZYslWyrfpNVqJSg9P928onytbx5Gx5CgKuLJU6VKjOZM=,iv:uqbsVC4zdyIgZ5QtcdvKwJL4HZe4MsRMxTfaWKx/gF0=,tag:Lwprp1oGmowafs28f7gSyw==,type:str]
    version: 3.13.0
