apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-postgres-backup-credentials
    namespace: nextcloud
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:yAWbudBkIyQ=,iv:tT76HgHU7lPwj2CUvAV1l9utZebn8ggjFfk9vmkI/Rc=,tag:+qQ3AgDJNEtBgiKNlLb1TA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:Et5sJ+i9tDpJyfyc+NtBNnNHxvXXIJgkP2CjTGN91BktrJGbmLZov8SVR1cq39PsXqfgZrQqfr6owv8OEVxmQQ==,iv:aP+QaBxpuHHdUmEKms4EJZL399AwecmtsCWGCSK+Uzg=,tag:s5hdz51sgoMTEyx6/Rlg4Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:5GEW27JBVMy2CAcOJ2OWtKZqQIKlPnV8Aes8Os9OJ+WadQnm8n7YV9ZFzgVAi88YXhOC9l5bXESQZEbo+gy7sw==,iv:7brfqfsw7cpD6kj5oiXYqTVcpGPaYX3GAKakJVD1qrk=,tag:CoPI6CMB6NfaTAbIugJk4Q==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSWUzdlhDMmNONlp4UGpy
            Z0ZUQXNoMzBtNnNuTTNyRFQ0UUxwNWtSNzJzCjZwWFg3YUJWL3Nsd0ZVK2c1OFBy
            WjhCZTNGYnpJc0x3eU9IK25kNWpiUEkKLS0tIE1WY28wQUYyS1dCTUlwY2R1eHRR
            L3BTWWZnbkVONTdvSXRiN1VLYmZqRncKoFqjkrnQ8ZH8fFvaelfIR2EUjX4CZGpC
            LWJ77d1RDed7lE7ivo/AD45wf5pmiDhGRYaNZ9sLKu7niNCjOqMKWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T08:12:17Z"
    mac: ENC[AES256_GCM,data:z0vIFNeQ6rwaVwelzt7STdaITrf7lsHziATVDvNyW9OwH4te/kL0KQNC70bNnHeSUsGiX8YYNAE4Rd3iU9ua0F5H9sEovjwLG/0k4aa8LLG7dO4xj88lXUZLqg8t4lDfxP641H+b9WsDZaqcikg+jme65OakmUGivhB7gFxqssc=,iv:iphspO9ecFumn2ZJf8ZCUKbQVp5WV8L5ZqaS/LUCK7o=,tag:lORjR3r/l0B+ElBDGkKL2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
