apiVersion: v1
kind: Secret
metadata:
    name: s3-monitoring-credentials
    namespace: object-storage
type: Opaque
stringData:
    accessKey: ENC[AES256_GCM,data:hL3H1E0ZHBlQcDLQWkrTgry7tbU=,iv:kq792Xc0QCqDzfRcMlkaWALHGQpZaZmTiVsVhCGt+0A=,tag:CBzhPLIbIwUWrCW3mvfzmw==,type:str]
    secretKey: ENC[AES256_GCM,data:zvrc+GM/ogCsuoMpL5UX69zpIzROrHIW9ga9ekZyVfimVwkNorZynV3poh8YYzCL,iv:mtjRMs3T1zATczuJIxazutPykJxMsZAZv1WocgHNe2I=,tag:jQhD0/aIMU5sr8Slr4vk1Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBraVlZY1NuSndlWWY1UzlS
            aU9ROXFGRDgyRXRvWEMrWUhRMnNCNTZ5SUJ3CkhXZ0ZqZ0FUbkpoYnRtQU9JakZ3
            TFFIdUIvQWlWV1Q1NVBkWUc1dW0zd2sKLS0tIEVYQkxVV1pZTndpeXlKQXJUcnFs
            WFdSVlpxQ212MWpucUs2aDZEbjVTS00K+/clblM3MiMRKibrBhGG2qg+plWK+USt
            y9Dh+rcE0HCskKehP5qWENZ19CVEyIc/6hA+elA6pRhgvdaKilNGQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZEN1YWkweENkTzFwVmxt
            WFVkNWpOcXVxeWJTc2Y5R0dVQ1hMV1lqQVNFClBSNEROY05XVGNsUFF4OUZCS2E5
            YmlrNCs5bFpscytNWjZNN3kxMkxxbEUKLS0tIFFDMHhxUDJuMmx4Q3pHR2c4SHNz
            WHF6Rkc5cTdDMC91aVdreVd0ZHhSRFEK42umheJVkXa6Wim517IpyIGCnCaU4nfp
            1QpnABlfPq4MTBkpAwcEeGyaHvY+JLDxfegeuHKl1rzz89hXsmIqQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T13:02:33Z"
    mac: ENC[AES256_GCM,data:XCEmOmeLUKN5ZwmL5IoKOMbT6NlQxtpEgEDZ+9s0o167nYZ6ZlY4hXDppS/awD6gM4thyAcI4xAWK79KBbg8sMNtJWgH7lJB5i12LPA9cr3Ot5HV/JOsyHRxy1GHNuUA/UPZgjkIV0DPZ+258SqC/83P/7SIcGCtr2Ire+3XS7g=,iv:kJBU5J39+cBq3dsBJdZE0mbYg5FFC/HLIdVOWnN1lPM=,tag:6+cP9CKFbYuh5XqEgWzlog==,type:str]
    version: 3.13.1
