apiVersion: v1
kind: Secret
metadata:
    name: s3-root
    namespace: object-storage
type: Opaque
stringData:
    rootUser: ENC[AES256_GCM,data:a+8aDY51,iv:sSkBfe0ryf+KzZzp+kw5hNdFd2p91oRJIqMR9OvKF6U=,tag:eKA9qRuM2z0hrdcA/Ho61A==,type:str]
    rootPassword: ENC[AES256_GCM,data:k0lekxscGFfS6PvDpwOmLvTgAU7zSH6b2IpUwozNzA5x3uWlEvnsSP04H3MEu0ph,iv:3JTWgUaEN6ew+NVanvyIQVUoEEOyxcR6nmqcVwg+K+M=,tag:8RM+YPAW951FS+Q1viJpKg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKL2JuMVpVT2NZYW5qem85
            VVRtYXNjUXY1cTF2RDQyQS9rRzJvclRxZFNBCnJwL1d3YW45cnRyakFjenBpSjlj
            cSs3eUdwT1orNnJkVVh3OEJ5ck8vOEUKLS0tIDNlbDIxajVWYnpaTVdkcGlyZ2hO
            YXRkc0tGOWlESktRcXpVbFg5TTVpancKWeKiBSdTeZQnZNoGzQ7yj0QEG87Qacoz
            melL5Rstdy6J50IelushWv/GXo8Wst1Kmbpkt+2adbb875sjnReXxw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2emxwNGFoVG1wYVdxTjZE
            ZkRMYVJvNkhyWVY3V2hWdjFVdFhGQ05ReGlVCmlwcEhGZlUwUUhrc0V3Yk5PYWRD
            VlRSV3dXc3NFU0xZT3N4TTh3c0ZPNDQKLS0tIFRlbzhWcDVTNjljeC9DMDNtbUpG
            cEFQcVpzU3A2NDhrOWNQdGNBVE1wZ2sKz13KEp7vxheLsrEf4b5cLKwwWcLt1Q0p
            vgttmNZmBFWI8+wn1JeR2kDY8+5BvegCygeHYovElPKrdhSblt3h+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T13:02:33Z"
    mac: ENC[AES256_GCM,data:naG3SHsuylDOjWaGv4+0XGz9ouqu4TCeUJjjr+kEGESz9S4gyM3PlzPG4YDFj4jRiD+4lmEiq+eqAMBnc+0WnLeuZj6bN9+xIsrJEWC/4xjB2sr6mYmlXOQAONR85hietiLcH8rKeLVvzY94x8oqV3gcO1u9FenDwRVsiGrEG00=,iv:A6WnBfrE0Rfh7fn7Hs/52LccHMRGspBPjHVEHU6+Vaw=,tag:JA5XzXJ6R0poyhFsgBnGfA==,type:str]
    version: 3.13.1
