apiVersion: v1
kind: Secret
metadata:
    name: valhalla-osmand-token
    namespace: navigation
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:n2AaX7z6mmwtenbhkYIL2L8Z4RpBhQYNFzJGd7hYTe09tVVmsdl7cs1loEpBk4VPZQOY+1djeholPo2jPTMe1A==,iv:b1J6hTzCiYZiCgV4uY3vsUpxXv9JgTpUwxTWBgs9BZQ=,tag:Cn5bfUfDozqVAuVTuztwsA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVGVFZVpBM3ZoZlFGcFli
            TXhKYmFTdXJKL2Zad29OVDFMai9NY1V3aHhnClN0cDNlLzVkL29tbnIrUy9hdG5r
            ZnRvLzIwdlR4d0hENXNZVm12NFVpZlkKLS0tIFVrUlBtNXNZVXdPcHlKTi9WRGNn
            aU1JQTU0UkVpN0Roemt6WlI4NlpnUXcKEsJJNp1lkmbU7+xDel6iTP9HcnX+gYT3
            38qlanN96+RsOiTBgC/nZQgXmTTQ/KpMn/wUQwE3hGeQiWP4CY4nsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFR3NOSEtETmpkOG5TNkNz
            OUF5S2FqeXpLcmk3RnRMckVPL25SbXZ2b0YwCmI3ZXZFdmcvSVhWMzVkNjBkZDg0
            V0RkcHV5eFRBcTY3dWlQanBmWHJLdEEKLS0tIG5mK3lLMTJrVnZVUjdLOC9yQjJ6
            eWdOVGRsdE5FTm5IY0l5VkRWd0FNUncKizBFN4x9xSPa9fUikPpp1Cy2Dp88BR//
            AH0+PdUITb57j+KnWWmnSeed/rs2S04mKyBtKu+2NUORsQnE1Of79A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T12:39:40Z"
    mac: ENC[AES256_GCM,data:PCjB2h/YwmAIqC1d/I+tPFpr/ENRkDJw/0MiKz4+q53NhKRUaMaJ1taHbEYMA1RJguRa+kWFA2jQ3kZF4z0bJnBVmC0mXJ4fKSr+3xnZ9RFvmOhC6npiXWfHoKqOQCOlw0644fpE7qWJW+T4bXXBaT38FeUjk82bnRr3VdkVfXo=,iv:Sdqu7JIdMQz27dZ99Zu7YW/zUgfQardIdFtUDIOqpRc=,tag:YmO6ZUkz0wE4/EXg9R3mVQ==,type:str]
    version: 3.13.1
