apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  - concurrent-rebuild-limit.yaml
  - storage-overprovisioning.yaml
  - storage-minimal-available.yaml
  - node-srv2.yaml
  - node-srv8.yaml
