apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: srv2
  namespace: longhorn-system
spec:
  disks:
    longhorn-ssd-1tb-a:
      path: /var/lib/longhorn-disk1
      allowScheduling: true
      evictionRequested: false
      storageReserved: ${longhorn_ssd_storage_reserved_bytes:=0}
      tags:
        - ssd
    longhorn-ssd-1tb-b:
      path: /var/lib/longhorn-disk2
      allowScheduling: true
      evictionRequested: false
      storageReserved: ${longhorn_ssd_storage_reserved_bytes:=0}
      tags:
        - ssd
