apiVersion: v1
kind: ConfigMap
metadata:
  name: base-config
  namespace: flux-system
data:
  # Default intervals for Flux resources
  flux_gitrepo_interval: "10m0s"
  flux_kustomization_default_interval: "1h0m0s"
  flux_kustomization_default_retry_interval: "10m0s"
  flux_kustomization_default_timeout: "5m0s"
