apiVersion: ENC[AES256_GCM,data:d9A=,iv:YB/UejVaV3XCu3d0U11vHGEn4PY6BOSFuRbbNZvCnHg=,tag:5w6/ibL16le+9heqCXf1qQ==,type:str]
kind: ENC[AES256_GCM,data:k+mcFT01,iv:EmZRSYkZCqw6BX8rKtU61BYSgOjB9MU/EFleXjqEb3k=,tag:Soi6QRhTEEz26bQnz+WBIA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:M6Kd1BkC,iv:iNVmNDWI6XublS9vVyvfBpdh7+aodjvTFPnB+a3WjjI=,tag:vab6IpxlpzC+ARLPJy3T7w==,type:str]
    namespace: ENC[AES256_GCM,data:ehdf4kq4,iv:a+JRFTV8wrJy7mI4nTsewTi+yJPFk5HKCHaaFZWI61A=,tag:VMfRS+Oo7mv2/qEkgZzaJA==,type:str]
type: ENC[AES256_GCM,data:rm6KeuPq,iv:5DitSRj5ubS/GD3GFCb40oApgjnVQXYinFJGIveR1hk=,tag:3H6/gdxS2uMrOgrcfF4yKw==,type:str]
stringData:
    app_key: ENC[AES256_GCM,data:s+MnixbT52PLPSwn5zbhwkRCICpQQ8TyA/NzvUlr0tQ=,iv:JCNMv/eOylbKiGNEoaq9jqHbsAW37lgvQcN4CvXzYQk=,tag:IQIa1Wlr1EYLhO1HAYUqgw==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSkhzQ1V1MkNyenNZY1FM
            aENsVFA4YklIUURtNTZaLzdDME9KUGlqemtNCjRzbnhuY2t0cnc1WjE0ZENuTVdX
            cDBWZ09TcXFKelZLcEU1bXMrRjhqRW8KLS0tIDhhbXBEeUNkSDBLZldpamtvUGJB
            eEVIakJicXdMeEhubDU4WUVoZ3laZWcKwoaRFH6D+4qUHzkJQSvz/6pFsTV4hkbh
            iepB4LOYFqWdGmXeAnVODmzZy1pCrK7uQslYgCPTvnSb7smN1OSmfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T11:10:43Z"
    mac: ENC[AES256_GCM,data:7zA4r8dNFsB+dwVPxKkR7Plf7k7cVHIwArnRqhPiayRXntrMiUqHafzSwUVLVdQUQNfIG2DEY9n/h++2FxOnhd8BbdOm9ZDdcshLNr4PFRjCqxOe9yD21kQiXmc+Yfl71EKTeUeTDL1sCC36g4HYrsXPfdVjqRHMHGV/xxNgAyI=,iv:RTL1U3stJWYcDrE5hCOfjgo9CXRMCYUvE95ghIhwifM=,tag:n5NbvkzIYRD6/gxd3Nlyag==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
