apiVersion: v1
kind: Secret
metadata:
    name: arr-api-keys
    namespace: media
type: Opaque
stringData:
    radarr_api_key: ENC[AES256_GCM,data:pkVVzLvnbHcrgdHiE9Cu24boHExoRUQKhvpDM4tq1gY=,iv:vL791DUKWN9JZ7svkfgbYzolvTfhXIaUX/yhhs3WaW0=,tag:mBJFNx/HI6r2UGgTG4As3A==,type:str]
    sonarr_api_key: ENC[AES256_GCM,data:JwlvUgvCOGKUwN4cfOtbqShvzFJcZooeylNO/lzEkQ8=,iv:HyVkVijTkxoo+LmK1wsoXO7oGfb313ADuPzc7zhKTEM=,tag:r19mBG/+6RiQ2De7rzWLTQ==,type:str]
    lidarr_api_key: ENC[AES256_GCM,data:92gS50lHVGpZBL7vc8PKohfIpXNSJSa+3e78onjm+v0=,iv:WLffCxpJv4e3rHTiJDDXjUSJaEODzyG7jxKsVjj4wp0=,tag:6OQQmHy00Ve4xNvO0QCvfw==,type:str]
    readarr_api_key: ENC[AES256_GCM,data:7mNxJ2bnSHyXwimlJJMTcRKhRhOJ2P0MZ8C4C2CIJg8=,iv:btX9ZYP3eGn/Cy2uHkKS9hESkKTAD8I0n9W6AoVxYog=,tag:uI58AdnyI+SvggE4rqS2Gw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFby9xbWJjZVdVZEE0TTE4
            YXVodmZPWVZxRnBxWlpPS1Z5ZkJPTCtZZjJjClk4SzhZZlVRNVBJODY3SEQxdkhY
            MTFZNFJQdmE5OVd6cWQxWGxqM2szQXcKLS0tIERYU0R1THo3cFVMN0JNSm9tbkpw
            alpnTGdDVnE3bmlzNXBmajdwbmpqQm8KHJHnLLsJJ2vh4D780iuhv5uvpAQQ2Znu
            L1fg67/LR+T/sACpEucDt4gtEGJSbQAuYYOYx3MRDSl+YnAVT6Ye/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMmg4dHVFTFVjTG1tS0hR
            Mjg1Nk53ejJCNzdlMVU3WGVnRnZlNW1VbW04Ckt0bjV4bGxaZTdrQWhpVllzcnc1
            WUk2QldHck9iNlVkRHQ2L0hIREJ1ODAKLS0tICs2V3FYcjNIVUlJYmJOTE1qRFpG
            SUdaK012VHFnTUlnQm5oT25LMlgzTXcKwOMlakDHuUO87ALHCd3pM14cWNCjX46o
            r/4Ko1XamF3uwpIWN+dNMR7cnsKUsEWggPOwWvmptwWfiPeujpsalw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T15:44:03Z"
    mac: ENC[AES256_GCM,data:xsm9wxpM/8ydTcIoam2eO9avts1F4dfh7k2mEFEOQv66ddlwdlRIaJb2UfuKtQTqbZEkQC7m+i7U+6l6v1KzOLBeYQoc4jY3v7pFwjM78K8fv4o4HYvxNlXtJsgajiiFjx/dE+cal41CQv6XHM1to7bSZTOjyZFojXLZrnnAsb0=,iv:oNnmm+rEG6UuqLyfvNHqk15JRViQeBzgew6zy+rXOAg=,tag:Wv/TcZhlJnIiITNv8FrSVw==,type:str]
    version: 3.13.1
