apiVersion: ENC[AES256_GCM,data:A1I=,iv:45zZcn220CUmJbJPJ75w47H/Fg8yPGopUzCGDaKJVA8=,tag:EufVaP4gN5tcKcFRiV8v5g==,type:str]
kind: ENC[AES256_GCM,data:Pg5NrKfD,iv:sZpaKgPMIj+0YsYYJCcn108AOu8loKxrQzLd9iCeCxs=,tag:o8xiukCOZmmztCvJFIG/Ag==,type:str]
metadata:
    name: ENC[AES256_GCM,data:HVai7fYRvxOdjlww,iv:F8tgMERTsM4ZcQTH0iWFNdnflFTF0wFofPIYoMIkxAc=,tag:r+5aET5SP+9giZ1zTb2STA==,type:str]
    namespace: ENC[AES256_GCM,data:CJo9BCA=,iv:YMwS2MQehOOE064KwdigitlVIM2efclVk4FF00BX2AE=,tag:hVb3eu4j5miPr+3a6j0+BA==,type:str]
type: ENC[AES256_GCM,data:5zg1YRtU,iv:CfW7mPf+BSf9UKEE5D3f5CUnUdqXof1Sx1OR/4pvQTk=,tag:iMqtX3jQbQ0/+JGIHm48MA==,type:str]
stringData:
    sonarr_api_key: ENC[AES256_GCM,data:+ogDzAkAl/xGVytAVyOn6xD5zE2dKfKHKymyhsXkK0Q=,iv:X0ICCEigCsIXk1F2Uq3SThuqlFPgVMBzv10fbPakt44=,tag:KsAp3rZmVEz1WHcihqgG0g==,type:str]
    radarr_api_key: ENC[AES256_GCM,data:oiN2dEGItsWev9wJAt8C+Jp5VlixtotueuFBdJkAuiU=,iv:p6EcXIvtySokNfRwurrO1u2nJE9GHOeX5mf0Fj58yzQ=,tag:L5zAcnh2A8X1zGv665ct/w==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMm4yVHhRUUR6WkRYZTF4
            V0hEREMxYSsyWm9YL3NhTFl1V0xnSHk5dDNnCnMzRzU4NXRmUFh1UVp6SHAzcHRZ
            NkpueXVsN0RkTzlzV01JVTExTGhyczQKLS0tIE10cG5zdndTSWZxQm5mSHlQUENO
            bGwzcEdUTnZmaDU0UnhhUVc3dmhJU2sK6q6dFChO9nyF2eCwZhkYhufzpr3GTB8Q
            TL0UV0L2zjagT1e/4vseUlq+jE24uQxGrGika3Gi0mPeR/WgIqaolg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WkY1aWlQRmRXYkFyOWE0
            RXhBbjFVQkJsc21reE45dU9XbnlqZm15WUR3ClpHYW03Tzc1b2RHS29WTnJyayt6
            aDl3bGU1OUl3T09WMUpBNlp3c0lscmcKLS0tIFpjWVBPODY0MFBmVUlQalVaNlBB
            TFA3NjhGQVdmSVVsYzFSQ05KTjkySEkKwqA/2l727MPxhwu8c4m5YOI06WqBfaSe
            nOprdKB2tqow1hJMU8sHlqEj/lcQ/B6VlC1Dr1V5o1+EOdF58qhwMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T15:13:03Z"
    mac: ENC[AES256_GCM,data:+1VeZhxBOVYCD7nm80aZeCX5nwSNYQcWzrCQThjyIJZDK6aYamKRVXcZqIfcFbX2ZNsJuvCAJxPUeL3yDQQ0ly6Z/mxxrh8ZBTCM61aNgz8LG5wZFXPjSaIUEAI7wKBg0cV8oH6QWei8gtsjQaDNGzFscdn9CaXzI6oXqtX+DEY=,iv:UDbtvfMW1PJ8bGrtyJP2iQMkx0Izvvjzda/phcS2hLk=,tag:IFd6nD0G4+jHfUeMi22knw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
