apiVersion: ENC[AES256_GCM,data:Yv0=,iv:gRUzpeDmERNCQubQJubUN6Rrvjw2ZKvi/lknhejbQk4=,tag:KkJ/RctS2ZiNTzn98jbvSw==,type:str]
kind: ENC[AES256_GCM,data:yxQCn/6z,iv:XW8I/gajHBrpvbVO9k2y6n2SLMZRMS2MmtCWhO78LB8=,tag:nTrR8YAhGVNVDo7k3aTvvA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KKboIzjuHZE7e1RN,iv:jbq4O0TsCeqknCCY7TQ/uPQlr0e8S/0RhqbhuqhvJNY=,tag:biOegeGJgihJf4RLbabiOA==,type:str]
    namespace: ENC[AES256_GCM,data:/iGvybo=,iv:W0f3CMIiMvdzyszK8Z9yhVL1WIBuqlUzsLZc0uQVWCc=,tag:USuifZx/VwcV9m2Cdu1hDQ==,type:str]
type: ENC[AES256_GCM,data:6cO9fzkh,iv:6hy0UoccyApbKvLpvCzX0WFbuSq0mVdV0ffe40isBlw=,tag:DzPe3DIBzU229iUuH1W7Kw==,type:str]
stringData:
    sonarr_api_key: ENC[AES256_GCM,data:3badxuZZG8hPx0jcsMsJCbjdHGTYIkqdyzt2VB4KMqQ=,iv:6PDc3DHaQ3FnUYcpIXTX1Z6zEquVHQ16cOMtt/cy3V4=,tag:imojnJtRHzWtuvBqfpopew==,type:str]
    radarr_api_key: ENC[AES256_GCM,data:m01H0gBUpDjQhUsVHU3CVe+zuERsTJEFukw5Wk1l/K8=,iv:tz8sHeT8zuBE70rM9EtER+iniCh7H8v8zXpWQBd62u8=,tag:LoFlz361celCLa0LpWY+6g==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcUJYRGFJNk9lbTI1ZkFk
            TGhhZVVIcW85bVJocjIwci9UQVpGaCs2VkhFCkZzNUVQL0c1L2VMV1YvQXlJRk1p
            MFU0bmxoVFJSbjdSbXVoR3hHMkwwd2MKLS0tIHBLckN1YlFFTnROWUlHKzlrNTd2
            MldNUkdPQUJuZi9pS1NxR04xUGYwNDAK3h+qmGzkk8hav6zMbieBjC1T95/sEOkN
            DeT+x/zjwc3O3z5OxWrdl1/XX3XSzogqkkGGmfxrmNG2w8Q2IOI56g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T14:37:20Z"
    mac: ENC[AES256_GCM,data:i6ZyG7AdWcyuR3dgUPpDiiM85lXRruEuS2OamwmUSeYxNib+c+Eh/+HbRSpVdB61HnuwGAdhjDqpzXgXvWY64JcVTC+c5zL3yMXqX3wUklW4znoPX1TPiNPgAPh+Y3plF2KMRDzKRo79pnEApzP+XlUYrl7YOIGFFAkeP/zu96k=,iv:WpcDtcuaeahwnWWJ9OeRWTTAQkebd5qUGRN1aCCFwlo=,tag:QHGWjbYClDR5+aisy7Bl0Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
