apiVersion: v1
kind: Secret
metadata:
    name: attic-postgres-backup-credentials
    namespace: nix-cache
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:wQrUqYCv86StM3bfYP/mTpGDW0k=,iv:/HUCYj46CZEF+l9lThKUMs44VFfHws9PfORbF0GtNf4=,tag:7Ak5HycDwmMZUouTpH0OpQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:e2fkMiZobJvfboYYblVz1bcwAOkUCG+rrZOFZE0zvXD5Oce+4o+l9w==,iv:QA4fSN3QxY4f38AOhxiuuoQtlnMEplSpovevp/fThng=,tag:1BoCWrJeUZxaz7gLqsWODQ==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:txyWXrTMgGihfmpwezITdlUikm24x+Ci7FY=,iv:YokjBLWaMzpLHe257GQTjav7Bbt5fSdqAR3foj+tToM=,tag:g0VzlTFwsdAa74QoCMD/Sg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1STg4T1plaGRONmZBZ0h6
            azhLT1g5a3h2c3U4MDJjQnRNSzdMMVdoVFJ3CmVqYzFmeG1wb0tBWjRSUFZCbXFF
            SUxWNWxzV0xtZjNzS0NhMXF5UmFBUzgKLS0tIHpaREhZYUNTSEJGRlBWSHY0TmM1
            OWVmNTI5Qll2bkVqN2ZWU3BsUk5neXcK5sDXca8fdCMtoCxICdTbjmaHvpJ4zt8r
            KDJWDRcBkar8uH39ObUZqGl7FzgmXH+OIwAU/Z/LsAOB4YfPySG69w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNk5zMFF2ejlZeHRjeFgy
            Myt1TmY2REJuL3V5M0dFRHU5M2RVTGd4bTFVCnd2V1lTOG1Oa2crNmJVZnZwbnpw
            Q3Z3b3NNUUV0azI3T2g0VGwxNUxWTFEKLS0tIHlFUHh1ZDloUWpkLzk0RXBTVEU1
            ZXBEZTF3ai9aRkc0RW83QTlkbFp3UW8K4SHlcFC9HcMuizY+XJhNPbBuYIO18p58
            0BOhn/GxnSZzKDQ2RtmcvDhyAhgV977urE3gCO+Y54pY9c0JgdGg9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T11:30:49Z"
    mac: ENC[AES256_GCM,data:6QjNGDUJRSwUfgcalYggIUMlO5FpeLe8j/q5sQ3ZZY2/NT2riBKSVPTj64xlOrBhb8r3z6YYrzycYyQTQNMGYxegxh56PxX6b34xVyUYXLHO2znx+0PGfrpZ0eB9gfvUeFXXKOXLBrbXLfKceswJ/6HhWrxtFIcPdjaMtM8UWKM=,iv:V9rKsvooow88prYILeHxJRnvMjoPHgm3KV5/4R8uP/Y=,tag:hJ3PEvAPuTsP2NX8364+PQ==,type:str]
    version: 3.13.1
