apiVersion: v1
kind: Secret
metadata:
    name: authelia-users
    namespace: authelia
type: Opaque
stringData:
    users_database.yml: ENC[AES256_GCM,data:8DBh37VsdMAmi2UDkifVcrtKbkbNF6xUwUHqlLi8kJU7EMLu4HU9L/1Wy8bgl8+G9xdlD7XUTLl4hgzOM6GJaGtkGKcnPLPzwPEvL9X0gAAoIE3y7yBDnbbDpmEp5cB8XO5+n1sLwfyaH123V05EBkNu1Lg5VZN7ohLDy7RllLHFT/iCy/T42vMVowdLcCcP37Zq7Eiau5D9V/bYsa84XEJO82D7SvVTNFxon68Y7OdmIGVU69LfdMSBxj8nTVvF9+bFk8m/LatZMehIVnGIAFQVlokdGGEkbQV41EZZF1iaea6PBeZKIQ/oXjz8FPws/12buVmcdVHTxPbC3NebGQSmj9oZpGiDTTWmvQuWniPB8Usnmt1dkkrvLUccWq6D7kRB3JRv4UpXHUymhdB5dG3Tfn/6D+SXDpmrczJf7WMq/iJ1Zg7oyiCnJcmc4dCJQiFm9WagTpxQ/WPOgU5ONGJAhp20D5ztEWosrLF2ei1b6oGes2FPtnLcw4bTq6rvkljudJe3kNDITTufKyozAKvRIDgSmn9TwEz1Hs3lOW32Mw==,iv:Y5j2W28dK95Zg5TQnqDafsJnT9EMbLJVdpPWLFd4JLY=,tag:55H43eJBK2hOkNSqTKn8UQ==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMmZ0aVhTanRKcXcyTlZy
            bGhEL2syZ1pyT0VRSG0yNXRuQ2hRWkViV1E4CmM1aFdoYWJxeTRDV1VDMUhKU2Zp
            YnBkYlJueDR4NkJ6azBCK2J1akQxbWcKLS0tIEpzcGhpVW1sY25uYzBxQXBTY0Ny
            aHUwZGZJQUZPeWhnTzNDUXZ2alYvMm8KDH7BLiK11jBo2ucsuPEagVW1R0ZvSWJB
            vwFbCqZ8l3GAzfcOf8M3bl7hW4yY1nXkQ9voh7ObLarMkYycpjAlsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T13:11:53Z"
    mac: ENC[AES256_GCM,data:kB7PKThq888ueuUf23xlAHZdppDuFAE+QMixlHOyoNb1gU2CSutFVZsEkQdNsSZzyaOlCqj73/xQIgU7GXAApQ8V6ABttJIxem9cPon/JgnmBLhUkzT+c1DFndAmg9tZtpo8KT37Bf0vdm0bZnKHuC61cmhc0Mgt9Uuge/Gyn/Q=,iv:MjziaYglJ7joQV1zn6oebX+7RBf/aziPdMDiQZCtQBo=,tag:sYZy5qANB6ZFPgliXcnjig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
