apiVersion: v1
kind: Secret
metadata:
    name: authelia-mail-credentials
    namespace: authelia
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:Bv7EuitXjR+FIOiV+utWMUffmF43WEfhSg==,iv:NheXXsy+vjl+BjOQFHb9eqfOBQ5m+p8Wu155tYXrR44=,tag:Z6+tw37AW0SdBROl/1OjCg==,type:str]
    password: ENC[AES256_GCM,data:AWLDxpC9DDx2oZzMnExZ6A==,iv:fhjOEN9WYTmG28VGt6aHLpFh5Vc5qXrCxq0t6BgwRi0=,tag:q8X2ELf/38P4TIWkZbyrbQ==,type:str]
    sender: ENC[AES256_GCM,data:vnUXPcvC0Oj9ceFvwKM=,iv:kqTVlGMDpqLF4bouLXzobekn3b1vlTWb06Dydk5Os2s=,tag:9wK4jUkG86EwUPAUsEDZOg==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUGRjMkxQRVA4ZHUrTzNH
            VmNXeHUwTjRLOXRmQkFMb1JxQmhMQ1E2OWd3CjVzNzc2dllsekI0KzMzSUpqOGlp
            WXFpTW84TUVVY0xmOFFSdCt6Mm9jS1EKLS0tIDNNc3MzcjIvNW1BL0NxOVU2SHFI
            OXZPZlA3SVl1c3lWK2tFNWV2Z3VYY0kKsvAuXNZT1fVo9+JD40u52z40302BtPrC
            YmyA9Qyid9gB/Z62SxTQm1gFGHicMe04blSAsu28AHeaAH0lYwHxKg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtc1V6NzVBTDljazRNdzFs
            UGFBQldTV0EzVXcvUEs3cTJBVlhNWXk3M2dzCkpqdFkxMXZBdkdSTzRsenE3M1RJ
            TUUwWkFhdWpnWmF0c1ZMbmhRRWNGWDAKLS0tIExnSzBsUWFwd0R4eFJ4KzFMV2Zy
            c3VNalB5d0djeTV0NjBWNytQd2dCREUKUV+bPzVvXFswjSix0zER30RbDX+ZnqDC
            DPhj0dgEVExE/kSPa6s0ymEqsXD11GYhsIVVe6WIhMdSvD2NIuHk5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T13:41:04Z"
    mac: ENC[AES256_GCM,data:wUFfcFB6NI/Qp+Up6KclOUbvg+gaBB+Pk+fs69cizPBiRY0duym5WYPoh6YICysAyz7zBTZUsjDUAhZ3gG74UrBzCaGhh++KOVPUodkO8/AUkFgQwGBMqOxJLn4Pu56P8283rXO+pwDr0MKUnCA7LZU709ogjy7g60glm7okmBk=,iv:KE0KjlRpBZO34Yd++ZADSHe0v4kpA6YOAy9K4zLoXnQ=,tag:X2ICD5QwhDUy6hDVAMwv8A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
