apiVersion: v1
kind: Secret
metadata:
    name: authelia-secrets
    namespace: authelia
type: Opaque
stringData:
    identity_validation.reset_password.jwt.hmac.key: ENC[AES256_GCM,data:fuASPmEiiGwupHghjPkaJJ9k4wCDGEFp3UBv1kvzNj7nhkiqR+ygCJufwNNXZQBQ5WkAKlRIxxivIxQt2PfP2g==,iv:31pBQxfvshfzzL+vX1g8T5LNer+Pk/zphDKLJj38kA4=,tag:wdR6s+kSV+qfJlLLa1GHTg==,type:str]
    session.encryption.key: ENC[AES256_GCM,data:oQCVAiaHkxGBDBC8dgf4LitUv7C9gaS4Ait8hq+8YYULYnNIPIQrpfN/1fkZd0Z1fQjrIbIVM2KDol1Zr2w/2A==,iv:6qvSKByZ6a4liKo5TFCNorHk6/2KXkQW0kB0NL5eb2c=,tag:aUnp/07anl0DurJnw/TKMQ==,type:str]
    storage.encryption.key: ENC[AES256_GCM,data:eifgcdakzBQdkigB7e04vWf+sBDPSIBfFb2kIkFaK0yEvcQJA33t64jVolAWd7hm4ORC3ia8fTHL4TfHto9I/A==,iv:0H9309WekV0/IfoT17VgPPmBRWHixigBs4ClAw5d0Aw=,tag:PjSjD57lFPxTD40fMLQIww==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUDdiMTQ0Zm9iWHgzcHBC
            bURiZzk1R3FEdUU2WldwVEN5WHNBMTFTVWowCkhDU2hzN2JsLzIvbWNXbUl1UUFF
            ZThjV0M4OVA4dExnRWFTcmVuNzVQMFUKLS0tIHdFeXJPbEVXajhyWld4ZFJ2NzFF
            MDlxSU96NFExN0srOW96ZFhNVnZIWXcKCPNuK7YN1LvuWzJWpfl5sw5waqL35ff4
            qC7oMhs2v383QWwhqW1l39Pc9YsZCzKvUMEq+Ds1QZS5P8uLXrSvsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T04:31:32Z"
    mac: ENC[AES256_GCM,data:ctx5eiF4nJJam3sFZhvFReGZFOk2gOpTM2t/RJPNCsZOBXCgsWC85JsOXfXLQxUywlyIO+00DBfcxocpdvhi6IJE7GmgfZB5EmmsK36EeUsBq9hUsXu9MyKt+VtLuyi7AJehaZmHuxZm41hXxR9PkReeWkvwkcxiifxeghwG7cs=,iv:G2qGAvdqABloBziWYgakMV9tAvRaO7kvRr6/DAMU1B0=,tag:hem4Ms214ufb4v1VSUZvyg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
