apiVersion: v1
kind: Secret
metadata:
    name: authelia-postgres-backup-credentials
    namespace: authelia
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:+nomfwMFEWkl5mAv5PxIE7mfBCY=,iv:0TmWk5gDCR36kug6vkA9v9xsP1sL7PTrNdwmOM0sDG4=,tag:24AFs5BmnDlEhdA7oMP1FA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:0Nye5NsYofqG4NMJRhDsKQ1FvoCgy8O7nV7NZGylB3KgXREVOrd+VA==,iv:CULm7zZdKTjfwgmxXOqKGzu3t6CM+EEX0XHXKeT7vqo=,tag:TaPc5F4Yn+a0V6JiSrSfbA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:CrAiZ6jKg6Oyis4acasKg9gyQZ80JTMydc8=,iv:DjbbzpSqh4f4WHe36kTeRbFgZqBXArvy68eynqVc9Hg=,tag:Z+8/Lh6mhKTiTSDvFMDvcQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBY1NnazY1UldTM1A2elMx
            bXhoRE1ZY2ZYTEZGcGJlRndMTnBIQ2d5RWp3CmprcmZOb3pxRXN5SUkzenZaUzkw
            bEMxUWRzNTFIdEd1VGdsYWZjSllZZG8KLS0tIElETnFSWjFVOXM1M1dFdWRmbjZj
            OGt5Q2JSQU1UUzMxVGhxRUFieWxUVTQKPbPwJFiImfRtSxmfg8rrWKPiCzWFNzAF
            3VZE2k9URS4ONuTI9PovMZw8Ou6k1dArenfB0jaEXApHStqWoglBzw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQlNmWHRTa3JneTlkZThF
            MVJQaHJsRTlCRkMwbXFLTnYxdXY2RVRaSkhNCmVoVnJHcnZSSU1TYmNzOWY4WHV1
            aHZtc0NzbWkxL1d5cEZteU5YUm94aDgKLS0tIFNpcnJaWUpQMFI1eW5sa2F3RlU1
            eG54ZFNGZDRNRyt4Q1phN0xpK0dVN1EKIhlcGmds6baNw7cEaRpBS2YXO3T1jGcM
            iyzYgVoYGG9IA9YkPd/S1SOC2lppAnT/Unx4VXpA/KTQEoPzj9WKPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T08:39:14Z"
    mac: ENC[AES256_GCM,data:VO/VoA2iJFGhd+YdXwp58hzD1Nmf3nvmRqJWGKvLp7/7nkZBKHs8htZUVb3zFz0/NJD9IijKljjPtxJ3sdVVVpo5nDcN/edV7+DWwI6tLDzlkF2SEdudsS4w2m6EZEppbT1IeL3LbSmshpyKtu8N/MUifck/WDWYJjxLA9LG2iY=,iv:0KcsydQWluPjth9Xic68nsENgcRUdydPROxKZXQrNVg=,tag:p4u5ombsxkYjNU4mmyt5Lg==,type:str]
    version: 3.13.2
