apiVersion: v1
kind: Secret
metadata:
    name: authelia-oidc-matrix
    namespace: authelia
type: Opaque
stringData:
    client_secret_digest: ENC[AES256_GCM,data:Va6ToRTOHQkJ3S64zagr93DGnE7GOTeZEVrSdI5wfGJPAV1bIivALvNNXqFCgnQSDRtV1I1Zy/o9bzhkVYYSaeXkcF0069dSJrcNGZnsFr8gnVAntEeZRny2CzNjpWFbFQ==,iv:SopkiNahx3ArvN1je0WbUr38tZdgvKfLNPgNYEZSCFc=,tag:H5OOkX7zgunEw7tKPCnwzg==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwY0M4Y0UxZnZNYWRVT0NO
            Q0V1enF1c2JkK2VQOHBkbkc1S1ZCYktKN1hRCmNyYjRwM1JHRUo3d1E4Tkc4SXBO
            TDBiNkNvVm5kMDlpdEVyb3hFUXRBV1kKLS0tIEllRnJ2QlNMTnE5Lzl5SWlkTGg0
            czdSSjFubElmY0hPRnNPUGlWY0R3Sm8KZQeWwHwbdY6MGvKm/vg0/bwnzPvWD5od
            EUJn8FrodwlqiUXFom5orzz5zAo5fei7pzTIIf+LE/7LcHN347evoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T08:36:36Z"
    mac: ENC[AES256_GCM,data:83C5siyafGZdkFt1cN41wYvUStSTKw9LmUtljCR84pnbBIBLyhqno6eZwVm54uwApl2yGvokn8+E1PkZVHgnY4U8ewWPUntGnBZ0keUzn4uoYjNNLzV2gbsyKdQxWKT4DbpdOQXopJfpV2UCJuv65grNU0DMts4xDOwi73gdCCo=,iv:SxwG3ytZyYJR3NFUivpx4qYbhyVFd9TrIy04aILF7AY=,tag:JljSPaDQs0AHObC9jsEd9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
