apiVersion: v1
kind: Secret
metadata:
    name: authelia-secrets
    namespace: authelia
type: Opaque
stringData:
    jwt_secret: ENC[AES256_GCM,data:JKe3c1pJuYidlm7evDQvsu8LGarBVYifFBja8HN8bPhAKPQWYRUuPlpxK/xifqZ7+xRcyrdwW2naGsyjkzAzZA==,iv:jbwyHX+8/VvX3JctuRxkvDvuP/ZtQ66i/ShPGgBG31o=,tag:rfhALGU5qicBqlA86guQaQ==,type:str]
    session_secret: ENC[AES256_GCM,data:nU5fjToFSsT5pPYQ4K0o5/L35vYgl7upOIiOnvZx7kZbW+6JSMguhe29Dd+qCvl6Ah1lst6ExtbCmyG0grQxMw==,iv:+fXw4FqYcI4yY8eUxagKEv3dtoRmB/Z0MGNoJ8F0P2E=,tag:l8g7Rr+TlUe7islrHFNiNQ==,type:str]
    storage_encryption_key: ENC[AES256_GCM,data:qvKwLeg6HpFtDswekkIp4rbsB43ncKLim/7qjl4onWOXuO32OcNZGDyW12k3sQge6gKVRLYRn87o1gD6391E3Q==,iv:YMRCpgdQZfIVfeLTiaxDdwPwJdJ8B7PGB8eVtXFAGuQ=,tag:8P0T37Bhnlx2Dvp0TuhgWQ==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYK0toSEhWRTZxNldUOWRl
            U0ZlM1ZqRFBPTEFzZmZKSHo0OEJ6NlZaWW5RClFoYlJSM0M0TElkMk5lejlURGow
            dWNkZjMxOVVlV2xNZUlwM1YvSjFiZ2cKLS0tIGNMdVFqTTlGUFNQaUZoVFNvMXlS
            cjdIMlFwcHo5T092QUFwSnZ3QkkvRE0K8O7S6pD41hioARW/V4cmvGV8UPuaI33M
            bLMFFSKF/REov4vQviGwhwwNqGplAnsU74R0n0tYDc7MA94KHVIg6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T11:17:07Z"
    mac: ENC[AES256_GCM,data:DttSwv5TWtVZchVYSOwaBJ8tHjxy2zlf3yoEfF3Py4eOosHoo0r0naKH67A5OasEUOkBdlIls0sa2YOotNop8niBekg79mIhEehQraVPGeOW8WEig20iw5L3Ckw3x5OE2Wvdl0KLl3G2qrvnSPdVwzLkAW6n1KrxUL1i3VK94sw=,iv:FyYESpqy22ZdcBf+7F5RIlG9KAL/0z9Pn9QCsqbN/vs=,tag:d6adElCIm57HlvpOWP0iuA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
