apiVersion: v1
kind: Secret
metadata:
    name: authelia-secrets
    namespace: authelia
type: Opaque
stringData:
    identity_validation.reset_password.jwt.hmac.key: ENC[AES256_GCM,data:fuASPmEiiGwupHghjPkaJJ9k4wCDGEFp3UBv1kvzNj7nhkiqR+ygCJufwNNXZQBQ5WkAKlRIxxivIxQt2PfP2g==,iv:31pBQxfvshfzzL+vX1g8T5LNer+Pk/zphDKLJj38kA4=,tag:wdR6s+kSV+qfJlLLa1GHTg==,type:str]
    session.encryption.key: ENC[AES256_GCM,data:oQCVAiaHkxGBDBC8dgf4LitUv7C9gaS4Ait8hq+8YYULYnNIPIQrpfN/1fkZd0Z1fQjrIbIVM2KDol1Zr2w/2A==,iv:6qvSKByZ6a4liKo5TFCNorHk6/2KXkQW0kB0NL5eb2c=,tag:aUnp/07anl0DurJnw/TKMQ==,type:str]
    storage.encryption.key: ENC[AES256_GCM,data:eifgcdakzBQdkigB7e04vWf+sBDPSIBfFb2kIkFaK0yEvcQJA33t64jVolAWd7hm4ORC3ia8fTHL4TfHto9I/A==,iv:0H9309WekV0/IfoT17VgPPmBRWHixigBs4ClAw5d0Aw=,tag:PjSjD57lFPxTD40fMLQIww==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQzVyMmRQOW5YNGthdnYw
            LzV2dGZJd21iYkRpZzN1NFBidXlKNlYwQXlzCm45Zi95Z1lBN29kWVRVYTNCcTR3
            QktNVDJ1MXJoRGtISEJyRk5USnhLTU0KLS0tIHhUaGk1NC9KYys0TXpEelVONVdD
            bGtpMlpQU1FOc1kvb28rb3piendMVXcK0LixYQ6jiDYKb1t454ahcSHbOQcSMb1h
            uUMJEuwpparp9HzIIFMyFpD5yJ7XFfGJehT0jxsX9pOw1dmhhxsxIA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArT0tTbHgyd2VQOFdNMFR1
            c1RsdmdqYVhoODVFMFQ2Z3R4OElaKzZQNVd3CkNjUGthbHV3RVQ2U2lSMUEvbEdX
            bzlEaXk5NVk5R0lNTGxTL0w4S2xUd28KLS0tIElkQy9IbjNjWHVESWR3bEIvc3VI
            SGFTUkY2RVdnVEFNeXJyUWZ3Rm5INGsKYK+bwvMn0A6hrcNRvrEnU9DweuDLSYl5
            pHE45kClDcsWYb7C48tzfSWEF3zmEvNyjgJYDcq2JiwnBWdN1mMPsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T15:26:00Z"
    mac: ENC[AES256_GCM,data:ejQCbHej1auWynqWFb/sU9iYKk0kkCA+3nF5Tljok7C2NT8UKmgUDatY7mOsbtsKUc7bL2oJ9JuKs8BdEqsApf1MGpYw75hypzkqaixZuOwarpsQ7oPyoDdqa0dJgTmwY1v+SL74rot7Vs6W4hP7keD3g9DxaPYqKfBtOcFcp+0=,iv:0NLmfQ4ySSlSo2YS1yI7e33tAb3oGxpbv/MUi69fHug=,tag:YCtQYLqIt03PBEpKbv9TOQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
