apiVersion: ENC[AES256_GCM,data:2P8=,iv:IC2SP6NBNUGny5LnhNwlfIyKnb4w1rr0su1BOrSzUtk=,tag:c4EtV7ZMSejPGH9d9TKeLw==,type:str]
kind: ENC[AES256_GCM,data:1tuhkHSM,iv:1DoJ/7llaeSVQfoFt7wTVqcfDFdm3sWXk50/sBaoVxI=,tag:APCks6UMGAiDtCXIGlHuOA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:FyKv62bG1Ud6TxyoZQ==,iv:2iLpUU3TwL/Dw3pW6HfkO5Hjr8UZDptgKKl/t3IuL+4=,tag:gM1iErFjqrcBsW3nd52xzg==,type:str]
    namespace: ENC[AES256_GCM,data:Iz2S3dUj6GI=,iv:dJJu9yNnGOqCjuPPvEbG3Q7OhANqXgaolTi3EIRCEjs=,tag:jEYWR/1ValXocAtqVjAOwg==,type:str]
stringData:
    password: ENC[AES256_GCM,data:FqjC/o30US3x5C9Du83POSiw23kxktrgFIZLR0A1ng==,iv:ZUu4y+sLUBRYRt3vHSd1Hqsf8U4zoukKtU2lywvv/Ug=,tag:UBMxQZ1O2SSCoS0FFqNJmQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYnkzbFpidllmY1lJVXRv
            TXdKd0FjTktIVFFBemZidktHT2ZSMzFGbmo0CmUyTnJKNFQ5WFpSc09hT2JRbUR4
            S2Jud0lXT1dQM28xVkZrdTRGWjVsNTgKLS0tIFVYbkZlTTZFMDZIZVJjdzFUeVBC
            Z3pVYXpoNWwxalZkUjF0YjIxV3VlMlUKvu0jeJNunBjlql6oGSsMphv6TnMzBKN+
            aMYmjUA55GJy+gAmSqNN8BINULv656sHuqfVVJhODVIQWnT/j3rhQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTXB0RmJuazliYXlrdmZo
            YldBZzMzZ25Lb1RGZnA4eDAram1lMm1Eang4CllUZGh0TkYxUHAzYWFTMlZMUEFi
            Q1A3SFZXRnIyeFJBbGphRm5xTGlGbVEKLS0tIGVDL01ZWjlOaHFGTmFRdDZOblZ6
            dk5sRE4wUDQxUGxNeXU5ZFR6WCtzSVEKq01ePWdp4y/7AmIX9vDeC614Z+JhIHHQ
            rhFbysnzQumsvgYi+KtORjBsXLYwPaOUOxaw5e8jJBRy7r0DdMLqSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
    lastmodified: "2026-09-11T12:24:20Z"
    mac: ENC[AES256_GCM,data:O5h6nSy/ZZYrSVvelo/SKdtktZJh7GvsqzKu8EoXpAkmX7N/q939idNbHgaPDQyG5eMyUjorCH6G+rl1tREsll/iN6QFhZjBPKrj1fWZPC+QRpo5eZ6novrqR77syxIg9qoX2dDRXoYvkSx0Hd5KKNdW/fCvjJHkV/LY2l2D/mk=,iv:Wv8NZ+WJRylSIW+RKtn0uGBjFwK/rTYiKbruWVbYfPI=,tag:nSJBqPB3pJeepkXOqDXL4g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
