apiVersion: v1
kind: Secret
metadata:
    name: authelia-oidc-matrix
    namespace: authelia
type: Opaque
stringData:
    client_secret_digest: ENC[AES256_GCM,data:Va6ToRTOHQkJ3S64zagr93DGnE7GOTeZEVrSdI5wfGJPAV1bIivALvNNXqFCgnQSDRtV1I1Zy/o9bzhkVYYSaeXkcF0069dSJrcNGZnsFr8gnVAntEeZRny2CzNjpWFbFQ==,iv:SopkiNahx3ArvN1je0WbUr38tZdgvKfLNPgNYEZSCFc=,tag:H5OOkX7zgunEw7tKPCnwzg==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTjJXRlNabklxNVVhaHJX
            a3kyNTB5S1gxeFRYZ0prVHlHdFJhNFR2MjEwCjhKcFlEd1ZvUy9jYThiWHZURDln
            b3IxeUdDRjhTNHgvdy9SVVRjeG1aeDQKLS0tIFZqOXc2c1Y2K0JqVkFIeGsxQjI4
            aEVnemd4ZVl0SGVKOVRDSXFCWlVoeFkK4m5k1q9FFEmkHo96HQBVGNcFjmA5urF+
            NYZ3vzKorPOJDFqxfN8nQ9H5ywjyB+HoR6oy5cvqp6yFGiO0yHB6RA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZUpXOXlid0MwcWo0d2xP
            TzZTOUpOS2wvR3l1LzV1T3ZxUWdINm1HMW40Ck5qcDloVkN2cVdJZmNRY2dMblo4
            d3psK1VRZFRoc00yMjlyRVg4bUUvUFUKLS0tIG9CemJINGd1V1V1bFpuQjNTT2xk
            MTltdThFcUMvd3gzam1YY2k5MnpmY1EKuY0OtFquzAB56iVxQuqMoRhaFTLCm5vP
            nvIe522hgVt9it2uZZjtwqWFlIxnCZvSxy6iTKt3B5Wjgdq0VXOOeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T08:36:36Z"
    mac: ENC[AES256_GCM,data:83C5siyafGZdkFt1cN41wYvUStSTKw9LmUtljCR84pnbBIBLyhqno6eZwVm54uwApl2yGvokn8+E1PkZVHgnY4U8ewWPUntGnBZ0keUzn4uoYjNNLzV2gbsyKdQxWKT4DbpdOQXopJfpV2UCJuv65grNU0DMts4xDOwi73gdCCo=,iv:SxwG3ytZyYJR3NFUivpx4qYbhyVFd9TrIy04aILF7AY=,tag:JljSPaDQs0AHObC9jsEd9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
