apiVersion: ENC[AES256_GCM,data:eG8=,iv:530oNQ/+fzIkiTXlNp/qoWXD00ZoAllubvfXXyAMoxE=,tag:+l1TlOnghglK/EKgmXnUdg==,type:str]
kind: ENC[AES256_GCM,data:aV7yKeyG,iv:VsJXXsvTDsEcR+ZHuQDVvFzeLm/+G49n/jEilK357uM=,tag:/vAA3dgfRHY7giT08TSTcQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:CgTKhtpUoCz/MdB3d2rN,iv:dWRCmtbqH3dWTfnUs8Mh3VNJ8hj/rvfDVo35lnuwfVI=,tag:GET+xUW8rkZ7T4wKuAGoPA==,type:str]
    namespace: ENC[AES256_GCM,data:plfdZ5A=,iv:QzIQsGfldCXd5TJIP+c0XhKAvaR/fSmMax1QcjwmW8E=,tag:41KWtI2A6AYzYI430+vokQ==,type:str]
stringData:
    buildarr-secret.yml: ENC[AES256_GCM,data:bbx8/OO6q1vOyBHsG/ViQgKzEnmS0sA+v2NAz1jOMwsQn/r77PKCd3MPuEEY/VoarxTv7t0H2hG6+Es=,iv:cVtEs2/CPv4Pp7w04MdmBa1mhy2Lul1uxlcd6dOoib4=,tag:YtoywsUSwudzBFWk4vuhqw==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhU0dpeXAwM3J1SHZqVVZX
            eWhBUURXbjRlazlEL0M2azFIa1JDYytlZHcwCkhWZXNvOTViVDV3aitRYXVjT1kr
            eUtCOWhTTmxuaGxpWjBUVm5oTUpUYXMKLS0tIFkraDNEQ3REZE1iMTdXT3Q4VVZk
            azZWSDh5RVhOWlRkc0VTWHI1a3JMTzQKfOHccZPteCzDnnZK/5RDVbKIFG0mVh4K
            Ota3R/T0ymHyipUrrJJHWOglMfvC1G85QExwSEZCt+rzuWQZiGYMSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T09:34:07Z"
    mac: ENC[AES256_GCM,data:PFnjdHiQ0vuamyhEV1ybbVknltVbM+0qtU2U7fO9EfgSlvHAylrP+Z3+8af4uxJT7j3beVZP8oxJYyNsaNWNkuK337/KxNEdt+zeo6NR2yXyQLhft91wSJey5jd30vCPuZ0rcIWo23inn+mITgktl0aLq2PgexQ5MKEcSHzkSTA=,iv:tU0hOSQXqS+301F8FUc9YgzWFwbA+2D6QRTcwd6Bcf0=,tag:XQROWFh/GCEYnyZBR3e68Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
