apiVersion: ENC[AES256_GCM,data:OqA=,iv:NCQdZKk323dfp7bEbdLTy/bQsiKmVebgy3n6CmjVtOQ=,tag:0ak1JnvZWiAixPpsJUWppQ==,type:str]
kind: ENC[AES256_GCM,data:FHclW8qD,iv:r+lKnhrZlLkQ3KBqNKg5pijUo5AeCaA/mbBxP7R0ftc=,tag:bSFUE11Dt1dGLGXTRBbNFA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nnaLVG6QcUJpvIxqFo0T,iv:PDj41uh8ObrjgqUODR+L2dVutW5Dv46CYKm5mcPyxNw=,tag:mn62y1OADBU7C/5Kr+R8Ow==,type:str]
    namespace: ENC[AES256_GCM,data:/3dzRts=,iv:CEm1aWlsvaLYj9Ugz30e/TLkesnBN3FNOMbB235FER8=,tag:dkIptTRHvO8EGrSmVGmcaw==,type:str]
stringData:
    buildarr-secret.yml: ENC[AES256_GCM,data:souM11XcUbc1Zk+t3Rj1shGTEtpJWzgdSrQ6F05e/P73ozjp9NktZtfL5EG/8N/SREioigHqCavYzxh2taoJF9GnPam0mIhnRhPllOKWC3nj5PwCn1VhZ9RexmuztWja7TVyFFItO3xIybA=,iv:KMaV52LvqU6Poz77rnWyZmDeg6TbxulCIwI/uE4KXUk=,tag:T2hkZvTND23oiuDdCwfdGA==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaUorWEZacWRDWjR4YkUx
            cU16M0V6QkZaYnNDajhnbm0yY1J4U1RwVTBvCmJiV21PWWtRUDQ3S3JEWk1PMEZ2
            S1l6MmhnSUdzYjVVM3FjMmhXOWJCdmsKLS0tIEZuVVhrYkhBY0wrTklmTkpuQVpC
            TnA5RlFEZmNmY0g5YSs5cFAvZlZRdDgKGTjU0WeW0Jf0VKAw/c4r3A/JU5ABrh7j
            975r5VuQtHOQv4rd4rW0nRu5UZlM+KxtItreOhvsMAF1mktgY/mWZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T15:13:03Z"
    mac: ENC[AES256_GCM,data:6e2tXLZHUUm0WpqquKYy/za9dLkgG8cyg1Rcp+dRIOijhszxbOIDCpNINOKlTjywCxHHdsjnP7THUIScQONSa/2A4OMOfK1E0NmG5lah0zao6mRkGRnYQmFmRbW78d4+rv3YFO6fp63WSnGHovmiOyWiGbH4vC9dx+/m0R+sbfQ=,iv:raVyNmpb5Gmh22FcxDrIQ9WZFPQo8vTdLdALXbIugtQ=,tag:+onQk+NExByASGzmU0NyMw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
