apiVersion: ENC[AES256_GCM,data:RzI=,iv:H3j0Ur3RTsgV6a/m0ZXUiD4ULzocH12e3rzTAmtVUKM=,tag:uiBGdqEcVzkTEVfFbCG8Fg==,type:str]
kind: ENC[AES256_GCM,data:7suB0vMK,iv:WqK87OlOEC6yyBska5OTDB+qMKy70Yn6xMz9Z8gaAIA=,tag:c3GHxEf9jN2qVAcaUMAEgQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:YOeJNzHB8SeHt31Pli2k,iv:D70yvyyVVq94zvPNZuMLGEBV7b/b2ChnAFDAiW7dNNQ=,tag:VacshOc7TO61sqh865p09w==,type:str]
    namespace: ENC[AES256_GCM,data:V/XhY/M=,iv:FDNtg1VREbTxU3LzLdotWZe1OYcxSHi4bjL969262pU=,tag:pfQ9kspH2nTpvWUciPP2jg==,type:str]
stringData:
    buildarr-secret.yml: ENC[AES256_GCM,data:xgij3TRmWViy2GQMW8mGcms+xGkq0N6OonqZZGnzaUxwZ/6VbWJS87bj3DuB6IXkyaQmsiyuiD9FvHLF7OIsMSGXXMqFQdGpU6C6jz8cFkXgN6IlPVywfMzpCvSkM962yYrzDY2W479yHVk=,iv:Bi4Kf2++GuSIF1Lt3d1+e+avWeR3SSY9jbSyfeMFajM=,tag:eDw2Q8wr5TlbQwMCkoB5SQ==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVS1JndEd3dGVodFh5bTJE
            cXVuYjU3a2ZCc3hkZ1F6d1FTR3dkYkUrakNFCmtJV3g2OEdOZS9IZGVPRzE5NnRI
            c0hiT3MveU1RNjZzYXdjODZ1NU11VVkKLS0tIGFOYUwwN0c2NEZDcWVlQndLQXZ6
            M1ZoUmtwdXFubDZYU0pzNGxBWkNXVlkK6TiMiIfrmBkiVJzlnD/scORo7YhgdADv
            BUx2iK4iLDciZiB6WU5zlrWT3yG5+nhxhXl9YdbiRgM9b56T/D1T1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T14:39:01Z"
    mac: ENC[AES256_GCM,data:bkt8QS55yrJb/oTz9Mc1ZFMS0vMigqIMop9Uqy2RGTdRdUJnSN4Q5Sr4D8IP2UYwhNQCCHu9RZriqKFT7ZI7Ym6JGYEXrIXt3M7CfUal4kkSSP8aZ2Z21bJ1rdd3Zd7zkeS/e0GqnZFbn5V0Rrc+CrI27fh4GX6ziDmSndhuJC8=,iv:e7knoB80486iINaLInEVvYJeYs42R32bC4icMwQfAeU=,tag:h05SoCuAECxn3lq8RkDCBA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
