apiVersion: v1
kind: Secret
metadata:
    name: csi-rbd-secret
    namespace: ceph-csi
type: Opaque
stringData:
    userID: ENC[AES256_GCM,data:AuGeErG405tPBg==,iv:FNUReSbAob8T4WkZ2eKhqFIa/w1JljmR/IHqzlR2quQ=,tag:FFLBknJt82e7RmDtkh/G3w==,type:str]
    userKey: ENC[AES256_GCM,data:pk6ldNfE/0v3VH49gDm+U18Xdi3mmtgDcc/DARVeZQz+3k/39kZ+Bg==,iv:QnvmJdL+/w8BeVcjQ3nnY1FtkEUMVr5KHmQBEWrbD4g=,tag:86HMz1wBwFweOnWglpUpsg==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UnQ4U3lETUE2T1ZTT1pX
            SGxtVmRXbnR0SGtpWlE3U0pNVWVDOUY4NWswClVvWmhJVlZCNkhSb2c0b3NrczB6
            QW5zdHQrVVdSWVFQb3c1RTdwbDJRNE0KLS0tIC9vU2xUQVpNWmJWVXVQNllCRFVF
            Y2lzNVlpNUVKZVJ0eVJjbXF4NG44TE0KnIN9Q6SyMugeccxvHuqH+pgDfDdyT6Op
            MG1BqpJTrdTaVc9aWUwmZWCqfgjcSWBKKjeba5xtRmoVA660r6j2/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WmxRa2NKRXQ2ZHBkdUVF
            a2piSitWOEp2d081RFNrdVQ5N3FHYVZaZENZCmw4TVB5aEIxY3FJME1OZVdpS1pY
            WDhSb1ExK1VjZnoyWGh6dzNMNzNSQncKLS0tIE9IMWY2M2ZnUERBelBleERZdjBB
            SHRkeU1WMFVjMkdJdklBRTFKL1BoWUUKawzb6B1NNPodXcz+PbfyFZY1VoukAg4R
            RTzqJtuBXgCm2zxauSZuCcbSdJhuPhze6ijXMNOdncbsYsRQKwS7ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T20:04:19Z"
    mac: ENC[AES256_GCM,data:uQVjrL1Rqr9mczE4a7MQ8YbBZ6ZYXxdCDedw8Wtl0DeHDRxkFh1ky0e61LYhvQjBwGzBRpRXBM9hOc3u+Fr4Pm4joaRTH4/ITwEIdwB6bUqTrff8a1tGeON726sr+Ecu7iBVl1kILxtEDAlKbR5lG2Tz5nbulPMbqhKaeKIt8t4=,iv:MHMoFgOQg4HC0xPJLuGwoz46I3Um8Tb70zEEKFfTSxo=,tag:X42ypKVD/AFcTV9g4wF1Yw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
