apiVersion: v1
kind: Secret
metadata:
    name: csi-rbd-secret
    namespace: ceph-csi
type: Opaque
stringData:
    userID: ENC[AES256_GCM,data:AuGeErG405tPBg==,iv:FNUReSbAob8T4WkZ2eKhqFIa/w1JljmR/IHqzlR2quQ=,tag:FFLBknJt82e7RmDtkh/G3w==,type:str]
    userKey: ENC[AES256_GCM,data:Seg6Xg0kppjuBkmdq23ijnAt49+Hf1YSyr/SSz0A8jtH3xhNzwsWBg==,iv:Il59SafNThVsJK+IvTqimk0tgg8NwtPYFAFaFnFifWA=,tag:wR8VhPPm7V/DHM2gtiyz4A==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUV243UXAzMnVLZ1VrbGV3
            UDFVZjJGeHBnb1lWMWdRdVNzVXBTTGpwZkdjCnVKS2ZtN1NZY1QrZTRBTWNyTTRG
            am5WT0gxMmtmL2V4MlJWdzFUWHVwQ1kKLS0tIHBaNDc2bDZNWTVoS1NtUzQ4VHhF
            aXhUSnBBd3RMOG1zU3orNzYrZS9JN2cKgYGLmeK1GK6MvTyREHG+fdVOEKZYtLt3
            QlEjQVCnb7EfzqSgse4m7ZHibE3iEACpa+VytwvTYgbKpTojL7fNqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T04:54:43Z"
    mac: ENC[AES256_GCM,data:symht+5Rg1sEhFnWWgX1vjD+UX0Pkj6AnZS69LJc+nTpTIMuPM20KjVN0LN90nF3vLouspJVaKLfDniAsNrfXCOpwMdJQQtlMh3ogOapmLbJeBvKg4JIANOOF1t865MDiaTIwV7if6pyCuZl4NE5W1R8U1Tb8P7cBwZJaT6gFL0=,iv:nOMOqii4JURxCC9OQ8R/WZYDxfGV+JRF8DQJwdc8jOA=,tag:6+5KzxT8QD8Z4n32eVIEkQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
