apiVersion: v1
kind: Secret
metadata:
    name: csi-cephfs-secret
    namespace: ceph-csi
type: Opaque
stringData:
    userID: ENC[AES256_GCM,data:lZHbgT5AnOYlAg==,iv:GYEG3i2d8gS8m4QQlgyDXhAY0s1HRubXwBSXxGjMWyQ=,tag:sqg+sFtecW2USTZvvSMWFQ==,type:str]
    userKey: ENC[AES256_GCM,data:OCppk2RhZ355jb8VMqAgqqETjiQZ3ntyF7mYK2Wjw4NueEizDm6AnA==,iv:u1tVKXQ2oKyLnXaAjfpK2X10thiLvEMUTVwy8dUErhQ=,tag:1W1WD246nt0K5dWD16Aa4Q==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRmFlalY0N21JYm4rR2VD
            LzdpSW84WG9DMjhrSHkxcVBEZUhkL1lNaFJzCjljMDlON1JZZDFySXNJRTRhZW1s
            YlY3dXhsaStuQkNOOStmM2RPZG12NzAKLS0tIEVJZWtSOEZmWUgxcWhEZVMwNDZl
            dGprZDIrTG9idHJGeDlVTzlSQko0NXMKbcN62fS5BFTeO9Iqf9YvvSRWsoVpCWwZ
            cuCQVGOULmIM8b83OhNXD4DaeQ5ap/wUgdcgFq8Ouvpdv5cEfP6urw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T20:12:31Z"
    mac: ENC[AES256_GCM,data:/AuBAhWYH/K5/Q9ZY5OrwuiSPxHLwEJQVXaw2gODfi3NKxBfAPj4C/x4vIqiEBBdJTqpszhlVPy/zDDrGJ5Vi0UwPQeX5cWSDRHDAJpv+M/nlzGKJK5/lZ7+JoluVkNPOL4D2pgRNacUsNnMr7e2fOVx4eH6sGN9275j/+mIBkc=,iv:GK3EeTpXiZ2p5t2F9rd1zBG/ONSpPjxYrgzjEpa2JX0=,tag:sXZXWuRBTFU3p3PvYY0xxA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
