apiVersion: v1
kind: Secret
metadata:
    name: csi-cephfs-secret
    namespace: ceph-csi
type: Opaque
stringData:
    userID: ENC[AES256_GCM,data:lZHbgT5AnOYlAg==,iv:GYEG3i2d8gS8m4QQlgyDXhAY0s1HRubXwBSXxGjMWyQ=,tag:sqg+sFtecW2USTZvvSMWFQ==,type:str]
    userKey: ENC[AES256_GCM,data:OCppk2RhZ355jb8VMqAgqqETjiQZ3ntyF7mYK2Wjw4NueEizDm6AnA==,iv:u1tVKXQ2oKyLnXaAjfpK2X10thiLvEMUTVwy8dUErhQ=,tag:1W1WD246nt0K5dWD16Aa4Q==,type:str]
    adminKey: ENC[AES256_GCM,data:kWkwNkcu4I+Qt9hFYjRnNhXgvPsCKcB964Vqo68Y7iEd6jT2JMLovA==,iv:Yu6IOe/kbwHhIYZLne8IP1dWBe/Vxu/EGwxXFilzr4E=,tag:VwtFgZ/SuyAt8VrjhwImTg==,type:str]
    adminID: ENC[AES256_GCM,data:VaGiBwlAflRgbg==,iv:6FDl7LLAXaJystZym8Pvsb98xoozB1oqoRgX2AekXN0=,tag:N9wSrqCCoX4vJtMV5zhF0w==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdm9ndWhzeG1zN3p4Zm1N
            aVlwNEFDeVNmdkhnYUYvMEVyTTBFcGU5TFRrCmszNkFNaU5Sd3hhekpBak4yRTE4
            SDh2NDZTK0RmL2pvcHBoZ24xLzVyVTgKLS0tIGo2aksrcmtQUTlYZnhvbFV5Z3Rx
            YUdDRFl3WWlzcXc4UHBWcGJoWGxEUEkKRD1/ZKfeEkAcVrIUdGfgUZa6bxYhkz2e
            UuaSj6cfrDmpOOByz9IF+neIbVXfW0+75K2dS87JbY+/PsjNXfjwOw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrV1k3bW9xeUpaeXhCd1p4
            MndPVEtVTXozaXJUbDJEUXNFQ3RjTnYvcHljCjU5cGl5OW5IdC9GN01YOWttdDdD
            QlBoVHRKSUl5ZzkwRVlwM3VKT3FBRWcKLS0tIHgzdnVxVVNkTG80OHE5dlMwM1Zh
            Slp6eWo0VjR1SE02a3ZRQzlGUi9pV00K0nQKHNsm8onlmxGFHq3dMudEsdgz/JSV
            wMZ6UIlXKJKE/KTmSBuI5eJ+uhXd09UnIHYnvF6rV5PDp5DTgc6kvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T11:38:09Z"
    mac: ENC[AES256_GCM,data:7+JxQ78dhRFVrQjkCd0VKFsgfJtIYTnm7UNR9GcJAfv6Eob2Dzr5E/sd+ane5R2WBeE2WAUn5OH0OXv2gBPEljth4c8ityJMSDk+zPOVWoWOxeK2WlHk/OktEyJ04NLZwpfW1n/iWlsA00Bj+AOzPnce3uthTegLPK0RlKLTITA=,iv:VdLoVj7BjtsFSYkd8lu0WObISCgcU7Wvm3TN8DjF8Pw=,tag:uMko6KIbpxSkdWgWr9L1NQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
