apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-credentials
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:XoF4eKV7zG1AZns9C7al0A5PZuvTvSHaf0dJqcr29AFbmaJ9iIc8JWBzvEAQOHHolNWgWz8sXASIVXobS0T/awtcH9m0WZ3yhD372pOV8QJVqrkHCy2PcWtFC+XFpiG7y0rtv040koX5TS3pknHWLPBt5Pa8dUhSpeOUpqJpFbKfIM/LUUmkaD9ADJYbQHp1FP/tS6I9aGtSkTRf+QVoC0t+8MwB/2AWhnj/DQN8lJijkDGjNhPGfw==,iv:PmmEXi7jmgjNrID08GzD+/QUN+1KxTNQ1avc94uw/74=,tag:iASGqJAOkStl+VPH7wypZw==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxenQ3T0xsaHdrWnd6b2pw
            NmN5ajl0U0U2VzZnZ3NiZThrd0xCVWRqUnhvCjdKeERvVFRnWG9kUGx4Z0dFdXBT
            UTlrV0lZNDNvc2JPenV5V2tEWHRNcGcKLS0tIGovc2tPOUs4TksvLzJnTjJVOGQy
            dkJac3h1bk9KMmZyQittdmt4WTNhTFEKIvABKSfeuVLXwXup/8/6JgN6lUt8j+GK
            zlZlZt5I5Ng4h7Dxr3D/gRtO8GK8PXjPThbdv2ohDFU3yWkatdx6iA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T10:39:37Z"
    mac: ENC[AES256_GCM,data:1un3NqZfZa6PZGX1ZafTbF+Hy8KItSaSWxFmdixUJfVPzY5RxWFJq+vl8w/CUkNY3U/Dq3sXnCUbqd58Vi+JXntnQcbuuaiBuvYmsC+1I5pPfD8NSF7qimZGar2M3dbbuTPr3h/PcLW3ZTLOJhcIK5Gji553ny8OsAOMJWRwDaw=,iv:3WjV10y3qEdCntbLJkHXlMTXt+qCQeiqc8VODqiiQSU=,tag:z3f/O4xzOwV9bozhVpjkQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
