apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-credentials
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:G45Eqj2+pAY+qzy5k6gTuqABbhKslWby5A/UCiz8reat2B/ctSEjErZPabdzv1s2BRx519Pw0WwKx4+pS7UyGc7YGtRK3ZW2Re6Ef+JgINYWWQCUnaH4eBHTeadP6G0QSFoQaqqopodYrpnzCp3nUntPatpUMUfFneqnuBMZ9tSNV4pdCNI0cqdfie1U18Jfq47rFsiNkhtXEqsxK5Byb4+X4mHXoiWNriakQQUSpCL9wUuJ,iv:DbF/v1xsVAPa5HHm9dSzTbLkWzk7fbDqN+nQNDiKLAo=,tag:Rn5Nstea5wH3AXyIvntfWQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:32Sf98b6+sbn3bf60LTg0mahaAM3E8AVqX8BHcRGrLR5a0qhqMoj17sfQDSJuzAU+R/P/KolK1z6XVs86h82lzwXfP7VFUTwYT7sPW7OnAGkN8gamTGkOXiJnt4pWWaFj7VxkifbKxgnHFk4hGnBIex4ETJQ9LDT1T1OGhvFeunnLQ845m6kKbHuBf+NuqbdYW1XlNBoPpzjhs97EcUCCcv0h3iMqoEBM0iYFT2GQw==,iv:UrrMPtu64cTyvo4d+YHGUBidlZwlQws6T1pt7/xVi5E=,tag:CiLi4KknmRMTiJJrkUrntA==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkT1MrdmxSRGNNR0NETWFI
            ZFRLQXYxeHo2Z1djQkFJd3pIRVF4SjducHdvCkMxVHNEbkFqWmphQ1VYeXhWSHBP
            M3lHL3FQMmYrUUt2dFFvRlNBL3orYmMKLS0tIFU1Zk5nb0I5RlU4ejVodkRlUzhV
            cUFpa1BUQVpRSnFKaitVeHhpMzlmN28K9yeUFe7hzqhmUlVLu9+pbBaZfU1GQ1vh
            MKzoyZaB5Kw6V1lRiUtU4iW3FXoUEPanQPZZoItRyGS/SiIefSPIPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T15:24:52Z"
    mac: ENC[AES256_GCM,data:4FFZRTXjtFWoeUPalJ+y6sE1q2wNOuj7NWKQZzjMcCMOQzEDwXhmZtfo+RWkRqO77SZD5MBPlU3x7Y469gY1kKQ9zqfIZmqqv4xCIjS9XMLCO4bxLIXA6KSlT3W5CW0SPvadb9YCHNb47mxY0+hCgP1bloRa5jaWtd6d6uZF73U=,iv:ijFfliZ+MprEbTRic7zNF7ktuSACb/ve1ISwV1jMXK4=,tag:546dPawtCK8S1gbxjlrzRA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
