# ExternalDNS Cloudflare API token (same token as cert-manager, namespaced for external-dns).
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: external-dns
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:9MkWSZauYrSzy4eBUNN9mPDS1XxeFxFw5hvLby864dxjnGS/yKitEA==,iv:U/N3GZkHyOdTzZO1us3/heMI7gB8L4S+MuUDCCJnfKY=,tag:e1fABTU4GeXyWt0Lk2IWKw==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERG9wRUVoOEpTa2ZsNWZS
            TFhlSUpwRFRqRGsvTDUwRlIwZ3pkRFdtSmdRCmdPWnNSbUJoWWI0TUY4ZE12MFVW
            cXZFTE1zcVEwUSt3RVEydzQxL0tyNlUKLS0tIEVYeUZFWjF0d095a09RV204Sm0z
            TFI0MkY4M05jYnVHNkF1L2gyMTFqazAKjTAJTqvP4+81RGA1QtTkmyCb5pLzHk3l
            bnR9F8TobL4Dzzv1bzWvcDEWQAQD7keq/xkJS3XT8r+fl0Cl2bDEJw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdzNRV0RKTlh0bW1xTENQ
            d28zeVRsdjFuMnRpOHRtK1hpa05OLzFFTUd3Ck5JMS9rL0oxcVhmSVhWTEdLN0d0
            TmdXWjY1ZXpHSElEK3VrdUV0WTdHcFkKLS0tIEE5WGxjaWwrTXRqSzFlQ3h6b053
            V0p3RFliVUowSWZRZmNxekE1UlBQVkUK4t54iDUbCLvBzexDJH5d2Ne9F6dDRfhU
            esrDPzB00lpRgodrHQcdP1DH4nPZQycFwNur6f8QYYPmpxjW194RPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T04:47:30Z"
    mac: ENC[AES256_GCM,data:ycmvMHTyYtdM5EWyHNmK6LoWLv9u6tRBaTdctw7pbZnF+dRD4KM/9mNwrj725CxH1/nhgxzb+L9TUWaBD2/Li0Ptm+s9VvqSh9qp6Rw9ppjmDYludoFOv4PBXgPw8uKqtSTowTMWXWR7cm6WlYQFcis+ouzpHH4cxbmfAdn4//c=,iv:AjFoRx9qOFGuIk6AwLYxHd6DNCFbEEvDM6U02zXiA9w=,tag:CglrJbdqRuA9M8Csbex3wg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
