# TODO: Encrypt this file with SOPS after adding real values
# Run: sops --encrypt --in-place cloudflare-api-token.yaml
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:9MkWSZauYrSzy4eBUNN9mPDS1XxeFxFw5hvLby864dxjnGS/yKitEA==,iv:U/N3GZkHyOdTzZO1us3/heMI7gB8L4S+MuUDCCJnfKY=,tag:e1fABTU4GeXyWt0Lk2IWKw==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZEhDQUpRbXJINFowNHRG
            cEc1T0N2SFRSeCtvenV3NFlZakppa2g0c0g0CmtrbkZRYnE2N29OT09md1dndGd6
            ejRWSlkydG1VUmJocXRzdzNBMU5yNncKLS0tIGRNYlBORDNJM0FJNFVRK0duVTdC
            cUFJYXI3ZDZ5RVZId0hRNlROTEt0RWsK7iEyluDpeFXsiPkw50ZqvNxzyWiZgV2b
            8bhAZt11kkaJ6sK01XrJm7BwlleldKO2AjKMZLRJMz4xuc4ajUS3WA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T04:47:30Z"
    mac: ENC[AES256_GCM,data:ycmvMHTyYtdM5EWyHNmK6LoWLv9u6tRBaTdctw7pbZnF+dRD4KM/9mNwrj725CxH1/nhgxzb+L9TUWaBD2/Li0Ptm+s9VvqSh9qp6Rw9ppjmDYludoFOv4PBXgPw8uKqtSTowTMWXWR7cm6WlYQFcis+ouzpHH4cxbmfAdn4//c=,iv:AjFoRx9qOFGuIk6AwLYxHd6DNCFbEEvDM6U02zXiA9w=,tag:CglrJbdqRuA9M8Csbex3wg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
