apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-mgmt
    namespace: external-dns
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:CbteSdwCrpT87JvaFngLnADenVpQpMunQl/ufRnntGjeBfHAOJbFEvbq3DUlCWRymuIj8zc=,iv:uw0NTZsiClTJGtxy6VAN83alrGOCo3CrC4sxyQaPjJ4=,tag:jTIf/4XsVrxTdW4/oD2LvA==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SmF2SWV3c05Lc3ErU1hZ
            VU1GazUzb3BnSUdjQ3Q2YUZlYmZISzlLUlVJClpyMzd4cmhnMFltNzlPdmNFNDFn
            dWF1L3VNbVkxTlNuVFpITEFlSmFUUmsKLS0tIHErckIxVlFDdlJuTUFydU9mVzRp
            QldDOU5xUllsdzRtV2NxMURhaGk1Q2sKy4kzJJx/ykCVSkDeMi9KUPoGwWnmLek3
            Gwuy/MihURnLri60lKZMqig4AFmKVeF5YbriDGMTjuHMZHqJ00uuMA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVm5wa3N0M0FndTU1MzY1
            dy9ibjMwelFic0V5RzR3VmIxdlV2WEJNRmgwCnIrOENiVVUycENUdWt1QkRuSFFF
            czdUdjNCWTRHSXVyeFVLVnVoZEQ0WlkKLS0tIFRRQ25YNkRLdEZkV041RjNWZUts
            K0NFZEJiNWFHNE5zSGUvYTZNL1plZVkKwklJqkoIMFqbl86n8t/DAwthRyktAFKM
            bKOxr4n06DaQQA6dU4eWGhtxr/Xszl3Ma4AbAugi9klvSJBS4Ik36A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T12:48:33Z"
    mac: ENC[AES256_GCM,data:lZTQ8is3E/AwKMb0i/nvq1zpa/TBj1MPlrIiyZtdA9TW7JEDCAbw3qpjbzon2DWY3IcFeeN7DvBiB4aKdN8nbO68A0CA7354lTDbd+MtVBN03eQy4ftmiHYUb35Hs5dglIzrBI8b26lpfFmBfqjhKLTEstM59uNO2lr9UQW8PTk=,iv:ojptyzgl2sIO5QrUsbKurzFhmDsnvwGicgTKEFMvAWw=,tag:b6bgslVTI3oedHqbkSedug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
