apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-mgmt
    namespace: external-dns
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:KuCdsPU2YB9m6b89j+R5UuB0kndaPmtjEGXj2z10AOuhisbeRHSxwPH2CGxCKeh1oX9HyEY=,iv:8Guzvtgt9RhsYzb0HGZDfRWOryD/sajfE+jejLOxakI=,tag:pJwY22QlYLr7z3mzK2U3bg==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZjZvTkFmUXJRZ1ZucHRm
            QmlibUtaZnJjYVVDcHE3eUtLakVoM0wrOWxNCmJXWXkwbFdMTjN0L2M4aHYrN1JB
            c3pLSUpZbDVna1F4UWVNMFNENHNUSGcKLS0tIDlkVzg0ekgrOXZaTDdTR0lRcVd5
            NXBjd1hSTk1KaDBnTEQ4WGdYZDFIK2MK9IdhYP+wIm/DruPS4+0lp5YVaRPnSZLY
            A2dIwI2h751NZmfVz04IMjcNEzYWthRqBMu6n7R7jpWTkjux79izoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T09:00:35Z"
    mac: ENC[AES256_GCM,data:alAgWKqv40ehzbwk+k6mv0yndk0AFykLIXbVW+Pcm215n1B/6TDZpGSpM33kJYKFAlKTGwSXxM4vNMzVqL2xiPIsNkdx0ewklfEO3o3nQ1LE5/almaRl/ZmVg+5qffmN76//4ciQlb4Gks7nDFo6cJsvskTAFI564TpQtcRlEt8=,iv:+yBbbilZYkYKkvIqTZeabNQ9a086jtXwTf7v+m+rD3E=,tag:4I4vy3MTPU50Jpyvz483Ew==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
