apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-credentials
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:LRXNgfyneqWW+8oC7H3Iy0F/jYnRh+cDfKUC4ZPyahPXq2SptzEe7U7uvgvNhIHT87un+AeezEau/IE+o2T3fzuIJFLaKgWsBtsaPV7iQHpjZEbSruEk5Vs4Aa+FnfSMSKHdoTk7PDyv4kw+63/xFE+VtZt6XYiwDS+RYKi7QXRG43DLAbAIoiDdZjXJ0kkClJuUk4zgDXLYdL+7H5zKqKOJi3PxpfeBPshpqcNPJ8+2bW4cZmZvsw==,iv:hyIh37XbkX4pc/d9qpF5lYuueBFAbJwQ0Lnw6x4q79U=,tag:mh6hBSnaE+ejUrmEz0hdpA==,type:str]
    credentials.json: ENC[AES256_GCM,data:F5nOiKKUCG+93iCZl8dtIliot8h8zDLHaGJF/l2jTrB9jEjwNxH913BESfcc37m2nBx64UlrRVsX2txSMJOC743q+FwS1+MRghmBFqHpm0MN/s3JJyrxOUmesTcCgmxbCC6HPtIEYB13yGqt18OXp0y77M6OvOGhd9VYdNgPH1WZaXY+EREYWTNunlWVD1DeDLVfagPlbW4aisnU8ho89Ucz2MiojXtnmmwxi1e9Ic3TbtXU,iv:V2Qb3KSFUCpuSCEAaXGFtdQU6AZlPV44CPZLqTEK4+Y=,tag:SzX5suPbx5yMig73r9r7zg==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkT1MrdmxSRGNNR0NETWFI
            ZFRLQXYxeHo2Z1djQkFJd3pIRVF4SjducHdvCkMxVHNEbkFqWmphQ1VYeXhWSHBP
            M3lHL3FQMmYrUUt2dFFvRlNBL3orYmMKLS0tIFU1Zk5nb0I5RlU4ejVodkRlUzhV
            cUFpa1BUQVpRSnFKaitVeHhpMzlmN28K9yeUFe7hzqhmUlVLu9+pbBaZfU1GQ1vh
            MKzoyZaB5Kw6V1lRiUtU4iW3FXoUEPanQPZZoItRyGS/SiIefSPIPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T13:10:04Z"
    mac: ENC[AES256_GCM,data:zRX84I/iJBtmzb+RVzRNrc+mNW7m1UFSXqPDVGgMO7QRv0yD2focYkCH7DxlOhdQSXeJiL6gJIJTlVmRDV11L1HGN3wwhfuM8zmUmdVGZZ6VwQm/U1c8xlvAyokLNWN7oWa8IdupH+m0+RyWcY5EPRW7TruXYZpjWb7BzYb6GYo=,iv:IMU8wLHD5zY3ycYCRFgXnjk2gmNchOrfaOFTnRFutA8=,tag:Ffux84hnSSrwx+SsNXCTgQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
