apiVersion: v1
kind: Secret
metadata:
    name: codeberg-read
    namespace: flux-system
    labels:
        app.kubernetes.io/name: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:mYch3kEIQqZbAB49HmI=,iv:DirKUV57C9Amgcj+5EzAm2VV/znTsEBgtOsWAQdKsrI=,tag:21IpNM5/8HfBi1VingV3Vg==,type:str]
    password: ENC[AES256_GCM,data:70HZi071GIPMx0h215OcZZoxSLceHdoWvXg/t8kmVvBd1dhe5xJYmw==,iv:xoMSLUzecMuq9csJFSqp6I6l4EL0NxxNUmnDB8STvcY=,tag:qf2Y8vnMZWTBkW44n7PBLA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhS3V0TFlkUlJuZHk2Q0Ri
            eE1KNHp2cTREWmdGSUhXNjZEWHVJTk5XemhzCm1qams5QTR6UzJmci9rZCs1ZTlB
            ZVJlRjJUMjZSQ2pkcVVNelczbXBSTVEKLS0tIEtqUFNpNzhVTGJUYTRkWDRKUkpM
            aHA4OWk1a1laTSswZXZvWFpXU1ZMSTQKzANa8My+BiPorvelOUWVrMi1S58Z9Wd8
            b3l0cai6KxtmpiwPcqOeilOFiCeXTifwfSI0XJG+7i8NWai7u0Wh8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLd2lPMVZsbUQwc3YyQUV4
            M1cwcjVhU0l6eEo1TzF5ZGtMQnFkKzFxN2dzCkJKRW5nak1XTjNkS1dLUjNWWlBk
            OCtpOVdyMGVOZW4renhCVzd3SFluT1EKLS0tIG10VFMvaFI3QW10cmdNMGhLcGpC
            S2ZmeGxyUythTjFvcnliaHhsc0g2TU0KAjudgBKR7MOLWzB4fc/n2+Fjx34hHS1H
            XDzPC2mIA6hMJT+DRjQZ1KyG9e5MnLX8skX347DGU+W6Vohttn5SHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T12:51:15Z"
    mac: ENC[AES256_GCM,data:34r1OzxCt5IgLYQI96loNLevPPSORS4kSKx6s2xSIR5DYn94hz0bp4cxkqaFq24dF1ApRPdBQEvjIr6NeMuUmPxl4caotX01NQ2fM9F/nqY6n8vs4KNJxUNDkA7LGjrcVBDva4C6jbppPpkS93CMOIsBd7c8cF2NRhkKBNjibp8=,iv:0aN1bzyqppPaZw2dqQiUOVHFtdMvcPB6pozyCFG7QS0=,tag:/Y4op/mZo4+dXhrZRvg3eQ==,type:str]
    version: 3.13.3
