apiVersion: v1
kind: Secret
metadata:
    name: collabora-admin
    namespace: collabora
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:zEhzk0t7i7t6EosAT7JB,iv:c7ZtC+IZp4FziUNUi0SKdNMyQTEMGPVOtiD1hsDLDqE=,tag:i8yiScsJQ4A0X8gvpfG3KQ==,type:str]
    password: ENC[AES256_GCM,data:AYvtQx7svCMbOmlTQ/Ch8DoZGUvrgn7NU9FKvfJe/guB4W/KaBw5+ZOmHw==,iv:AhAeFmvI5wlmf/bN0gEAQB+Vf7/4fglCcbpR7bG7bRo=,tag:nHZPOSHahSjP0C3TdYf2sg==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RnJTb1hLemVld3dCdm5m
            NDcrNnlxbldZRVlGbjBlVDc4eTB5Y0lNOEE4CnRMUVIyOU5TQlZwelM0U0NjclBn
            VFNYc0pQOXRpaUExVWpXT013Qy85dVkKLS0tIHhOaXBtU3FpRlhXSXFkSXJWZ3V2
            RFJGcUQ0bDJ0TXYwbGRDdUVYOFdGUTgKZPMBLiSqqQmxmYJIUqoZvWrSD2SF42Cw
            NgoFaNq0ntxz3bcF36D2yv/jW5WuWTHFlJ+qNG11C5VGcVXnXKEexQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTkkvSGxaejRZaHBZZVYw
            OGdJenlSR25XaG5oa1FxeEF5dUROaHZBSVhrCk5JdGl1TWVXR091QjFsaFZrZGJ5
            NFpuSjRUNVVaV3o2V0lmM1RjVkJLd0UKLS0tIGxFa1ZTajY0ajBYL2E4UkFQQmNU
            V2tUeGRHUkliMzY2Tjh5SXB0YjB1RkEKCM2U6gwG4LFTAL/twCwSXTZqGblWYkja
            wxSHDplCYWHf6BsYSr8IYAY1Wfw57Q7DogZLU1CqXV6/fFUeSAB2jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T16:22:11Z"
    mac: ENC[AES256_GCM,data:HK/boz7FBYOlSx9y+ydf9myEtyW4k5xtRsNLKaMTSTU4RuE8HUR9v63dhiHertkFh8E3ybmttL8kNMI7gqSnuBvrrAqhNAFketlMbKBn9VczRAsUEIHtDJH6SEfFGbZm/c494yVZ1dqyZvbd8W3cMNVQ0tJ1IVYRGgWQ0966l9o=,iv:ofoj1DiUAPwo9XU04PjndS1ObFHzDct1Xx4P3GgayPE=,tag:vjgycz9kLN5o/5imavY/Nw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
