apiVersion: v1
kind: Secret
metadata:
    name: collabora-admin
    namespace: collabora
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:zEhzk0t7i7t6EosAT7JB,iv:c7ZtC+IZp4FziUNUi0SKdNMyQTEMGPVOtiD1hsDLDqE=,tag:i8yiScsJQ4A0X8gvpfG3KQ==,type:str]
    password: ENC[AES256_GCM,data:AYvtQx7svCMbOmlTQ/Ch8DoZGUvrgn7NU9FKvfJe/guB4W/KaBw5+ZOmHw==,iv:AhAeFmvI5wlmf/bN0gEAQB+Vf7/4fglCcbpR7bG7bRo=,tag:nHZPOSHahSjP0C3TdYf2sg==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAveTdOTkxHdG1qL0pYYzV1
            Yit3eGQzUkpEQnRZNyt0cXJDU2Q4MVpYNjA0Ck9WN2ZuNVZFdWk5d2d1UU5ya3RW
            V3VQSzJLU1E0ajlzaytXMUE1am9OWEUKLS0tIHFjR0xZZEVVeUNqZmovZGhEU0dr
            UVExTWk0MjN2ODR1WU9yV2h3UkRNTEEKB+875XXXaizsrXmI/pjT9eLgHEZUFR07
            mx9U9DXjsGjsKqOfwYrpkEl1Pb+b8qH0AelA7E+YUimYmbckHx/tQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T16:22:11Z"
    mac: ENC[AES256_GCM,data:HK/boz7FBYOlSx9y+ydf9myEtyW4k5xtRsNLKaMTSTU4RuE8HUR9v63dhiHertkFh8E3ybmttL8kNMI7gqSnuBvrrAqhNAFketlMbKBn9VczRAsUEIHtDJH6SEfFGbZm/c494yVZ1dqyZvbd8W3cMNVQ0tJ1IVYRGgWQ0966l9o=,iv:ofoj1DiUAPwo9XU04PjndS1ObFHzDct1Xx4P3GgayPE=,tag:vjgycz9kLN5o/5imavY/Nw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
