apiVersion: v1
kind: Secret
metadata:
    name: collabora-admin
    namespace: collabora
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:+Sl/kgnFM1c=,iv:m7d/52d5e5s37q4n+y/nw7xKj7z7hFcMP1a1YvsyL/U=,tag:OiAFIVbXZErFr63NEaPbfA==,type:str]
    password: ENC[AES256_GCM,data:pn3hRBE/3Hk=,iv:+MWzLuZlYwrqAMINeLFnBO2BZJBbmfVRmxxEpMOMKSQ=,tag:W+3xsGLXDqPIBDo4uvVs/g==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZXV1SVRnVUNQRndGNjY3
            V3NuSFBYdzVZSVFTOEEyZ3o0RDM4eGJmTFdZCkp3bGdLT09wSHpjMDlnVWR0OGdR
            TFh4cWhKL1Y4K25ObmROTDduMU4vQ28KLS0tIDdacXdodVdlbSt1UDZzNTRJajN2
            dWdLT3VqSmZnVVpLZGR5VUNhVTkvSDQKOa2jYK4fK4aMm7VBC79dRTkHdbgG0KHJ
            k0tLbOEaGUSBgHC7jKTbiWR/2+SxH4fzbO4G6jtrfzdnV13RPH9bww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T16:00:52Z"
    mac: ENC[AES256_GCM,data:YK3hAofEOn8vqabcfZRogKbcuL+27jwP5GzH9ldFkd2aZ0DTwejWqjePK8HIBhxmctglkjFTFiflgK8sOav8859/9SuhECHCCcF3yFQs/FDjrAc7X+88cvcpm1Jj9+6te8iH6ASBXTHQCl9reu3ng5ehzck6ESNW0EtSXrJmWyg=,iv:k3yyBX1GYPO2qRO/4n+vAHgkPFyp8Z8xYRKRkcG1bJA=,tag:PdBh56MNwOskRM8VIlvAwg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
