apiVersion: ENC[AES256_GCM,data:uhA=,iv:LnvH7Xqt3oH4thMKJNbVwBTajh1vnFK+QcvmHTwe05A=,tag:sS/TDSE1GF9xEgcxtrk4yw==,type:str]
kind: ENC[AES256_GCM,data:Hl7DV/nA,iv:pobNP+gv8lNkziPHfMYC+0FZdQwk80rnGfl3NswVVbg=,tag:o1rJ41ilRyJE9x0sIv0uzQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qSQmowYDW2AZzlf9pNb4pHRfsVQ=,iv:t16cADfBnBkleNFQerN2K7OACUk7B6YPaTyoVTnnJJw=,tag:woqqTf05zDxNLxmliaghqw==,type:str]
    namespace: ENC[AES256_GCM,data:mp7HKT9K,iv:PSM0EgXPNDvRvQA98FGX3NYF5MvmzqWuum+BsDrvvuk=,tag:QIflMsoahL+3eae5tBs93Q==,type:str]
stringData:
    secret: ENC[AES256_GCM,data:O7SvIdUXjrn+fFLAgHmQbMpvW8EFvKK8fwzKEVy35xvHM6Bya6Lb5g==,iv:2TYWUuvNCh0pIeBcW+51OvD1RaYaU7YHsEVQYD33Yi8=,tag:u18Epy1h+wrI7EvuCbxwSw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVmxlelIzTnpLRmlkT1Mz
            MFYrNytlc1ZCU25vR0ZOdlR5aEhtTUwvc1Y4CjVleG8wcTQ0YjFzL1JidkhzcmRw
            MFNmQkdpNStzNndBVndlWW4rYjdnak0KLS0tIFRJdnhPaFdXU0ZmT09xSkdWbTFz
            RmpXT3hhT1k4S0tvRURHV1lHbk04bW8Kr6mCqgI9WWpcbVsryDuaNtf/hRi4Ofm1
            8WksC8Lp/SzrL1KSLuU4KaF3ENWXzHZFG8Qts9s9NSmKKhoHyqtKBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbmRYb3dsd1I5S1lCT29p
            VlNORkVRY2pNWkFzWjhGY0x1T1JLNzM1eXc4CnBjWW9qQWxqZklwb1VJL0xWdE1m
            QU1ubXkrd25QKzNKc1puc05kQWpBcE0KLS0tIDhLbFVwWWFkZXpEK3BnanI4bCtT
            MzZndWdweitOdFpkNEN5VGdXQ3FDUTAKNpFh+SYXoxsCxFkpfJd28SRxUUUo8fj/
            gPpiMIcqsAVICL1lfMOe3BFCB5C9pRxBHGjsWlQu1Ig5J9EzWMF2vw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
    lastmodified: "2026-08-26T17:29:11Z"
    mac: ENC[AES256_GCM,data:PwIr9hw6hXT6NuTpa21m+QaPAdkM6MK5R3uGv3gfnaxCq6gZb0iPOfKmZ8iFHaAYffqKtGmiLht4rXFDLQNqhJMbCXWVEiHYOHW3ha2av8hdssf3Vcp8Yr4VkUgkMk7MkaLx+f3BrUC26SEBInaDkuZQJ8Vvl8iAEh82OvNsI28=,iv:k3XJ59PB78+hLJgdKodu4AQYcCJH6iVVA0ZdVyxkaQo=,tag:L8sBz9bn+i1zpl0D389dXA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
