apiVersion: ENC[AES256_GCM,data:9gM=,iv:bO5UpaUJguwQ1nL2fE35tFE4F2DaJ9dZ3civ/Y89D08=,tag:PvSqAi7yXp3PoboHy1LwOA==,type:str]
kind: ENC[AES256_GCM,data:190gv3f5,iv:E8zgSRBEI9NUL4GBgkUSz9qVu1E8Kest2QEurIviaFU=,tag:PP84O+Hy7/Hu5lavA/6/rw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1vwkjTBlnxxbIGmkhA==,iv:SrsUj3vg9Hfbu0J22bVASyD71CbFbqzY73YBH1anYDI=,tag:BNby8g3LzhqBLuo1ciM2og==,type:str]
    namespace: ENC[AES256_GCM,data:S3VYdyJuVx/4KIi2hZNXQGk=,iv:cCWYQhfxnmJYU+jmV6baAKhlgc/bFfoCzIO+c3zDu7w=,tag:KTAL+q23rO8AN+gO2Cd0Lw==,type:str]
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:Kk1uHOsrn4c=,iv:ktuabuBB6wDbw5D0Brx+oYlKOJxXeCyuoYQZvn1ihdo=,tag:M/zY18rU9kNHxmxQjmba7w==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:Ha6wBEmVbdZT35c3DCjMbpb9EjSjmfUkJ07a18nS3Yc=,iv:iwYY3dGHFLzi8kIUARtZTgi5vKAq3mD4KcGBSZudPvI=,tag:rgCo2LqVGni6JY6LVMVqOw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGa0VEcllzZ3BZMjZnazRv
            bmFuektYRG5pWUtDYWdTR2E5VDFaSE1BTUZBClJlWFpLUXlRcVU1WFVVTzJKano5
            MlFlYW1nRWJRQzlHL3BEdFZUUUNmNzAKLS0tIE83NEVVT1NVU0dzMzVWT3lUc3ky
            Zm8vMzVMM3NTcC9mVEZUYXNqSXMxS00KZLuE9nH/cE3h2opRWJL1r5jBcEi7T5EI
            FRX6Jd1C+RDF69LLCrF/ZUmdOVAXvfJvCIzLuj1QS7RLB7djdj3Qig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCaG5WbjhXRXpJOThTZ3pT
            YmR2RmNpRjcwN0c3VTliMlc4NE43WFBPT1ZRCnR4OFRnakMvSWcwYUFwd3RyNlgy
            amswMDhEWEVvOVRaZjNWUU5qNHo5QkkKLS0tIFBVOE1HTjVaTGFLUDVXWEhXQmtm
            elVYREs3ZmwwN3JpcW93SDQyTkRTbmsK21VhV9TTE08OGRXj+0DPR+4LGEplSElV
            3194ry/TwZOOVTxM1Om20NKMAZUBrt39+uFBOXJV3ZV0wi1d/Cr86g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
    lastmodified: "2026-09-07T16:47:45Z"
    mac: ENC[AES256_GCM,data:GqWUU/giK0LiwAVJM+HT3g1aGuNCQRPDdKilx6DNUuJNAdCMQABOag93gF0S0rH8dOYSpPG5io3oaQuzCZcWpVXqFWcDngi47ravvHD0bBrS62u6X1E95lTEg9RHsV+/Slp+WLiQluOcFJiYaykGirZJTLLBIarYdrotRRoXhww=,iv:Pr3wTs1lp00I5W/WTJwwNJfpUsSrMGComnNctY0fFKM=,tag:GxyCexyVtO4FhgvQOQ4avg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
