apiVersion: v1
kind: Secret
metadata:
    name: ddnss-ingress-wg
    namespace: ddnss-ingress
    labels:
        app.kubernetes.io/name: ddnss-ingress
type: Opaque
stringData:
    wg0.conf: ENC[AES256_GCM,data:YYB9odDwtu8pTeCoVs7FEk9lMyK/bsuSbshdyun4RWwlEcO6aBbU7kUDAffWsNX22hitbJgN3Qp/MhbdJNfDvigx0oztQQrVPyQ36vMkNqCRiSEqkn+WsSqP8f62nK7Ko1Ucpcd8v4+f+N/GIja7DshgZRK/ztXS8YUuvXCOLld+O/E52LVF+aPWf4w69hH2NCtYew3FkkoSryhi5jtvSwjNjxS9IyuzKRPNHtKIqCB6k0+gtmQC45WKd6MhylkE5bnU3qCYP3sc3ELov77crE/Cps0v9nUfHOMqxrfwQxEo4W/aEB7+yQ6HBbHFqh+sM5bWrEFZcjnxSIP7bt1m,iv:gZHoQqzaeIqhW/j/5rMttuKhYenkVnsv4MP2w96C++o=,tag:+vqhlmR+y9VIzeMeypufaw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVzF1NW8wbG56eWltRGJi
            VnNURmxjMmNYRHYybmZSaStQK2VrU2RnTjFJCkRYY3U0VjNLY1Z2Q0Jta2ZGbHAw
            dGVYZkYxbnJEVU5ieGNiYU13b2FXaTQKLS0tIDllQk5aTkRMaURBd2hNQ21hTUJU
            Q1FISHVBQzBxZ0FEYUhNTGpvUHpHYmcKUXieNhjF7mLWSk03A7hR+OD4/+67StvP
            WHmRuQJbJsFx6Wo8HJZ+egMIlDjcyjwlIq//pDAq7nbhHAhtIqkydw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdmx6ZlhvTWN0ZWZQblQy
            VStBVG8wcExUYXUrRHIxVWFDQW1PRGdXMWxJCnRCa3EwRkNNOExPcEFiei9QMFky
            OWlSM0ZDcmN1K2FOMFFiYVloMG1QZEkKLS0tIGxqeWNKSTcxVVZpaHFnc0pvd29n
            MFRMNnRRbzhyY2hpSTNIM0J5aFo2TUkKowlG9/jE4qHiPOANNepkibZdzRnsu4N+
            l+wp9Ph8s/SICw1xbP0uNqJzalWSbL5oyxz/Wbpk+MhollAPPLE/dQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T16:44:29Z"
    mac: ENC[AES256_GCM,data:ToVZg5mdIlx0T8bM80HKda5kpl1rPmYNYq5MUCpcnl25mDmp1kExvt4bqU4zxGDxNKEM5cXtMK1z9Ox9JJQ8jp9eN6y8/RTbjZ5tkN9Sj3SXC50+Z6kow0zLNm8faq/2T75askvFUxDnUm+6GuKyoTfx/pGU/O1D+on7OFaETBs=,iv:zyRA08YqxqdSDugxPJFRyHb/12EfXbI/BsnZS/oB4Jw=,tag:YEZl/ZZAxwO5yAqoVBu+SQ==,type:str]
    version: 3.13.3
