apiVersion: ENC[AES256_GCM,data:McY=,iv:/kKJYh0B7qLakGENpbvOHMZk3qVxJbaFusGIRlZcapg=,tag:DivK7CZ0CIhoChJ34nY+rw==,type:str]
kind: ENC[AES256_GCM,data:pjBS4jWd,iv:38h+a+GYmeJaNawR1QsVICl0SWYmQirxLBADft3cl+0=,tag:CKqicsIvjEp9Uyr7EnGvoQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:aRa20tDodWuzCg7wtIaw7WSI,iv:2sVRoZfrvZd094jeEYKWQzmF4HEBYAoL+w1pIb4ElKM=,tag:oIkou3vd6B/oXjvsXSScnw==,type:str]
    namespace: ENC[AES256_GCM,data:pyAzVbNdMoeAEF8=,iv:VoiQDcfqZ1Q99iV8OVKfzYNeh57kiLQgDxKnEV1JYpg=,tag:/PwRp/NzG0jWIEsZfPNhgw==,type:str]
stringData:
    token: ENC[AES256_GCM,data:cxP2NIpHr4m9Gy9mLy6+kl5f5bpvLMgg+IG7/j8KWnvUw42AfcXJ5Q==,iv:VO5QgyiQa9Alwtux7fwC+2gTcetw2trWDBtLDgoU9+Q=,tag:mvB3Ttr0ZemGTdVldRbIdA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWnR5K3kwTVpZS0c2WmlG
            ODA2eU4ySWtmc1kyQXl3MVRtcW9OOUFPQ2xFCnpLRHNPTW9yNTYxTmJQVE01bE81
            YTlDODV5aGplaU56a0Q0clNYaTBoMEkKLS0tIG1pZXljOWl1TERPTS9JRm5KRlZw
            cWJ4ck84THVraG52NjJSb2FOYzFSNWMKfSsSCYna+8u6jVVuAR30fdzDsFHhZlbX
            A7vrqv9e8T2/KLvDh6mKnyQ/yN/DTq5/YpJAKuyUB9VDX6IDoqQ/5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZGxDcFF6cjIyeVlWTXN4
            K0ppWWRsdFN1QlNzZWd3M3BpUGtvUXBVbVhnCmRxb2JkaXEySkRrWG1wRC9RUnJi
            dWtsNTJ4Kzk5MkxnNnRuREMwQi8zVDAKLS0tIGwzaFAyTUJaR210dFdIaG1WcjN6
            ZGhxREVkRGZVbElxSHFIcUxXYTFoRk0K1en8yykV+JXeqhnFbnwzXOMDLXJGyR4Z
            Jj9lKUZq21+/19pYNz2NdTcKaDhBovT7DqAlQtngzgqEZcuYH5gbbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
    lastmodified: "2026-08-26T15:26:26Z"
    mac: ENC[AES256_GCM,data:8hpEWeYU7PbJMjchi0/65zXGtDHln8t0jTchHD+UCYtD4OVm3FMSwd6dNkaEnETwIVLUFzvmTUXmywDQ4ng/hlWbysIPIhEd3ikuRUS07pzYMBCnWpdT9GsFzyPxju6ci90Zdf1ElBHrcExDjFibDz0v2P3oRMPdvehjxmjJK1s=,iv:wOVEbkskVxJ8oGq+Kq28OgCnM28nRNH5vKxU58jILXs=,tag:iK1bkr8Ei15H14ZBc37sEw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
