apiVersion: v1
kind: Secret
metadata:
    name: forgejo-oidc
    namespace: forgejo
type: Opaque
stringData:
    FORGEJO_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:T9yJDp2IE1mX2dTRyfxkC1Kzirz9Cm6b/u+o0ZEzA9LEpIN+Y4X1y1ludhUzakdZNpoB99qAOHd4dUS1oxDlyA==,iv:7zjZ+6LnkTY7AxOQ3CG2NAvxwQPbhLA/D/7jHi1QKcw=,tag:EMa1f3aDnvDsU/91UVMx0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRktGTElsNEp1Ukx3THQ1
            a1VBSmg5WUhTL1FienJjakw5d05wUWw0Q1JnCmtIWVZPN01lQVJWYkVEcjZPSFdD
            Ynl5TWhGWndQUHdPeENuN2pCYXVkZXcKLS0tIFRHdS9IK3hRdTRBR09HRlhBcnBh
            ZWZocENoVXRzb3c3dEtwdkZsSlNzUzAKyBqXho6AAazmwGyrwzPK6u/WnXZ7Wcr9
            eTPUU8MZ8NuxJ9zDw7wEJ7glQkg5fBHOoptdpNODcKN8ZLj4zNR9Uw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aHJaSWRmc201a0RqODJO
            WTNEQ2RwazRnYnU2QThHSHlPaW1kWnRIQ2o0CjVFYW5RZU5IM0R1NHlxV3RaRXdV
            YXhrSjcvSHpvNkIrTThlZ3pzbDUydHMKLS0tIHc3bmpzdER4N0FUVlVWckhWLzlB
            NmxaaUhUVUxXaWh0THZzblM3RS9XcFkK44ogqIsbSqJkUADoQrlWLEru5W8ZtV4Q
            pmVOLu7zm0ns7I0+HpNmybtH80ToRkfPUerL49JiT5Hp8E3qDg1qEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T14:58:10Z"
    mac: ENC[AES256_GCM,data:sxiyappjXgNIDbCfDVjVuj3orOen7EDu+iSlrU9gJoTsjKoB6nHCSQ3/wJ3OL6lPVEuT0e1Lu/XH8GqOdSJCKde2UBGKWe7tAgR2vNAVk7lFqNeraEy822SA6CllfXOBzljfKwcZgAvuDM0Usvygk+Z0wSyV3s1RYXkbPgkFVFQ=,iv:HhLfRh5jgKRaV7ROMPvzlznHF91OHt/7m+96pcwDDpo=,tag:StlzhJ0ZlUOP45N6sJHVmQ==,type:str]
    version: 3.13.2
