apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin
    namespace: forgejo
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:ycz95amh,iv:i1AwbXYFkxoz2TcSFW6nSB8t7MeJMMv2tK5FV+ORdvE=,tag:bZQ/HVWYeAC7n36F6TN8/w==,type:str]
    password: ENC[AES256_GCM,data:cbWRw+rjg+xTn68NFhy4dqkFOrCA1UN6M0EWZ0QeVhkwXNNCDnmTHw==,iv:Lg8elC19rF2qgS442mg7Kr03/XA5/OdXJ5VozKuGNhQ=,tag:G1YGYABLFZ4jesRhuabtAg==,type:str]
    email: ENC[AES256_GCM,data:cqPMAj+ken873o2+idw=,iv:R5tkVHUAMO5HZk3aha4lkE8OZjmJCyqp8Ziu8BXel3o=,tag:JwbXubzvuWWYUyZ03KSqRg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPOTl1RDhQanhabU5qTktR
            S3VLMEM4Z0ZBby9rTlFQWS9zUlA4S2h1amlFCm1OaG9uTXllYWlVZ0VnQmJ1YSsy
            ZEZWekYvWmdqSEc5MTlhc2IzdmlIdGcKLS0tIHZkVXQwMEZCSVhXaTFLSXI5WEVu
            MXFMOTVkdEgrdDBiSmdkeUVkazUza2MK4VUv0gvmHXfR7eRA6R1CRw3lSs6hKQ3N
            iNAKQmks/qY4W/wy/mMxNbmFRHpEj18lu1GyXKqPCsejxowzhKc+Jg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyYmxibDVRNlBWQmdybVZE
            MGY0ek80bnIxREpnb2NqVHhQQWlpaXV0OFZJCjd3NHB6N2NHK25zdEsvb0ZPRUVq
            dWhZbzdaSjJRaVlGdjNoMzAxc2hQOXMKLS0tIGZjVkxKOC9NcnhBREkxOXZYU3hG
            eEt0TjdubHFKVTBvbWdIZTIrbG0rV1kKxiyq6ApehZ5TNctxAsjP7+l/y7ZIYfhm
            zzspDGaPfws09tXCTO7gpnQCMdhO/QyL403fMKc6jezXZN0Zt2RTIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T19:43:16Z"
    mac: ENC[AES256_GCM,data:yRsC3m/pvQuG60VXPtl+bXi9fr1EhPapjriN+Te0lE+bXpOnmT9am6O0ZjvodRQBWa57FogEZOVwUVsddIcusu6Ow0TDD2infoGRoFOtVdq0ekX/PsnoMmlHdNsmx7ffdy2VUOPYvAXpTgQeLV6eXn67OJJqbcg7YkLLFNWnEd8=,iv:S0A0FvaCbrrkhg/p7iDCUmNSPU6DeqkDTmzndDyHK/4=,tag:HqeBjv6xgpta4tPSoxYA+w==,type:str]
    version: 3.13.2
