apiVersion: v1
kind: Secret
metadata:
    name: forgejo-postgres-backup-credentials
    namespace: forgejo
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:6gm6PV55FgvWX/ONx/uNlEavmBg=,iv:OQosy83rdI+mtwZCDNwIuV+L/x7jWv6KSS3ANMq+49I=,tag:ftP5+cLYcp1XG5CPwAj9aQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:lgyQnqhyC/6bpj4J1y1XkVRo2KUKxMgU+NGi7CufM1WixdJSOSFoWQ==,iv:vdkomBlQ8xae1cTXlrXkhDjqrocpQ6naGTK94wuVmAs=,tag:otQsxGzlmpp13jqx9m3ckg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:kNVLqTgbhcYpUEREU+oGFrZJxgSeudo7eo0=,iv:WlG/kKfPtqQCT05cvZuBvAQnb3UmJNGuyDl0G/VdaT4=,tag:VE1qFqkF5CSOnpyqp3mECg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMWxvMXhLSTNQSkZHWmNo
            blRrLzlSQ0d1VWFXQjAyR1MvT0hkRlVVTTBZCkFNOVZ5YlRqS0txZUR2M0xSUC9I
            SDZ6c29BZVZKY1Nsa0VMZ2VHN0VMMVEKLS0tIHdrSWJaclpydS9XNERwL0JPeVBF
            eWpMR0FhcS9GSTVJUktZb1lmejdyNzQKIeSVJ5noBo/omWCH1Nla8S9gseAl8fu2
            vi5j4zmdh1qFoUqtDPSfQ8Svucel4odLXWSMsHALAhZBegPnfpQ1uQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCM0VrYVBVM3NNcmVydFFH
            YmdrZnFnQ2ZpaXhkVW9GZngvYUR4WmRPTjFVCmpXVDg2QmIxR3liK2hUektBMUZS
            Z1JRMnRrTm1pNlRBcU9xTTlqVnVuV2MKLS0tIHUreEpRaGFVM0lOeDBEVExOajFX
            Zk9TTGRiRm43aktuY3lYTDFCWGFZY1UKIAIQiDQkSZty6F3JgNKGEcR2njPOk5QA
            7yQSovaiRduRjBEvm8tYqUqcj3d03wbCWAJ3ACxF3IkOlS95V+L/zA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T04:59:17Z"
    mac: ENC[AES256_GCM,data:34qUfkrIrLo/sqYmqXRqe/ON0O2ni+0YzOaBWm5tFQmIxdABHjVILfutHPCJ3Hs5XRXNThieNsf1vWv0SJcjAhBna5E2l4zEzI0lPI3GvpYJkRKyiDxgfQ+N3WOtQBQQJFBpW5aoRYGzhLkZCL/MBngV6QG5TwTa7WN/PDanj2k=,iv:LE8LnCAvSHbwwcwNx3uUxrcuhqWqo+MuWUajUNL15j4=,tag:eW8mnqqIDHy1bOEpjeERqw==,type:str]
    version: 3.13.2
