apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-token
    namespace: forgejo
stringData:
    token: ENC[AES256_GCM,data:V1vdKiFg3/SuK1QPV8kRrYy0K+aBzhvE+txsQv4yX+Vp91Oom3h9BD5qnA==,iv:0U1yjUjtLg8fhI9yb261Uf0drqGT71vXN1BcjeN66HY=,tag:PCoAVzVEopH8RpzXZfkX9Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZ1ZYNGhjaXBYcHlBVE5r
            UVlHQ0lVWGNzZ1JCUmh3T2xEM1JkS0ZGampRCm1sNjZaMEJqWnFWK05LVmFUZG1O
            MStWVlpmVjFFaVNYcUlJQjZuWDVQWm8KLS0tIDE2MzFpMmxKaytKZnluUnFwbkV3
            b1ZqM2huVG5obmNIRmpHRi91UGExVEkKqlgUzFn1d/cATXEOgfLZpAjKZytq1Ik3
            HBcpng6cGf14xYBKfWMeduhly6AXUNPKTFGK9x0FjFz9G1w6x8UW2w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybDBMRzl6eU90MDNYMzY3
            K0h6RkowaUdVVlRUeW1YaVVVSHA1SUhySEJjCi9HSDBYcG5zMGJESitwWWZhYW1T
            aXBjY3ZBUThweTdSZTdvTDF6SEtHdmcKLS0tIFZQajRncHUwOHhoVVJLMVFpTEhh
            ZkJRZmhzMlVleGhrcytLN3BhQnhPZGsKQEmy4/xPfbZUX6pjJlcCnpq/jJIcGXdZ
            +GOltSqOpb+jh8cy3IFmYrAOJTPAyuAllGOnN4jDeviZ7pZqa3++UQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T13:00:38Z"
    mac: ENC[AES256_GCM,data:9Q48r4JTQHyxZzPoA9HL1rnrfKgE0Jr7e0/lDHeYksecgdMEhm4nZo8QYBn1NsjtLDblFuM/jkK0jFHdy1k05oCPHjU0KcX+e7UL2MWqToGasEh1SVp8da1CLEyXGbYcFsx9ySkTFZABveiYc5j/vhEINb5uarIRo2oy2BWvamk=,iv:K+lfvkM9jmjiNQTZjE02CP50tYmLHUJ6MmarfeANpiU=,tag:FTwRqbOlHuz/8TxW3IDQcw==,type:str]
    version: 3.13.3
