apiVersion: v1
kind: Secret
metadata:
    name: github-read-flux-cluster
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:I3xBvxxYYo2lV4V7N7c=,iv:2gPocVma7ldCzU65bCqYIYZkLQknYK7Vski16tKsIWE=,tag:nYx4e/f4qq2sYQZEbpnlxA==,type:str]
    password: ENC[AES256_GCM,data:+IEfijZOws0m2SjvEqMC/RVbrjrDANVbFAylxaEdr3ms1+V+0ETgGVYKvImdqEaXTR04maOYzer3qt9wirEu2gz7tjSFu6opQDHqWgaXBskh5QDp1y80fTXQa7MV,iv:sYLpedbtoPw+DkznrLwjBTDrq6fvoMfiSny1dGgvqSI=,tag:aq+o/BxtNvCI6jR9NH0Ogg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UnRoMjZsTnRKV2ZrNkQz
            YS9seUp3bUhudFBxdjNJRllwNXZPZ1VrUm5zCmtERnJXVEpWZFZRTFQ2UXdTN3NM
            Si9JeWQ3Yk94c2dXd1ROSjNHUXJ6aGcKLS0tIHhVVVI4d3I3NXlueEtJdllVUkto
            MkRwNm9jU3JDcnRvamJpVkdIVHJRcXMKKhQI7LSIE5Xis/BhS+Urked8KhWggguk
            FIfn7x4x1Tjy86VLkH+wNZRkAmafx5mlwRGADiG6OktNXACALoPN9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdXRZazFPazlkYWtjaVZ6
            QUJNeWtnRzIwa3VucXgxa2V4NytRK1lxUlZBCkYxa2ZlL3lsMWRGTkkyN3B6MWNE
            RkdCUUxWYWpFUEJkM2xJdE5CbjdVUGMKLS0tIFRnZ1pwdnltaDdqVjRETDMrejRo
            Z0hIdjB5Nnd6cjA1NkZWeWJrc1h2VGMKxXu1QG24qIpYOswcD3QbtbkA8gGxX56V
            DCQbV2u6bXj7FM5lVF4OmZC4SqCrLucJ0h5bj3xFxrje2JfPoR5qNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T09:17:05Z"
    mac: ENC[AES256_GCM,data:mG/RQ740veej+n8sgs+8MX/k1xTzHMPODvV1HVGazpLojC2RXOtSO5Y7aUEZuOCpfiMCk1EKqUMnZxOlPdhm1nrvmmxOBEx9bxhVJeML+JHCf0/pnkccO1BVvXV2tMoi2HYd4wpPSUMmA/0S5cz8LxK9EG4np9+RgenCdp4MJy0=,iv:KdHFE74wakKBOanFODwR+RrceYrVq6Wjs+6nN3xr6JY=,tag:zhpmd7i2SWbCa/B2FAGFNQ==,type:str]
    version: 3.13.1
