apiVersion: v1
kind: Secret
metadata:
    name: github-deploy-flux-app-media-prod
    namespace: flux-system
type: Opaque
stringData:
    identity: ENC[AES256_GCM,data:F78idXljjH/7oz5y8e7oyR1htGYxJiNUaxXoMXg1NKBiEcl2ZOjzYGMj4rc4Sg7If1L6wykwIZlNW2vTaZEH63v0dL3C/qHOKanxnkg3CDf2KOklcoRwaxfl7efsj4X/QoIUv6qTToKTR4WCFiIZZYF0pYdSjajjRfH/Qpw4QXD/UUJhS+gbinat9HeBqs8kN8CjDBvzPB5kO5Zs0qfJeuwBuHi2JDH6yCIkHqMsVTK3EyvXNQAMMVR4M2FLLpkx8jVMm/wpmTP+31EFTu45jOiPlUlrYnmgSNDM3L9LD3+vPMIYimsu+fepgGg7/bi+ZGlo8iuP/AREyWw9BPIrcfvmgFoZY3opsrUgkwBWzacBk6gsLW8tWJU7uCMKZwJvaWQPU0EWMSMELxNkcq94IepJQM0CAzBjeZq46NOktIHq5PR5efa/40DIZtC6sHx1Rly976kzLp35Ar8CJ7N6+2j05mm+sIYGHoVqJERo/hn2z8tGyIPM7pJeS6lv88WOFUwCsg1Lk5EBiJzc79ouFNrTfnLfMUHvL4xfNRWsc/lR+bEu53kbjhjS7iPyUedDGBtMx2Ft/jZMSVUb,iv:LXBJXXi8k+lmxdlKK/HZD79WTvVi0pCHmWoEkAXc71U=,tag:DYCOx3DNbm7wziW/W+k9kw==,type:str]
    identity.pub: ENC[AES256_GCM,data:lw/1ENJFD3X8at2wkqDuD8iMv0BZygRf8bYUCkGfvGbd/X/49DwHEwO4BdVvzcz3qOkMGMcpcn5yyQZgrfB6vyV3l/qpJ/tdEKFWpEFx2mwNBMDDtURQNrUgPqzTMajfreb+k3vf5h9rxaNeGnEzrOYI8saZiU8wQbqIAQ==,iv:14U4ZH9HKZyfOtqEcPlajaLjpXeveVQ2xwFeAmn/q5I=,tag:KRZARsh4GQv/hJKcXaR2fA==,type:str]
    known_hosts: ENC[AES256_GCM,data:8Wo5R2jZK2g64MdeVjbd+5y14Yi0XaUlwU0vSdx9LVwiKGD6qDgYLLiHOYejkrz7s3Y+s46mtapUQ0VWPXb5OsOP0SA/rGdwbZJhihqfAB8aNtvePKkzFPrWKAFNC0a51GrUjsQAHPN9AeF3TeEYjKz16umllFCNJ1eOb1xc+qbFcJRvycy2vKQATwvhGE7n1xIfCw8ttbLa5q4edomXMRQLfs1BHJbq78Ra9epUhTsBWZCMFcyEHdCiHrx2S6ABYEmcJDlsphm9wOMJ19afnAZBX+BnYtdloV4PsXhCiSpv8Wgwmo+z+mMAiTZWsyfReXcGJWG90wkkPNvFYR0z3erdF5n7RyZJv1tPOH0MOvF0lDfGybyG2jisCnLLvwFLzji5HIFgWf+bizFou7s+WNtof/pC8X4kjyipk91l8PVUwvaxhFLcnGU7dy0ykiak33igx4KjmeD0HrbNA3sqX6t1dcpjjmCiw9bQ84BHCXHtU7iXHolWuYRMdnSHUzU6G/c0LKlxW7anhAwqQwZ/gmqr6iOKHDls5lsRziwEbQH1hSEjM/n44va3QavJqg0/nyfvt5dFuxHsQ2/+MSwqPvkkvnWaGF3sQozGH9kQCSmZMsEt99DaJGN1iiqdqYlhQ3rphfh9ShfGNglWLQFcqatPur7hLISC+Mx+dHKL5Lndb3uLlst2xmSV8+8PDc2dA4r4Up3e8BOKEkXURfreeH+3SA1OD1dJJcdYyUynTy6VexGv7JVf+iZeT6sTBPrF+2rKYSxZDwF0HJyCp6PREfU7fVsi09X4jPd1ljfkfvUtwQiOEm7YBY71QLfD16u2gyibeAkOttSKdoyNqhg3ip4cM7imQ92l3RaaIaovIpMcdie1pDmYjsYTU7jo4h2nmp4iIZddlKbWSoeLV2AOIm3HShfMQDA6H5VwCdqb6Y6Zk/tA5zLX3LynnWa4Nwc8RSd9GYUKYZNc4rYAOt20Cz4PkJUp3P+s/kPlSPaY5f61RCTIxZz6cMYzahNCc/UEhxzt3MsTK/HDeJXGHfaNObKza/blaKdHeft26IA2Rfd2AKsnkN09aaiXPOTvFaVTYK+eptbnz+yk9A9dqwVCYi4fTkkR/78bRuX0KaoYRqOnvZQVuCqnOihwWeFel//VCKg9hpkaWJjDfZQu1RM73au2YU4SjhcVsZk83Bj9qAicwQmxx4NCfxLAEYx9v5F7UPIb6Zg1lYlO0mME,iv:+9UQVQZ114wG3WRDgkA4kz397LGhS+X2ZjQdDKWMSH4=,tag:t3TwiwR5cb9Cw5euEOSxrw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbE1kR0ZkZkxhYmpuN3hR
            N0ttK3NOMVc5VGFOZGx6R1B3b1NkL0tDdEFrCklmeHpTMzBPU3JNaW1LcVUrTkFz
            QWQ2dlF4T3BWd1hhQVg5Z1BXL2FUZHMKLS0tIE42M1FRNFo1NHhBWXUrZVZrYUd3
            c1hjOUMyWmVVakVtcVBPa0lJVkpxZE0KUIzTPw0QotRmrFkX7xDWED69vGArTv1S
            g2pctK/KOL81fOGK6/NC3LKcSUfPoVYrwgLNPOI0+9GVHNgAc3CrzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTW9odFc1K2lMMzh1cGJt
            ckRMRk5FY3JJWWxFNHhQcXAvNThVaG13V1hRCmNVdng5MXZKQWhpbzNpSklKRXhO
            TXYwRjUyZUZjM29wbXAvWlgzZmJORlEKLS0tIFB2NHN4SXNkTGNaRHFwRU0vTFR6
            WEdQNUJ3V3VWb2RPdlQrS1ZvTUFwWWMKSlklYJ4n+ap7lvm/gE0ntZ+w+WQuwX+v
            dLsoPGflcozg3N/B4YpZfOZ4138OFTUDWE85xqe69nIVjgtP3FUNPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T06:02:54Z"
    mac: ENC[AES256_GCM,data:a3LLRq5jWJuJV9FN6i7h5puwJSikqbQbQNZMnaS8L/P+JkoPkhTSbKDHFa7lrs+cnG187hqFGC/h25eRrlYsFSVPZbTZ5pMj8yDt+3MsaO/SYaX2gKV6MG2QLOBR8XWsGpiuVWoGLEjvQ0gDsdEeVmmW/2JFWbiy1xTZx/1JKZ8=,iv:kSTqjdCC93WBdtZKNxBgGTXIkCpUMIZkquZ6czoy0nI=,tag:NrFOIHs10AYcyGkotTHeDA==,type:str]
    version: 3.13.2
