apiVersion: v1
kind: Secret
metadata:
    name: github-read-logday-prod
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:TUwq09P22oNa1mCWixE=,iv:SS3YpzkUrRcNLCT9GdQr+iO6kDXu+XYAHZomGyGNFPc=,tag:QV1is1lYkGO39AYWGt6D4w==,type:str]
    password: ENC[AES256_GCM,data:CIqeFwsWeU6VfQvbsaG3ZVsmD8ipZErQL5CsvxhGid8dOdiwpDdu+A==,iv:AoN2hCFj8M5l15Kzx1/SOUoHlIwt6Yfn4A85QH+obGg=,tag:3nxy6h+ctOETOSjav9FNIQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpcHlsQys3Tk4veW9lMWlU
            SFlyVHpXdmQ2NERCWG1HbHVtbWM2Y1hCd1FZCjkvTVVRRVVzQ2RYWmNrRWZoTTVE
            SzRUQmRqMTM3U0h5cXNvV1YvM0tDTVkKLS0tIElJWXB4d2lSV3MzeHFEZDZxaTFY
            bnhJOEtTUXF0TTVEaGtTNUwrME9OMUEKO8y2OWWUlQ3Bhvb7FoVjI61RXcVihiFl
            jDGcJLGHeERMSFmkGUqy/xrzxoL++xCf2CEiEX+CWlt4R72nJQRy5A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwV2N4NUdJVVovQmZzR0VD
            U2w3RXgrVGdiWnExSjR4NHFFWWZXQlVUOHdvCmQ5Y0dRMFZmaEJRNDZENWZ5VnZ5
            cGVWSFliUzNPMXdDRDZZcTZwamgzMWcKLS0tIHVaOCtORVAxS2ZtTm13OUhySjhZ
            N01ENTdaN2p1K0F3T1JvNVhFZjlTNlEKKUpsd6LvqQRlfdKJJlmhgGce/BUp+8WS
            1gcP4ko27qdnFWkuX+ysDRg/ESt82r4ulZG6ClKHndyHGMGBsfpmJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T13:07:53Z"
    mac: ENC[AES256_GCM,data:kqbaemKtudQMF4phmHnkzuXTcqD2CkqiICMbjN2q9DscVEWNhJOVa/CbVhZLI3H41kuR+D5qRFKlkPkmo8GU0zB7Yr1d0w/OCFmjI+v9B7t2+udKpzFpS1+LrJ5eqSkmdN13Ysn60qUnS5abJR3Suidk3pZpSvEQpjBDLgMkg3U=,iv:Kqmny019zdiCVbN5YqkkXblabWLBETY1ijWxuM/9N1I=,tag:qZhdU87zq39pQcwXWvv6kg==,type:str]
    version: 3.13.0
