apiVersion: v1
kind: Secret
metadata:
    name: github-read-flux-apps
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:sEOqR/3YVHnJNbAAmoI=,iv:1YinVqQQPn5/Q9I0VE2QNB3muRbOGiYxSkgEoDtDvEM=,tag:DIQp+tEDxhkP6SsTuLwsNw==,type:str]
    password: ENC[AES256_GCM,data:D1Wda8gLnoW0028e14/iG/0sv4/zl2d0idQEc8uyREbl66dlam3OFk1WbpKe6eYx0I072fEVDg7BjRsiDVvxoJTUyNORuZ/5Wpizyv+kulYPD+SuIuGTJO/uE7pW,iv:MSlG17HXIsKI6kt7oEO11LkyyWO5G6OPYrIcr6VVGu8=,tag:5QzgGuAiWHf11iW4io5CRw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcW05a09SSHZFSXRYRzNp
            T3F4aHpLR3ZWUytZYzNpMFBNZzRkRENWY2gwCk9BSGV4aTZtLyt0bkdQVjlhU1Ux
            clhHdVRka1luenF1bDY5OHBFZ2ROMUUKLS0tIGVnVHBYanJBTEpnWDlHZ1pUYnhC
            L2JtNWNYL3JwdndVVnFscWE2K2hOak0K+lmrZQ8ttpYMvFu3yB4Jm67aAG/9AV0a
            MisOvsxTnHe4UfQF54dgCinD31TI0iaIPSgX2RbwXpOrrwgaM91ISQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcitXVnJveTB4NVpmblZU
            MmVsUm1tdlY2NkdiWEJodDZnajdLSWk0cEQwCmJUV2F0dXVtVnNpaHBjWnZHZDRl
            dUtrTWtKMExqcFdyKzBUZFJRTHlrSlEKLS0tIHh5cUJzQldCQll1VGpYMDJsbDhz
            d0ZBeDAvYitzNlE4OW5wRWhoelBscmMKP/oXW1SYaSzDu7NmZw5UX0rSboJP1xS0
            dzPDEPFg8MFtuEu0uqDo/bL1Vym63LYHfZpZ3nEgxcCusiMipVA86Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T09:17:05Z"
    mac: ENC[AES256_GCM,data:0rsR/a4hJboOpGpiDIKJafilTEM9uyBIQjboeh3LPRApddu6/VjeJXGwUyKEL+EyCoPmDiErf+DQz0TtdwjZUs0ByEGzz4at/hsyZ1b4eX9ZBMz/ULNBEbwWnXirPgiY91L4OH1vkeBInrPovCulgIbVAOQGYJeoNUSJRdqyTyY=,iv:eov+w9rkY0Shx6/fskBqmuQk2DFRewm+zcvECa/2YVo=,tag:pEYLlj8VBh5Pk+GUJ2KtAg==,type:str]
    version: 3.13.1
