apiVersion: v1
kind: Secret
metadata:
    name: github-deploy-logday-prod
    namespace: flux-system
type: Opaque
stringData:
    identity: ENC[AES256_GCM,data:GheDR0GDgoJ3q9hfwxxd5RfSdq13Q9vQNcd9TyWXxfzhqKtxevErfCk6bdZGwzca9zoaAF3fBOSYvfOU3+Hdw70AL/8YrVAw/5lDiSuzFJa9oon2LKYtdWExCr9oR3ASgz5VNj7c3wNVAxsuSVs4laCeNOWeoDQDVjThIJnRJrZpUldq2FpAIRHSd/apk2b4RmFtdf6Ob1k4yMLfz/80nojsJ5uSxAp2VxWiKW1FEemTFtP5D5kHf2ZkWuVl+bUIwmfLTR8mfNBEp0Az/66AGsmkNyeOvYuNhfBPwK4CuSVa+p62tuVEdYqMLrD39XVUojRoQc3YAz9SDtcsyoY9Bj2uSTc8CHpfhixymxmqUoOdeOTwYJ0S/E+TOidLqMVatMIUShLBvJdvt2ieBXGS8srH15hwl2kb1MY6BIKpBE4KZ0dMXnjQgAJGi+PTHjxpyHsP5L+iQ1e5yvK9xqpA0ch1TEs5xNvaKYb9Nb3Qjcl9OVCs9tr0FPqlJxmtIQ7x7unNnkUZSWut9ztBWqWho9lfShnUH9o7a60S4+18INIiMkE=,iv:+0SwO2TGa1ihmywPn9F71TtxRJBZf6MKmchn5ebM6J0=,tag:C4W4kCKoGGrAbtax8SR3MA==,type:str]
    identity.pub: ENC[AES256_GCM,data:lnlcPD6Cf4kqxxXk45cDvq0nrKHm/y4lIrN5doTZvnciJIcr6WFyGJ8RixegPsbteeOQib9yliERoYETYI8JEt7ILXPlDw3E9rCe+a0fpDvJgKT1BwVyzaZkV4uyhL2Drx72+8rhsrfVzWY=,iv:fK1R1CYNZPUDTLzl7V9UkNeOBqA/WTAcHOEt4RWT7KQ=,tag:nhFYhsA+H7y9Sg33UB7pMA==,type:str]
    known_hosts: ENC[AES256_GCM,data:AUAfFrTsxSrkEkh8is8Hh1b9ZIJ1zv9msxmQTh/HVeHeUOhl8z6ujPHQ+Qy4N7ZJllTNqp1RM3wRJnee77/0G1gQLyH1bOXx69j2JSmjF+heU34MCRsarItsZ42DW5YbUVvY8pi96cgOfK/JIb1qmyMkAaabKgyXtZAGaAymvzxyM695ZZq5LYxZyoYf0mpntX4EoGWhmYojpR6Paiw8FtmR/cf3Rhxj7VQLhydjjsCTZlQnXWye1fU9MrBLcWsJQoj36X/+gEO+IhVctZmiySHiM10yswyideEgZ7xoC3zNpVf9OE+SLwLHCMTqUdnZWYHSSTGgITpm+RJD7tA/0NnZpj1tOyST27ESsPPzAmHytYU9L9biMX/RU3JldskbCvV39dk5LlzA2hhvzjybChV3L1cNCjaZpKiujD8R79D1Z/yKk3xU4B+8o/rkvWcNXFRaKaV2DiLebZu961SnJIg8bcqwLn3tYojTqrC6l3TDyE43YArT+T38e1Ov0fiUaNImLUzu0zIA0qRY2SVRGLHofb8RTyXwxYDmmbcSNM9eeqh2afcg3SHDCBEywVxEwx+ltLyyybKseretbiexly0geKEZ5kQNT3/ExfYXrrtw8zGr4FTMB1kGf5aIK3HA1AxZaKWtfjFHCPOVXc1Hd5Y09SgZ9mLgRvoiAtPPNkA7QwoSRtzF0K3T1czyMj7/sLm5I9hEldYzzaA5WNpcQkFQPT0lAWjHNJ3UHjMZFEP2uiBFgSMbr2/JN8s7BhDpkPsohK12sNn+3GwgTe8wbLKyI/tm/firSFhcN+0DksvQcxnAQMRlcGpV+Yt6ZSxpoH7Ys4RyNR1RqkS8KW5Krhat/UHRW58uY3o6aRAoACaaWT/OxXRMUXQ3GsU/u4ZAGwrXYpLjfiZHKKzHk10lWJoA0FFGQFyZciue1vP19KrBWKeF2ccgA4DB1kD08grKEStZDuq4jMKboZtuD4tWZIdni3wdfUDYp15jiRpQNDz5XZkISwsUwLI7BoX6YSreSMhq88/eyU4q/QsKLIezFRz7SLqLwpokjJT9Esm/GGMtjIjZwtDx4IivQ0/pCuKHcF5/lrmi8PSN4Epi,iv:LM7GplGIYDJPva0x93nnbXjNCYaE0h8/QKR4N6H5+2I=,tag:TdCHhfGXnDZGc/EA7SBUGQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cTZ3NkdId3FJM2t0cEFI
            SFN5TUxMRkV6cEw0bGhEek5jSXNZS0xlQVRNCkw3T1Y4eDRycmJZc3lyL1NyZkRG
            Z1hMNitXVm1YY2RwbXRpV2R5S1k2cmMKLS0tIGc5M3J3VEhFUlpDSWRLWHY4b3BV
            a2R1NVNVZ2ovcTVXUUNkdlNHdXBmeFUKAd9of7Zso2u1FrGMnbwAB/dIj8Q+dc4k
            xPUsffDI7ItDbWyZ8kLQa+0WUeK6VJy3mWjMv+wYdOrheZStuPy/NQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMEU0c1RqNG5ubFdXS0Fk
            VWpwQ2l5U3dVN1pUVlJ6QlRHMTJzU1RBL25JClBrVU44WFlTMW5nTXlXYXA2MUdq
            RTdPT1lHWW1DZGkxRnJhNlRVUkVzS1kKLS0tIHc5cVplN2VBcFJuZDZFKzliS1pF
            azI2eXhJYUxMOHRMckNmN0NoZUx1MTgKSuFO5BCARTS+/LNJsGwDOahvYRTOuikr
            UzIN59AcNFgCjpMrUlIP4H7r4yxEtwuOsCtEXDF9w2f1qU25KbKCcg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T03:24:45Z"
    mac: ENC[AES256_GCM,data:AMuvYQZ/RUjS/72HFi7QVjNMc5Zs++It7jm2ArJO+7nfGDKtX+MiXA596Ys48xR6n1szqLd25ajbNZqvWkFs+2JW9GQ5eU1E6niCwmOyENfMrqwem132kt5p2k9l4DAV38QYbkJBaHLHemDlXntNRftgLAipgeexfTy91O8eRlk=,iv:p+2uIiBZkrwBWDR7LCYkca9+gfXRRvmF3Q4OLxuzHtA=,tag:cfGtpz9kTH3neqznOm0ZGA==,type:str]
    version: 3.13.2
