apiVersion: v1
kind: Secret
metadata:
    name: github-read-game-tf2026
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:y9paawK5ppDtrj8lOJQ=,iv:vB1oDHSp9XtgIjW7SBiuNoFBVJbKzPjI9oOa4ne66A8=,tag:Nm2tegUMyEfKLkxnymbo5w==,type:str]
    password: ENC[AES256_GCM,data:VKkNWivhFcS9kzdjNYp6YoD+id63mxGHl2KnQqyA89T5MRAFTcyvWBB1B0Q89z/P75Rz0sr65Wc13hHYIJ8+spa6e+f+NI1SAVZC3kIoEISGJMN2LYkfYfwTbpXF,iv:bxNx+CYJjt7Mzi5VyzdASGKXQu8H7j9AUaNweFxe+yo=,tag:m16Zr6ts2kLBNP6Y6Drx8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aWJDU3BpeDVreHhUSjNx
            ZEZ3Wmg2YzVpdUhzcFNOTkM1S0MzMDBNS0N3ClFla2NMMndSdXYyOG12OU00clB1
            NXl6R3pvVFJ0U3lxWXJyUkpMQmxrYUUKLS0tIHYza3lPS25yZUdWTmZPT29nWXFv
            L1dHQXlkNWJPTW9Jd1B1eUpDWUo2UW8KT+Fgurt/KYSja7Cp1tCOf36q4cs28/uP
            NKvEZxmhBqLNs/FBy06B24DvK1u8Kz1YSX4IpoRWtxfBRw8AA8TH/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVGtHaUVxamV0YU5QSE1x
            dE1ya0ZkVGE0K2UxcnhzeU5kajdpTm12M3pVCm9aNTdYTytQOTFNZDNWNVJsSENr
            MWt2ckVxazNDc3Q2ZXB3ZDVOaUwwVEEKLS0tIEhwUmFGbVBiN1Y4ODJ6c2xiMHBV
            VHpTand3SlN1YWxQRDdxNFBGVUNSQjAKzXcHMBmbkfk7DkopaN5c3O702c/2x501
            iGNxCjjjCwDDGc58eQzzN2jMrfI7BAAPRde4vhouJG1gJ1qmeqcIWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T20:21:54Z"
    mac: ENC[AES256_GCM,data:uv9ruTqXu/xeI0Q8neYHK8039RxydYRWr4YcmUDVoKqCuJCTA9++qpN56uGK8ni9YjI2gkisUqETmjfWT0EwMG5mBk3VWXdraaMNYII+mKPfztXiw35k2F7Wbzd3an88Zd4XMu5jUXNUwBWN5jN23dOGuRhvXvq04RTuXjV0mEc=,iv:CIdVonA0nM7Ev815IkeoKYnPKEQGAHfgl83L/HIHi7c=,tag:2c3qkoh1A3jfMZ0DcMX02A==,type:str]
    version: 3.13.3
