apiVersion: v1
kind: Secret
metadata:
    name: github-read-logday-homelab
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:KPoQGdqd+quS1xWJ28U=,iv:5remHIBIsgcFknVFJbkTQahPRJP7DXc1ICZmfdNChg4=,tag:T/MpuxuH9gsyMuEWcTkJAw==,type:str]
    password: ENC[AES256_GCM,data:OHTYU4L+9+fiRdOwew4GdsfL9XhQvBon/IEupuM6g2UAM+KoxM1ANho03LcjK0cF7Vu39UEYRzPMNQOotiKm5nHbWHynVNKMK8d1uJU1EywbWkJcEIrNFWOk7mzX,iv:LJoG/3y24sJ1DruwGTDuoJgiPVnmGE9jaiCMMa7j2qs=,tag:zTvTKghOx7mZT7P+5Pu1tg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWHJNTmN4S1kyR1RvaStK
            ejVQUldIQmU4WFlzSGk0UmFLWlYxZDU3bFUwCi9XVU1yQnpGVnZ4Q0Nyc24yQ3E1
            T2tKSzFNL0FscHpkM3hEMWxxUFNOQXMKLS0tIFF1TTcyWi9YUjA5SDRqN2dEd2Nk
            NEd4NGNRaCtLbG1RR3FSaWdoM05JczQKoy7uvxxIHHYsQbwEKLEl1bJC74HrHDXH
            LhnT4kpZc4z/fttEUFEq9Bywe/ESM7QJ8S4xMdFGmVoLaXr2zMbUOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TlpYS0RwV0ZuYy9PWXdk
            S0NCTDlUcjZiaUR5eUpsUkhIY0czV1J5RkhFCkpiU3NUMlZuVjFTTGVweUlUSC9j
            dWZZampWVUhJclJMTk9EUk5VaE5ZeEUKLS0tIHFNMzVGUDhKNXU1ZDRBWkZuVnhO
            eENRN1Yxb3hNeDFYMnpOQklCaXp3cTQKC2HpNCSIcGiD4uQTZT9B8Bzp3iul+Fvx
            EciMrRSNfhhabOM1a/j4oDmcp3IB7Azlz8f4zPJvUCjOsfw8IVZYQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T09:17:05Z"
    mac: ENC[AES256_GCM,data:FwWSgKTkMAp3RLOpXcUecGfGWVe/0jbsrhfNo88yJ0iiYTHG1gNIrbVh+uGmOdgEXpvw/cBMwzCKEQxa9rQDnZ141rWBLs3bW3d8O8txrn5vLH/U7/S/fifugC+gtZJX6WDM8jtpqunP46XqB80BPfOusEu75DWgvNqWJA8lVDM=,iv:KxxkxnsdcOSMe0b6VqFW9ajl66VVVrrECbkJkwVWEBk=,tag:rNomv6ZqQnR23h7vQXAORA==,type:str]
    version: 3.13.1
