# GitHub PAT for flux-apps repository (HTTPS authentication)
apiVersion: v1
kind: Secret
metadata:
    name: github-read-flux-apps
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:+F/+v2chqJRGILJAolc=,iv:SFfluqpx2633IiqLOzu5QrgeGVyg5RG6w73Nqj7Guwk=,tag:eIeKpwAkIjxnhsRcRSHkvg==,type:str]
    password: ENC[AES256_GCM,data:bWJVX6xMX86sp8c7MQ+I0RBfPCm+tbfDzow5zA0yWula8dH4p/+NmhEGxR2vY2HmCzLfBL7EnQVipMXybJSEbg6cxR/41iU4NeVGq0wWMUia4MN8VlAGG5d8wGY1,iv:0aZWqhPTkmA5OqSo4mrZ1uXP64o6Q2d5C4RClNTOjOw=,tag:egHv5tPAyKE8hilMlTdZ1w==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUR25UMHBYU1E0Nkh0cmtq
            RjhyaStENmZqTG5SQzd2cmhWU3J4Z2dFV0hvCjRJMmQvSEM1S0VvNWlMM2IveEor
            eURHME1DcHNQS01yYlNSb1pvRVdRdmMKLS0tIHNBOGp5eFpBZEVPSEJrbVRPbFE1
            a3o5YnlWU1RubTNtMmdKRVoyc25WL2sKjIWP7UyLn8h5BhD6qlEP39AzQWKo3bK0
            BVvDrVRCGp+r9N8WNzJBWWaeU5SK9RdF7k+yckZSJIrsADSQqAUWtA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuU0ttT1RoeDRpbXJMN3F4
            MFJvRTRIL3Z6ZUlkcG5GME5LWnpMdXFNeVhFCkxnNWdWREd6Y2JSbGdqenloYXlt
            Nkc4K1p4dVZ4dGdGbkVENTZFQVJQOEEKLS0tIEdiaFpXdm5oWEltOGJoTDVVMkFP
            YktrdUlGZGpoR0k1R1FJRUZoRDlocDAKHWIFndophn/jcHcykJSPejVWeZWYnr8q
            YeRnKyjKDhBuCW3c4GvN3jIznoyGptEeXh8xfnvfG+0+xymbT4o7zQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T04:47:30Z"
    mac: ENC[AES256_GCM,data:EGC0eF/VKPYq+70P1YioscTxTCgozTWXPIngB7nQV0CvWEFPJ2UJuV26rYO/U838r1rDc8G4AcmEZXI5ZowEHu74jIRIKj6ho46FSzMYPRCAqIqe4itDaESlq8Koe8NqjJr1hWAI4Rm8q5dznbxs51X5nitfPetTRM9M8mX9OIY=,iv:PdT+Njn+kRvB9TUeiIXCeIYG9IMNqUa4n97nKclKckM=,tag:vJ7EfKkfMU+yzM+UKf+drg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
