apiVersion: v1
kind: Secret
metadata:
    name: github-deploy-flux-cluster-prod
    namespace: flux-system
type: Opaque
stringData:
    identity: ENC[AES256_GCM,data:svwJCADQ4+PfyYD7VqmF7jn1RFZZ9XPmSXo2S7HNi0yz9HeqeG3Pt62W1lJGsn+Jdv8LcHcB7Azee0G2HOJIqBQ+GBtWNDuBKH7f8odVz2hZpqsp3wFrRekDV/yJaAYIhhiroUeRaVxU8ZZkAmoD96BUlc6F24JpJZE0mLG2fscCpOoPA6J49KVfx/c3IdJ15+HAtIuKUx4Z2dX8id5unDa9uXDCmb5WK6pbR2wXYgsFiYO7Ru+NCr3ndVgAKhbaRUNMyzxkz7+C4OY3mYTnxXsHPoh3/G6L56Fw6L0nkS/nEZiIxt7pLlReL2zohmhrp9YDAtxe7C5RIz8B+ik38P2MbQWnafEIY63pR4/q0zheBDOdrijJx/m4aR/CIPzPoOE7FdndcL6ct3k6tbe6UhpvCb9QodIhjV/H3lcqtGD5lR6NDLY+A2M9PGflGKIB+EKEdZMETHGSOgotldDLE28rnJXqeJdbk5keGcZIK5ZcdEQvgch9VPMG50YAolHGyr0Ei/9MNNd6TbJDR0eWFwe1vRMbMPamBH5ek62a2MPoN8Ya3QCBbFDU29qavmio,iv:HhY5qoC3KaespeX5ivb37QllWlcEs76akMldu/fmoMo=,tag:s2bw/Y8Vgf5PD9oZeQw+Pw==,type:str]
    identity.pub: ENC[AES256_GCM,data:fuSg0O7PRZwNb1K5XqJRFcaUE7sURBWw1LKD4gyHZPdTaaROH7W1A5WL61M8Lkb6rr5E/Bz23KLtsPNuSobZSli153g/pxP1r6uZLUJDRCJPbCgrs9RK1MhAU5kjCEZ8V23P/CaBr9WOkw6iovgNH04=,iv:B/Pwx8/YBon9g5Q8phyFp/esXRkSnfwRKRP4uuj8enE=,tag:+clG0XAFyRvwaB/51Nq0Vg==,type:str]
    known_hosts: ENC[AES256_GCM,data:YFgSkAlj1wV0cvHxKaZIQQJOvjNunS6hJsQISeuRxXr55QdvDIQF/W/JvvcM3zPMTsDSU+bWWdK04VkVZ/eytsq/FGBEcyEdRHPJevMEArkQ0PhATPCeyI/DE3EadSgvPHqOJ7MYdcDCLg9/D+IRs8VeHrvVMfJh7pzIHVDn9lCq2ZSQBXLw3gxE9+Z0hQ0QiSu0zA4HxBV8S9G0dLYkA+UppS303+bcuZ2feBKnv/DF4otmTJ+J4BHNEzcB/gguiSJwX2Q+R9KvzsP+peRitf9TH42t8NawAKM32DykdVd9kV2eq4NubrmqX2lQJh2GNrczgDSGaHFN2MHKMajZGIi1an3vL1KbLQ1X6jNiLLsJDQx5NXJkHhfUA8ug+Wuqy2mHi0sO+W0pD3+sQ+y8i6Leci+tN50b8tvPq8zYHr1VkQ2YIonpEhJ7G54gjo1iSDALWJTVad5iTis3aEEGMmIPS6yu2rY30+9Cy1eTeDVwq6+4uCkWBri/jSsHAkhPeDuXLRM+4YJTzlrk517QQOCuyAv55Bc6BaoRD1q9Adz/7JeImno35tC0LKCfwn5R6An5Gc6Ajlp1izvOkUUCFbkmfHrAvvJWCi1W9Zm/BIzkBV4guzviPq6TeLjdGbp2ZU3jcdqm9ohMV5ZRd4kB8V9MROUVC+N/h+v2yJI8iTYppM4kZKxIjoMZg3i6rHzVgC0QHqFkD49OL8FPn4hEo2Ex8g0Ic1rKqZwXQ8Krwq2IdPHOtk2YEWPV3BV2HEinvicbetChhcWxKKKMRJFHXb12Zfp+FfY8g7qgNylhMrDX7XCkMR9eysR0dKtJbZs1ABo4T3ntScV14UW3n7v6eCxjsqvO1T5rcu3j3SatjKcoLoYJE6rFuR3/bsqOvmm+h/C+GKi95h6eVkKH0oWyi1GJHJ6NebtyTQEx0IFltQI7eR0Q1cLwAGoWpcywUj9+ottBxukExwnZNCyZaYBtGETq5af+OvZGMI/nf/hnk2rvGaZcfIKdGriDJU0SSiVeLkr7oRoyKdHNlufe+n4hEmDIsLOcn1ATVOaijjhN5sYedYJwGjw3NkL/IA2xohf1hT06wpGJ1sOpVcON,iv:Z+Bh8jK9yvVz+L0xYU8DWPx93PuB8I99ueWk4AZTHv8=,tag:7YAMUZBQtZjE3SfuZFjUhA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2angwYmtsWldsU3Zsbzhs
            Q09CeWJCK2gzWVhEN1pMa0hhWnZjOW1mUGxjClMraFg5UVVCenpXRFNLWjJBTm85
            MWMxcTlsdjI0ZkduVVVxN2x1KzRkdk0KLS0tIG1tcHFNRlN4WGlGZlpXcGpCYzhu
            Z2NSZFN2RGVuaGNqRVVsUUgveXNyWlUKgkc3IRcZ041Yj0LG1aEsQdMKwscq+i5m
            GXlf49TGTkbipEOCaI/iWolInuMN+hUdn3GqAviG5yl41jjTA6tpdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcjNLL2pEK2xSUVFTRGlB
            ZFlBeVRTeWMyTUx5M21iKzVPcUFvbmo1bVFBCjBZOGttWmJkUmZCQ3Y3ZEQrZDNn
            VGtGV2g2S0pUWkN5VHoySkFtY2tnVXMKLS0tIHE4NUdZdzRCZWNPQkpqQWI2Q1dW
            bG9RamFkQVZFSC9lV3dyVzhyT3ZtVDQKQLKqEnlkbtLVoP6OKU//R84q+vA6WBq4
            p8WsSA2+QHNdfGPnF2tjIc7BqWlSDY6KERdENcv1k7XH70GydthBwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T03:24:45Z"
    mac: ENC[AES256_GCM,data:uaMpPCNfg0fMc1xzkbAL0HsoA06oyhcA21UUzvkbf16QoHQl9D3Vc0nj6yHkT0VwS9WcxCnMeOOH0NGAc9FBeevjR8aHeiw9Rg/GdG8Ok5d3We98Ee9k6q5HQiJrDv056bK/TtnCpOWv3IjP5POst8fHp6dg8CcAncr8L2cfqTM=,iv:df5PgDs8cgo+3BymRA0Ve+O+Ctf6q81ZNHJ0j8NKtIU=,tag:kQG1fPAefwn5ieD7GDLiOA==,type:str]
    version: 3.13.2
