apiVersion: v1
kind: Secret
metadata:
    name: github-read-logday-homelab
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:ET59+nbpkheqbuqn6w8=,iv:1bRAsvfn3LuVcPH8AJkTEyO4+4mJsUc13bRngm1B2DI=,tag:h0wDipI8M5KYEaxBd8eqDw==,type:str]
    password: ENC[AES256_GCM,data:g3YLJ4HOUiZ490lpxziWNV9DDzxsR2txOQldehD7FPizOcO19Q3lEQ==,iv:yPkj2+61Hc/Euo25GM9+8d/rhXM3VLYCWQuT/6us06w=,tag:BbHDqmvp6eeY98n0Fgcg8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bnZLOFpkWkJyRVZPbm53
            dkdLNEFNaFd4QWNZcmF5d0VXSjJuS0YvZHk0CkxxVGJmWVFRRHNaRDZHdDJvbHNn
            eFIxVkZnVUZab25NMnhsWEgwczVlRU0KLS0tIDZTdVdYMldqR0NwQkNnei82clV0
            WGt4eGl4S2Ntc0N4RHZMdERxRjhma2sKkMwg2dGsfFK8J9ImkxRIdgljBOXzohaP
            coIQqotYf5M123UERH30zp+ZZ3IbokFuHTm1tWfOp5NS37FpIz4eOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUVVjbThoV2V4bEtlZnVx
            ckZPVGdQd2dzWUEwL1F0SHpYd2Y5MldYZERVCm1ENE9rZW5zby9aZURTWVVSMm05
            N29yek1nc2FNc0ZkUmRhL0hTeFl5TTQKLS0tIC9ZL0ZnWnRPTTBUZHBaM0l6OEVn
            Rm9oYXF0RnFMamFpaDdaNmRxazhEaTgKWqAd3v/9ZZwAcihszjg2ZOuXiSJgu+/3
            oVMLOhf39DKUwIKgl6f8I4KjtS8GPFMi1pxGXaOVBTgKBdXFsuii/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T13:18:34Z"
    mac: ENC[AES256_GCM,data:bD+sjv0ubrV8QcmGt8DNYhgYUKBmnJZDpDGpYhFcHq+Z+wSFFc45JNMtGwIxc9qXHfgGfGo/6734NElf7DFabVtlerO5nj4eB78R4zqXIZGrwoPg3X8U8yNa4Ztz/WLACQzNNgkdzQYPdlxfKbaVp7ooIx282fAsSs0NsN8hCLc=,iv:taIBI4CFHFIWKbo8wT/Wi9HqKYfv08gGtI1fODINIfI=,tag:9491bbHAbiSGnhbYZ0AOTQ==,type:str]
    version: 3.13.0
