apiVersion: v1
kind: Secret
metadata:
    name: github-deploy-flux-apps-prod
    namespace: flux-system
type: Opaque
stringData:
    identity: ENC[AES256_GCM,data:iUz1GDyb0BexPy4kguKpD9jfUhocfIQXoksY8SmKzcG8g5tS0qJ4XMqSSwkXIpa9RZlweYQ85k8LCXB6ZbWuerxMMp38wM2QxcI3yHCsL4TJtkwBDDPksMhBwfTwENKgTf2x5JfnJlj6/6aOhaz5thxThKD1Z7ahxSk6o6anjeASGKeBerfPH3ucjLNv9EUu0HsRIKDwf/L3Cm+T19rbLTOHZ4bHSvlVXvgZajNO53W2oiJWVrx2ezUiLZKk0MoTE1B2s4/gwftFHtxiBgR4weHf205GdCLn28vO0k0+umz9W0jet+nvwQn5p21bU3nJRLV5hprFOqXnJC04jJkGAJR/k3AsYidatTuQo9LWYRVdZ80XfgaHdlVhbjzKd15Bm4DY7qrImhjYxi54Ear5bigqvwxuvm7JV9X6NVCLtVoRalqabY50j/SD50HiqCm35Jy+hprnWRk1/7p9hmH80D7EI/5ryjS1Ma4Taq+m7NUMGmZEi+ULKdSmEaD9o9tRvU7EMGwqSSXdxDud7en/NKX63jt9N1+Yag40ogi45FzRR1g=,iv:2OHZku+hARQqj60jvIOTNF+IHpmg2qpNCdQ0Yd6OpD4=,tag:XtgOPe7kZYPxUNgAY4QD6w==,type:str]
    identity.pub: ENC[AES256_GCM,data:4Fou+ApiWngBnCPkC924hl5V2p3DHqpWMn3sLnxFmo4NG5Oya78HMTgVl9kjwkUybdsUVuQJQb2nVvr/joXURPaazKthx7Xo+5jpFPmX/u6wpITvOAtM4UwRGdvC1ZqQdUuSY1xgIS8sQszKehE=,iv:4+o8rYsO53rz0IB6581CQnXozU/iVCdC3GY7A+Ir/90=,tag:Xm8fNcP6gBz2oBItsIJchw==,type:str]
    known_hosts: ENC[AES256_GCM,data:xBw1Fam1XPPkF6ccLcaoZ2UakRF4ks44gpOtb3ZuqChlo9pxTss6JHoLmtxqSsWkBnO+0Y94XJV29n4JRl4gWNFbXsFS6z9w9TxIImRESm3ZbEHFsh6P4YRhmDy3qdBdRfDL95Qg8gFpcIZ1xx0sbOtpSQ322fmqvdXMCXWdrO9qDlgDGzxcRsftSivZAHca19xUPmwuFY39pSVLpdpZ3lajPtCMChPP3og4fejSzhZZAwLu3FWwjiSltK2rlYV2iE8Pijv18rCeVHMX2UFhJDV0xniscmXCXaM0cfWCZa0vqyxT+I/MCY/MnzVvdeBxjdJ+xRd+IZRQUHgTVS1+YqC9qlkyEo73/wzfBEyFN+mpWvhBehiacJpYvQyWZ7jARCOxW0uaZorqSOPQDjG8fW5XxDZb+LT9kifIn+Cv2B774e34ufpYv7nCM99XDF7KnL++3RHyWOPm1AC5OXDWozFRvVJM0J4mMc2tXUIiHibNvMwbkO9iZdw8cq06ZRWjakczhMGmPDl5wo31DDm+o8nTNugw+5fOLd2JaNYsmAsuHve5ufgUPYpe8WGdz8KyFqF/J4vdWxEdSLp6PcSfh7ym5yXCcR4X8GiWflvmokQtP6j1ID2HRq0P7Q7XDt4uETZMtjL3LT6WHzbozJIH3nEXIHViMx+f90MfyoSpmgwH5lF7NvycYY5iGyu0ruu0ZDOAlpt+hvwYfyNGYubRIe6fOLP/fJte3mxHiuDvVbAgj4sREQiMp0lJn+S6UNOE/aFzEex4NrnhOhCw3/INrMyoLt+cuYGM1JxNZ0ZlEOmxPnTFlctCthB6h0oyvZ1zuQtat59aIFU3AQhlCy9DmCxbW/egzLUGxNu5bpK/MXNnr9NpPwgrY1uBA3YSSvngXPv0PraJq65Q6BmPx/djnaBY640oEqWKFVmFOmDZP0vZujb/9a1a+boxYUNjI9/SJFNBRoAORZqlTbWgWIoDVC7/+AFCzdM58LqgrD4q/ya8bNnRBScYz+ILEUIBRKZqAxvVPfCyib6CE3IBfV5YtPiq47yZegbpuwNb+qSCdTA4OJ8PVjSV4Nv4D6UjZ89ky3K8SJjqn4FaxYtW,iv:3qHMQaA2v/31RVRivmNiXuCrQHJcR2dbWB3u+8tGrlg=,tag:x8Wx/nSJ3BshNqlLEMe2Mg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYTJ1NnhiVWV2Zkh3bWJu
            MHhLbnNLM3lZTGk1S2J5RmxKTFhKdmJkNFRRClM3V3pQUWRsc05MTHVZMjdENmtR
            YTFGUEVoanpORytzMk5URzhrNkR5WDgKLS0tIFRiV0FubFhmeWc2Z2FKWVkySWQz
            VXNQNUVQVXFEeGF1YWFhTGxNUEU1eEEK6C8x7Hzlj+nDdVzIrE0U9dBArUGeMQcg
            coTtknozXiiuD0uWVIKI4U79f+qNDD1m9ZKXKVRXWOGjMMZVl7zjpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTnhhODNNbGxpU0REdlBU
            OHhLa0hWRlpFQzc5U3JmSXRab2tHN3paTlFBClJuYXlWdGUwbUEzN2lCbmdwTUsx
            RGJodXZQbEdoOGU0UHcwd0pOejFYa1UKLS0tIEY1cWNxRTBPVlZoSDUyaXJUTlhR
            V2hScnNSOWY3RmVCOHNoNFIwUHh5QzgKgFR5YYf5hmOomAAvQzI7xZpzBTWRJAqs
            Z9PATfe0ySo5FV7oACQlD5oHtmA1wAv1vK68df1wU0XlTmZL1nZs5A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T03:24:45Z"
    mac: ENC[AES256_GCM,data:nafBZrxTMc9wiMeNNEtXeFvBFyFvmBiM+0oUiygKkINEQdyzvys4k82pBQ+WAVr9ppNH27EqQE3Xme8CLc0Q8f9E2hLPGTvikhu7RMqRRt58wVkkpq1ts70e7ImWyB1jihqITfxK2RZEhKSBhbHgNyRIK4lo39Y1NFS5143H9BE=,iv:AsDZ+tkxmL/WT86Mix4bVLvWPCU4luvqqd874mwg874=,tag:TvVoVdEllrfv5S49X5WoWA==,type:str]
    version: 3.13.2
