apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:gbC7OAo=,iv:jf1klKb6L4inOWgoYf1sUPSiRuU1ySxsjtDqmvwHB/0=,tag:fPQx1suKUuxrcDTbsv8rzQ==,type:str]
    admin-password: ENC[AES256_GCM,data:X90JYqawq59a1WgLJ8wfZJazAWH6IzdVnN4hxzC7t2ZC3wJrollxeZuSGBU=,iv:wnR82zl1K2xktIGCzuKw+E74NyBo1PCjQYqKUR6h9+M=,tag:wuDFqMD1TyTCVpCKTQmEpQ==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArczBhNVVYSWlUaXhjU3BH
            Vlg0N2VzVG4zcjlITk1lRUk2bjhxMDBsUlZRCnNMcEtuOWlOSUZONlhPY2FraUVG
            UnlQTkJQTmN1TXJyRFUyL3ZLd1N5ck0KLS0tIDcvTlpkekNCNE5CZndvWSsvRytD
            aHdhQ3NNbXRqVllpUWVsWHVyN0hPNDQKKHl2T3+EmikuHVpki1HZi2nnIQ5TQvbK
            53gbOIax9b9HiCm3cH+djex7nEsEwTyvDOKwF8/pUbzhJnuBDam/dw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXT3QyT2pKUU5maGNEaFRp
            bTZjbytWVXN4RDJJaFRUZGJvOEZQck5SeXdFClh3RGFzMk94cytCR01nM25hUFlk
            M3B5SkE0UHhZODhRTnZrVE5wcmUvakEKLS0tIHlTMitsb3ZJLzhIUSttRktya0Q2
            YkFndGFBajVWdDl5d1Q5dldBLzlhTlEKFrz++UBGATXHP3QL56gRcYvByuLNRTaP
            U7c3akF7lkqKKtdSdkoot7G+Iyp70cBCHnZqbBgfTuD7QiSLlQY30g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T04:03:33Z"
    mac: ENC[AES256_GCM,data:gCXBwjClyMoL7ejmRmrMW5BhszA8xC3qGIAFY+ts1wzbql0Fb0ETZxtEPLWQwAeDSqTDD6oXuOP6MvuUjNZK3m7MX9SAD5Tvums2EbNAPB+2ze0BwAShBYilni6+jh6gOLV2DCfWOzqpVgvNiyA6qrMSbhRC3cAJUrJGOE4DDNM=,iv:l1wxx+Kss9dZicRGdSZBbkA8r2LgMytdzwAzBojI91k=,tag:Gqc24UinWG9oYpB17jSzzQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
