apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc
    namespace: monitoring
type: Opaque
stringData:
    client_secret: ENC[AES256_GCM,data:FLqnW8tphOVcwNmsiRGzOvy1nV52xdHxpCd413LDKg729ThFP6fx0qAbqfqbNWWN,iv:5VGNAFp1RZeO+L4GAK9YzcCYus6B8eAjgKsx2oFJAoo=,tag:XkHgV0dVlviH75Ri6OC+sQ==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwamMycmhodENadi92MDU2
            REgycXRPZkJjdmpib25zbHdobjNEVkc0QlVjCktZYWtXTjU4VHpBQ2gzcGpTazVM
            U2c0dmtHaEtwa0gwWGk3elJMNyt2cTAKLS0tIEtyYjFJL0kxeXlaZVVZZDRpRjd1
            bk1UbG5JblBQUE14Z0F4WVh1RVpzM0kKqpaQZ1gDUrE5cb6Cy+HrnmJ3HAuPaz9m
            nWQ6gZP3mFY0DgfKUzFCUdE+MeShmTxsISkaGyHk34bypFaq2siHiQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLakFMR3BUWThYWDhWZXFL
            Zm9sREV1S1NPak92dzRWK0x0cUxNSzhwUm5zCm8wWU5TUXlSb2dQQVVNMzIvL3Vy
            WHJ0UEgvTnFCL3ExVXQrcDhoK0JQUUkKLS0tIEw3QmdTazcrOTVUM21zTnpSalFo
            MmFHN2JCazNlcndXUkRmL1UvOG8yeXMKQLVEAluCgwKf4phbvkiy9Ok5REmJF/+Z
            2NPTaqsD+elrKgM0Rp5Vm6pJIenkqHJK4bmRl8+StPxaIcK3mE+wJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T10:05:55Z"
    mac: ENC[AES256_GCM,data:a+VzQnftBCWARDC5wT3ORGWkW2SRlliaxKi1pejgYMRegEAEjTQsPqSuANC6gMLwSm8npYEvmECHGMJ+kPlb7pysIeze3Ep/nD68uw3T0nNQPoclH7Dx2E2wh7ZxgeS4ZaGryZqBW5kPMoEstJDJavrOMlFwK8OQc32ILapw7fw=,iv:krZURx3xpQUfiQ0rzEBIkH9od9sBKo3yK9W9WYD9ujo=,tag:UWF7s04UjSZXIqE6aeJzFg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
