apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc
    namespace: monitoring
type: Opaque
stringData:
    client_secret: ENC[AES256_GCM,data:lHav8//Q9ZycTBv5//dAysABer1n01mzSXECQzKF7g5VqN4RgkNQ5uF8V1X7vHNO+uNtzrwpxP7ccE9j,iv:dhOy5NHrAKHOICN1+qMZftOxmiBLFkcoc09aZ044VZM=,tag:WiLPuLRt6A5GinjZgJzVxg==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbkFqL01sOTFRbnFNTjdB
            ZzNseXN1cW1veXFQYk10eE1ld0Q5SVBEd3lZCllRb05FUXVZSnBiRGJQNlN6cnZZ
            MzhjdE1ZbmVuTVdidHlzVi9BZ1ozZUUKLS0tIHBpcDlmemZZWnRaT1pxYTBLVGNm
            L0xhVmFOb0NPRWx4cDQwdEVSbWRqM1EKQngeVINgLoew1LAVBGtRYcTJjUDWLpl4
            +bawzWtpa52ocO7GVswi7zuhMzJF8JTPij68/NaGiPABjyeN2Teg1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T09:45:06Z"
    mac: ENC[AES256_GCM,data:EeFuFa27HpUCRZ32u+bZugpX5pC9ZCwGqhxYhuzEiFJwQpCFspHdK+0echX3G4Xj51oawvutXPcF8KS7w5EuzzAaiFHAqCRomBl2pHOSXCspgO0otg5x2oUvJfgrWxYbnjICJGrZ6v5Y897Q//mMh6PI0lC5aEUJZ85ZSthgtMk=,iv:NUYnqiiS40WZhbz0kaRlZ+dcMIZjZ2nV7PboL9+uUC8=,tag:M/7gy0FSGqk59prUX9cT4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
