apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc
    namespace: monitoring
type: Opaque
stringData:
    client_secret: ENC[AES256_GCM,data:FLqnW8tphOVcwNmsiRGzOvy1nV52xdHxpCd413LDKg729ThFP6fx0qAbqfqbNWWN,iv:5VGNAFp1RZeO+L4GAK9YzcCYus6B8eAjgKsx2oFJAoo=,tag:XkHgV0dVlviH75Ri6OC+sQ==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbkFqL01sOTFRbnFNTjdB
            ZzNseXN1cW1veXFQYk10eE1ld0Q5SVBEd3lZCllRb05FUXVZSnBiRGJQNlN6cnZZ
            MzhjdE1ZbmVuTVdidHlzVi9BZ1ozZUUKLS0tIHBpcDlmemZZWnRaT1pxYTBLVGNm
            L0xhVmFOb0NPRWx4cDQwdEVSbWRqM1EKQngeVINgLoew1LAVBGtRYcTJjUDWLpl4
            +bawzWtpa52ocO7GVswi7zuhMzJF8JTPij68/NaGiPABjyeN2Teg1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T10:05:55Z"
    mac: ENC[AES256_GCM,data:a+VzQnftBCWARDC5wT3ORGWkW2SRlliaxKi1pejgYMRegEAEjTQsPqSuANC6gMLwSm8npYEvmECHGMJ+kPlb7pysIeze3Ep/nD68uw3T0nNQPoclH7Dx2E2wh7ZxgeS4ZaGryZqBW5kPMoEstJDJavrOMlFwK8OQc32ILapw7fw=,iv:krZURx3xpQUfiQ0rzEBIkH9od9sBKo3yK9W9WYD9ujo=,tag:UWF7s04UjSZXIqE6aeJzFg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
