apiVersion: v1
kind: Secret
metadata:
    name: harbor-admin
    namespace: harbor
    labels:
        app.kubernetes.io/name: harbor
type: Opaque
stringData:
    HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:Jl/Iocy/uapf5ISgLQPTEdvQDzT750pF9JI65A==,iv:OU/sH+MZOB+zyPPHZ5ZFILsdyd5PQDKdIWAKzkqBhOE=,tag:z76HzbhzTrqjD548LABOrA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRW9nRGV0dURMeGk5S3Nh
            Rmc4TzQvSytqdUJTbCtqZmZtYVA5bVFhTVJBCjdoQWt4RW1Hd2FWeWdNWVQxd3Vq
            UmJzVmpvY3V6V2wxRVRMdTZ4aVlmWG8KLS0tIEVZVmxqeXV3NytSbDVpd2ttd29J
            YkdQMmtmc2I5LzFZbUp2NENRUXgyQkEKQHnJ/ftJSuQf+X9lpktOCF56Pq/qHRQt
            /j2Fkc7gT6618g3pIlzSleF2kUuWyNGSoV2XcHSrOKiTW/z+IraK7Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdkhRNG1ESG5hK1JQbVN2
            MUljeW9ZUXBmdS9Kek03TGtiQUFKdGxvQXlvCm5OSWNNNUk3MTIwMGZxdzhuczFW
            ZmRiOEV2VnhudFhrVUR3Ym13T1RJdUEKLS0tIFhteXpvM1BjSGcyMTV0b3hENllv
            MCtRWFVGbG5BK3F0OE51Vmo4YjZoRHMKoLq9ExaHhPeY6jzwZ4P3AJIMEJlwvnJZ
            2NMHGvcnPYUz1pozwB9Xfn9MwrIPfy0shxMcMZdYwkUawtOVL5xsXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T08:26:04Z"
    mac: ENC[AES256_GCM,data:Vz1t4rOUIrTB3twuQ1NW3SB+LY23GFfpTmHKYw5D0OKrqWH3FAVrebC11jm2gVKDogE6vh4KJTQqaG9THKopNhpijXznR0V3sdaM4pptpTOUwCCqXfb8PkboG4Fs5UEH508AbPcjV6ObtytKr0tZoJ5vvoCgibMVw7iiOO0uQ80=,iv:gQJqTuX8+csDedxmE0eJB1mxywZ0+Fj9RJJoZJAVEtI=,tag:uMm/uSkCc+UtUJSwFS0q7A==,type:str]
    version: 3.13.3
