apiVersion: v1
kind: Secret
metadata:
    name: harbor-oidc
    namespace: harbor
    labels:
        app.kubernetes.io/name: harbor
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:SBTFXA/WYhtCTowjgo9qOC0xjbA0z6yyhCc6K4URukms6gqkVhzRk/Yg/OHLLpd++iQu3m3NxH3d6PmUz1K0RQ1lu/0WnZD+axVa1bnrLDx7Omcww7jOa85d8IXRSVQSBWa3eSFE9kRBCgN6ttgMRMIB7zbiwxPAy+hz1vta84stpckNdvkc43UFA/lh3cI3f2X9EVQi+CeNQuoGTwuMvfAfTFrEFn1SRex7uMWjmo4ytBDAZ0gTmY5SOpH5SdK83yg858vNhXL9hi6sSkuZZLoY1pq5TpOO4n2DtLL5QdNX2Z/NMRd7IsHtgUd4JWtvUH8xdtyX3GQYpGb6ns0qPVZGMQ2uCYNKbogabjj/25Db4uqJ+cPjZA+b72Qp+maUeoWC4fRhejQw425pd1qHSrRy+cvYqCOJNB9C2CYWlTYNskHwR1KMqB8/Tt6cp62F7AwsefZt0/NGyarht38V7FGgroXaI8vlhQ1M8ZZz8LuXh9jzYEjOnBfPybHn7VNYGCwKReyIdqVEsdICnd576PzU1XvYmphGpu+t30iYEec=,iv:twx9Y7h9pigPCWK4Gh+cVpgx4JLomxizOe39UnowTyc=,tag:R6TmYm5Gsqz/5UbH9n3IIQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQVN4eDdaTTg1blN4VWY4
            UGVrZGd2cjYzUVhoYmc0cmlsQTk3ZVJYQlhrCm5WQ0pVOWhLcnNCeWpzUGFxcDdV
            VEQ4VkYyL0ZHdzAxWVJ6QzBhb3ZNNDQKLS0tIGZGd2xNTkJIQ01XQ3ZvVy82UER6
            ZEFqS3QxVW5VY1NYZkhkZnJTK09tN2MKbKXP8+2KBUHBu+0QoMDMrAL7udHkggT6
            GZSRzVytfSf6J2EBOR7pqU4NdIZ7AmzjEhevjz0/nH35Vy5xlFhESg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdWlVSmlaa25qaVlaY3hN
            RVVYRzZ1bm96eEFHMStNcDNYOWF3VTJyY0RJCnN6RVF1c1MvNGozNEFydlA0YlUv
            T3A3WU1ZWmVvMGpqeVFwVDFGdjIxbmMKLS0tIG1LWmVLWWtwcGJOaEpCUlVrVi8v
            bTJVSGtSNzJuVjg1UnBJeit3dHFXcDAKufahWKyO+mTxTB7WI9CWjEacn8mRaY1j
            RDrN41jhx7o4zokHVhgghiyUypUOTpvOU9JbV/WN0uO6a6Y2d+accA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T09:33:35Z"
    mac: ENC[AES256_GCM,data:ZH0A+CyAa83JYokoASLS5A0M9VQkmU/IijWmS6FYLecnWRp4FXt0/JNoyiG9cBM0wp8FIEuXUQcqHL2v3m/Z2XXQI67kFrR0aQG1HlEchBPkMgAjSPAycF7tmIhuxgHAZNVqji0BM95XMeD4qmt+Kz2UpR1MTSqsDUMTHVnhyV4=,iv:K1odqqdzNI+uavG2RNpWNO9S7kgLGWGKSmgpwNv4szE=,tag:RcBim1q0RXJ61JAqcFRW0g==,type:str]
    version: 3.13.3
