apiVersion: v1
kind: Secret
metadata:
    name: harbor-oidc
    namespace: harbor
    labels:
        app.kubernetes.io/name: harbor
type: Opaque
stringData:
    oidc-config: ENC[AES256_GCM,data:46DPHkHx0t0KUtbleVyLaVi5UMmnRdBYhgu8BEegVrkMIFd/PzdfukpLABdBFOdI6TGOQm2NMFBlgcGeeZ7lYDn43rQAhkJ8CR6+04ZvxhPshEy56WN0toqokiJqsNqynIpZmOSJ+TDua2e5J2CjW+zcg7300wJZM6XclN+FhAojS+4zw27AVwCMcmi0eR6/iXwE2vSmjxDEsiBpm35EcvIR1mU2fMeVU6fYSYDdnJOdpbDF2b3oNbvmO+LPaiZP/dTOuySqXGIjcLFcjRYd543rLE7TUh2eg4uMgv9+xRgHHVd14NQGh4hwhGvw3eWapgKoA9P/TKOPO68SOD55BRRzG8mFKFQH3zdqTiqRw+2MHw21Fy8U28SmVLBjMW6I0znY7E855wAGootsFwZM8u5Ojvld3WmfmJVlWk4rYcYUnxrj/bEFqfxFQyEYsm0lU7pZY1di7LJOu9CETu5uyl0pPkXwyKOPspwzWcsVNZ7+H0GQYF1RQpmba7HGheMJWvV9MMYbwirEpFnK6uU+hGSdUFqy,iv:DWNss7cv9Xh6d3KoV/41mVoFLurLod839bqXGnMAQfQ=,tag:rKtNLrobY68dpomyeOqwCQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RXIrZG9zMnZyMXg2dmQ5
            cGNxQmRYNDg1RzJ3TGU2VmNSaWxRS1d5d0VBCmZUVWhhOEFyNGhlUlQ3cEhRZTdp
            VmFkOG12WkJpWXJ1YTRCVFBReHA3SzAKLS0tIFZLemFTVzRhbDdNQTh5MUhuZERY
            UjlncVJ0RlRlVFNjUmUrdERmWTd2bncK+4pZDBXvl/eTENc6pyofirdMqnybnCrZ
            IXqSj8Hicax6VMcd3JpL7PCjehAZfZDA3idJema7zm6HSDSipmDnow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNkI4aEZkMEg0L0R3a2I5
            NVJtcUdXMzFXdFdRWXNJNlplbWF5V1hXbXdBCjdXeGZiQkNNd1Z4QzVjbGVLaDRi
            OWRPaFFLREFYTW5mdVV4dVRFY1Q0aXMKLS0tIHJOV0ZkaW9sYU94bWs4aEZ5bHp6
            bm9oTlVyaTlNZFZOY1hQckFpSHRkbWsKD3IST9Am3dWCacqfAbw8kAJQPaWOCTqK
            88kRz8SiESFfwtR8Ey0niJk0qjzWpfdxBtFrEY3o64i5Ookdveo0ag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T09:18:51Z"
    mac: ENC[AES256_GCM,data:q4qjAbGd0JEgYfoQ2iOrPN+vN8RTqn7kS3Fizq19cen3iBq9Y+NR/AFmSG9ROBi9pDL0dwn9RgFl1Y9bQY7uupwRWVoLhyxQJ9joR3pY1xSfsfkm5hyxtB6MAkAavQ7zWbrNy0udnE6nPQZrWsiBpDNZszNxdAwYaOWbn1FzwkE=,iv:BoZKFTXW25z+37IERbXcHT82ZjcL1Qiy3K/l2aKtr8Y=,tag:p4bevrT5DOJAJ5jHN0SW5g==,type:str]
    version: 3.13.3
