apiVersion: v1
kind: Secret
metadata:
    name: harbor-postgres-backup-credentials
    namespace: harbor
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:3Gdub+7iXUtoJkCE+3S3mteSW0s=,iv:iXsJgD9uYQ5RJLZsRS7RSsJq3jN1/Mg8+1RYP99vYNM=,tag:fS7Nbd+pmW0tUBznuk5iyg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:VY1tkMuzj6kRIbJPAN9DJVbNdTxjW/UMCG5025KKRR9te6EjGIX90w==,iv:MntS2a56V7GgLxxGmYMxtlMW4bqFqHL30tTLetNOhvI=,tag:o54XSa6ATBuzYmM3j4+aoA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:yagRnLBhijtXq5+yeVwYzBoogdCnDZH4KFg=,iv:OxcP63oV4OH6dvIpPR+631HlfQkmSiQ+F/RtANj4bAY=,tag:WD2lCzAieYYDcaBoLBRciA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0QmpMR0Z6bC9PV3FPOFFm
            REZzNmpObXNJbUkwbWowRmpqUjlvTCtSbjNZCllqclFhWFdnVFdmWTFRdWpGT0JX
            TmY4K0VuMGo0bjlOOFd4dGUrbWJ5R1EKLS0tIHdqeE1DQkFEdG04Q0lmc29ad21R
            NGt0OWJvMGVuNW9sSkUydksrSWllZlUKcNatfLL7dvWpO8lARP1EmzKmV5TdVuGR
            EcnPFUARKGtZrSyoKAgxwiiTWVow/ZXA+k7JY+ZyBgXap20Rf8KCUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RmZESmN1R3lCM3FLUzdO
            Q29aTDB4N1VXNnZIcEFYVXdITzF2eFhVQmwwCnZPVERhVUU2QlBDZzlxNnAzZUU1
            NUxuZDFYN3Fiekg3RDVRQURiVEM3MTQKLS0tIGhKYm44cStWWmlSS1QzSUV3eVo2
            ekNlV0wzeElBVnJiSzc2QU8zU3VZSTAKbE9mM0Te89TB4QPMjBjnRtqRhEP1eguJ
            WxhQ7c3xkvb1Gg5lxZwWfS/sQnYQhMqvye9UJxXxFjhUQyP8F81Log==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T08:26:04Z"
    mac: ENC[AES256_GCM,data:GBDgp3zmLOTYGowXfg+0PbUiQUULm1Zn/xSeGwvVTKmQAvD5dX7/1GpJxXK7wccBHiAOci2cnFPpylHICZKkF/eBhaoILRg5ufxn+pwIlWsrTmT/xm5x9RCnm1RvQO0BzPVzEjyyFl1JSWzIIIF0Qkqihx0SnKpHnhOEwvRIxHo=,iv:2bK9SZpuv/K74zshls3xK91mZpiilSB1AcNnY8uTc9Q=,tag:FM1m3vkC2pkQVYNaFizBbg==,type:str]
    version: 3.13.3
