apiVersion: v1
kind: Secret
metadata:
    name: ${hydra_admin_secret_name}
    namespace: nix-cache
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:MSyzh8h3E4yM912YryTXFLSdtJLDnil12DPcqr3gW4rTV48RjW4crdHLEfA+5Nh1,iv:ImS13j1I76GOSHkfofREPdSsT8bcG1dzG88oAQsWkGY=,tag:sfhDRJKLCDcyFk8s+2dXdQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UFhoRVhncHBXVUVZeGJi
            c29aNjlvTWtYcVpxaTFFeTBjektDbVVUTm1rCjdjdmE0THBjTlljWWh1Sm1aU2F1
            ODZoZzdPaERYZTNxdWlwZHp2TU1LUjQKLS0tIE0wSTRoaEpnQzlPWXRRVGFUU1BW
            KzBLUjRNKzFYZlo2V2NZT2R5dVpKbG8KTPs0hzF7rHRy9kTfQKcFZlC6Yjk2lqYK
            tiJvvb60ZRTKViVS13N8sw3h44/m0hHU7JiBOERbjXjjBhpC9Fdd7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWkF5UUlhSzhMekVMVE1T
            dzhweld6aXFNekRzdXpxMlBwdWJvZENETkJJClFiUTVoaDR5YjdRQ2lKYm1KdWY5
            em5MdjI3dVFEMnh6OW1LcXVEM1FBdVUKLS0tIGFUWjNObEUvcHkzMmxTMjZvUjZG
            eEJZaTg2Q1BnaWg5TlBlbVNYQ005QzgKj8K5idx8RxnBaXfIyrIus18IuXylLFGU
            lw5MShd1ZsQRYeqP9X4cFxl2p/AW8B8R4fe68MmmTtsfCIvxiOoroA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T15:44:01Z"
    mac: ENC[AES256_GCM,data:NwgXp/jvduoY1uq+6qHOWf3OTI1d1tlo9j9WIJ5Vh4M8wQyFp/bAO7ykYEgR84V1W/m+OTYw0n8Z/kw0I4/yJQPIm1yxKCmdlW5/mpnjvPzQ22i+YTLUy6+roytrKrKflsvAy1ugWy9PLzZUKuhcGoBCG5UTT+lkY6j534pEalY=,iv:HGuBYKXuMkvSz7T+5N2Dyb+8WX4/FeJcXydzJMXgdWA=,tag:ydLEDIIWoeLEr1V/Q09S2w==,type:str]
    version: 3.13.1
