apiVersion: v1
kind: Secret
metadata:
    name: ${hydra_attic_upload_secret_name}
    namespace: nix-cache
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:/HWS01zqPI7+7mVZcMIILJLqzCAb2w5bVqxRtfVDgO+V9Ddz6gPWBTNhx1qCnA5hZ6gxU2e1oOV+ovD+cdHti9Wb3WH/Bkt8l4p1lg28nj5xudjM1wxc776Y3vWpxCZN,iv:p+mMu6ggitpy/DkCaNCNyw8bU5mXmIYSAT9ljgj+2nE=,tag:9G4t350fjeZRIrpY6M/DJg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybVd3TWswRUdza3Vna2g1
            M0RPUXBXK20zdEtZUVBQUDJGYnd3UDFCWm5nCmxKSGg4ZFk5bFVrQXRWbmkxYkxU
            bTlTT0FxN1R3WTVBdGFzb0hOM04zMU0KLS0tIEg2S0h2VndNem9sTVJsRFRwQk5r
            SnBmY0szeGFsai9SaUtKT3RrUklJMWcK3sr1uaA2sYNXHPq0IAK+HFrLvp4bvk3t
            l34dPbc3gtYIH55cXQ8jX4VlvOGi+6/l9oHZ0gL/yucqwo9NwhfZJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRTl4N1NSR3RhN0xFOWxY
            U1VETmlYUlcwc0ZWZXFCMldlWW5wRjBvMHhNCnRnOGIrdzBremtDdXV6cVBSYkUv
            TjhpRzJYNmpDb3VsdnQ5SHdKME12a00KLS0tIG9hSWtzVTZJMGI0K0RNYkVNK2V4
            WEpTdHJBaHk1WmxMUTJIWUljSmJiU00KYMPTMlhtWW5DHOVlJ80ZPDl4Qc03sX9g
            0iO6V5n8r5baRbll4IIUpZcOaPWdZ7hnc3LcmlJHnDtzqdKRsvePpw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T15:44:01Z"
    mac: ENC[AES256_GCM,data:hn2T3YIeTokNfVmR8SobVr4P5J6t+y2SwTQqzWgt7b3gujBNigF/hIyyRFCgNSMXTgpurOha2y4wxPCCQuYTRoQIGklDGAon6+ZtYM+tHrLMcRxfp2Zmq4WSZUF3beXYbPwEQpj2PE1muuby+g4zFWUsPOgIXmkeaT0orFiXyRQ=,iv:ygwWGaHHzTuNMnzPdnsNM/xJ3i/FwcRw5TpRgACy/GI=,tag:e/ZUx22w39aOIKIngNhVrQ==,type:str]
    version: 3.13.1
