apiVersion: v1
kind: Secret
metadata:
    name: hydra-github-read-token
    namespace: nix-cache
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:MR58Z9nnqUZ0LpbcXJY=,iv:h7LIFUH4w/SNAyBIPqaVxeDudAJNf9yQ5CJ5bVFCmNE=,tag:prn7baULAH6vVrsG3xMaJg==,type:str]
    password: ENC[AES256_GCM,data:sb/DW8hQbI2vr3QQ1HjLD/BMSYh0hBgkIlN71hdBXGGCIB98ZCBCqz+i/se6yZa6AMnltoqR8++ag3ZJY2YhW5BRyjFImPCIn9YyO8g3Rn/6vMXwtKCGQaOISrKL,iv:RVY78SxlEByBYpApQs+HtbIoOoj6wZIrdJBWaRryDlw=,tag:02/J6iRNJQUto2wdHlwq/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSzRKTjQ2bTU0UTVhaUdJ
            UU1FclFvd0loRytKZnkxTEg0eDhrY25aREdRCktaOEdLVFFrc255VUhMRW1meWI1
            a3lrL1dqWXNuWjVVSFRsWkcvSnIzZGcKLS0tIEEwd0tnaVptSksxWDRCa2NocnYy
            em9oWXFJdDZLckQ5aUJjaFFucGUxK1UKHR5v1y99h+WN6WwWWqfBPexdt9n3uuaO
            q5KppRxMPd7nJFJyTnVkItLCzLFOpHgNl8uiIjNlL0MR431Vgqi5/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENlBLaUcvWkJEVkFORlZH
            TjNrWjhjcnc2MnBmejZVUkJNcjRVRGVYWUJFCjhCa0N5Zzc3aW4vREZXa1hYemts
            K0JxZWczdjlmdzUxeGR3eFp3R2lNRHcKLS0tIG1wUDB5TXFXL0RyUjdyWCs4Q0li
            WHJ3eXYybklCOTZreUtJUXBjR3VaZDgKa3ssnNBqM7X3V5KsBBvXoCzrKX6D/MUh
            9BZBYGR/UBjTbStG7jakir0hAowO10DOdvxxeiGcuBvTyuq1nS5B9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T09:21:00Z"
    mac: ENC[AES256_GCM,data:qHD3ctVxJ2+x1rnupqKLy+aaIqQoQbKYB89IJAEgU3kCUbcbWxZapYEHeP9eFcHClPjNcsdPOsSwpCYklP8EhzlW7F9ilLXl46JZ0/ceNy/ld9mCU11je0RHCZ/oJPoa32SjG+RFDJKCoi6vawYXr3PnQLyiFcGsI51rlBig6WY=,iv:p2wn1eQylInR9e4loko7gZ0IvyGcUe3eLCK2q5YO9ac=,tag:FFVErljG7W+M9+oUoRuKiA==,type:str]
    version: 3.13.1
