apiVersion: v1
kind: Secret
metadata:
    name: hydra-github-read-token
    namespace: nix-cache
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:WQlw1fFsGifOswZXe4k=,iv:zHXYDlncn21lcTOvmuT0lHiRemGH6ueFm0mvykXGkUo=,tag:JAUzPfxC0NcG8uVl9T3ODw==,type:str]
    password: ENC[AES256_GCM,data:g06NPPxnIr8u/rAinN329cVXx0iDWqFPqspbkUxsKIU6G6NEnez36/XplaxGGrNQgCpKD3VbuSAuoSPOdjmJwsjSRPgPOEvGWJ10l/IuAARBhgtaUrx+hyseG5ZM,iv:GdFtiCewrVY2j7C6eZ/ZJP4YXXwAOcZybOHsQPG1M3k=,tag:fNTZTpK++/kF9p9YL1qC5g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxR2pNWE5SUk1jaUUxUkVj
            Vk8yUkI5YkJ5L3Nhc1orL0M4M1pINC9kNFFJClN3V01HM1hGQkJXdGFGRkFnNDBT
            N0xKYWw3RkhZaDdXcDNsUU1Wc0MrK3MKLS0tIFU3U1BlN29aTGR6ZU54c2JsT0tW
            WXZDUU4vMzlpczlpV3V3TmNPcDZhbW8KobvBOCd+gDRlPxo+YaGi6FM2rbPo9ueR
            dvGZN6FxNva5kMz13oL8fVj3fakW0R9dGYAyS5kvRJRmQG+8rMzjlQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQ2VjaE5DelZKMXc5UkJ2
            ZGhsK1AzbFBDUTV6V1pLZS9PendPMzFxL0dRCkt0RE9xQUxzNmNsYTFWOGNISVVn
            ZEU1aXZkWlBIUXJLMEhRR29BOTVvTEEKLS0tIHVUZnJEbkVuRE9NblRjSWJwRE9p
            OFg5bitBMlMwSDAwLzZxNlJZNDFNYTgKRYrLRwrGt4z8gcGlIpcP4//s5F87L739
            Hx0tUU1Ae1UwJaeCXGYwnHrfXPuIwY+qmugIVrQsucL0HSOj3By58g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T15:37:49Z"
    mac: ENC[AES256_GCM,data:3p615tibryIHj00+k0Lk/gUb8UHhHmBqgkr4le3Fu8HoqK5vHgZC5rXnnxNTtjRqapNe172c2EmAgPOA2XttObSfFEzcsc/S5WwmcbaUi3dcTjNIL80pin8BgYkaYtpyU2mjXZ3mukj34a9F2rQBp8cZPMF3jBfzShibUqCCWwI=,iv:Bsp7pr4+jid3OJaCwLBR/WXqSl5CNXIZH6si6XoRcrw=,tag:CbH9WVdX7qwUlvGS/SQ2hg==,type:str]
    version: 3.13.2
