apiVersion: v1
kind: Secret
metadata:
    name: hydra-postgres-backup-credentials
    namespace: nix-cache
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:aGRnaNjb1UDojfV+YWi7CNy1if0=,iv:VM/m2B7KRBRyex+OQbtKH1BKn4DScvSCfg9Pska0TOE=,tag:yrgKVxIytuN9/ggFnS8zqg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:2zyz/kLIEd46/wuorgPSE5sfFhoJlKc9IPYwawpAe6RMNB7qxJEVfA==,iv:cnRcOtp4sSRSrqYrQ+W2/FOQXYx9/rQdU+kfIkC99ro=,tag:GB1B1cIElSmzQ85Ba8UtIg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:d1PI8eZR/FIatnRTSS5LrwPrdBBtxvTMv8o=,iv:8RHHlCBIb21RdF9V5IcPCm0qvrV/70nm01u1A+buirY=,tag:L02pCmVPwcEIKMIpzRyoYw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZkdRM01VS0ZkQWZKV2tp
            WU4zQnJlR3NORWhDcHVTRFhHUSt2c0xaeWtrCkhTK2pxOE9Dc1VOZVZNbnBYem5F
            elQ1U0R4QUF4amNQUHBEZytKWTMvS2MKLS0tIG9OUXFwUUtlVmU0U09Qc0FHOEs5
            NVQrRUx4djZjWHRUWTV4ZDZ4S3FaUk0K85e5AReaxvEKzWc2W9uQpA7VLgz5lT8r
            jmB/yTcTCQWBDnQW9oyJAXjawYVDs+PAHBo49gBSPzWIBzNhuC6mWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQV2I2Yjdvak52cE1TMVBJ
            clV1TzdNMzZ4emRvLzRHWUVnZTR4VStPOUFrCldnVUdMV3ZueDV3MUlUdGtBN0xW
            UDgxbkZaRUJGTjJ2a0x4cXpJL0F4SVUKLS0tIGdDWWhBSm1RVGRFNk1sNnhMK0I4
            cUszQmR2ZWxUUTJqREJGVUE2TjdxbjgKfhzKIuwRYsOczhsu0nfCBX6CyLwnXQHx
            4qSw+13dPlkYxv7DcML/wPQGiIByIdpBYL1n16fXipxOKMkK7txX7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T04:59:17Z"
    mac: ENC[AES256_GCM,data:hORj71Lc+PCf9tL2VrTgPrWIVUJVwRV8NJ+xQdipB63jUxVc0/PsZ9Ki39TE7wVRDpaghCIAFUmHSVqopqshCZCQ5vqZ2vbnkLeRTtEBV5g39i9sP+R1U+Nvrt2uI1aUfKTJl2AMKZ/IusPS2xFSSmzhHVxojMhb463VhTKaJrc=,iv:hqJ8ZeWMq2YB0+xy5tP8/9+abgcFImCZ6uzqr1NyfTA=,tag:/5JxBslV2Y9Z/WlRtsClxg==,type:str]
    version: 3.13.2
