apiVersion: v1
kind: Secret
metadata:
    name: hydra-nix-secrets-deploy-key
    namespace: nix-cache
type: Opaque
stringData:
    identity: ENC[AES256_GCM,data:7jYvMhNR/uvvRLYL02zUmFza8xJZr9kWkwpvKHAMHiyiw0iuWuuFTomo/sUigBTqhgqgV9JJV+yQVVmBO3ceAS5KaKiDGR2+9C4M6XlvPagGtYll9kZnP8ZC6lYHh/k6ZluAwfORbGVzqtryTXhjHDPh8MphAnw8b/5p490pbJ3EPJFW1j5BWHmpGOeclIUZeVDbKDeHAwy/7FPQAY5fs7Xbo96WPhUeAvezfWdTY4Eh0/6KtGGhzzXx22i2RLDglTs65tWFl9sOAQ6IaS2/EcLBuoC9z0SCvA+0O3N4PpVJKEae45VX3vVYIRNMsqQRZvtf2EwqHu4OtCx4SI9CSBGnckNBL0NILV33KAAM9vVS76kb4Q7i2ht+Xmfn3x7VJ/PXzyyvh7zXPHVAvfPvbptP4fh3lTHUYw+kIRw67gceegFLpYUDdViZHSvOKfTXeL4s8UUI8BmNOLQCLXqdQFWRyod0q7DYlD09Vx412RO3w+9CnP7nxzAjfYwKcOJ/Ttr2UWUEwzY26bdrfwGOYGUV9EKUAS5xlKHOL+boMyPcGUsEo/uVWmUk9LhpdxS0QKsKwoFGsbdZvE1eCjFi9oNbGVF5N0/FBw6LyKVFawo=,iv:jlOlCPiqzvSzcnMIsRcDtXmu4jbmKYaufpeeGJRCpn4=,tag:1uOKx25jiu30vwKZSQiZHg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwS2NKbVNyN0oyeDJsaXdk
            dXU3c3A3VTRNb3Nmd055dXlmd2pValhTd1ZBCkYzTWVmbjJkTjRjc3RVeXhRLzRw
            VStGZkswdGZKREk2ODZJSzQ3Y0F1UmsKLS0tIFJMeVdRcEdBR0sxWm1IWllmZkkr
            elFkV2U5ZlMvd01UejhzOGltT0M5WUEKQHN8KCYndHtFPw5qZNQ5G6GD7r9Fusiu
            nt9bNHgB+zJInXMWOAdJkbTpogvLUm9gO15XSsXk5qxyMFGckPAwTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2R2JJNWZ0L0hOREtmMEVD
            Z1hFbjR5VHd2M2NWdWdXTGp4S3FFK0xtYVZFCmZUVitrRWlobGdlUGhFZ1JvbU1v
            UUhWUTVJZUU1S0NDYW1lOUsyc2FORnMKLS0tIHNGeXQ0eVBjK2V6YzZtejZ3RUsv
            U0pwaFkxU0pXdk8vV0ZUaksxdUFaZjgKIsq1puZ7eaxJErFV37UCeKZfmybzgmzY
            8OagrR3Vm1YJejXzE/6vNT7MnVEKC4vLbRW3VGNP7U4RFqlX27Zb1w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T09:16:45Z"
    mac: ENC[AES256_GCM,data:yszuA334oK+vTJKHXwM56aQeU/tmLn0tWj8hncUHIasVL01pmxoNTbTOO7Be35ojaNZbi701cWSI6/Exf57tUuiOBLCD4onJp2i1S0m5WLQYd2OF/vL+/1RIWKCBlRB4ZQM/IIN/p2zYIVkr64J3+Z+8pJoiRwlFX/IBGV4CifU=,iv:jlBuB1679ALAQtcAqk7vXwmMKPu6qKgpIz2OU2Y/M1Y=,tag:W414yNcllknhq8YhpXrxtA==,type:str]
    version: 3.13.2
