apiVersion: ENC[AES256_GCM,data:mhk=,iv:+JQKurWvW2rd4jRkludJzPRqyCbDL0i06nP0143t5Zg=,tag:sdyixR2BGy02441F4sikcg==,type:str]
kind: ENC[AES256_GCM,data:ZfgAxA6Z,iv:6UIZm+ngxc+I5Lzr8ETyq88Oh2Z4jHKnBEPD1NKTxa0=,tag:r52mDKI5IgmIOKHvkYILpg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:l0FmYEOZjDKKNU2UTTkq9voNgZ8Sp/8hJ4FrXw7qf8/1,iv:6oa/MkpY9FzWok9C911nkRmu6FVM+OCCmc6gR+gkCu8=,tag:3+IkAL0m6O5PL2+n8+anwg==,type:str]
    namespace: ENC[AES256_GCM,data:TwuV4oE3/5a0,iv:FL+DPDpIrSO7betBFBEO0tbmvAnNOJASBjwUNzFxhhc=,tag:39WsIAWD2czM0K3OAqZThQ==,type:str]
type: ENC[AES256_GCM,data:enCACDTU,iv:q0yfZH23CzHEYHzy+8SbXyilwA85lJ5O6U68XVl3+Wk=,tag:V4KL/7z0eV54Gf82547aWQ==,type:str]
stringData:
    token: ENC[AES256_GCM,data:os/zNwKdob91j0O9ffvzxcsHvxCFJhjeWpc+JN14/vyDYVJI+6oRaONoWLvkrZhIq7939061L8/kV6GRg3uUhcO8SPbSRKk9WHZIv+YgToEsErG7839RENxaZV5a/TjVuH5tJoR9dtNpZAnXdzcHwwm/gEvVCJLIdrz372cvNe7KK4CS3AT5aZxvwE+4LJZmqwXDcmiirT51QO20+v0KAzz7P0Ajt3JDe4UW6ZeAQwOeRsCiszUltL55k/u/q2nHgq+gV+dz+Na96E5MlAVj1JzIk5QRGWK+l1cDcZqCHMWe6Lh4oLW+kjJ4Emcw4qI+Lsiki04/WyKOOFYp0J5LsZ4mAXRJOGefZik7ktssaU0CmHVTxQo1+04W/RVzFi2UqMMvkM3M5nVaUhPzBwKIZ8EZeLU0UgHBzaBd0DFYx59tgcaf57mGhuPoq/HNjHcTFTjqdesRKe6/OwERBOGtj+2XKPM1nv4UGDFaZD7ruszDhlCTeAqNLbw59NVCygJs4Ws4Mc/13RAjdWzGn/RvaL49+g3ZzQQNOv8IwrXmC9E6PEcV+sDSdQStZWfKHmjJaGY2h8GXUUWxgX7D7z7b8eV4YlFQYHgJdFjGJR4E2sB7Rf5ZMj8QbMLe8ED3+bFW1YFZArZ0BV3Ixg2SCROJzKI/cY9J+XB1HpojBGtiIOFJUKbNzsivQkBJNG2rewTi7Z52XRiPlbIBdPMF6UVDrHbRMIihof2K06dWaiH2xppStvJMUYpXWTdkvWe6I11AOpyuygIHgFbQTXXNmcUa5vZf6L8K3lf/Wp1MkrBVHg36y4H7cpnawNhsP1lsrZ1KXuXXK+ISRCsCmbtVisOvTPdASYyOe1HVbZ7BDq2lUkrzVTMThXkXHsQHASh8tzMaRk+WoV/fMAURPnj+Wjrv+tZ80TJAHIDk8q07n7vD+o6tLq09teGRH84VvPfFt1FBYvsVSfABXy9moo84CXuPwaGRKVKAIOgTs6P4HCHY/DFcukUn8CAHI/Dp2E1jMB26N7QQn67T2/lAh3UCjiup8/Md1neChTKIpEBlP23V4IM/5Uq0LoWLjNqcNDQuwt+5JpyrHpzYk+VLv3J73MkT7efapKwI/e/nNuDVZKzbNK7Ofq7+SiYxHSJeOnNnOHqWJ0C9SZbSMq3pw2yqkk8NvhGYIdrLm/LyKTgnguDRU8Y=,iv:wgS/QorjTxpui7PUT/ZI7K/JWW+vn7nfT7FYPgTAc70=,tag:wk7L0G1ES5cRm/i8vINkZw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMFcwR3dzbTNqcUx5NDZG
            R3BIOThROWZpUDZtVjZ0USsxZUsrWklkSGhJCmZKaER1TUNIQ3dqa3NoSVVWQnQ3
            WGlqQ001MDRSOWNXSU5XclVKd3N3MlEKLS0tIHE4c1NDQjdPT08zZWlWOFhGUzRO
            ZXNlK1M1Z3hPVXFjZnlDZlFsekVPTW8KPO+q7OMQsuDuhrGZ/Kp2c7rarbTjd9Wp
            vl06G6+/KVt/U/Ef8yxjQHVegKyVWiBYtK7kLc0mTPPQKW7+b4HBRw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbll5N2VJV1lHdzNQckc0
            Ukxwa0dBK0lMVG1MenJLTG9XbnNEejY0TUdnCjlDbUloUGhmV1JGdHFxbkJ0cHVT
            S29KcWwxSytKTG5sdTBlOWpZSWN3Tm8KLS0tIFl5V0xaaGcvYUJnQUtLY3hQdWpO
            cHgzQXovZ1k1ZVFhMGRHUXhrUUFMTFkK2ZepBpVUGtzYo4HHEDT6TfHSpYKX6M3S
            8CASLEH6jiBCxRhSpZYUJ7feHMOtzG6wT2Si1WLSWFn9Pov9NiqyTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    lastmodified: "2026-06-15T16:23:00Z"
    mac: ENC[AES256_GCM,data:Hor7n9GFTmrIdCE9G7hBiM+E47IYWktyf2YXNLWTepWXzRSIniieecldjyJpKDM9OwIByZmf8mziu56uve7B/ntpaqvjjIeiQSOp8eRH4iRvHeRt0r4wiH0vb7SUxBNckvdp2e+7ZpnoA3Q3qCwGKfgKAq/bvIHVDGzn2P0i9a0=,iv:DMsV0bZEKZx+9a3SbOVPMN2phnY3XhJJ0kSc9AWmN5g=,tag:60xDg5R+mICLFl3d7iKBRg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
