apiVersion: ENC[AES256_GCM,data:lyY=,iv:aNsjTB6ArsHrByLSTjtuJpb2uICWyJTg6wwAaPIxvmQ=,tag:I4IGFvzx3Frqr6IiuG0bCQ==,type:str]
kind: ENC[AES256_GCM,data:5ymsL7q3,iv:bnzX0WhtbcfTEQsGlkAvpjRb3csGxIQ3cSxNY9LMSHs=,tag:r9oBiEJ8NNhqrxBYmXTFdQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nQiWihexdFb/K1ZiiWdA+ZHE,iv:icA7u1JI/vAiqfuLC/M9agA2r/Kh9qQMZzY2IveuwGw=,tag:OhhWY7NV6oQWLUOyVnQ4Wg==,type:str]
    namespace: ENC[AES256_GCM,data:YVW6aZKN,iv:7dBbx35CFO+5qDUNGF9FkX36zZybqaGpdr7VfBNkvkY=,tag:PRA/bY6VBXDI33xlc9EAoA==,type:str]
stringData:
    join_password: ENC[AES256_GCM,data:+wjHHIn/n5gbjD8EgtE/2S857dU=,iv:g1swiIrrg2LtSYJfEYYZxjQoZrDXGMkPdHvOgRTydi0=,tag:Xe7o8e7u7KkP+91gLdvwtQ==,type:str]
    admin_password: ENC[AES256_GCM,data:iARJ/kUX0bAkWQ9dTEe99rO/U34=,iv:B/Bo5GRl4rGZdj2zZbwVSSP+vNusE1kOG+snYYvhhjg=,tag:asZVR5eSFRxUYfQpvhVTRw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZFRTV0dFak5nRGF5ZXc0
            dEFVN05XWHJUR0tadTQyenF5SW5aWGdWZDFjClZlNXptNTJsRHFJWjVzMk9HNnBZ
            V3hyNVdjMWNXdG5XWHU4cEVhWnJSMWMKLS0tIFpVbjNlaU1WZy9WVXRZWVZBaFcw
            UjkwRVE5OXZCY1JoUEw4UlZPdTB6b3cKPmNCxeYwOJNyEdv7N+PhUVJ2FYjbwMAm
            pQIASgNSHoxACY5efz+9GKA8vF/iIPbtI/HpyYSyG3xDm+OTT6jsLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSDlPc3VyMGEzeFFPU2R4
            bndSeVNzcGtpTGhnbkVXU3h4eTA0bDhlQTB3Cmh2bXlZZW1ybkwrU3c3N3ZwWmVy
            cWZoUDFCU0dVZ0ZtL1JXZVB5ZGlZMHMKLS0tIEpVUnZRRTl0QTF3S1h4bWVYb08z
            UW1Eai9OdVpCd0hCMU9oTHpINitnTUUKrtYg9vjzBiZ+BbpgsnNS7unSmCyYcUMU
            cKyuUKO0xJXUWogueD9vWRwbssNusJjZz1V4SM6STFcvHw7Q/N2Lvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
    lastmodified: "2026-08-23T06:53:09Z"
    mac: ENC[AES256_GCM,data:y8SNQ1QAWaNVZtFgaapmoEf9X6YC2RMgitHoBPHGj+P3Y8hPgdP1ycGcnvKU2JScHFbrj/UFuoiYD9zHIrKDVaObWHXrll+F40HCwmz4wrYi/0bXLLae/cJkC2il9cSiZszNZtaklvLn6oQ9s/QLIrBgoOY8MLrbAWzYws4wdQU=,iv:KApvwAp9noe20ys0cNFZNjQ1tqmUhO55WJrQbDZ2iCY=,tag:rtnvS+abhLJSC85ybm3pVw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
