apiVersion: ENC[AES256_GCM,data:2e0=,iv:oPz5qecmDGZhCQDPOCRlOyzMMD4utu49Pf3aLZBwmqw=,tag:yqybg//2ntsyEE5kQt2gKw==,type:str]
kind: ENC[AES256_GCM,data:unnDHE8I,iv:KWBq/r7zhI6dQKJgKgJKV1LQtuygM0XtmcAh4BqwfQw=,tag:i5pl0XKfajFep2iivNwf6w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Ugz560CKSNpnEG+XtCALLWC84orBqqD3Ug==,iv:wwdlAkztxLwDRkmuC7mWxZxVj5yk7Z/RyGCloY/Ea4A=,tag:52owZ6BnwKJOuH2eFGTlow==,type:str]
    namespace: ENC[AES256_GCM,data:g7l87qLh,iv:+/3gvFxPf5rxXJp8DZzTbIJ0bDw32G9jaYgyLKxJxAA=,tag:GhXRVZMWmY0IFnAd6n5oCA==,type:str]
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:KGje0kVoRSuTyXumYEZLJyAW7tEvdVq/+iWEF2rKqu9uwnuvtpWA3k9aaA==,iv:5hQO+8mcR7bzdSZFJ2jt4/p0JYDvxJjDNJDIeRxszbA=,tag:RyWLFhdh2P11TTefS9828w==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:pwMsnzwIlwGsLGWA6nfQsBeJEP4ZXqwR2xBsOWI+LA==,iv:32lhpro2wpeMuBTeixqIqq8/fspnARxIOZX2J5P+lgs=,tag:6ADvmVswtMzlNgp4J1IVjg==,type:str]
    #ENC[AES256_GCM,data:02KXfRN8t2UfFYYCdDmq+nMZdDnMZL9bzObTsqHjp69E/EZXzAyYJBvbiy4oh1xPILYQ5Wgmp1iGImL29nGAqgrkrUXTv7Q=,iv:A4EltFAfVCSoSYRnf0GX7Q5oznpv01O77z6X8O8e9g0=,tag:noKpD4FlKErq7z5eNzBobw==,type:comment]
    #ENC[AES256_GCM,data:Ewf3L2520wLxxxQ4poZDp4tl3hLFV7aGXg==,iv:dqG631Q9slKyK5QYM90R6NZbQZAw9fTqBw1OVSevn1I=,tag:UjSbOepMUMGi/a99mLqnVA==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:naDJLhm4lxRM,iv:rBI/P75AWaDBoQj6L2YxjqqhSbrwrj/BbYFpTNeNZTs=,tag:vgConBiIrviS7097UGmgCA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:C4QUCn8CHVQK,iv:IoYCC5SJKSZ1tIb5hcyFQtIrXglqJL6egG0ptzgfxJ4=,tag:55vrQU4ply9jRRQYO1qkbw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5OW9OVXFOc1BrcVh5SUhI
            SytNUW1zNlVFeGpDZTlLVVhNUk9CMnpFOG1nCmRoVmkwb0VMQ0NtenpFejZJbVZa
            MFhUTUU1amI5djN0SlZtSXphZkRBV2sKLS0tIGFDVWRjejdITzg3V2Y0bFdZUjNu
            WmFBQThlUysveU5vUUx5RlUrbG5JTXMKIrcZiv+8jmM6wU8UeXJKHKapFzJeJj/I
            pOSdi78Lgs9WJk15pFWsU4sJEvZUXencI3Hc1UWkR3WzYIVR7sYqWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMV2Nic3BRRTZJa2FmYytH
            T1RiSU05Z202R29IVHM0bWR3aGtLOEwzWkhRClNRRCtCZ0toQUlESkRUYk4vMG9a
            UkxXc2dyZWtuR0FjY1REeVdTUVNoYkUKLS0tIHVZa2xCbzB6T2Nvalg4L1ZWT3or
            bFF5a2NRZkJobFFndVV5Q0JEWFE2eVEKmdugGuogLrKrHtvDFaRfPlkkyXaRkdR/
            C0PF4N05L7h4SCuBFgdjJw344+At5yNaZ464TIQzGW9yvZrbc0Y9ww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
    lastmodified: "2026-08-23T06:53:09Z"
    mac: ENC[AES256_GCM,data:4VvLgPrMtKlIfrZ8nseqaPienM6ONL4fyj5iSXx9nuL76QF4rOti+r+vIf+2J4FaaA0f9AnMGRPLqFnh16OWo5jDnHW7/9VI1uhfeb4TB4TWbxff/cUtuFf5aS/JyE8yQbJbGZBY2J7kVTsId2ff6rJvhH1v5ubCz3EDpGAc+sA=,iv:MSrugmIV6KLcCV5q7vVXTU/7ZZ0TXdlOnmlLufqb9wo=,tag:mlb9D85R3tDA5XFV1O4AtA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
