apiVersion: ENC[AES256_GCM,data:lyY=,iv:aNsjTB6ArsHrByLSTjtuJpb2uICWyJTg6wwAaPIxvmQ=,tag:I4IGFvzx3Frqr6IiuG0bCQ==,type:str]
kind: ENC[AES256_GCM,data:5ymsL7q3,iv:bnzX0WhtbcfTEQsGlkAvpjRb3csGxIQ3cSxNY9LMSHs=,tag:r9oBiEJ8NNhqrxBYmXTFdQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nQiWihexdFb/K1ZiiWdA+ZHE,iv:icA7u1JI/vAiqfuLC/M9agA2r/Kh9qQMZzY2IveuwGw=,tag:OhhWY7NV6oQWLUOyVnQ4Wg==,type:str]
    namespace: ENC[AES256_GCM,data:YVW6aZKN,iv:7dBbx35CFO+5qDUNGF9FkX36zZybqaGpdr7VfBNkvkY=,tag:PRA/bY6VBXDI33xlc9EAoA==,type:str]
stringData:
    join_password: ENC[AES256_GCM,data:R+O2oLPRMH+GIc0+Yw==,iv:whmCUhgD+W7S3nXObbVMecOkkrnfx6q3Upu4mmlUA4s=,tag:BNQoSEKfmIH5X3pSrjCVyw==,type:str]
    admin_password: ENC[AES256_GCM,data:iARJ/kUX0bAkWQ9dTEe99rO/U34=,iv:B/Bo5GRl4rGZdj2zZbwVSSP+vNusE1kOG+snYYvhhjg=,tag:asZVR5eSFRxUYfQpvhVTRw==,type:str]
    public_host: ENC[AES256_GCM,data:1ivI+NZjbBOwzfaU3TTOHioK6sXA6O6I3RQgEg==,iv:9kYQSXzl944A+h/io25q72geqJSoFXyBKMLljnxi1gQ=,tag:RAAdCv0al0LuIvMmF4fDWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZFRTV0dFak5nRGF5ZXc0
            dEFVN05XWHJUR0tadTQyenF5SW5aWGdWZDFjClZlNXptNTJsRHFJWjVzMk9HNnBZ
            V3hyNVdjMWNXdG5XWHU4cEVhWnJSMWMKLS0tIFpVbjNlaU1WZy9WVXRZWVZBaFcw
            UjkwRVE5OXZCY1JoUEw4UlZPdTB6b3cKPmNCxeYwOJNyEdv7N+PhUVJ2FYjbwMAm
            pQIASgNSHoxACY5efz+9GKA8vF/iIPbtI/HpyYSyG3xDm+OTT6jsLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSDlPc3VyMGEzeFFPU2R4
            bndSeVNzcGtpTGhnbkVXU3h4eTA0bDhlQTB3Cmh2bXlZZW1ybkwrU3c3N3ZwWmVy
            cWZoUDFCU0dVZ0ZtL1JXZVB5ZGlZMHMKLS0tIEpVUnZRRTl0QTF3S1h4bWVYb08z
            UW1Eai9OdVpCd0hCMU9oTHpINitnTUUKrtYg9vjzBiZ+BbpgsnNS7unSmCyYcUMU
            cKyuUKO0xJXUWogueD9vWRwbssNusJjZz1V4SM6STFcvHw7Q/N2Lvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
    lastmodified: "2026-09-21T17:29:34Z"
    mac: ENC[AES256_GCM,data:0GYNVNL1JK+IkDIHiEggZuOTyESOdwDz5NMWT5RZRF7AbyUYwd5xjavfnpDs9niLGiPXfZocYyv4Et7IivdvDfm/jq1O9kS9z4U+5oZiCwZyTlwPsYmWTTEPgLaPdC1clbMOYzXoV3YwMOcKK8o4QnK3OXMduavjqAy9Sd0GGzc=,iv:hrT2p5k8dfJdbw/VmFAobPp5LLPZS3Rsqpid5RTDQGQ=,tag:q28rmExxn/JpL+YHrhYaBQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
