apiVersion: v1
kind: Secret
metadata:
    name: immich-photos-postgres-app
    namespace: immich-photos
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:sRdh6OEd,iv:J8FvczJYt20ClpwLhNJ6PmDkwr5T4HqHTWrIR1GT9Pc=,tag:XZmyxXEGqdcqNFnhzU7aTA==,type:str]
    password: ENC[AES256_GCM,data:cASQQfi6W9eCyF+baiBH4d+cnLK26lB9h2acbg9hwk+94LN30rte78Om7j0OP/0z,iv:kMfS1/qRggYyidTomDAEmtN0zsq0tc+hhsO5iUQvaHo=,tag:89u5cosUL5GiVg6TRQSHEQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNmtDaDJuaHh5c3NtdERu
            bHJreWhQWVIxd29LRlhhMHVpZHNFL2diaUZnClk3cWphaUJWQ3dyTHlUWGN2VGlG
            cnlZQjhiUWRoOWVBTXYvS1RVM0IzcU0KLS0tIHQ2MHRUbmQ0Y3dnS0FhL054QlhB
            cEZ3TnI2Ykd2cHExS09veEhoZ0VURlUKR4/keMzAO2pdJ/UNifRdcP7syFMDX/Y4
            AM+HESb/XYh/jk8ao8KFGJkVKgMyzTx056G7SdCOuTVzOkGHI/dTJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVnk2YWhGSTQ5K0ZmbzZB
            SFpHR0tEa3dPM0Y5QkdybUtvSWE3MW9QQ1FrCkxUQTJ5OS9IdUJ0VjV2d2ZQc2pN
            UWc3NVdpTjlSZGx6K0hMZ3NnYlRkRGcKLS0tIGFjL1V3MlVtNGFHMSs4dEFJVWNo
            RHBobVpiSkg4UlI1R0djMmN6dnVCL2cKHCMNVaYxPQsUfbyGUFeCIqlW5dYRPQSh
            zT45UJo8fBfnpFw6lozxw5gWkCzE0Ke0DIhYh8sGJBLeGsWw1SNfsw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T15:44:01Z"
    mac: ENC[AES256_GCM,data:oxB5KYr8BI03zawU7MYOZ8Il76LCc/7wwiL4O7kEi9il/7/oYZs4V3xBraqG4XP4Ln6LcCRp4EFIa0dVfS2tHUkD9FHM5CVnIs6ZFyYcVtxeXL19UWhhAHf7Rplx0mTxnIlhd+Eh8almp8vgTNC/VVyQmW06s8i6WHhHJWRTluo=,iv:1uBoLGkd+CD69UgdUHynbpGHinTXmh4hbe5+/nPBOuU=,tag:tvavBBrbMHdJfCDdrFFXzQ==,type:str]
    version: 3.13.1
