apiVersion: v1
kind: Secret
metadata:
    name: immich-photos-postgres-backup-credentials
    namespace: immich-photos
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ffL65s3yQs9tNXLL8HxcEmarIzI=,iv:Rj/u6JxUNnHHMG1Om8zJbIBuV/mpwTwdtKn3FYIV8eQ=,tag:3RstGb8/LGCLwHxFh6vj0w==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:qZi5BZMSAPwSKt5G3tcKvuOqLqlr/C4+FLI3BeMMhOYnl2v6giDlKg==,iv:MGnwta3kyADI7CwLj2l4/EM1NRJcVTfCEP2x1FI7dzU=,tag:WIeic2pSLB8F0vR/eqaSFQ==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:Zdhr7BuvuZmXUXF0+mhpsM6VEb88IIFUL0M=,iv:RWLa5fX8l+1ASn/rBAKwOOoFQPDfpnvT+OrrWnVSCiI=,tag:djtBrtDPUo8T/gPIRh/mPQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdWQvenlobTZmbFFwM0pu
            L1pPdkRHS3VHZm16T3N4K2NHb2FDQU5OaEJVCmlYSWdVeVgrZVRPVVFoMy9BS3ll
            bXRCTGdERyt2bmx5dGQ1T3FSNTZteG8KLS0tIE9CYkNHc2NhUDdhZ2xBZEFPZEhm
            a3dUZkVZSUU5d1FHZ01tMlJKNDRsNmcKVgFXy/BVjiImOA4shSo/5A5oCEmdIjyK
            2PpJZSy/V96FcdbrYTrnXRpfO0G8llQm3xwXZXasOiia84LKBrpsCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxL3g0d040T0xnYXpsdEpr
            NXc5WXRWc0dJM2dtcHNUb2ZqZjRTU2QwRWpBCkkzYlQ4S3ZaN1NsWmg4Z3lVZ1VJ
            MElOTTBldmMrMk5LRTJDWXBtRVVTNUEKLS0tIHVwUFk1aGMxQWdlZkN5YnI1Mk9E
            ZVo4VE82b3grMUtjaGtvZDZFeE5rQ1UKa1dHSvcRB9LLfQa1cXHtmLGmVs9406MT
            wk45VxZOU3DUAn3q3LUIOOeRausmweMg8F02LW+zlm813YoCcyJAtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T11:30:49Z"
    mac: ENC[AES256_GCM,data:SqDIBX0NcZwkSESGBC7SgUj8cgUXFuCRnF73UNC5BFTgkYksN0qNZtbd7OtpwGP6ohqBvJekt8AsHRs+tRKkxCnc1BM8Yp4sjWLC5C8lVMbfvOUl2nAKq0tk23eOgAYvv6dhBV2/bxyeLpUTj19eXVeJsh9NAOH3dAs3MS7r/38=,iv:IbgjbdO6SBsa+nzYsc3l7VmKt83REdGMlmP/Pr3trFY=,tag:jimUgfmz5+pBYWPuiXFBcw==,type:str]
    version: 3.13.1
