apiVersion: v1
kind: Secret
metadata:
    name: immich-postgres-app
    namespace: immich
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:C53VbueX,iv:/3831ZjcO/2ilD85D9CI6Ld3XG/yYvxQieMFRVN3srg=,tag:uRZao7sr3iVT+ffYZskpHQ==,type:str]
    password: ENC[AES256_GCM,data:Fyn16zNhA5Yxa/eL7uqiAMFXFWAQ9/y+QL8rtBp8jZm9ss2zLLcOqQYfeiFdMVTl,iv:M0960qguKHiwg4ESlSc+yJgMrhd94GdfutCWKOwaMbk=,tag:7BG2G/B6MaGAMCCbYIDMSA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxM0ZqZDVZelgwNXpRNnBO
            bEhDR0t6QVpjQzBkODVjbDhQdldBYkhkNGlZClVvL0xRSlNsQUJ5WS9zVnBKYnFs
            T3U0UE5IUHQ0Q2g0TnY4NVNMN2w2dTgKLS0tIEw0MmhjSTlXZ2V1NExtQ1FwVTl0
            cGEyd29OU0dhNVNwclNoMG14Sm02ekkKrVVtmyUnCT8QW/QS+fk2g2KSLFMG1csZ
            P+7xCHxcwDdm9Hf+dO6Ofse6PKwFnAWRzu1oghIgfDMcgnOYxSk52w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRmxQT0hma1l3VnpndDBt
            RHMxQVcyUzlub053b09pNGs1bGxUYVdQVzNvCjBKb3psdGJYTW03eS8vb3Y0NExt
            YTRWV1JFeUE0Zy9tNERGVlRLbWluR0UKLS0tIDZWcERkNUMwejhXVkNXS2VWNDRB
            TysyT2wrWEJ2V3IycDNzdENyak5RbzAKWyvC5Gdd5U16fP3G/79ZF6BRWM7pr16x
            8EOQAWaN5XmsWHqzKjNVxaPVHKWzH+CgbDWI9MbpUQA2njQxZPDzQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T15:44:01Z"
    mac: ENC[AES256_GCM,data:tHMS9aKOL1dRzRr8kRTbaMkczGqQD26XOc2kfi0/8HIrTI35UyOj+gd5wwoUu2w1TyUI0uhTKF/M5DOghpruu1huNow0H3aZ5N3lAr0iRDSZGSyuOM0RP+hCyamsmJ6lr5scMiYifmVIWPurQxwOJKMOMFRJJfJ7BLxDve7TSAA=,iv:uFbstzWBZD9Q8TxR5C4GU1bA3ZM5oFykJu2zl1Ft9b8=,tag:q3g6hMTp2ZaFetM/34ap1Q==,type:str]
    version: 3.13.1
