apiVersion: v1
kind: Secret
metadata:
    name: immich-secrets
    namespace: immich
type: Opaque
stringData:
    DB_DATABASE_NAME: ENC[AES256_GCM,data:kP73ns51,iv:ZSvtOvipWV6LxnSIUcFVAGo+0cyNPmaYSqwBSOCKuAs=,tag:JTG6VKyplKHyW3BPkWvI5w==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:PU62l5bo,iv:S6DlYj2d6jyNVSeH2BO+XdS12vbvNoFJf+wL8CT2QuQ=,tag:T9NXWSjgbU7+A5Hl+GtdeA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:yM0d3cf9HTns2kYctzhwenujkgK8/LIR1F5XrxZLff21IF+8Y6K1Ab+eIv5sHs57,iv:LPgEo1ydm5+UpqBm0SR7xbHhKOGDBlsa1o228rR6mkU=,tag:wrvwYAyvfUyl3R50kZEoDg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:HzBKcvEVYt84cv3GQf6YTm+be7T+VSMXzjmXw8KsTwliWHekM/Mjbi9bQmmgpuD+,iv:+KoZSxpSSa1w9Vb/vRfsksv6+xZBkEF1R0ogp4pVOYw=,tag:wRk7uPD2Z6/lls+RIw8X+Q==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:R4f06kCt42WUfVqu2vdYY7gBbUNvlX20HYtr0L8pm7Q8OBt3Q+nPRu6paUr612c+z6yPYkCRgdL4j02p5elADQ==,iv:YHxOXf7LRxEGyfF3DyfEcvtVeo7UPvkjwl8Qi8iDtSw=,tag:pXYRkv+jk/tKpivBmsd0FA==,type:str]
    IMMICH_ADMIN_EMAIL: ENC[AES256_GCM,data:MUc/L38LBOApScvpGIRHrMa9,iv:kxYpRG8Y93c4HR4mCWhNVoBVwnZjeb9yr3N8lPnkghg=,tag:PXRv0/0LaFQJQFeNeFViRQ==,type:str]
    IMMICH_ADMIN_NAME: ENC[AES256_GCM,data:vdOXGtvijOsOD85Z,iv:v4qkU0NaolB5aGVp2QbxVf2qaJv0l93acn2Z0EmQ6w8=,tag:UGt3M9z+b3MVlbgO4ABE4A==,type:str]
    IMMICH_ADMIN_PASSWORD: ENC[AES256_GCM,data:G5B2sH+/DsdTQ80UZ6t3qGhe6sTNKg9+so1NKqhtc6NF2XJaR+pnbvrYH8Dd1bOo,iv:S8akdyKh5fCZtBCIdZ0cEReCV6u01jD9PAx1YxprGt8=,tag:jtj/WLagoRcPQuL2Vi1cNw==,type:str]
    IMMICH_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:gamNLMsqVY3YiyD+iLjf0USo1V/27WKx8YDt5rrER7S4aZkkL6JZ7yqGymIkqYBnwOGD59rAkX7nx1VTy1qQ56w3uLS3okTSQnC7tCD1J0p9t1UPAsk/02Q32+Z5Hobm1g==,iv:OBtYK5AjM5ZtydFAPgwXC5wopEYqGWWP6w9HAi2DRw0=,tag:I9Ky39X2Hq+xWsQOyfjmMg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaHRQejFmZlhEZUIwTTg1
            RVN6VkdVc0dTL2tGajJyV0pzK08rdjBSMnlJCkVhOXNhZEVZRDlMaW1LZ2ZHempY
            YlJRMTBEMEQyYlRScWM1WlZGdW9YZG8KLS0tIEpRMXQ5elBmRGlGcUlrV2hmNTFW
            V0MyU20zN1NYR09ERXVOcjluZUVWeTQKXRPUj3ihItxVciMhObZTUWMFV1te3M64
            j2cLqoEHqiMs+Zm52FJsSvmbFwSho7lrG+tshJVtk2HG86tRodyN2w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqaTZWYVJxVDlNOWkvekcy
            ZXFYN2ZEZ21nZVRoYk4zalNTUzNod2U3eUdjCmdseGd0Y3UzNWRwMGJtQWRURjQv
            dVA0MFFpa0UwaUI1Q3dLUDJWMXNMemsKLS0tIEVvejB5aHVZdnBzcU1ZMUx4d2E0
            dTVHOHVEUUlQdnQ1d2lKdmNYVHVOUW8K3EEIGWP3GcA4ekD56gVjXMsyptL7ATW4
            FWj10gI8PDn1mQ8swqom3OfWaRh8Os5kyHGUXWiE21Aelu34v58Fiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T15:44:01Z"
    mac: ENC[AES256_GCM,data:DMEBAMClwKWaiU2fois2oAjreRflcR4mQiWFPvKDVjfPCFbSy02pkFL2wCxeZq8bYFHKG6m9OKvyz6frJoEnpzZsNP+Ca3VqfsRggkrza7Vo2JXx77JAB+D1OVoBTQr4GqG5xwbErregZIBPRt9USCjVFMTfM/Bz4bDM1A4+boQ=,iv:dMnLrioqvwYDMQsyTupGj0pZQ9kk+xHLkbLzloMhe4o=,tag:WjE3cd2JFYoRgf2Cosz0ig==,type:str]
    version: 3.13.1
