apiVersion: v1
kind: Secret
metadata:
    name: immich-photos-secrets
    namespace: immich-photos
type: Opaque
stringData:
    DB_DATABASE_NAME: ENC[AES256_GCM,data:976nm8mt,iv:ZGr+dkszm2eOOsg998pmH15E5K1Xl21W7uudkbEYtxk=,tag:5u316H0bKTUZ6RuPB1DBtw==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:txtdmnmS,iv:vngdWYP6BawHfTX8ttdXG3A+jEhUPQcpHNc9mp2gUrU=,tag:CrpCxSFBe1kCq4U/qp48dg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:nweI2/4L5zuemc44mP8yM3LQ6nhgHX7teOd9LjW4c/n4mnaD5pFUT/QqCsLlUJcw,iv:tF4GPP9+QwkjGZ4b1SE8SvKBimWAyJO+aKxCoMZMO6I=,tag:BgPlHMqFv4NJ0PB9rIJ6rQ==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:oUXy2rjGx/uB/pSUQqfq6chbRuD8Ek+s4YbpaRpt+3uScahV5T1DWL229eQOxvAy,iv:59gbbNjgY6/hYwfCcVM0ZQb1CbGy7eqObvBguV7Tno4=,tag:ysQsOkfNunWvIlqyTcDFbg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:25C6Ez9UZ3VbZuEHvrsFjAbgZ3hqARebC8aOed9liN/fx5hpd/grPK1XR8nfaU2+njmIDYxqDXLYe0Cn5uHi0g==,iv:K2pJjXjUKDyCDaHYg36gEkOUfyxi3rOqM0Bxmomwt7I=,tag:DC+v4h530DBFUIhelS9TUg==,type:str]
    IMMICH_ADMIN_EMAIL: ENC[AES256_GCM,data:T2jQGCJJrB9c54b3wWk5uGeyJos=,iv:6i5i6xKwQoQQJy0qzHk+DpXWzqaa5dxY3tJIJmZbQKo=,tag:Dw7nRt5BfzDQshmWavp1hg==,type:str]
    IMMICH_ADMIN_NAME: ENC[AES256_GCM,data:+Qvkt6QLDQA4ZFvs8MpM0h+D9w==,iv:1TYAHIsYHp/M/uIU7uwyzgwz66fIw/xLWlDNkTBVDN0=,tag:LwLbblvEIVnjwk/X30GhaQ==,type:str]
    IMMICH_ADMIN_PASSWORD: ENC[AES256_GCM,data:rn4eDaamKFd6FWTaUDr651861GoUaGOk6I9m9SyZNjOGfwNAhdepC6OurZFA5bFl,iv:CIIjMeTtfzUeekOnGKMfIs6wSY6j3gNSNNlPrjZP8Qo=,tag:I5q+mY4RT1TA7YljLmIiLA==,type:str]
    IMMICH_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:swSiKoGoxoV9feUmfoOXmw+wj60njU2RqhZNFKu4K5g2yDRI9IYFu4cO/oucfVKb,iv:0MixIADga2QAQR0RxHsXqKARUfl5a/105TrMg3Zjags=,tag:x4WiV6Q9mwRuEis567Xagg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0d3duZHMveUJKUlh1dEZl
            aFRqTVYrQkRZV1NqRDVDamg4S2swZTZWL3g4CjhlcDlZODFaVGY3RTBRaGRFR3Zl
            NW9OazQrVi83Mnh1TUZwRGJYdWI1bkUKLS0tIHhlazZjamlEbCsxc0loZkx6VW40
            ZjNVeFJab2l2Qkc4V1VHSEcwOC9wSDgK2p4Nm9U9MejGsDIpowMmlaA45BwcnKoq
            BEUb98fPhF1CNMqubZuj64yquUoM0uEBnWKnTkOEOmB2EUvcFT3+zw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWFdsSnRqM0RFLzQ2cnJC
            VDlmV0V3bjUvTDVLMjFNcVNjbHE4dlNmNTFjClVLVzFkQVJPdnEwYldzNTRoTEFM
            Q2FzRHlzcTRKK3lEVHgxM2VRV25KYW8KLS0tIFdod0xCR20xamNzNmFVQWo4clNT
            Y1NaUnVuL1E0K2pUZk10OEFJWUxkL1UK+RKwGbSC7r/ZymFicPWcjrL1a5H1c4IJ
            gOBJ/lu/mYGUoPbCMWJ83tIalul3mU5QYUQXp/LbZZzH4vag3I/ztg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T15:44:01Z"
    mac: ENC[AES256_GCM,data:lrdBV93pEjHzbf0cKwfhbrEX2kOUwH+Xc6BKBLZ5z5w1rmrOuV5yY0l0aoRw8zoZXDxpn+b0TXWHw01teHm/DwLXPOQS9yHRwnzG8avlefclONIiYAqHJSOIgKRNiz4cDcNlOKT9dVm1H368ZJIklWw2ueoo1hueKXrJp5mRKhk=,iv:aS6vX7b6732n9nQUeWLEfgCM93aJHJaARj/JyQ02oSk=,tag:dT2X6sffjGD5z7cq1OUutg==,type:str]
    version: 3.13.1
