apiVersion: v1
kind: Secret
metadata:
    name: immich-postgres-backup-credentials
    namespace: immich
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:IbEFZ0dsW80JWx4spZDer4rQEmk=,iv:klcbDTljpdt+2QqLhn5d//r8h66+2n+rJhxJaUIrGrQ=,tag:lX3f+dRmK4KgMJv82UY0vw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:CHD4GF8YNl1YHhLk+tB7/PjH5fnKmyFUSxdBLr2MPy3Xo0F4rhF5MQ==,iv:WldvFnGjLhgi8efu4Da7ynv6d5s31wYkzGI6DR1oH1g=,tag:td/mqwD6Cdq6DZWNKNV0MA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:3URxqOLKfmo2AxiTM3JTGbYQSo3xxR+5Bmc=,iv:XHODf8QLURukW18X7NKx+//yQG1053YPOnMKEIGz+Kw=,tag:su8SjYSZPkOJYOS9pahGUQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjU200TDk3dE13cHZaMmNX
            bDZTQWs5Y1dNMURXTFYzSCtlLzd0ZkpvbXlBCnNOZXdYZHJDVXR5QlVvdm1uZzRs
            V3dZRWlHcFl1QW9LL1pvd2lWNGU1SWMKLS0tIGNnbVNOREhuVHFzdURyMVpMMWQv
            N3JDcmgvOGk2SUpydXAzbnRkOXgydHcKQLq3VgTwFlIrCYA7gw+d449wJ/pKSDZI
            U3IBUF5dCrMKWljqa6yjdkHYXe1gmLdV/luHF7SYWeYTfFOIwylUOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNm5wOXJNaE96YTdsSXN0
            WkZyc2tIbGlYeWF1UVVJdSs4Q20ycDVkb2pzCmRLdDZON0ZkblBLNWJqTnlYVEhq
            L2w2RWRKY1JxY3lPeEl0cVlEcjZIUU0KLS0tIDRZMGpkYXZ0ZWJaczUvTCtHZnpV
            ZTVSb0ZndWEwSHpNeWhQNDY4dXNmMVkKeV4x0sehMpECkBMrDEepav+VZ8t1fPR9
            mZjbtC2q8cu6Fr7wdFTuEVvn4jfLqe95rTX8dO1A7vCz2s23PxzKcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T11:30:49Z"
    mac: ENC[AES256_GCM,data:11CRL873X53jB5ATS5FLh2x+E+jFySOKSSbsx9niZQplD568o/dhuepzeH3fIeu5wYNCG3/pPuACZP3ogUnFAOVFPHB9JKwYoI/qKSeEDExcppsThVyYV6uNYiycTHhX6h7ahsZ4DiaL8Np5gYpoyVgkM86C9QOfUxB8JfSzXg4=,iv:uA5ur+AS36T9BmfiRBCN+u7RtsoaqDgu26gRtNV22IY=,tag:kOD08sfbKSf9nTzNOp1GTg==,type:str]
    version: 3.13.1
