apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-e2e-auth
    namespace: media
type: Opaque
stringData:
    api_key: ENC[AES256_GCM,data:7FzLDCMvqUW9wzV05gOsDrnGhnYMhB9UDbzXXIu004/36+o4hWVc0w==,iv:ccGQJhjR3k/Gxcx9ageuvTKu/wse4HCFz8YtZ4BUefA=,tag:yiFQOtHVfU7H0+1cCUmTrw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMiswY1FKeFNjY2Y3NXg3
            b0laSkdKWXBya2d6Q2pTbVN2NGNUa3UyVVNnCm04bzlkUzlXc3c4cjNZMTB3Rllj
            b3hjTSt5Z1RhT2E2V21qak45UWxZclUKLS0tIG1zeGJYYlYxWmpIaWxLREV1WEti
            NzY5dW5WcmN0N29SWG5ISVZkTjN2T0EKU+v2manDJwciFsQ6NbJExGgrgmzqWxYX
            X9N4ocD9somW2resbAzzSuY81QRT85G/Vt4J3o4yN0JKyc+VLEPl0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVS1J4eWRsYWZmNW1Db3Ja
            dHFSdElvS1A0TkxERWUzeXgvMm9DMTdmdXpFCktMQmhlUmMwLzFtRGJ4cEZZQmlN
            a204cURqcTUyMEY5MjlxN0pLNUNubEUKLS0tIGw4b1lIczBOZ1Z3QWE1MWtZcFJz
            Q214S3RkbWlKUHZGbTV1ejQvUTZCd28KSgRJ1d5S3+tzyVu5N5EiVjF6eNuOMmGp
            p+1p2IiPgBEBbeyrH/0be7rOonNJd3kbnfVWKMSMqYDt7t1puzqyBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T10:35:26Z"
    mac: ENC[AES256_GCM,data:WXqnF36nioGNd7dGGGIDECDFfZIgY0445Vv98M+g5gkIfALKTtOBy+x5+EmEX2nQUZIRlB+OR5VqnJzQprM99pTs3RN64SYyokOu7rGIXrr9b0UZZ3IpK5Tb3oaW9lGIupJwQZYHnMaXy6Rc8tHXyF6uRvxqT1e2y0Rq6RQbnpA=,iv:a5twTQlAfG4bL2WcM+Hm+bhmqZMEk64KktdJQ7CQzt8=,tag:kgvxncfdtnzpS5hYJpk1PA==,type:str]
    version: 3.13.1
