apiVersion: v1
kind: Secret
metadata:
    name: jellyseerr-e2e-auth
    namespace: media
type: Opaque
stringData:
    mode: ENC[AES256_GCM,data:BAUWsmo=,iv:XQ0N7YRt1qTaDiJg49LjWG+zMB95pQeWwYawuNRN+Zk=,tag:jmkikB76EvoNRJ/mfMB16A==,type:str]
    email: ENC[AES256_GCM,data:ejP5wcSMSwZvVx0Rh3IB0E07ta/6qu+d3pyEI80z6O2MjUjAjR5qDZGL4DQC,iv:jKpsh97Vt16OX9UxI3+VOJMbq0HwhI1YTGLL4A4q6NU=,tag:xo0gGtdsyfnYGw22Ie3oDw==,type:str]
    username: ENC[AES256_GCM,data:kQPLaLkIGbakV91sSTM=,iv:uUf0XcwO5hTWg7bCZuV0D8o6C1tjwqOqa9/p077J2Ro=,tag:GjzrPwP8i/ZPicFIEdc76Q==,type:str]
    password: ENC[AES256_GCM,data:GB2d5oSv5T3bu2+26SLLqOsWg6ZSTi7K0GWMca4yxEs=,iv:KyZp9ULhxcHSCfD6Gh589Q+6ylGVSSD9JAYhfwe0Xa4=,tag:uya1akg0Xnim7s2CmtlPEA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0elFaM21WOTl4a3MxV3gr
            d1lLQ0lOSUpndVdZMS9aT05lNkwxN01GRkZJCmpxdjB4ZElsYWRpQlFoelhscmhG
            a1Jjb3EwSXh3UVMxN0tSVVJZM0x3ZjAKLS0tIHcrRlNPWnhueGc1VUdMWmplZDBU
            M1hrTmZ0RjFKampDMHdPVkJ4Yk9palkK2Ft2RGK2I4Ah060rvSEt6xDkr+0SzTxm
            KjCD0fRfkRZuzT4hoTLnuH5+dC7Eu1Uc9jW+ONssg3HoilMELdDL9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZnpQRG1qdTZGblYrYk9n
            eUFyd0VqaHZIZDk5ME0zd3hTblB3anlaUHlrCjA2ZU9YT2R5ZDFpb2c3Y3RuSUhz
            MUkrcjJuK0pOTWcxRFgrV2hsbENYbkkKLS0tIGoxK1N3VDJSUDVQNGttMlZhbUZK
            K01SRUtIWVJKWjVBM0RCeG9ydmJNeE0KHx6LNG2MvVuqkFLSDRrWLxp6UUyossE5
            wJO4G4CcgamXlMqI40LFsk3fFA59zLR30gjMpzL8oEEYFn77VLnHSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T14:47:36Z"
    mac: ENC[AES256_GCM,data:5VtwJycWYVQzLeWSUfOIt0KV9Q5SD7cYCsbwnzOEnT4KILRtZpjoPI5S/MWNXe1ZRrGWlu3DRI5N8wprD6xd+1HIaj14vLS2p233oqSHuI2463E/zN1tv1BanxPs9GA1NB7Qjn6TFLPtmGjp901NPdmhy4tCSR37rilQ6Zn2Xaw=,iv:LF265ilYsD8vU44ZZRFlX0lQceXSe7gaY1q5S5s3vVc=,tag:ixGneFUJzR/jfxi+gCoKow==,type:str]
    version: 3.13.0
