apiVersion: v1
kind: Secret
metadata:
    name: kryomat-tracker-read
    namespace: cryo
type: Opaque
stringData:
    KRYOMAT_TRACKER_USERNAME: ENC[AES256_GCM,data:SAgsY7LTxWj72XmoLw==,iv:lc/+cHqVNbFWRxRZfGTccf2tyqeEJLm35jscPiFGU1U=,tag:7SI6Qg49t7VGoIklY6eaaA==,type:str]
    KRYOMAT_TRACKER_COOKIE: ENC[AES256_GCM,data:kz3QAyU9BRKYLqUG1/7guVyvpZDQtt3LSLCaZWknPke7kdB8ohRbbBZKk/nkRLt9SCm4oQsQwJXoHtgyS4+TZqlaU9qdPlMksfw4Mjnz5A9dACF9cx05nOOYCilEeEWrKYCvTGg3cBSnk8dPap3b1vwW/Loy/bR6XqcvuXStBucoFO5sl0uofqQGCQEVByrRCB2qcY2NmP9J1SCfKmMe9YcFf9jOhnMrrTJvDkpKiWZERWsOREB7yrfjp+/qIQdpws1W/WjLDrwTJkLa48Mqm5wHvEpFcaqKwlY2v7tSlrjxZhuuGvcQftLlL28rM1yHjyIHBKERQK/jnEWTALzGHSo6xdjUhu1BgGmcQVzY5T4rhgOaSTt7JKHIENOX5XNyVXG3n2+FXunpZGy5+g7ggHJ5vsinUt04aH6YbwwWZd4cC+7/C8voVfXXPXf7U+s61NgwaO2CqaobdvF38/svN4qKmDEwEm+uMoQ3lc6UssihH3+GkQiin9TNQymUMPLSPnuMyklit0EpXSD0CV71VrelUYv1NxwrD95v1WTLbYAmy3iB5ehPTt3xkLbyqthfu5oAWoaXplt9919iKXUX+o7HdlRwtUMSbsE66vCe24Lv30NTFhaz/bbc0ayCLn7ovgRr0anU,iv:X70KNKeCMoS9Wjda17+nI79VGlKIKPZnaTZ6JZMDzyI=,tag:5PM7VkW+NiKdomXLBsGI3A==,type:str]
    KRYOMAT_TRACKER_API_TOKEN: ENC[AES256_GCM,data:VX7OHBHH/H38SBm9Zy5fkcj1aQhjoomTZfUrlbLBAutdvrw9dnfkKz8LfP3gqMNpYZ065xLUm+WBa33WjK1hLOmOzIZrD5+8B5aePBVCOA/8014fpgbzS+KjSsMG/9KSxEuziQ==,iv:YmO7mN4Tw/YS8By3w75JBBma8+7Dmt046lw/d1Nd5W4=,tag:KzH7O08Jxcn32xNEuPHd7g==,type:str]
    KRYOMAT_TRACKER_COOKIE_NAME: ENC[AES256_GCM,data:HQp+t97VJzG1kpFslcSlDAYqG4GiH5ihd10y0T7F1tvy0Wrn88e3yAUV1WDVl6Hl7JTNyYc=,iv:YKp7xzZ5BpsUi9bqcRoT9MIfU21BUIKZq8vfRUWv6xs=,tag:XKVTpIu0nqZSUsqfs+WpMQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFby9xbWJjZVdVZEE0TTE4
            YXVodmZPWVZxRnBxWlpPS1Z5ZkJPTCtZZjJjClk4SzhZZlVRNVBJODY3SEQxdkhY
            MTFZNFJQdmE5OVd6cWQxWGxqM2szQXcKLS0tIERYU0R1THo3cFVMN0JNSm9tbkpw
            alpnTGdDVnE3bmlzNXBmajdwbmpqQm8KHJHnLLsJJ2vh4D780iuhv5uvpAQQ2Znu
            L1fg67/LR+T/sACpEucDt4gtEGJSbQAuYYOYx3MRDSl+YnAVT6Ye/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMmg4dHVFTFVjTG1tS0hR
            Mjg1Nk53ejJCNzdlMVU3WGVnRnZlNW1VbW04Ckt0bjV4bGxaZTdrQWhpVllzcnc1
            WUk2QldHck9iNlVkRHQ2L0hIREJ1ODAKLS0tICs2V3FYcjNIVUlJYmJOTE1qRFpG
            SUdaK012VHFnTUlnQm5oT25LMlgzTXcKwOMlakDHuUO87ALHCd3pM14cWNCjX46o
            r/4Ko1XamF3uwpIWN+dNMR7cnsKUsEWggPOwWvmptwWfiPeujpsalw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T22:13:43Z"
    mac: ENC[AES256_GCM,data:34zDk/V+P4itp7GNSKUuu1Exo+n33n96PwYNKJdnNB21J9roBYt24NPHPHLM1XpDSKuXjmSdC+64eeTmBJlvB1zlj1ABGeYrsbwxS9V/mqwos5FQCCSt9QguV5OVRXCyrAlgd6i8JB/RPwPYaAx/ek08xhg3Hr1JbI/dsUS1Mt4=,iv:+ilN75CMPP49JMS3rISEgG9yVAFc/kwSINJq8WDsRcw=,tag:Gh6NDxO6NSGDMjdAcQLpMw==,type:str]
    version: 3.13.3
