apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflare-api-token.yaml
  - cloudflare-api-token-external-dns.yaml
  - cloudflare-api-token-mgmt.yaml
  - github-deploy-flux-cluster-prod.yaml
  - github-deploy-flux-apps-prod.yaml
  - github-deploy-flux-app-media-prod.yaml
  - github-deploy-logday-prod.yaml
  - cloudflare-tunnel-credentials.yaml
  - nextcloud-admin.yaml
  - nextcloud-oidc.yaml
  - nextcloud-valkey.yaml
  - collabora-admin.yaml
  - grafana-admin.yaml
  - grafana-oidc.yaml
  - loki-values.yaml
  - mimir-values.yaml
  - tempo-values.yaml
  - s3-root.yaml
  - s3-monitoring-credentials.yaml
  - monitoring-s3-values.yaml
  - longhorn-backup-target.yaml
  - authelia-postgres-backup-credentials.yaml
  - nextcloud-postgres-backup-credentials.yaml
  - immich-postgres-backup-credentials.yaml
  - immich-photos-postgres-backup-credentials.yaml
  - matrix-postgres-backup-credentials.yaml
  - logday-postgres-backup-credentials.yaml
  - attic-postgres-backup-credentials.yaml
  - hydra-postgres-backup-credentials.yaml
  - forgejo-postgres-backup-credentials.yaml
  - attic-server-env.yaml
  - hydra-admin.yaml
  - hydra-attic-upload-token.yaml
  - hydra-github-read-token.yaml
  - hydra-nix-secrets-deploy-key.yaml
  - nix-remote-builder-hostkey.yaml
  - authelia-secrets.yaml
  - authelia-mail-credentials.yaml
  - authelia-oidc.yaml
  - authelia-oidc-matrix.yaml
  - authelia-users.yaml
  - forgejo-admin.yaml
  - forgejo-oidc.yaml
  - matrix-oidc.yaml
  - matrix-postgres-apps.yaml
  - matrix-mas-secrets.yaml
  - matrix-mas-postgres-app.yaml
  - matrix-synapse-config.yaml
  - matrix-whatsapp-config.yaml
  - matrix-wa-config.yaml
  - matrix-telegram-config.yaml
  - matrix-signal-config.yaml
  - immich-postgres-app.yaml
  - immich-secrets.yaml
  - immich-photos-postgres-app.yaml
  - immich-photos-secrets.yaml
  - logday-ghcr-pull.yaml
  - icarus-credentials.yaml
  - icarus-backup-credentials.yaml
  - flux-webhook-token.yaml
