apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflare-api-token.yaml
  - cloudflare-api-token-external-dns.yaml
  - cloudflare-api-token-mgmt.yaml
  - ceph-csi-secret.yaml
  - ceph-csi-cephfs-secret.yaml
  - github-read-flux-apps.yaml
  - github-read-logday-homelab.yaml
  - cloudflare-tunnel-credentials.yaml
  - nextcloud-admin.yaml
  - nextcloud-oidc.yaml
  - nextcloud-valkey.yaml
  - collabora-admin.yaml
  - grafana-admin.yaml
  - grafana-oidc.yaml
  - loki-values.yaml
  - mimir-values.yaml
  - tempo-values.yaml
  - authelia-secrets.yaml
  - authelia-mail-credentials.yaml
  - authelia-oidc.yaml
  - authelia-oidc-matrix.yaml
  - authelia-users.yaml
  - matrix-oidc.yaml
  - jellyfin-sso.yaml
  - arr-api-keys.yaml
  - prowlarr-private-trackers.yaml
