apiVersion: v1
kind: Secret
metadata:
    name: kutschenapp-db
    namespace: kutschenapp
    labels:
        app.kubernetes.io/name: kutschenapp
type: Opaque
stringData:
    root-password: ENC[AES256_GCM,data:GTMz6+k6AtnvqzbsVD3gomenFoP7fclZ,iv:Y0D17iIPFs7jQWehK8IaTJybxKvF+u+hb9AfJ74WP54=,tag:ms/5H5qk5G5XQtXU2O8aZw==,type:str]
    api-password: ENC[AES256_GCM,data:gFCTrNSTqFLwYLtbq468xsv9MPTUShAs,iv:9qv+GG9r5G0MotCzOE8d6+c0m2Kc4CjYw6Adq3lhs64=,tag:AiD8R1cqwqqKqALKVSZspQ==,type:str]
    database-uri: ENC[AES256_GCM,data:L+3x1vFTi3zz7mxV8tgxSs86kEZFYZ/BL40yqemtKrA7szWMRlxDqUdvST6htWgSfLSH+Lv80RVWVv3RawAPOjV2TQvJ9z6dfitxww==,iv:7yiGuAzmJ1YxRYG/UDwgVaQhVrMFN+kgin1E3JfXmqA=,tag:EfHapgEi48O71B/MtCXpmA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcVJ5eHhEVVlSemZVQklJ
            ZGgveFpTbE94aVdtaDIzSVlBY091azlkNlhZCndlRGVVU0w2N2J6VmkzQWxZSXRX
            UmNIcGw0S2x2TkpWWVVHSnJOOTEzUmsKLS0tIDNtNGJmSkQ1SXhUWjZCWXdBNlEr
            c2piSGg2eUk1MkIrSzJ4U0tvMnJPUUkKfJMYFB/2H8yUvizw88jeEbhdI0iwGxzy
            5rQ7akVqMC2C1KexUGjzDCrzhIZ33FZYu9RuEC6SdAIuxmM7EUqZKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHeGJvcHhINWdjN3Q1YTVD
            S1MvT2ZXWGJnZUExSkxBdjVoWm9XN2NkajMwCm1ueE54UjJza2pBZjRnSHl3V1NY
            SGpSZUFPTE05L2ZTeWRENXgrZmNlNDAKLS0tIEhnK25STGMwK01PWGFaUTVadUZC
            Vjk4US85Nnp4TVd3KzhTMGNxYkk0WXcKyYClJHxVyCoxjja9YYi/eUetbDL2RR5r
            EXJRsqO3gPHrEqctET8CI1bRJfN4V8rvUVY6Q4vDwBwakvjy3XWCeg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T11:33:53Z"
    mac: ENC[AES256_GCM,data:UO5WeGwbYEW/35Pgdlq8qAyETBr2sxuTvqq+WeLJAAPw2u2OMGcWZZrgXAkFujRTIYUP/NB23FV6h093zD2xB4dvm1eGpLeRl2aUq9435f4NyBuU24NznUPCbPHr9YIPfgcbqEfFXyZpSMLyl3no+RskwuFOpFv/fsAdsvg60+k=,iv:FG7M+7APlnWTLlYWIAZyziIH9nRhKuRDeY20ZmvzdHE=,tag:dr4YVeIbxgIV6iinU/MbyA==,type:str]
    version: 3.13.3
