apiVersion: ENC[AES256_GCM,data:wAY=,iv:9Zjpn/pL4idnRrj9nuOjq9WqVBpZK1KjxNbEoorjrzc=,tag:YQjx9sGHsac+feHpburQLQ==,type:str]
kind: ENC[AES256_GCM,data:dcS1G11a,iv:MHfEfMbRqC54ZF79+MBS90iUoLBAm0J3qHhRzw/j2UQ=,tag:+HNUhVq3ScWUngFma08vrw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:CQYkxVMBu4t2AjdiNg==,iv:t6CIK7tMW8wgwWL3IDw8hat5OZx/2h4m/z2UDh1Zevk=,tag:L2F5No5FDiuynHzY57QnAQ==,type:str]
    namespace: ENC[AES256_GCM,data:pAy/kcM=,iv:t0kqY9v3RcFyAPqN8QY60yJm//rJFUqef07d4CsnVHo=,tag:Zj5KtAcQegOufTJKlon6mQ==,type:str]
stringData:
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:UjXe7bS7FYI+sW1wKbh8wncRUeYgpFzvJGo5L5rFiOODkKKj0NeHWiWD,iv:S07vyXCkSTNiaOFVaWwM5InCzgpeKyhqp4aWa+NuMdk=,tag:9UP0I09zGlnPLU7Upydj/w==,type:str]
    LLDAP_KEY_SEED: ENC[AES256_GCM,data:NzcOmJqhlk4ISwMoIx0rg9LkBFAo8VTNitB452OIPKBIABcqAcYcDZhn,iv:6a/Yq8oslRX7L7HhfD24I2Hqhm4gwL/+lG9fXFU0vFI=,tag:hI2BcYGXBLiFnJcVr+NhIw==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:q33z0CXQ/dJYzSbItfsacFAq0OtYWRbZ9+x9arJIrQ==,iv:ZEB7ZohcN40DRaB26Xr372GuGNdMOxaxzGAV6JUeA4c=,tag:qvw+VdeTT4XZ3GVQRFxkNw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1M3VTSlpFQjJpNi81M0hC
            aWlNRnl4Q21hOVhkV1dneHFtdEV4dEpsK2xjClJHcmZwK1lIc2w4L0dGbW9DWEZJ
            dUtTTmZmMzU2QnhGeG1NYWo4eURoODQKLS0tIEJ2YVovVFp4amR6VlBGTWd5NVEr
            cWRaTEQyc3J2SXJCTXY1WWcvM1AxenMKsS+lWcYoOsHGCIO7iNBAFlWhJfbN6lNC
            gjJ+e0t2kkPla0fsBdQvX3g32S9QI3h7FDFdtA4saxkX8DmKMs0Udw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RWlVWGowbGczMGZFb09O
            L25XVGh5QmEzUitzYnRzNnZMemlqRW13ZGxjClY0akxpSnBuRlBFS09nNVNabC9Z
            TlBFWklWcEFEMitIaUNVbTF4SklmVlUKLS0tIG1EeVhJMFZJNHJ2cGVPLzZHSmpi
            c0lOVndtQklIYUE4U2VEc0JGUlhqR2MKEo5V5hmn9I8UBfori6xnWkBWlfiRUMUU
            veJDNSeMi1hDiWB0tL0c/bbYHCC3RKsHqPoAik46JB5EvAjVy1meTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
    lastmodified: "2026-09-10T23:11:47Z"
    mac: ENC[AES256_GCM,data:uSytIuvc5vjTJqg13WGwlJAHwyatKO0viQihDFYk1AO82CoYrHUZMZPxGnuE+QMM37qY369+TR0Vhm3YrBzToq2BQxvXas9+fRyQVVExGitegzrmEkhV1Bb2eqrOFpOM+TSW7z3P6zkR7Xu/ldDtvpucwv9HT9/9MD1i/ZsJ5aI=,iv:743k4X6UfkyXYGGe1o4eU2nLxyNSPqnZcr4ONOEyjj4=,tag:3XwTG8Gdj+/ltTTDvWvUaw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
