apiVersion: v1
kind: Secret
metadata:
    name: lldap-postgres-backup-credentials
    namespace: lldap
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:GCjzi20NRYY8WGMHo9Yt/eLrY/g=,iv:/5Le257RRCcywUiUlLT4zxu9AL/4lP2a/tI1vi4tIiA=,tag:4Y3DGY0FanI3KLfAt60VXA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Jztj0K7WfiSiYzSuewMY5TF4cbDf1zqYps3Y3SGk4USdPRU0P1VLow==,iv:iapNmxraP7emO+/fE3KD8tckEzyRVzoqR7aaRuYFQq4=,tag:bg6uiH6D3AHF9tqu7k+cpw==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:OuMlJHL0fFwpf+ZmHTCdKQN8d1v7AuO5dv4=,iv:AC2E12Vwyxqr2xSy0AKX4V9Nb49MJ2RsD5sj+RWHrjo=,tag:OrZCkDHK8PbduIqIqP2RRQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTldqVzIzWnpnNUdRdE50
            cGRhVjc5YU1rRWJzNCszcTc5SVdXdUlxN0cwCnRrcnFNMnlGWklUVGpuVU1Gd24v
            YlBmL29DZ01rdGdaY3o1RlFjaXVzbUkKLS0tIEZ1SUR0SFN3VlltYndLVEQzRWJh
            TXpwUG5oRG5ZQ1RqdDVxU3FSNGZ5YU0K+TOvhf15YIEbsTSM3l/MjR23GkmDy6BX
            ZKHZJN0klFNVP8idAEGkNOWa3jDet1lideh0fxKIfgqrOOZsdn7QQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTFI2ak9jU3BXOXh0bC9r
            U2ZpUHBMOHg3UTdhdDlQanB4QTNtb2tPZG04ClRRN2d1RFZuNGszdVNGemhVWWdt
            YXlITDVEMlplNzYyVGQ5WU9VQlJDUFkKLS0tIFdpTVhtVW1CRkVXZlJqZUJaVGl2
            dElCb040VGExRFRSOUZxNWRCY1F6SWMKE1HxZMtQfleanT1re4tBbYjXgVhMB3NU
            Su2GeNsYpiBlU1jPvtUIQIidccfYu9qQsqiXFmsiOUF5W5UKxtNXxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-11T20:16:02Z"
    mac: ENC[AES256_GCM,data:gGFw62AM09wPVNGmsd23SYSfJ3G3mR89Dj7HSDFJNqLRK5Rm6hZ6LAqHJxNWlIdsnGWYWwq9kVTa6JI0CKtzsHr4NSRyWyezGGnJOejrxSgVY7q5m5Z+zRFNKP6g2zAi3L6VAWKyKRHRf8+H6Qezb46ZIR6HmGq882aXkFZtDDM=,iv:PSKzw+DPeAqYMDUilX5iZwk2I/UD6IZ+a869rnh+Dw4=,tag:bDDZ6PYST2ao9rgYbyYFBQ==,type:str]
    version: 3.13.3
