apiVersion: v1
kind: Secret
metadata:
    name: logday-postgres-backup-credentials
    namespace: logday
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:aTDXk1nb4O7YKqO8DrcD4JK1HEo=,iv:1YQFk2hxPrdcl9Agm1/KK0QXPPUaKH1FEwLdRps5mcA=,tag:Ne/ACWKcqfe1zxHqTiLIGg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:8M8LAabfuUklkQj3OovGtQxewGJp0VUukTp17VNqIc54onap5gbwHA==,iv:hQcyid0RevUNBJxfmq6BwBdEDt3K+AZToY6nv9efxdI=,tag:YWgxBCbvienvMl98I0SCXA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:vHEzWMm9fV58N1Htw1PU/2Ha7d0XQg1rsz0=,iv:GZyzBuFEeQOudlRfio7XKdCKyZH76VUfJ997C0Q/914=,tag:51nLWiH1aj41z3gJsiPbSQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYVNmZ24vVHY0MW9yQWZN
            NHJrcFBKOTFCZU9od2JqNnB5SGFtWGtDU0ZZCmhDcms5TjNBb1IrYnNPclkyL1c5
            NmM4MnFUSVlEU09maW44OEJGM09HOVEKLS0tIE9EandZeWdxRW4xa0JYOVNlaG1w
            YWg0UnRqVXc5eE12TEZFSEhMUmNZRzgKUwkHl87zacfPzdQhgxMezwLqkqmpmya5
            JhFNvU6o3ikhx9EAkqC9gol8dwzUNWlw28qHR58ppsBxbX4Weju2jQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXeU5vZzhhUTdrTFBPMGpF
            QVptdWE1elN5ZkU3dWVOVXhLYnFOL3VCMEJrCk1tV0VEaDNRYlBwckdOWkJLWXhG
            ZEVPVEV4SE9ZeUlCVWZ1M3RjREVkdkEKLS0tIGtJQmxpNmk1VDRUaHpUZzR5aWpH
            SnNQbmNSSk8zQllFUnF0ekh1aGRWeHcKDgOtgPAIcmypwaCtIpKHS1XbA9u88jh1
            beTIqELFxlEIIs0LVtfjT+yvEExapznJ8BT8rqWF/m+PgQVlz03mcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T11:30:49Z"
    mac: ENC[AES256_GCM,data:krYXuH09QmLXi+6tmWfFmrgOomh3pCA6QXBxZRAuSO/DhuXATYg0QAeVHN1CWc8RD4MBudWsSvaHVpI+1mkq2ebjYd4LIxhzszK60OwmxRt94hgFr9Xgt+/3NzbC4w0OLMdK/k2WdIAOWnCPuktcpAKWnYrpyXlCkpp/fUahQbk=,iv:Q018h5KgRXMxfHXpV1PpnYY2WKUAI0LMadWers+XxuI=,tag:OF07rzVB++8yBGxEKj19mA==,type:str]
    version: 3.13.1
