apiVersion: v1
kind: Secret
metadata:
    name: logday-ghcr-pull
    namespace: logday
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:6++K7nKuX2109fECsG/b2cBYsTRxMDcV0a52gPw5cw+uen1DsnE+a5KMNdgsqXyjh69aIGisF/KxKO4B7a3abIsSrNky8mVgUqYS2cY9rj9QQZZxZysjbbRDUY7/z85WrBENulpDKwdWuVEvzA==,iv:PRGUw/dDFcIIPipv064VxeVl7CDM6hSJOPi8Ybd/U+s=,tag:yLmE4zcB6Zx80K/h3g0B/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZnZHVUZ6QmZMMEl0Q1kw
            MG5mYi9MQUZVM04rVkdvZnNsZzd2WWh2TjJFCmJUTmNyWDRaNjFXdzZkYWZReFhM
            cmZmZTExU01XQisxRDF3YmZrYXJRQ2cKLS0tIGdNRWZ3dmM3U3I0R3lLU2c1VWF0
            OUd2QVBqaGJXcDZZR3B4MXNsaklKa00KuMMKCOgYRLQwXZUOxPw0rvxF5GkOfHJQ
            ubhV3raV8tqqx+HlvF5u9S6+kKXbEhL3gTf2jO0+sT74tQLIiSoykg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxakt1L1RtOGlnVmN0UnFV
            QjJaUmFpL1hvWXEwOUVIWW50UVZ3TngxaWdJCjBFYXVpVU94cDVqbFNXaVRxMHdY
            czJYam5FajN0ZXFYV0p2ODFBTzNxZEkKLS0tIEM4VExqaUEyMURmTmd2Q0FDUWJE
            bmJNUWJsZldOT2ZWaGR2dEhUM2QvLzgK/d9/jAinEFIbQbE+X6w3F2qPz73fuizp
            efU6L4Ydc3l8NaQRCKpVHo+HazJQN3wUotnrHagapgllNEbuPasdRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T21:03:01Z"
    mac: ENC[AES256_GCM,data:rqTSaxkxr6F1lQF7Z/Tf3B5bn2b8l/O2QvK8Lvn1hH8n916BRWqkGTeapL4fvaSTts2Z364uLIyaLk83InsDPRruCIb8G/08I3KGa49DZJEt7GQkBpmlU4Uv/6AHKhD/ff8mHt2foFeSjJgnzdT92+ikVXa7xnvPgEq+W5Dzylg=,iv:vsybNe5LflaV1uU9iw8a6F8cOo1TZ+fphUJopI6fAhQ=,tag:/inatzrbDsvOUyVU66u7SQ==,type:str]
    version: 3.13.3
