apiVersion: v1
kind: Secret
metadata:
    name: logday-ghcr-pull
    namespace: logday
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:E+iGoKq9QWnY3m9CKEOP393JrENBxZ69vEGyljelJKDTqDZP382rzNzJi0VwVkJt2n05hyLTgZshUF8y+8Rhu8QdnwA4E35tk4q20S80xEeVyyUDI5yK9gvL1shu8TbSuSmX8yhGsK0ohEQFh17R8mdQkqDYSuHlHdeNEq6g2nY/ocuUmVypWr/3s41b1haROfp72Dfsa7EaCFID1qlG7yhgAv9wS5cL3EULH6AAxEMTM0m8nq242HqMmoCjaiPr+tdiEzie/8O4p/MY1k9dD/xcPDiPXq6jpq4tGt9nN19aGsdnxet8q/fqiQ==,iv:NyPIER1qQ3ZUT3EjxSBaCBRWhMg+e38nFl7I73//RXY=,tag:B3K567lScxiy4SflFcMm+A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBia1k4SXVQUmphZ2dJMk9O
            enMvVHFQdThkZlV5MW40Umt1eDdkcVBHWDN3CkdRRHVFOHMyZjR4UTFZaC9VWlBR
            UkYvcUthSWRZM2JnTjN2Sjh1S2hDL00KLS0tIHFabkgyVVdpZSswb0hseWZDblFp
            SjBDZGszWjBMSU82NWhVdFA3cW1hVUkKhEqtaOJrYgviyvDf5NeV/g4PTMhJyn2b
            SszIICRpbB02gvfSe9MGDCzDRGoUPFSprs+PN7O+8TIPSV7Giqge3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTFEwY3VVd0JJMGV5cnVv
            Tm13NjY0V2lBbm1NL0NRd0xzREUydzg1THdRCkQvZFluU09oenh0WklTVzRTZVZZ
            MUI1a0VpMUthQ25kN2NjdlZ6cUltR3MKLS0tIHZZVkNnSzJKZVhLK1hKTkVwem1N
            NDJFTjhqbEsvcGlHWVZzVXFHWXhVTFUKIhzXjVJanW9Oy1Eokeyxlmfo3H2jzWf0
            OFmE/cuY3/caqLy9VxGi7Ahp/fjb/DCRnoY7pddkpGOyNqj9nNgVow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T15:44:03Z"
    mac: ENC[AES256_GCM,data:OQJa5LsCSpPyKIj12pn/9dCZV64F6KZUJKwkFFSRk/YuVcByA31k+Ww6BOUaovDz8dGzEV1N1gkUguUdJlmpP+s5JTiJYwS718L2y2FCIKnQwHZVTNIIIAYwOHpZT4KxSMwgWYepjZQNgIx9iIxVI8/7WF+W1+NP57h1sn0Kreg=,iv:kvMASBcBxfQU8yw5TJ/isWyp+4v9ODhRN3JfqKuImm4=,tag:Mp6vgHOxier/y+tnXmcblw==,type:str]
    version: 3.13.1
