apiVersion: v1
kind: Secret
metadata:
    name: mailpit-relay-credentials
    namespace: mailpit
type: Opaque
stringData:
    MP_SMTP_RELAY_USERNAME: ENC[AES256_GCM,data:FsiyvahmiITEaYzMoIw8U7J25g56,iv:vFVeleuy27JT5FOFrrfnfp2gGqU54LnmtvYe5rdFaM0=,tag:Ix8g93Br/taGjXcIHh497g==,type:str]
    MP_SMTP_RELAY_PASSWORD: ENC[AES256_GCM,data:kWNSLlw4aS01i0Z/Ub/kU5MjxkNEMyEPbiaMtBqzGrk1uhaRkT1bLg==,iv:QDtNpmuP0jYaY/gAJOG75DeqFeVIIMQpLQVguI0cOPo=,tag:QpVo0e+olAGwHUIv3ofLpA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOb1RFQTVGeTFpdFJRZUFP
            VlB2ZWRLcEpwc0Qzb3JLYWpSZVpJOFRaZEd3CnpURUtkVkdVbzE5QytZcnJWQm03
            TGlwWjd0V1RPbVJvTU1iWERxeUF4bUUKLS0tIGtXa2pMV2pjYmQ3NEErMHlpd2Zm
            cVRTREJRVm1KeDdtZlV1WUN2Y01oU2cKGXvB8wfj8U7T0j/hjJezUuE/xxdCXVTm
            tlfjr/XH5ftsPnM5/WWoNhlNUmL/FBInuepTZBwRAzVsqW2gdN3Q1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINVptdS8zR1pTY01mTmlR
            elNuNTNGZE4veXh1R0JvTjYzbTI4K1AxTld3Clh6YVVqQWcrRlhrUHR6TXN0eTBD
            aUlFdkpsRWxGaFB0c3Y3b3FpdEVPKzAKLS0tIEtuYWcxV25VZDJKbDdjTGE3VlZX
            OFZ2QUlYY2pPeVZFZFJBT25PSUFySjQKkNgQvyqj/SKWgXfwhaFD1YZipbc8Fk93
            UDd7uUGjJqIN0dwEWbSzAKxXud+wBxtKoOQs/nZUA281KtFxiT2pqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T21:23:53Z"
    mac: ENC[AES256_GCM,data:CcAtAnvBFnKC7Z5pnPZeLecbY0ZvbzQ49lZEBXwGQPO+pzhfFN1H9XP80qwBlE3m1sum/YpqiVa235Waduxy9J9yq5KV+nlATvEWWVr4Dton0go5b2zn348LvRS/anXAyMgQ0Tq5LULcx4RvuWXvfbO177AecbXOPz1/QHp1Zjg=,iv:HZ4OgY63slp4wvDHtdACSB9S+icyqh2/HET+8iY4MZE=,tag:f0LqDP+lr3fJmup8umvwQA==,type:str]
    version: 3.13.3
