apiVersion: v1
kind: Secret
metadata:
    name: matrix-oidc
    namespace: matrix
type: Opaque
stringData:
    MATRIX_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:/tVTHC8MjI2qBTOTMymdxOPJB+Nne+FyV2Q0OvtGVbBxBC6M/ocbBhZnnQEY7yNsUswyagL4MWxMCKKDc8GcRndSU22Xs/Of,iv:ravSorAnKNPL3UABLnAkX8UBH5deTX+kAPFqCxIb2hY=,tag:As0q/lrNc0xSfkR/1xeJcA==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VjZoMmp3cWlBSjdHelA4
            Sm1lZmZpQWd6blFWV21oS2ZjemVGZGVTQ3pRCnV2M2tOZVVabzR4c0k1cmNISHdS
            WDR5a08rcEpJOGhtK055cFZSeG5mencKLS0tIDdoUXArdCs0dlNqUTcwUlZzdEg4
            VjZRcTIySTIxWVF6Zng0dUdFQzZLdjQKrDVeS5n6Ee/V7YvDwRUu3E6jB+yF2wfg
            iptn168X6NRVaKe0NWY7Luh+kbNxS4z8LBZZbQRLc//6ltGDLX8hTA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkS1NKeVJHaStHd2lXNnF6
            TXdabHR0UTNTUTJ4QTdCZzhFNE5sdVc2TjFVCjdYNkxLYWV2SUNaQ1J6YlBya2lv
            NFAzRFcxZndsLzREbzhxc0M2TllsaVEKLS0tIFNIeHRyWSs2VUxuUHhnTUdHWjYv
            TzlQQnE5WGJCUHgyMmpIR1BkamI1ZFkKe/jwAltQorRwAij98F7Go35/KswCX+eZ
            ugvqeRPbycAggNoe9cRkBv5FJxbGX2CHtIQ3tHjKPAJmK5MtXjAokQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T08:36:36Z"
    mac: ENC[AES256_GCM,data:EPLVikDMCql2FsVUgfZ9cS91DtlKXQn7a2eJXjcfXtczR9shLpmT1eyXRqD1MTwe/iTVKN5LjR9Jq1OxfdU06Gy9t91cHqObHWIJJ/uqN0moPtJ7OzWgBphIA1Cxx3D8Q89RCgWlbkkAWox097uoc5s10cmyJO0CseWko1wSYc0=,iv:Ib0Ut0/yvaKQxLvJgkZrzpOlasMnJ+VJT6lghtRVJRY=,tag:pfdXwyK4r2L6GEs5mHGXIA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
