apiVersion: v1
kind: Secret
metadata:
    name: matrix-postgres-backup-credentials
    namespace: matrix
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:GbwCjs+CSlEyIV/aiWpffiDh3Jc=,iv:OWkepWqhGg99rfRtCbNyttqniGte0e0SXWb0s0W+ObI=,tag:nwzKty2IotNNBVKq8Z+n9A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:7JYGWOeD/Gt8UI0rlsOCiGiGDodFTDg7YkBcjn1niM4vU3GtRSpOgw==,iv:cVGgUhcRgJxRKLfFwZDCaCA1gGZjIqThGq12cGD7Zus=,tag:9SudOr9+u0V+ji4MR1Be+Q==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:rQVO/dPJxiqsoaeLTks2rJg/e3UXwHVhZbE=,iv:b7GzGVA/yhb0aU62ziZxP95zta6/KIXzsmirdcZnJPA=,tag:IjIe+eHQ0rTKeLxMBKGk6A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMjlZa05xZzg0dmdtN1d1
            QitaSUNIcWRONVVlWHFLazZDVWxvcjdzYm1rCnorK1JzOHFJRlVBTHgyUkJXem9Q
            M3R1TjRuWk9pRXQ1S2tXMXpRc0prZ0kKLS0tIHpuMFlrcHJCUDBVa2c4am5tT1hY
            UU1rM1RndDI3eFhrL3dyR3RWS2MxZFUKf230RnFs74FCa1jy2YmpRGCBZrNXDfh3
            VpTUQuwAhDlJd+SgCMFaJLwVLjDzgzaxMbnkk8HiWg9n04HlFvXKZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBraStySFVkaFhOYlhGYktO
            cnR6Q2R1WE1kcGJ0TWFiZFZ4QnV2K2VDbVdnCk1FQUN1NVczbmtuZmZycmUxUGhY
            RUdnSVdSc1pSRmpRVTlTM3lPeWcxOVkKLS0tIGw1RFIwWjg5aWZHU0dUOS9XUDJl
            aHBwK3JoWFBlUzdKam5wK250OUxIdjAKgjZuvbftntltPB8ct+l9TnrAghd5p/79
            CoNztx56gXCld9Uncm99bNe3fiy244fisufJo86GB2rg66jcJFI/mA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T11:30:49Z"
    mac: ENC[AES256_GCM,data:zcIr8kdyBmIKn0qH4JXiGNGDHzB1b3hXdj399CyF0tIecFUu7Qla3A+lPxgACSIfrpQGTUvB/BHjEI9hK8SKDE/HD6bhPuRL0euyQUdZphBffteefTpCKT+0qu0CJlg6tXA/Akqxu62xfGD/l51yvJgbqDMipl5negL9AgvKQlE=,iv:Qo1uOAxbqm9hvIn0JCchVHWghNQsgYm13HUbZmLxsik=,tag:usIRSaHb8lPS+m8jg7T8XA==,type:str]
    version: 3.13.1
