apiVersion: v1
kind: Secret
metadata:
    name: matrix-mas-postgres-app
    namespace: matrix
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:SNFf,iv:jL8JPqYoc4jFKOFIyA2DmYseLoOD5LeNe01kPQJfPrs=,tag:/JjPTqLBzu/3IhnTyfcjpA==,type:str]
    password: ENC[AES256_GCM,data:EhXxMzmjpK0tx7YC/ghk2Iu4jffCRMT2d/AEHJgVBpKP43fKQoCRW5a2wcpY3SDf,iv:eHgAmBTfKkIkV0n/mk5FP1GhAEvXIluckabNeXfuvWc=,tag:nQc4nxoOxwUWAOxbMVusfA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiMXJlb2ZNWENnU3lWL1ZD
            b0lkUlZUVXRjK2lTcUVKbWtSR3BaTHlkaTNnCkY5RUEzdmd5aGgxUjNYYVZyejhV
            TGpQN2ZrYzM4WlVidWFOZ1U2S0JiWEUKLS0tIFRkeHNwZ3E2M25sRTdhNksxTEhW
            SDV2WGoybDBxSTNmYVlBVHJzeUhDNTgKJrDyS7s+iU9rhsl9ApZ9Y/X9DEfBkU/w
            J/Tf0ZOqhx6ri8xOJIYJfcTycvx5AkyCuZq/8xVxZNHAXv9noZYeHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBad2tpb3ZLVThhVFFrUmFI
            WnVMMzdMc0Y2S2Q5RVMxMEJPQVZkUm83YmhrCjVuMDdhQ2pBRmRZVUlJb0JsMWxi
            QjNoTHRjZllsM01VeDlYTng4V0pYek0KLS0tIHRvUzFzMVd1VXlyU3NKNXBybVkx
            bndNZXhJU0tuV09qaG5VTkFJd3M1S00KZv9sF8tW588wl+3AtjXWNpPQkxI+BUeq
            LxNZH4zcuSl02lVzjQDPBCHiDAAsIEfQk+CxpNfnRY0uAdXwF6wjqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T19:02:00Z"
    mac: ENC[AES256_GCM,data:uQseW3BYmewquevODIMaJxX/78W9TU9nN/9k9sRYMCotR1t2PFTYBq5esyXEqsPagTW/6dI4FPXifxjn9DkTNtwIml/LdQ1B7iq3i9I/Y65Y2kHlZFKsvnBWfiyig4uxnLWGyBqtbmT8ly/9Irt4hZgUle3FF8DXVm6hgPCiiuk=,iv:hO0cYhWoyvIQRElxbBEuv3ZKqnxska7mpY+EC/w9awM=,tag:vu5lyvozKshkyjadVAcXYw==,type:str]
    version: 3.13.2
