apiVersion: v1
kind: Secret
metadata:
    name: synapsedb-app
    namespace: matrix
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:gOwdsPAxYg==,iv:6nlsfGicoG7G6CuC7HJDUaVoaT7Rb/nAjzDIwUaoq4s=,tag:scy3xGGqj0fTHfdQO7yJFw==,type:str]
    password: ENC[AES256_GCM,data:qSD3Pc89z4G49cVtXbFoEZDEiQUCyFsmlIKhOMUPp/xaD+Ygl5hdjApH3yY17pRC,iv:uuRVAPD1uJbQw8zbI1OuV3j97Hk8cwFZJdNULzpf0z8=,tag:Ottqao9wffAND6TZD5Dsyw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcWliTXYrUkZxVkw0QzZ1
            WnA1cGNwQjYreWxqWVNnek9lcEt2N093SWpjCmVORE03dG0weXVrSGRNUGp2WThE
            K2ppN1lUUEZXRmxqOWx1dUkrdGwrcU0KLS0tIGZzTjB1ZzZONy84OFFyUWd6a3Bt
            OEczQys2OFFNM1Azcmw4TFc5Q3RTeUUK1epadO2ssnjr5JtXw6V1nBVuRhicMf8c
            YC3ZoroH6zBZrRPls4TjdvqG64jyO5xWuaWJTnqklfA7NzS5nzKIpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwb3lvV0hWV3REVUV6UFdX
            Qi9yVFVib25aM1dMeGVrVnY1S0d6U1h6SjNJCmJWR2VMR3ZmU09nZGZScTRLQno0
            OWdSczYyYTJsMklVUlNMVkRvbVFlL2MKLS0tIERMRUdST2Y1L3l2N05sL3lpK2Nh
            VW1TYmJtOEZQQXVSaVp5czJLSWxoMUkK3X3fsOsXfPw9VfvqziK7nxNw0++dpJ2B
            U0AvjTqnOLEpw5BFfFF7FeEBi5Q91jdzuKHv6TxKrMpdyvsy1d71fg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T15:44:01Z"
    mac: ENC[AES256_GCM,data:YP3nKAJDEPG3ZsZifwDPCU6KTPFDqe+CfINbWMr/KhUnbf7Zhdecl+LYrzlOnrUJGOqcjDt14hKp4DWkiVlcRUdHarvu3oiUF01HJm07EwC++XqeQuehQAf6qJ0aGyUVUejC6SZiGM5knYmeZDK1bLvp7XXKSnVoSrAUi9vz3G0=,iv:plh7nEiv/Y1YL70vCm4calHQ1nxBdr84KYjDTE9KLbw=,tag:9afbgOcIwMKbnvT5gT3D1w==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: whatsappdb-app
    namespace: matrix
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:1ePta7iQKReTcgc8hFoD,iv:KZtCGj5zMXUH3SX6T0btgNBK8t0K+W/Xvt0m6ixGcj4=,tag:gla4cqDFO3smo9BILhp1mA==,type:str]
    password: ENC[AES256_GCM,data:ILX4nkg4rGnThp/Jd0UJV8RHHHst2iqEzy2tkWR57IN2WxsIE/f0MYXb6sznwTKd,iv:+rSnuvdKMvsHB6dDmci3H+11cMc5cDlCX9gkR0mdMSg=,tag:lPBTQ5Wkqmv8SLnyhlCCTw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcWliTXYrUkZxVkw0QzZ1
            WnA1cGNwQjYreWxqWVNnek9lcEt2N093SWpjCmVORE03dG0weXVrSGRNUGp2WThE
            K2ppN1lUUEZXRmxqOWx1dUkrdGwrcU0KLS0tIGZzTjB1ZzZONy84OFFyUWd6a3Bt
            OEczQys2OFFNM1Azcmw4TFc5Q3RTeUUK1epadO2ssnjr5JtXw6V1nBVuRhicMf8c
            YC3ZoroH6zBZrRPls4TjdvqG64jyO5xWuaWJTnqklfA7NzS5nzKIpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwb3lvV0hWV3REVUV6UFdX
            Qi9yVFVib25aM1dMeGVrVnY1S0d6U1h6SjNJCmJWR2VMR3ZmU09nZGZScTRLQno0
            OWdSczYyYTJsMklVUlNMVkRvbVFlL2MKLS0tIERMRUdST2Y1L3l2N05sL3lpK2Nh
            VW1TYmJtOEZQQXVSaVp5czJLSWxoMUkK3X3fsOsXfPw9VfvqziK7nxNw0++dpJ2B
            U0AvjTqnOLEpw5BFfFF7FeEBi5Q91jdzuKHv6TxKrMpdyvsy1d71fg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T15:44:01Z"
    mac: ENC[AES256_GCM,data:YP3nKAJDEPG3ZsZifwDPCU6KTPFDqe+CfINbWMr/KhUnbf7Zhdecl+LYrzlOnrUJGOqcjDt14hKp4DWkiVlcRUdHarvu3oiUF01HJm07EwC++XqeQuehQAf6qJ0aGyUVUejC6SZiGM5knYmeZDK1bLvp7XXKSnVoSrAUi9vz3G0=,iv:plh7nEiv/Y1YL70vCm4calHQ1nxBdr84KYjDTE9KLbw=,tag:9afbgOcIwMKbnvT5gT3D1w==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: wadb-app
    namespace: matrix
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:jdwUzEiQ9+ZxlN/W4ciX,iv:kNldMQqVy87cDdWkLMLjk5yzyBpZm1TTtAVwv8hD0Cg=,tag:qMkxhfk74GiAIVyYaN41AQ==,type:str]
    password: ENC[AES256_GCM,data:VL7LuTbL6PJaI366yFhRC6xw9wuOTVeI88UBcrxZ9rNYdA29Gy0CwBeiGHqJXGg2,iv:KpvzrABNxzkgGW1Lt/KYXFfvzLVJluvgoB7FzCQ1ERY=,tag:wOB2yntQk+K1czNCYcnyaA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcWliTXYrUkZxVkw0QzZ1
            WnA1cGNwQjYreWxqWVNnek9lcEt2N093SWpjCmVORE03dG0weXVrSGRNUGp2WThE
            K2ppN1lUUEZXRmxqOWx1dUkrdGwrcU0KLS0tIGZzTjB1ZzZONy84OFFyUWd6a3Bt
            OEczQys2OFFNM1Azcmw4TFc5Q3RTeUUK1epadO2ssnjr5JtXw6V1nBVuRhicMf8c
            YC3ZoroH6zBZrRPls4TjdvqG64jyO5xWuaWJTnqklfA7NzS5nzKIpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwb3lvV0hWV3REVUV6UFdX
            Qi9yVFVib25aM1dMeGVrVnY1S0d6U1h6SjNJCmJWR2VMR3ZmU09nZGZScTRLQno0
            OWdSczYyYTJsMklVUlNMVkRvbVFlL2MKLS0tIERMRUdST2Y1L3l2N05sL3lpK2Nh
            VW1TYmJtOEZQQXVSaVp5czJLSWxoMUkK3X3fsOsXfPw9VfvqziK7nxNw0++dpJ2B
            U0AvjTqnOLEpw5BFfFF7FeEBi5Q91jdzuKHv6TxKrMpdyvsy1d71fg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T15:44:01Z"
    mac: ENC[AES256_GCM,data:YP3nKAJDEPG3ZsZifwDPCU6KTPFDqe+CfINbWMr/KhUnbf7Zhdecl+LYrzlOnrUJGOqcjDt14hKp4DWkiVlcRUdHarvu3oiUF01HJm07EwC++XqeQuehQAf6qJ0aGyUVUejC6SZiGM5knYmeZDK1bLvp7XXKSnVoSrAUi9vz3G0=,iv:plh7nEiv/Y1YL70vCm4calHQ1nxBdr84KYjDTE9KLbw=,tag:9afbgOcIwMKbnvT5gT3D1w==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: telegramdb-app
    namespace: matrix
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:LXef4q9fu9v+NlQXtj3G,iv:oxlmuG95xqGMfovw80rJGjI5YTFru2RXHj918DjXGgs=,tag:cp3+lX6fCT6tZyjV1d17uA==,type:str]
    password: ENC[AES256_GCM,data:YAgGx9W5XAzMq/yYphYktqFu5D9PCdULzUlUsxw3JVi7hzamH8GEUZedaxGaEQid,iv:gYZ+Cbux9EWZHCr5GDRnOauCThQPEiUaufdQH2e5GgA=,tag:npvU9sbUUKH0mwEv61n+Hg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcWliTXYrUkZxVkw0QzZ1
            WnA1cGNwQjYreWxqWVNnek9lcEt2N093SWpjCmVORE03dG0weXVrSGRNUGp2WThE
            K2ppN1lUUEZXRmxqOWx1dUkrdGwrcU0KLS0tIGZzTjB1ZzZONy84OFFyUWd6a3Bt
            OEczQys2OFFNM1Azcmw4TFc5Q3RTeUUK1epadO2ssnjr5JtXw6V1nBVuRhicMf8c
            YC3ZoroH6zBZrRPls4TjdvqG64jyO5xWuaWJTnqklfA7NzS5nzKIpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwb3lvV0hWV3REVUV6UFdX
            Qi9yVFVib25aM1dMeGVrVnY1S0d6U1h6SjNJCmJWR2VMR3ZmU09nZGZScTRLQno0
            OWdSczYyYTJsMklVUlNMVkRvbVFlL2MKLS0tIERMRUdST2Y1L3l2N05sL3lpK2Nh
            VW1TYmJtOEZQQXVSaVp5czJLSWxoMUkK3X3fsOsXfPw9VfvqziK7nxNw0++dpJ2B
            U0AvjTqnOLEpw5BFfFF7FeEBi5Q91jdzuKHv6TxKrMpdyvsy1d71fg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T15:44:01Z"
    mac: ENC[AES256_GCM,data:YP3nKAJDEPG3ZsZifwDPCU6KTPFDqe+CfINbWMr/KhUnbf7Zhdecl+LYrzlOnrUJGOqcjDt14hKp4DWkiVlcRUdHarvu3oiUF01HJm07EwC++XqeQuehQAf6qJ0aGyUVUejC6SZiGM5knYmeZDK1bLvp7XXKSnVoSrAUi9vz3G0=,iv:plh7nEiv/Y1YL70vCm4calHQ1nxBdr84KYjDTE9KLbw=,tag:9afbgOcIwMKbnvT5gT3D1w==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: signaldbprivate-app
    namespace: matrix
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:pVVmYtEHLYx5XMMu3A==,iv:0HWH4R8kxB7avd8Xm/Vil3PAvh/GRK7iUGO5ARuYf1w=,tag:3tyU0v6Qk/cOBzXLne7uFw==,type:str]
    password: ENC[AES256_GCM,data:19i69luQX8x+eSaVtI8FzEyZ7i4MNsQWuLLysYsXckvCVZ1vTudqNgf+EbBd9Hjx,iv:pjWJ6jGEPe1xIXlSewGIm+KqkDo4AaB/sMH6fNIQZg8=,tag:Wz99BBrMr+jeK/nDA+JwjQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcWliTXYrUkZxVkw0QzZ1
            WnA1cGNwQjYreWxqWVNnek9lcEt2N093SWpjCmVORE03dG0weXVrSGRNUGp2WThE
            K2ppN1lUUEZXRmxqOWx1dUkrdGwrcU0KLS0tIGZzTjB1ZzZONy84OFFyUWd6a3Bt
            OEczQys2OFFNM1Azcmw4TFc5Q3RTeUUK1epadO2ssnjr5JtXw6V1nBVuRhicMf8c
            YC3ZoroH6zBZrRPls4TjdvqG64jyO5xWuaWJTnqklfA7NzS5nzKIpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwb3lvV0hWV3REVUV6UFdX
            Qi9yVFVib25aM1dMeGVrVnY1S0d6U1h6SjNJCmJWR2VMR3ZmU09nZGZScTRLQno0
            OWdSczYyYTJsMklVUlNMVkRvbVFlL2MKLS0tIERMRUdST2Y1L3l2N05sL3lpK2Nh
            VW1TYmJtOEZQQXVSaVp5czJLSWxoMUkK3X3fsOsXfPw9VfvqziK7nxNw0++dpJ2B
            U0AvjTqnOLEpw5BFfFF7FeEBi5Q91jdzuKHv6TxKrMpdyvsy1d71fg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T15:44:01Z"
    mac: ENC[AES256_GCM,data:YP3nKAJDEPG3ZsZifwDPCU6KTPFDqe+CfINbWMr/KhUnbf7Zhdecl+LYrzlOnrUJGOqcjDt14hKp4DWkiVlcRUdHarvu3oiUF01HJm07EwC++XqeQuehQAf6qJ0aGyUVUejC6SZiGM5knYmeZDK1bLvp7XXKSnVoSrAUi9vz3G0=,iv:plh7nEiv/Y1YL70vCm4calHQ1nxBdr84KYjDTE9KLbw=,tag:9afbgOcIwMKbnvT5gT3D1w==,type:str]
    version: 3.13.1
