apiVersion: v1
kind: Secret
metadata:
    name: media-protonvpn
    namespace: media
stringData:
    wireguard_private_key: ENC[AES256_GCM,data:AsJpp738uf2MzdX5tE0+/Xc4HU50jp33iU5BFTGvj6AFwQHS3zPTw18Q3bE=,iv:+y0IU5YzNecGw+pg7KC+QQrhksRk4eI7rBx9qPLyu7g=,tag:PdA6kjf+3eEIvMEmWQXKvw==,type:str]
    wireguard_addresses: ENC[AES256_GCM,data:SFgI+tSiZOt3kE9Uw8oC0KkejRjpKnaCYoaMHXRa,iv:vhiSGIi/sdqvONL48L196ZLlhOLRcBkv0ykzbsV3Gi4=,tag:TibZrCcWJjJFRPKWqVEUkQ==,type:str]
    wireguard_dns: ENC[AES256_GCM,data:9den0aD5baU=,iv:8GlV1eEBPKHxH25VtvRkgv4lbWzLh8+dch01LH614+M=,tag:KEqMORzlXr5UQ8vKk2ipyA==,type:str]
    wire0guard_public_key: ENC[AES256_GCM,data:63YstbsVB3WGUVWpot/aPPHvUC587VokQJIo1PWxgrhPBX5JWW0ul7XfQo0=,iv:/DBY4ij/S215GnaXTWphumoJVPk2SQ6nuUjVBwzaU0g=,tag:tudfgp1wDZbnpByPcDWGBQ==,type:str]
    wireguard_allowed_ips: ENC[AES256_GCM,data:1QRrrNT/riJVdgOiq4I=,iv:dp0tnIZFhwEGhBX6ODvH5NIkp77Ig8xnuM6IsW8po+E=,tag:SJfnCSNG8Y4FWFhFI9Tobg==,type:str]
    wireguard_endpoint_ip: ENC[AES256_GCM,data:lWkAN/QmSCINh/+d9I09/S+zu5E=,iv:AKgpUKQNzyWT+ARIS8FzRPxV16HN742f5DVk7Or4Gfk=,tag:Kw1jLPPqPS165jPn18w76Q==,type:str]
    wireguard_endpoint_port: ENC[AES256_GCM,data:R1MmNCs=,iv:KHHAJpmTkbfV4nBwZLPlgT77Ic3eHCSI1TcAbxSz8yc=,tag:4OmniIixvy2BhQuQJLJwtA==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRVF4MTJYLzNneFVkY0wr
            Wk9nL2lzWmF2RzEvSnQza1FmdXhwYTQ4OFUwCndwMFMydmExanZ0NnkveEZvOSta
            aElQNmNVa2MwYURFa1pheWxsbmhBelUKLS0tIEcxMEVFSExHci9jR2tCd1E4UFN4
            UTFLOHlwM0VsZGI1cENiamxKazlBaWsKUP8blNC3LNdsP8KP2r4kOExSh92IiCky
            hXqiQbEKdAbBHs/mj2PEfxbjl8spuf0FTgtNG9TeTWG1ynKKp5Hhiw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaN1RSaUMrcDNQN2g1cVpl
            UzJBak9sc1N6Skc0bDFFRnFXdEZ0aVZQTVRFCndVQ2g3bUhOVEIxVWJYMFF0OWg5
            bEhxME42c0IrNkZ4dW1VUno4R3dmeVEKLS0tICtWZ1RwYVJpZ1ZwZHI1WFlYb25M
            MExPNEJNUlA2UmJBdldWOWN3OERkZWcKk0Nky6eOEPRJBAi5O5TUkE9Fq5tUjzmk
            MK1LZJXEavr4rW8BCvao+M+clDuOllUSN0G36H9jtC3F6rymp+dNSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T20:26:10Z"
    mac: ENC[AES256_GCM,data:jR+nUcOeZYC9VXwQQ6rkySTXtETDabE/GnFLpgpSuj6qTtfHy5Aei1ZTMGSERCuETn+hK3F/BRUv/FsEB6Ay0HGuivz0ejLIRThAGMk2d5g0ctmdTPd6xtF0Je7516+jqnI3R5yc2pHUG0pjV7uqrT78458ku1t71zeNKvpE8Qc=,iv:hS7KS0MSUnUMfy3lKnBwFzgpiiS4C34wgt3Z/hecHi8=,tag:zJboMBjf9vdkdaLT35IGBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
