apiVersion: v1
kind: Secret
metadata:
    name: media-protonvpn
    namespace: media
stringData:
    wireguard_private_key: ENC[AES256_GCM,data:XTYkg/YMqkzmCUnnLos5KKP3SvCl3GY0qU4JFFF5nqZIrpmkGGIeRKE2OBQ=,iv:jaQ8wxn8HO8BUWoT5G5Y50S2K5/GLTxLL4byq6R95Og=,tag:NyEZ7piikL2DRIIPiAn6lA==,type:str]
    wireguard_addresses: ENC[AES256_GCM,data:ufKNHrhig2hUvVzBApRWQhbBFubWhLpO1MytobWs,iv:4RXjMoPLGsZ5iDukAehQFnrLnhKKMQ7f7t8EWc1mr9c=,tag:XsEtQbUJbk3zXHE8Guql9w==,type:str]
    wireguard_dns: ENC[AES256_GCM,data:zcU6iG7i60vwrmpa70Ch9bOq9hahd5k=,iv:Ls8I72u5J1riBnTPxxv/iAyHLt7id6CASFG7OjxR0iw=,tag:1wMWE/BpvnJf9Ljz14PTGA==,type:str]
    wireguard_public_key: ENC[AES256_GCM,data:TnJG6llDW4p7oNwCXCfpNPQbWIcf4WPCgHJ8ILjnKP2kE+SblOro8yOKIRY=,iv:gNlTXcXdUqjG4a379jJ0yxnoo4Ma1s8RzUjsZQ3oUHM=,tag:jz2VedaGP82HVomIObtdcw==,type:str]
    wireguard_allowed_ips: ENC[AES256_GCM,data:Eg8nTzrxkcJvyVaDnHA=,iv:QerWyot+vvem8NnepLZHgpxlgQL7dpGXqEpwa8W0nGA=,tag:fAsxOExZ5dkQ2Mg3EWtlgQ==,type:str]
    wireguard_endpoint_ip: ENC[AES256_GCM,data:UMGsv1GAo6xMShgxy3k=,iv:yUfWvOTZ+W/Tqun/bPtmUmtnVlFcm8OJrVL91GR83CQ=,tag:HpL14WAZr2rjuOZysz4Uhg==,type:str]
    wireguard_endpoint_port: ENC[AES256_GCM,data:HZU8rB8=,iv:sedfREjjE7hOv3N3qvLvfJhppnnVg+W1u+FlDinyuKg=,tag:DGGoHOjbePBhFWTLo9lR2g==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdHpPcXVCaDNWcCtYdDFx
            NCtPNTlOWURZamJsWDVrNjVvMC9Xb0d6RTNRCkx2ZjNrKy9PUFhMcVRUUy9zdjBm
            TWtRVUhVOHk0WG9mZ1ltYWlzanBGa3cKLS0tIFpadDIwODZLQWNYWFNhMmpVSjNS
            U1hoM3BnZ1pTYzdFVis0TEVjUlA2NEEKcJ1RKPbJLTIbQdAJbB7tf3xmni1KxMC2
            d/+cY22a14fyVezI7iM8zOtxXc3lc31LqhqS1KVE0QK5E3z0v6nXhQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WENaaGlORTVlSnd6Rmt0
            dE5qUmZJcUJpTGNKbjRtNWJJQmRqbU85bFZBCmVEVkVEMTU0bnNEMG1GeUxVQ1RB
            SFZBa2Q3b2RpbGdtd2QzRXF2d0xrajQKLS0tIGxGUm8zdVRxdkNjc0pVcGMrWENN
            YmZ4enRjRVdmbjUxdGNyb1YvQkYwUjAKw+wkyyGxhpJIDUaOpBXsi1CWVInO5jBO
            LBcBxG1X1xYW0zXreallXf/GJnpWD3VT+Dt+9zFt7hYWdx73aag2bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T21:22:59Z"
    mac: ENC[AES256_GCM,data:Xd2OTMg+4df6FtCasgv1fRetv+Q9BVNQ0B87SWfpG70fW2VvADlwcDbMUrxrQyrpK6ZnSKIvIYcQxznLtL+VBznmTqDzfNwZfEYnMqHP/1K5BTkHtp6DMUboOqUd6MTapOVUz/v20qNB8GLwYmuoufMwmtJvCH5zk2TNPS1TBlc=,iv:/12bjKR4qqdt9g2Lf+4AJ3rus9cYBbItv20gSkdpatw=,tag:kQIHxP1Hg03Fuc+JfQEl4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
