apiVersion: ENC[AES256_GCM,data:JFI=,iv:Jz9S3Ow7gDm/2y/TEoPjjEZoe02tOY3GbqncF7mAHxs=,tag:7d8HUp9k6f8oNuj2+0+HXA==,type:str]
kind: ENC[AES256_GCM,data:rqEbaCrA,iv:4eZWc6PburYox/AsEXRRbak8L98NLoGeC5lCPtqvzmU=,tag:GgDDxjFvWHGLdPmMqtFLjw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nyaeF+7VzDkSYynANYTw,iv:wHTkepM6IuPwZrIj/VEQGduVXFaHq4lj9ufjUhohAJM=,tag:T6gb+UvXd2+knY0bdHoaeQ==,type:str]
    namespace: ENC[AES256_GCM,data:Czi6zc8=,iv:kbOz0VXJxycWuD1lTjCluNWjhkRGsuM7Z+LXxbRVPzo=,tag:4Iv6A1T/hvA0sfJfmLpjXQ==,type:str]
stringData:
    wireguard_private_key: ENC[AES256_GCM,data:X/D+oaTw68lbGLXXOhHVEbjrU5YCdAD2oHCFSmqh6tz1+F0OMyyYUkMAqig=,iv:Iqa659I9b/5Cpo10fK6C3itiRUozFoe2oxAkjdTeSRI=,tag:PJqtxe2qp/zFhSZz9sRWUA==,type:str]
    wireguard_addresses: ENC[AES256_GCM,data:/paGcK5QKgIt1wKhoJekhwHtWjmwizHp7+g7mPhq,iv:Y9QxBv7/EbTZAQW809w62LUEKiH/CEmQ+/pexiJplrg=,tag:YUnm0p33gE4ppZyp+8ISFQ==,type:str]
    wireguard_dns: ENC[AES256_GCM,data:7t1WzLt/0CY=,iv:Z5PQUvAvUuGEZdtZAkG6fpyYpDS6We7mIQT4KwQdcaA=,tag:HAPAUy1GZVZaF7iiltjVTw==,type:str]
    wireguard_public_key: ENC[AES256_GCM,data:Oa7dMH4FXFg2lOOGmMlHCnNSISrnbQhvuiklihXP2a1f8OtAdFC/KyZ78Gc=,iv:fLNUWGvF6Vn3CJnPpeX8AiET25KPUSjh63X5dFxEkUc=,tag:BS2ubSH1QxathW0bP3qy4g==,type:str]
    wireguard_allowed_ips: ENC[AES256_GCM,data:YfdLIBgDwlYsxJy5QUk=,iv:zc4PTK1DDJ1im5MJE5eygTkdRwj5Cq3FdHct89EYJfw=,tag:BvBoTz5Ad4dM1OJzh00G6A==,type:str]
    wireguard_endpoint_ip: ENC[AES256_GCM,data:d/zQrO41NJp71VeCAuM5,iv:hK37fMjFTUiCIZNV3gPGMRrS0prSHAVen5KpPCg7EhQ=,tag:Lil9jDLauy+Mny2GS2ysvQ==,type:str]
    wireguard_endpoint_port: ENC[AES256_GCM,data:1xFZPFE=,iv:Dl11LnzLsApsdkm8X+s9OB2SH6zyr2f/ITdhxlXmk7g=,tag:af6zl+YRQC1ZjCVt48uOKA==,type:str]
    wireguard_pf_up_command: ENC[AES256_GCM,data:JMWe+bCt5TCBAFxI+7t0ImzFVOLMv2qyEwzkfIq+PH3IDFglt6mt192ljfxnBzaMCSDer0eCI6hiJvI+ezxRfGm6zu8JOFGFe0h0rQLuni8yRrzwDKRJadXsgH41gL1uhiKZSvcwKlb93AxR0PSwkTUkRBs4Y4VMnmooKoDyuuHIzMXO+eQGwvPjUHLsOXbFyXHiSCA1F9D4Ds75S+X0GV1dcbS8iyAPRsj2mWtk+mUsrmsE55HR9+1RU5lm2ITYs90RybHvMJ/hoa60I042JDIsnVpKS4Sa1C1gvqQF6HqNu+yD0X0D6G+fggnPanW4wlOfB5kC0any,iv:b78yFecP+NUXcSslfBQILnelXnzEdNmkjtwBfjsdvNI=,tag:9WW/ElfiGjYSTpmwRVQ6Yw==,type:str]
    wireguard_pf_down_command: ENC[AES256_GCM,data:c7O6rdyBMeBrSvJOESx6MR6YT+gnXz3hkjJ/9zMd/bs2OL2TexwPnQEdfAFNW7J+RzFf1Ozv4Ifr+A8Rj+Dculfwd/1Xrt+e584kxIM2L3qLo7KfVKNiBn+0Rfrw1+b4CNQtNBMlR2PA7sqM4rM2gQQcRkhlnTMMSWmiMraTN2AAqIFWj2cBkYP+G7ipaa115VWnvkLv27657a3AUT7todMHgwpjOUSaPY9XENI2eXf8Cb2Ybe+HiBwt0cAgVQ==,iv:se88mKSGd+cQg5PZzA7oU4ENL+PTAlX7rg3oUs+k2Ns=,tag:HxSPSw46Gn+q1IciuTEO6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhYkZpNmdPekQxVkx3Yy9W
            eURVWFYwY3ZuK2NrV1drWmRQUVExOXhnZXdrCnZLTzN0bnJkWnNPSWpjbjJuZktV
            QklIVUhSa0hCQWVybUZ4RmcyWWpWN1UKLS0tIHBvL2FPaTdVTGlzVzFQYnlaeDB1
            RkNyYUsxd0haYlNIUlFFM0puWXJEcEkKcCCaE9kyVsV+QTkyxQLB6uix3fwZojvo
            6cbuLKLE9dm9HOwsU3jCIsfhjx4yU3Z0eJXCqtMfst6/OFMcM2z2cw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RDYrQVlhNTA5b3ArbkZF
            bnlFU2NFV3k5VGVUajBoVGFpb090S0J4S0NFClFyUk5vaERLMkdZRHdlU2VEQ1lM
            N05HdTFmWnl1UU5adkxrN21scTdQaWMKLS0tIGc1MVRLcnQ1aFNVWXc4c1RaaTNK
            Z0NWTFUvc051OTBhdSthakZvTXE5Y1EKim1EKKFUys+f23IN0SBrl+4IOZcqQLZf
            FTdkw4Q2zZ+4gThXU30ARrfqjJ63KBgyRrXWWIfxcENeJMNJw2J4nA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
    lastmodified: "2026-08-17T14:29:25Z"
    mac: ENC[AES256_GCM,data:HPOty3EDtlQBIbwRVBu1W1zlszn19br/hCyze4nCKe04WS/mfKHQZceS/NnKw9ZbJXMj0opouknFBsOPh08tdy1BYG+WhTNlngolm8Br9pwbgossrCyVGiRu72ogcFrmBdBibPTpPU5F1lz1mSEvXUURUveRE+yUQlYec7vkxFs=,iv:aoWYIaFijo83J0dNrBb2TwWfPdTpdJ1pI42iJmk8BdY=,tag:r9pkKmER+ee0EBNEgFsvKg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
