apiVersion: v1
kind: Secret
metadata:
    name: mimir-values
    namespace: monitoring
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:RJM2V4nQFoGLb/v4SuxfZOOJB010bZDmMXNkj1o/F2cNsOXYoWpScyHekFAeaqPUpLzD3R8PqPt2Q47rlT1lwY7O7kbdvOgh/R7JJQ+rZNPN1/inFzPwIWO8,iv:GGKHJ0ixct7Vx2/yVkMx05FaecV8qh4yNuOvynU+BRs=,tag:ucEKJaPcQb8/jKW9m1jGAA==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndzJWRnZ1NkhyL2tvRW9m
            R0IrM2t5L0twL1VWajAzSTEwZVlZVE5Ua0VRCi8vT2oxYTJpdjMraVl3dDlnQWdX
            R2RvQW1jcVRxdk92QzVyZnFjOW9DNWcKLS0tIExmODcrcjZOYXQ4eXEwYjdVWmEw
            MUZkbmNtclRPZENKc2J1ZzVzL284WGsKaA8ub2BCin1DofbDEGvuvYbNHwtBH7jA
            p2HFjuc3a0Tri5l8KQGSZ92OgkhVNtRH+GWL7/Oa/o/mKHz5cMPnAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T04:03:33Z"
    mac: ENC[AES256_GCM,data:xxlO4UiTIIpuvejo1qVkWYF6fs0mxG/k1WjD+cM+mhfAch29NyRx0KCeMAND5ye9Ls8av0UluNVxJlu4+5tF81beTf72MO+OhIVZUDTwaFIjW98wrYgP3JwjiJRmS0w1rhTOS8R/5HPQO9nAknaQl2GJzG5CJGfe/9BcfYAOeBw=,iv:VyYTsTHliITgz1oI12Pn9NYEUKlnBRb2vQew3mGEmBo=,tag:SpoDLoNSdANU6KWa7jUNRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
