apiVersion: v1
kind: Secret
metadata:
    name: mimir-values
    namespace: monitoring
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:tq8zuqXBLOnfpGf24fjE68dXFRys8z7m1zcLmqtHzcgfVmXOHis66KlfvhHJ4swaLUWy6jCaiY0YVUAwA8CteZwqrAZ6NkwVXjwLyoO+o35EcUHIwmYodnK7Zw3QRSJ98IRJ4mtKhy4aA8VBkpGEYj7nzpJnkYqcntHgf2RAhkjkEWjyXp3sZ1ahP0IgRUksSVBZ4Ohi7GUq2kv/sBvtpRdulVTWX36w++DsdNdCvalSqdp3ep+Z+rV4xt3C5mUQKKzydNCMR1+hml00OmRfIPzql45hCpva849FUyupIxo9GgD6irptfSYJ3NXTNQU+wlIqVUrjtVyvmRV6DdQel9QaB0LoL5klRVvyPtEojziFYWSQGLjbxQzo8cajVH9lVb09x0Mt1WUmfDqyEAmUs+8UDRhMkLleFpNx9iqoHhcTi/xdimU86DGTX0F6GQElX+V6ZQYvJs9IJEli7ECu+maLZ7IfbJ4VLp6ZbJ7LxnsWu+cvWUp+Et6KWjdwh1KuFRHPmOheiKsFGSqS2U/I5b6LdHu15NaHctBTLWiRIR0yhsbgqQPpTTrMWsYXwsGRUAqHeBIKZf33KfqWQpcvC/jkwhx5PXpEKywBjID/TbM1k015RfXKE0E5xsYosCG8tSBjCSuEEAWCuyEvqSNd+1Jd7dtoRe+SWs0Q7XFjPMnQqkkI8mCNn66S7z+QS1Pva5emeEWifrV+hsLsZotuIqZbm/FRoXLi2D+YSLJPW+IEtsLuTGp4zGC0hrNdCySZ77cBTnqYvqd7VLDMU49mSpunGOf5Lb91aacwohftS1GiuyKxW7bpAtKKSjm6NmoaYFpLJoP/NBxQc02AakV7ndr2hPZypr471CxN1qoXosqbmNDUhedj5qj1QWSdf3CrRetJFf/puHTFBpsRVWCqwbHCJUofPiYl6TTAtcpaccbWpypZ6g==,iv:CM3UW+66p2ZouJi0HYXfgcJaXRbay3LGcotknFpVwfs=,tag:fmfU7JuMNVC5DE6c050w4g==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQ3dmVitQUEZNWXkxQzlY
            dm5RSk4zSU1qS3c2Z2ZaSjFvbzIwbnB3ZFY0CjZtVnhtWW1Ya3VhQ045dnlZUi9W
            OVcwbnpsaXAzZEVUUDNodlBUZlpTS28KLS0tIDd0RTB5dVh2YkFvNzhqRnp2MUEv
            OUpLcCs0aGYxb3J2ZWtlbmpvZmlUL3cKeFfdhfjaCF8mdSVzoprTK6DlV7v4m5vJ
            5R/m4ca/VHXPHmev3QviKWQkLXbKG7ws6IG5lanc/sk/WIGyA0u+qw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YVlnZE5CM20rczZFS3Ft
            U1VFTm9NRlMzZTdQaEErT1l4OHQyL3ZkMkdNCjNYelZFMFU3a2wvdDl1eEtkMVVl
            VGlUSHZ2UG5kMTU2alQyTGw3R0tVL0kKLS0tIHFZL0RRSFVDNW5mODlYZ3dyaEoy
            aDd4ZEhsVWxrbTJqMlZ6d2FSeC9ZOVkK7DzvHnp6YXXsFEkyQfuWVD/EDwdGt94+
            0sdXjiRc2nqYJhQV7FJyabN0yZdKzRkzg3mJIWNU7ECaEHhT4N59qQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T10:13:04Z"
    mac: ENC[AES256_GCM,data:0oAx8NInuzbOl2vz8tKps/Z0GSekgJE0oeQNh3+msKE9Cs8dZ8tKbaG8gj9dCQ4/LRCPwmMWzZeaHotXlzLoHe3IYrXNR1tQMqRcwOELaUUFN0XmXaO74kr5wDpPrrZ+EEXWfcH4i2Bsxdk3nLN9iojaKKaBK8ZTbwMHXAPdr5s=,iv:X56d7lkK4taHXbnqVwkewkLBprJ48ySMCyzZCk1VQqU=,tag:7OENhhzEd2Wg8e9zyBr8AQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
