apiVersion: v1
kind: Secret
metadata:
    name: ${monitoring_s3_values_secret_name}
    namespace: monitoring
type: Opaque
stringData:
    loki.yaml: ENC[AES256_GCM,data:ZzvgMU/5jbT4vd37KZVYV9Hnw72FD2z+cs8zZ9hLc2fIL4MD1kifEUIlGKuFW0f0LaHlpurWTAThSIm5lS3JxE7YV0rK9i7KB/O/5V124KuP9d/iWzGTw2l20Bf3RxBmWaQ9GPyy4CvdyplNj50nuKqSSDZQmK8N5mju+FL63Oc4iqJPYrNxJhm/IymwjdvRExVcCLI6YYIu1q+/t1B6r8hGxOQ=,iv:BfZRividimu9hA1oPSakj2gSKkviw0SYuz7jmLj14cM=,tag:RLR3bbEPREWtB340cfxXkg==,type:str]
    mimir.yaml: ENC[AES256_GCM,data:bfctcT6qthTAPDdhPvygVqw+TSLVrwrNlyi5aBez1ey0ZSDIn315wfk5J7EI3Z8/4aZt7XZEmN9Z10WQbzC3rsGssZ4tLX1Ss6t7+RNibf0A9PKSsSXD0EUzmV8Z2DrAas6cCB8Uf9id00Lu+CFTvVCzHGXPYVEfX1sgdg4YU27cl8iKIBmV7NdwO3Cg4wSy1ImXL5lhT4pGkzbk2kL+w8XoJaFuNpjF3Zs1ICM2+1xhTS78wLry02c5THh/YEMxfueXJGZn/StfBHVyCfq5tbcBFV6ArCqvvZk6LBSxXJTCx1YJz6ZqGIpww8KOGtQAlCYLMCP38YVmfvnyz4yKu9k4X6BBiBFc6J8XhDSTnRxnvqsrMJ0NT7oKJsyEUEArZtEUc4enL9HuutnmhLSdPwrhguK6090bRiybtVbDTViFBZ95zBQCrP02OKeKm8uIMgU9dzAKlaUqoeaCv7GH1y6C+/M5eOIyB+Jd0hnE0F0vNNA0Vz00SA7mmvU/Z3ARO+zhx6bj2gNure0ogvD6HF/KwNd0dAzdx2cR7BYcr/TZ1geHIk+RyWv2bh6kQrFBxQkRCYkxC3roPcFX2isnsXMqKEumFMahc3+axenKiAddiqtstyU2qJP9lQQ9U3uolpCywxurSd2lph5VAeWNQj4Ijoq8yrY8F1Ok5ntaEYZ0Ud5Qj+4HVCoKGZLQXKNZ7vVtvslLvIepvy2/0Ve5UVC1V3a4Lgqx0egoCwZVPm+7BmSumXLAPLFMqCbLUZBt33xRHg8wXHWdmINTpZ94lQk9UnXDKe/ZKfqNPZmAjM071OtRcE5KwhYJW2/wQ3Fk51yr1T0r7XCuQehug6CtCPMzTL90YFUE4lqG3P8pae9EOWN95pMgZYuIzkw3XDT0Z+DhIn668WDCVxYRoa5HSa/FW8inoKiDFFeY0QDjZaeRZxG4wLjkbG/bDKCeAHAqGkp3bK+a/ekeL4FajAfAxD+uhSgoo1bTnjCSIrvvYvSu,iv:cyLL2rBM+e2fZ1OEOu7U8K/5N6qQ/3svKkHRJXcIVGE=,tag:L13Pg5YQ6hIkufrkzhxeHw==,type:str]
    tempo.yaml: ENC[AES256_GCM,data:ROTRN3e5OmE+ZF8/sUMLR67RlcQqvdQVRPV98Nu7Vq/tnT1IPAtxKtDPWcaAwLCEOoURKfseF6X6AlHuAQBZ5k3ZLeHGiJM14tQu856VcKkqTP5OrWC3WgpGAQM6pwH88MxqBrGJU2z+dQ7YoGCmw8wKu2PDCoxmY5o6qgOuBskNNNeXRGYJPNhRwS2ENQc4/8TV8BS5DAmPMIdmgB4U,iv:T6lRyhd+Rw292DxPSSkEZxwhqkdSIwa9pcru3A8HmLM=,tag:rm7YUErTCNDac94DtWK8AA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCU0NvYlk2TldoOXdQUHIw
            WUpHc0hIUFExc29jUUlkaXNkN2NMam8xZFJ3ClBYazF4SUpnQ3B5L1drRVAyTlJV
            a1hCTnVlWGIwK2ZNZ2FIQXN6ZW90Z1UKLS0tIGNGRjhERlRYa20yK0R1ZmRqbm5M
            SFRCc2Nrd1I0SW1OZmJkaUdFakNoOGMKHUryBxQ8cwjdc1YZLO3NWCNYIglIxeiB
            pr646zoEhI4i4BLqC7DSOcjldhB9YlNAB/MTFSYTqzy/sL78rZsH+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxa1RMU0c2UTNTc3FVWVJ3
            cUFYaGtzbUc5Y0JLSHovejVDbUNJUEl2VDJjCldWVWRtOUcvTzBIRGdLVmxJaGkz
            c2doNUxUa1pab1ZiR2NhNTlWT1NSUEUKLS0tIDRGRHJVMWh2alJXZ09LK2NWRVdZ
            ZWllT05CS2ZuRCs4eklsTnFrc2dieGcK4YI0SQW4XrgTIhN9Uuy3e8wURm1GnkpG
            kha/C5hrLaXIVoT/MkKopuQ60zAU7U+S0Y2/FEhjxHE91nDdEzyXvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T09:14:52Z"
    mac: ENC[AES256_GCM,data:MSj3gldiB3rY+tM1PNlTRCk3yYwiI/Zo2kn9/LfwUDtvG/Tfov8M0D01YIjsDcRBjnJ5iZQu0HyByZxicvtnPyJnO4uqvlbLmRJ/Ik21O4buzlmXZNq3DZiZiT//8D7kfwY7C/j9BEzF+da1cknuQ7XWphBsIJmJwlo+Jn7rwvI=,iv:AkUduHLNLjllwgFEATwHYJ18wrkb+oIBkvlY5onOpT8=,tag:CgSLYUAywqrGzWUruRoLvQ==,type:str]
    version: 3.13.1
