apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-instance-identity
    namespace: nextcloud
    labels:
        app.kubernetes.io/name: nextcloud
type: Opaque
stringData:
    secret: ENC[AES256_GCM,data:leIviQ4unHlGrITrFoC4gNjnwcNbs4ENFw8mqdb/NBoxRt7FNZB4l5+CwIQHnPk9,iv:BuOxce7L+ExZPMe2mEsd/ablcKOOvLZV0SyzrZBFpDE=,tag:n23tqvkqNhl6X1Pd+qzt0w==,type:str]
    passwordsalt: ENC[AES256_GCM,data:hMIrqLZ98ngU9GyoRskkOssn7t4ogxNXufiR/622,iv:JbljU+LlcGSB3V8L7WVPgqFMXWt2zajQG7hlczJShVA=,tag:4oBXv313n5jqoOSoJ2Bq2g==,type:str]
    instanceid: ENC[AES256_GCM,data:lC4E1l2rFYnrqXlF,iv:HXrIzSRK4v1RU2s/Xo/+BL0xzMcDOduNMkidEef6jko=,tag:E+0DlzeJi/HRkMyh9dudQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVY2ZJOHRkMGk5QTV1dnh6
            bnIyL3dvaTlBUWVwa0tuNWtGblFYeStMeURBCnhRd0t6UWY2eEFCZnpTamd6NGs0
            VWdyUU9ObEZLcUROcWJVMXJjNlZzYzAKLS0tIDR4ZXFncy9sQkhsT1d4cTJaaXJR
            eFJwaGd2d3dLbkUxT2RLZEFPNmpJOTAKVvEUEOoc+WSoafAFXpWk16oGShocf/Sn
            uoB5cbxKY0G4hfzWU6IvnTxpJVkeykMB6YmK+hnK7QhAP0aAiw9I/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTmdhVjlUQm1rMWFzWUVo
            aE5ZYXhpWGhUaTVraWFQL2xtdksyR0ZkTjFzCmZWUFp5Rk0rVWlMZndRNGZqUE95
            ZnM1Q3V1Zzc5WldYNEUxVW13OEtCZGMKLS0tIGExTUVBQlA2SUlKQlF3MWdhS0pq
            dTdVUjdsaUU0RFh2bSt0QzlxUGRrKzgKv6oC7JplpkIw3l0dOPYNW9v2bL3x/FTO
            NT1WlUSIlJ1tebL+ZrjaTWs7Gx/jg67SjGNccYWmT8qWrZY7zzchbw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T11:17:36Z"
    mac: ENC[AES256_GCM,data:Z7BehMKrz36lPwuceBtSLkcEcHwcig/in8CM8TfFQpe7NQhZM52fcbRBnhHUMTouVsAVmAtm6t7WP9SKVenZkeEzfkYDtkPW4ngRWmLNdWVDErKsd7biIegqAztAhM+vpH9gMSdMe3rb6zd0i3fpRLatok0B7xuIuuebXhJLY8g=,iv:bLrqaDHjWBskilBX7QaaTaPai0rUFbqexkQGaU3Ekjg=,tag:fVg8xJ2LI+Z+x8GnsG88WA==,type:str]
    version: 3.13.3
