apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-valkey
    namespace: nextcloud
type: Opaque
stringData:
    redis-password: ENC[AES256_GCM,data:FCLGj6JXgcmkmCTRvHRb3hevGqnoVEq2YNh6Uvdq0nO6qZQJfQkKlrr4Hjs=,iv:NBbZR3Nsk6f9LauHTGHeGPaH2zRcUh9eUN8GHnQ/eJA=,tag:W4R8cnPfIm6y7M6Ip5eo6A==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWlJCRjNqQi82cmE0aTlj
            YVU1T1hnZC9FMU5BRkZoQ3NDVkFzRTJCTm5rCktub3daNXRsRUNWTGVtVTJTVEk2
            MUMxazdEWk95bmtwYXNDK0RDWUttRDAKLS0tIExNM2d3QkNlY2wrbFhUaWtPNHFN
            ZGYxT1B2Zi9GT2Y3NTNNcXFLZEJibkEKllgGRqNa95ZBrifGZXj8bk7A3lDdD9Q9
            VpScJDo9HlcEbYZqaCKRToay2cFadQKj5j8ZcbPGEWYtlhkbfrPlHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T16:00:28Z"
    mac: ENC[AES256_GCM,data:1AHt66G5f6nwTvIF4PLc8hC1p5YWD4rHqlR+K8U7SJrG59NUKJmo022bYhU0nxEXk2poxbpzavT4xi3udSgJTfslsbKwF5kEUSB6B7dIslOqI8c8BRzUNcCtfvA8dCDv7McN+vIyK9kB6/K8wkTw8O/tTw0nc6C6SDIlHEbATp0=,iv:TZ+drGknCTSMvpL8naG+9aTf2VHh00fHSmMWjlKlwoA=,tag:UuGfOYwtQoF/1uftLdbx8w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
