apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-postgres-backup-credentials
    namespace: nextcloud
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:H4hhah34QvFIrG4thSqDfCsPDbg=,iv:LqwXmcIvW/IadIaQXduFqucITb+6pvvJZPx3LS6/t68=,tag:nhQbIFTfY+t4xjSWTIBHgQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:KpBF5oyj+ygDNBc2jIE7SJzq9EuTPH+t7ZRjZb2h98RSe7M3w9KrNg==,iv:c3hKrdqmH1tio3AABwu+7yLdlPDjjwZn05jIBJC+wPg=,tag:mArODJSwQ1fK2IALFG2zRA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:ZaoJH/LddwtaYETHZZ3YZlTlcRnKpaNsR1U=,iv:NQeslovHwBOG4JfKGtJe+PdDoyXBI3Fmrp+eVL4uI30=,tag:f0XTGI8EOnE+NZMpJNndVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpYWdJMTAxTFhxMWM2SXM2
            c2t4eFV6QjNUNGNqMFBOcnpKbHNFd3FFUXdZCkNjVHRPc0VhM0NWODhaWGRsUzh1
            czllMkRPd3o1MEFlTUR0OUY1eHltYncKLS0tIEtNT05pYVEvN0pSWXkwOTh3WHU5
            R2YwTUw5MElNWXYzalRjTEVKQk9xeGsKbPF1kQsmVVJ816Aoa9t0nrUPzhQhXErS
            x+SN6YJ9Q/jbg05jTiPZ0P7ehVfLgmSHcBomTbi+H2OKmmbUUzICDg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3a2l3citPUXNmVENJQWFv
            TzNFVGRwNkM3V1BENnUySVRmeEFBZG9adUVrCkxxSndBaklXN0tkWTZkTEJqMEF2
            NGhncWRhbFNWcWphTC9iZDJGcmVrd1UKLS0tIHRIcHR0WXcxNzBuMmtTdkJUYU1O
            M21uQnJzbkxDb0NkdlVaUFNmVTAwR2sKSGeXBVmPLuwlgXEfN9UhSoihPHbP7dXA
            Fl+BY5KbN8rZ5Wz562/yXRxY/lpRuLl5LeEgxIl3jAKxe3xpUs6R1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T11:30:49Z"
    mac: ENC[AES256_GCM,data:knKoakkKu1jFHMwig/fwEwsbqv3Sn4AktyNPnux7jw7MKnr++hiQNLjrhjGC2a63p/dUoJy6GIy3wOX0dm7lrn68rWJianglwuljNOmNx6jCPkd/TaoQXIsycrDNzQTRvJZDIaLCWplJgzd6CloAn+hbJAcubXl7ubaQFlbwvAc=,iv:nangK/eTfENMosNRRB/OxtyRUeLqQrDE6TgHA3FZpFM=,tag:Ft7xXK386hvVlQTJqT9r3g==,type:str]
    version: 3.13.1
