apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-valkey
    namespace: nextcloud
type: Opaque
stringData:
    redis-password: ENC[AES256_GCM,data:W7tThGcVaY3p03GXe/rBt1PDytIbOC/YqSS2qw7NGoL/XJHDQ3VnjArgZD4=,iv:smLiZhZcyBAa5/hnnpxEijwfALPSIaEBq8iw6sSyDig=,tag:teikKM6IyIeYKP1eNBEj2w==,type:str]
    redis-exporter-passwords.json: ENC[AES256_GCM,data:hQ3cEmyG4zL0Bw29ft4MCukqT4dyiWxr6ghTxP/G9ginQlJrJPzYvBN1g2dgXr1Wd0FPO4qdzJVf4T/vFSVtqdMZY5h50Q3jKA==,iv:+E8Kxj/wXwo1OaCMTjRQvsOiOapgLfWgGTl8oW7FFT4=,tag:Pm3EhsaKbojYOo00SV+F3A==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdDkvZUhQNzcxSXl4UjRJ
            cW9hTTNIS2dFMEFKSlNZWWpZL2ZZTm0xc25vCmx5V2ZWejRwbFZnZUREKzdDcXVz
            ZkJIMHhVelh3dmVrcGdQQnV6VFQ5OEEKLS0tIHBqWldxelVNQ2t1a1lCUVRURERh
            SGVGQlVSU1pqQWxMY1Z3eHRSMUw4ZkEKGCqOwnxF9m9opFQFSgLX9ArVg01Wh88u
            34oiRot3WCu/+IuPoPzAh0WlCgwSwQvsfwIgASO5Em6ZXIviG/auIg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRVU1bFZiekpkV2hGT0sw
            b3l3aDVYY1ovTnVrQVRDV1g5MDJUNk5UclhvCkFvL1I0SWZnUE5VYUJNclJ3am9v
            YmIvLzJCMkFkOS94U2RxTUllNHNDaTQKLS0tIGR0T2U1NkNRWUhzcGtmTXFLamdi
            Qm5QQWY1TDNTU3loU1FUQXArdUx0UncKSkgqUsJwBJV3HxFm4lNgXw56XnRxcWF1
            /Pv3ojALTaGE4iTyMOTjznSEgbOAL+GNFVVB3vXo0LGfYLMibqjIqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T10:12:37Z"
    mac: ENC[AES256_GCM,data:2392uWFhFg/4Cs2FD9qE+oDYmR4bHqff+zkGYQ64qHGJMwVBlBwiTjhSr/Fd9mYXgiYg0u/w/vV02ptqfBVCXl0XaT3dGBrIJQJwX5Tyx57gwnKRL/T5VP4/vFsBHRmdualSJOjjBbxjeh4Slh8SNksRvhdCWoM/zUWQNBGJS/I=,iv:dnutRH4i6iZhlBW8s7/5Sb9FC7Z0G0CJw51jo7zuRk8=,tag:weV73Zh3OabYUAjnZYMqBw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
