apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-admin
    namespace: nextcloud
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:Bq0CvRQ=,iv:P6ZDXBrJwJU/M3yrE8LSQYeyFIOs1MZCwLKB6awvbYg=,tag:kWOjbnyrlp5TOXqB4sy8YQ==,type:str]
    password: ENC[AES256_GCM,data:8yi6PXv3LuMZSQlvz3p+J+1cY4HNwFCn,iv:TbqAE4agDW5hqx8zztDI32tsmE4AwlV//RUDCb17nXo=,tag:zxVASYUSyisNSdnwRh10lg==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOGx4bmV1eGtLeC85R3Rz
            SGtmbmVtUm96WDNucUJaditRWVJ1V25WVVZJCnhFSlN0VGhFMnIzREhtdGhGaUJB
            d2c5SHpTdVFIdmpKK1Nhbk8xc01XV3MKLS0tIERPbE9wMWR1a01zWFlvNzRieHNW
            VlpSTElGcmk4T1pzOTAzS3dqaXpvanMKRZfv9hFr7isjeorvZzofYlLvX94xL7CE
            O3n6YWfaFjDGJpUf0WUe3GoLmSJ4fTmh6dpdUy+GfysROS83sZLwdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T21:47:40Z"
    mac: ENC[AES256_GCM,data:VXlCKl28zco/rFSK9yxWrhMOwMs+m06z6hKstUNUx7GzURjaGKvjL/tZ7UJccEAw1cwxthp7O/vTZthm2eA9cSFXaectsrfG0GrDWAisos93cEvmZzdbDkxvrsXqAKkQcOfDXamUYOc9HVov+IiVzwCJfK43b8YDLDXKiFHb8Ls=,iv:IbMx5UosJl6bn2hWHdBzR/She3qc3ngy44sK+OeGc0k=,tag:9YvMdfPWVz9rHadDlcoiIQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
