apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-admin
    namespace: nextcloud
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:Bq0CvRQ=,iv:P6ZDXBrJwJU/M3yrE8LSQYeyFIOs1MZCwLKB6awvbYg=,tag:kWOjbnyrlp5TOXqB4sy8YQ==,type:str]
    password: ENC[AES256_GCM,data:8yi6PXv3LuMZSQlvz3p+J+1cY4HNwFCn,iv:TbqAE4agDW5hqx8zztDI32tsmE4AwlV//RUDCb17nXo=,tag:zxVASYUSyisNSdnwRh10lg==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOFR2NzRqaEFDeUtOcDJv
            OGJCZlNPWFY3ZHBBYTVieGhlVEtVMmZ3QzFvCnNpMHAyUCtLVlBBRlBpSU5RZGdY
            Tkp1d3Bta2kyYk8xbDBDb0ltTHBIM1kKLS0tIEtRbmwzVmF4SEsvN2VzZ0E0dm1h
            K09PMWpIOVI4U2xaemhHa08wRXMyd0UKd5LnlIFkvwBQGuzkyQMtnl/8ivNKGLsw
            xiTMLOmoqJy16ppLn/2hqJi/xDGYndt/cGokXpcZ0qeEMwrNjBav7g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaY010MEI0dE4vSWJWbGtN
            OUh2UmVZMFk0RDI2YjNrdkZPMVdOMkdHOEV3CldrZzIwV29HeHBDV1NCWk9RbExq
            RGxoL3NNRmJDcjFQc0lOM2JrVU9kZFEKLS0tIGIzWVlEU2w3QlJ3Um1QblNTVmFM
            ZE5QMGIrM0pkU2lob2F1L0hyWjZrY28KCqUKcnWkJZKeV4CiJTdBPNlGLVAIAzFQ
            oQD26qMUkjYN/e4/vqZ0APhuqrdzTDqSV6xHqykhi/qERAU+VWARdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T21:47:40Z"
    mac: ENC[AES256_GCM,data:VXlCKl28zco/rFSK9yxWrhMOwMs+m06z6hKstUNUx7GzURjaGKvjL/tZ7UJccEAw1cwxthp7O/vTZthm2eA9cSFXaectsrfG0GrDWAisos93cEvmZzdbDkxvrsXqAKkQcOfDXamUYOc9HVov+IiVzwCJfK43b8YDLDXKiFHb8Ls=,iv:IbMx5UosJl6bn2hWHdBzR/She3qc3ngy44sK+OeGc0k=,tag:9YvMdfPWVz9rHadDlcoiIQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
