apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-serverinfo-token
    namespace: nextcloud
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:ace43tly3DHvNqLjbq2D75sY03V96blu1iMJ6DpdLdUboui9X1g9R+Y4RM/dZe85aic7IqIsoMvwX+B24+5qew==,iv:AiBjnVVJ9WkSJnHTdUMJKHlPHHD7oqhSvPLoz+1OaAs=,tag:4evMmiY44sp35YImy4VVmQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bHRUVWtlTVNQWEF5Z3kr
            OTZWazVQUWM3cXlQaDR2aEhRU2FxZ3EzMlJVClBqcVNTMUJzby9vOCt6cHhZYVJh
            TFVJNVhSb0dta3NCSGQxbmFXcEl4cDQKLS0tIGtBNjhuOTcxczFyMnlod3JpRk93
            eUlaNDFOOUV3REJ5WG9CWjFzSmFRYVkKZ/RdwrCQu9RMiQsqbnb8054sTw/UAoCl
            AKxPhmxceRmhuQtLl4tNy4HLzMIuiKgAFxPkLfSM9F5B1dx9yr1SlQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T15:35:07Z"
    mac: ENC[AES256_GCM,data:y6y7MEq7oC38YE2ETNo0MsSNJIXpoXxZIODuzknNLHgsFtTs1Lu8sUbJUNyH+DLt349mudLxYD/y1cpadt75AGwN1tTpYRD3p7GknWum3i4YzNBJI90h5MbdWXqb+AVxdGTs541qJl62517h0qoCbhKrJOQXrmq818WPzaYHIvE=,iv:IvY22SS8mo8jfX7ma9uNFT6tM66QZikZFZZA/jSaMds=,tag:hKMWDxoAZDl+fsevF9RSzw==,type:str]
    version: 3.13.3
