apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-oidc
    namespace: nextcloud
type: Opaque
stringData:
    client_secret: ENC[AES256_GCM,data:RNDGqk5Tzt1yjnWeodvrEYV4rX383BFVagPn41eFa6j8GYQOLeiTecwfwDXwf6Z/u6MeTlwRDUSS5rklrAcSYQ==,iv:uo0DFmJTMuQYobAb6xUrF4rGArMyCcQ9PrxDX7taC38=,tag:bbz0AvbxCxy3lpn7LW4vRg==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Wk0ra1hkd3prVEJmZjY3
            b0tFWWVJK2FpNXBwZWYreGUzcTVxYkd6RVc0CnNFcFhrZ0xSdzgrcE5mQ0lFZTIr
            TlBzRmVHUjBLK0MyVGlSS09nNGZQNzAKLS0tIGxhWE9zOENlRmdpTVBtclZQbkht
            K0tNdHJhcUFpbnEwUTlQWU9TSzhpVXcKvj/9swEcPZhwWzlh3iDAAKCEwqTC11hP
            SsEa+jHx+4Fmmskg2qi7AXog+CmoDBO8IbzseYIl9O1ssG8YhhjzuA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdVRycVpiQ01pbUZhTXJM
            cjk5VCtnS0lwNzEyZGdVQ2MybFFHdGVLK1MwCklQSWxXZ1VxVWs3WWNMUlRxa2hx
            cFZwY1lOV2FaMmNCUWQ3RHNVV1gxNTQKLS0tIDZLOXMyU1NKQTcyK0p5YlBBbzVG
            bkxXalBWQmlnaXlBa3RCK2txVWJ4YzAKeRQ/m+RxtS/0Piyw3rbpnvE7319Ap9ax
            6TIPcxSynINGpC/TnFO5O6D9gTvCV0payi09QuLhJLUM0gevGkVGIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T16:01:19Z"
    mac: ENC[AES256_GCM,data:k/tVUJhSvvgGZlArSqFyLC2AaQIoSFocItqCp1aymr5DBetfQP6r6lqCisU8T+W/zhTDB0xkf9d9v3e50TP5eLSVU5+tb+h4gkNjpi+D3SSfIrGAeAcXT3ywczPp/MjQdajfAFJhek/TzZlkZwcGMADgh7NoHhDDrSJg5mlkdXU=,iv:tiAMv+/FG7OkbiOb0KJCMLDV9E02rdsFO1iR4K8qJaM=,tag:4aA7v0adzx3FmZ7CeGmxJw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
