apiVersion: v1
kind: Secret
metadata:
    name: ${nix_remote_builder_hostkey_secret_name}
    namespace: nix-cache
type: Opaque
stringData:
    ssh_host_ed25519_key: ENC[AES256_GCM,data:OBJmwLlBpUpAz5BOXKUzyqpEStproQbmP9siJY3gg+S+R1rxn1AIUyvd8b0NJl6rp/2F42R5Azg4SGWWKbBwg1DgDTmNoaNRxMut9Du+bw4m01rtHV6g4dQwdjwL3NR5mHJ9PGzlZn73cvx/womrRMDI2b26rxRkyki11yH1/3iwLsalvg5PQfSWjCPaDMr6PB6X3ITynPnSeTx/HV7jia3cRLXyQrCmwgV5xYGl2lsS7+1K4xe0U5ai5jFu9KpjzLkjcaqNhgB/b25q48MiaFhQBicsWQvS80E6dyRDoPNuDzkyZ5iVE6vOeBKi1Ge6ZBiU7+3m83sb9807K/KrlA4dZDwB+vi0STcLIoj4ZFG9St86TNS7SfQToZiQVUivSSbfQit0/NNtIbn8J58oMlWa8T4EiUyLSOjNZvbWSjXp8qjUu+ntsOeswpFj4DK7wG0vHGmP5QqaYesuIjrfZpoTzmvWEk81lWOR8HuQlT82x5uasrxrMN543Lp2FoWhGzUMxTwo87xMbjVp/OHR4imCXYCePWC1CKbTl5VWOJkst6pO1KJGfBPxcPbTTeI=,iv:k2zQOd78NgOzHcl6M6nWWkEu9IFZbNZaKeKlVP09Cyw=,tag:LUeMMxNkuiCr1//R5Cg1Jg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWTdrWm5aZVhnNlRlRFJi
            bjBCeWJqcGVzVEhNbllvUUtyeldGS1l5ZkRrCldwNkQxV1EwenB6Q3FnNlM5V2U5
            NlI3dlQvSzhhbXVFYzhFcVJwSy9xY0kKLS0tIGZGRDgxMVRiMXlpVDhzeTNFK214
            UmtwamVrMGdEYUdjSUthOThMdmZVUW8KmsGIfKpZOIDMA+E8coFpwwcUvNO78IIv
            7vB0VVf5C+xUc7cv6KngHXLRxiWdHxAU10ryT4LjMeQZcMSxQY2OZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRUdlbHVlWkZtNVlZNEox
            czhmNjVrR0F0bmtTN2Z0ZDlHVGo1bjMra0R3CkJTYUpJOTl5eUlXN3N2K1VtQnZ3
            cmd6a3ZiUXhrdCtKRmdQa2F4Z05TZ3MKLS0tIDAyM2x4c0JQNGNhbzJ6bzltNk5X
            MGgrNlJpYXRWSXpHSXNzZGdOOTMrdlkKwYiF4BzXmYUM4PTV171DeHFR4Hc3/DD+
            tGtN9tJCNwaEc+Iv34IKB99C5tQAMzmXHUxvanKlTSc3iu0uW7TNSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T15:44:01Z"
    mac: ENC[AES256_GCM,data:XeR2K4HczPlp1uwg6EnqCXE3wo9CpD8V7USUPC9eE6pDyjXE+d6qJGD469wtW1zL75jVNLpS9aZtZ7OoEHNVp62knfhNpzmFCGUhzIu8LPKdiW1eUqO/J5n4d/0tRYlPF4kOEDZ6PzNWz/XocEySpizGfiesXMqAZ1urV+O5dG8=,iv:3E42GI6Hb5Dh7i5bxsZCYIWILPr3uphAlhgm++HAWGo=,tag:tu8hWmNlNU1I0z79nzkbIw==,type:str]
    version: 3.13.1
