apiVersion: v1
kind: Secret
metadata:
    name: ${nix_remote_builder_hostkey_secret_name}
    namespace: nix-cache
type: Opaque
data:
    ssh_host_ed25519_key: ENC[AES256_GCM,data:xjeKGaEFJkE0dMm8hB4sjttvoAKXWFXQbO++pzmXofyiwKSXL+uGttVAueS5A0U5HI1hE9kc3kYAIxRF1FvrzNMjglY6HEoyaVhO3Y4U8l++svyF5/p1PTm5eiQhY56WiSnNAhdSAYVSKUZw7UPTyRycgWP/aeK08cDpLxVK6jvaPyQ2jsOdFXkFGCMQtp11yMWCg+j604T2ReI5p3CClFgSfGQ8hJ9Vs/SgUDH+A9KZQJGDiAqwP7FjuQR0dtrbzCSgWv9qYsW/uutseY2SS7Ey9DGN4D30BiOhM3/gxFRMBO3Gwx/D8Ak7SX6CNfceO3CLXdFfsl5ZbTezMQGAGHj+kri7IoAJEujqGc+boKPt2EZeD4gM8CJ6ihEoq8I4oc4+0y448fzdNf+OBPmBQlVJz9H0G2xRSux2bSm55PleaRqhbl5DSPUSV0yE79/q6PofUYp5jmIiwvsRpAmKD8pmNfwvL3SmFcZMBhJtkIlvnf7MiLko3LOlznyJLn8V9Fr7f/RfrWPDo/GIlCrrubEvtAKTQUGLX7QpgH9tGJ/GuhUF3VFAucFPU/yLp7Vh7/je6O3+rHC5daGPEyEg+fhv6nMb7Ca8GyomYEk9e9egVQXwKkNn/1tujYnfkdRyVdiDmPDon4cnRBjIj6FdNsgWNdCUOFhX7YJUAMOSGq2mkderBBjhdPq+C7nCiW0ZqDQQKREEZ4bogikiioeUbINbjC3e36cakS3qmvalrmSHlPzlZSg1idWJZvKmPuCC,iv:2NkPZZIpw8HIkZD4/mz9ouh7CP2FdB8H2acS6wuuzjY=,tag:EouRToPu1aarcR7iKGGWZA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmOEFtM1FQa2llMXo4dWNu
            NU5vS2ViSER5WjUrK29XWXBjSnZ1YS9NeDAwCmpObFBEUDArN3lvWVVvT0RSS0tW
            UmVpNHZEL2xlcm5CSmEwWkRaRUE3UWMKLS0tIGZxdFRZNE5HYmVJeXhFcmVwUWFs
            eDV0T3p6QzcrbGtQbjJCWUp6NHFVa0kKGnb99zFD/wU4AvBJmlHTAnYg+HZqTn3p
            i8Wj0A/A0RndEjJcFcca2FpJmoAAC3d+bizXpweo2Rlh2M7GJEAMGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSHFjMmlneis4cFlIemIw
            eTdpa1NCZUIybWxHWXBPdVFvTStoYzh4OEhVCkl1MDl0SkZxeElIWXZwTUg3Rm9B
            ZmYzSWtrWkJlQjlqOVg0b2tRdkJPQTQKLS0tIHpnRk9GaTFod2N6VCtJMnFXUGRK
            blJXTWNBNFhyZzI2OVRNRndHQmlTM28KnxCS3CNXCzUMOyN3vtH+7Ic6LQOpvUeD
            KI9AdNkTgmr4S3n4KOFkFm5bwUQ06gvDLw6/21cJ8dnhVHQwgMhI7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T15:54:00Z"
    mac: ENC[AES256_GCM,data:Va4G+2xCqiygRKYiNG++UcKGdLySllDGP3IZvG3a7m7vPNYb/LxGvQy1eoQ4jyT0mYdB1I7nXA8CF/vMbJcoHg8fVEcwbFmDOjFefPEo/h8AX4x4T9ID++3Ww7V7G7dc/vGIpoXpYbx0SYcmQe8EmAC7ZAUz6OI3nuy2aR06TCM=,iv:HObXqBaumyZM0bM4Iq0DyjKflUBA04yNY9jBQgFojhk=,tag:xPLIbpSIYxJy80yq+n6GgQ==,type:str]
    version: 3.13.1
