apiVersion: v1
kind: Secret
metadata:
    name: pretalx-postgres-backup-credentials
    namespace: pretalx
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:+HlqiXeg2+RtFzdVBT43PPCj0JE=,iv:LVAHZGJVrSEWsce6joPZQV9qzIsmiEBf1ZiSkNldYI4=,tag:VT01bftQot+W0VmQhxor/w==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Qes3J9rj/zqFlTpp2BP1MC73D50a1BOJX02xzbbb3UfjhdUvtJWInQ==,iv:o21uGvRtMWTyiVGiCTWJ+JgzTRX31lKk8lExeyIOC+Y=,tag:HqE8tHOdxVT+yBuJ23k1Xw==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:aS2YNHl9HTuQppgsmSDxhPQKcwOYo45EB5w=,iv:SRUH3pTGvcDG+YJX9j0FkqZwTiOcVEhAAP3QlHledZs=,tag:we/H2RAijIrn0US88SGJHw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3QW9DLzYwUURzbDFCdWFN
            aDRzVmdLTnBoaTc4eTJVSWJxc1RoMDFnZlNZCnRISUlOMGJ3bGh6ZnFYcGk0blpw
            QnRaaHVnTzJ5YzM4TERFU3NJbFdjSkkKLS0tIE1udE9oRGE0bW13eVJXV3BNSlBE
            dFF6MXQwVzl1ckVKOUE0NUttRmZ1aTgKCTE9CBeo5Q3O7DXmWUAccuZ2BePcZDmO
            ZaNY5Vjv1kcp1GgaqZ+6oEscIJJGU4ZkZrMS5Yu0UJ6PzLS7x0GklQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNV1BKdmViVmovNFJhamxE
            MU9zblJlN1lFSlJ6Ymk3dnZ2ZXEzbnlIUUdFCkxmV25NdC95MHFLL3dwemY3R1dm
            cFRTRlBZNG8vUFgxVms3aHk2UEtmaTQKLS0tIDV0K1ZUeHlPNzhOVGlDbW9Ha0JR
            MHFEZnNoM0ZJd0QzSmU3MUxyVFVvSmsKWJVzNcr0SNUx3xpYMHA7K6DNBPOASBZd
            VzpUkTl93HDuC3/5ZWttUkFgPjm2YH2ibM6f4FqmQfr86gN4/gDSSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T19:36:03Z"
    mac: ENC[AES256_GCM,data:Der4sFD5hSUuDCFNPOTa/CEx54vFMU8a6ZE+E8m6lVj6hMRZNkbKOcrFESXwvpnytBg5xPPiC9cNYBDrO0dpGr4ZnQ4to7OQQAen9YsXWDZzaQLqFcuAcDYs9u0Tkyvl0PXu0p807yXy+tQP0WnjIBLJzVBCaWXM30J+E8AgBJI=,iv:mcip8Gwf1YQeXdMzn2H80N6nc7Lsn4eFiKS+GsWPsHQ=,tag:yGsSoWCYpIhaZvxt0nccQw==,type:str]
    version: 3.13.3
