apiVersion: v1
kind: Secret
metadata:
    name: pretix-postgres-backup-credentials
    namespace: pretix
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:B5EY+dsTgKLQ2E7bxPlR3tiBO6I=,iv:9WrjBsyNcdzm147ka6R7y/WqMtHeygw9zmg0m4eAwG8=,tag:iXIMDDPy8bbDssyllStoNw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:J685OUadoAq8YN9a2wH/MhpduvRN9Fayk+GxQZkRlZVdpYIm8xRynA==,iv:B8+S4aPmXDzcE9JiX4JZDxtvGw0T4gtK8Vw3gO+B5tI=,tag:oz7ZnPuK2hLKkA0dSzlq7A==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:EcJqVk6xLRCntN5v0FaYjghpG/xzm/tQ4yw=,iv:OXrXWGkhhr8PGran9umfDeZ+zDn6dLn1mn1VJX5gXpw=,tag:BMv/WZgave52HBzLIKt2WA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHL2RWZi9oQWVFTXFoN0FR
            ODJHL2d3VWpWSE4raWtLSjM1QS8yZVFzcUdFCkdnZjNTUVN0bUlBMzcyTWhMSmdL
            QWtFa3IvdVpkdXZFVWpqWi9VMVNHc2sKLS0tIHZ3S1VMWG5XMU1VREdTNDJZNm9U
            RDhYTmlUQW5oSElJVW9xWTk2OXZyQlkKovZDxaLmu24ktLvdPVZWFvS+dJSriiqK
            4o5zj9Adg+M3eJc749PlSseoIHpZN5ucJWyofZc1g433AkKK8xL/OA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhV3FpTVBnVVRjRmcyMGRM
            cTN0eFhUbGVXWFYrWjNzakQrUENwRldCOUFRCjFIUTdpRFdFL3VET3Bxd3htbDRJ
            Sm9xMllTcnpwbUp3YVdXSERnVyt0bUkKLS0tIEFKUGxqNjEvRHNDS2FGNDJZaE96
            dnV0aWJPMy93MmVza0VWL0JXNGNCR28KiFDUU4hkmDIJBzrYVBHLbdHmy0s6Ww8O
            IOXbGc8p76sY3LFTZRPF176FRFNRhM5zOreKWQHQnei1xFR5RaieWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T19:36:03Z"
    mac: ENC[AES256_GCM,data:HuSgErFcDmFIIJBT5m7wM+vttSBKbMe/sZVFlruMpkdzUKh66hL8g1tGpgFmIJ1a4tn8Qfz45pPL87a+xlxWynSCTFUA6/kD5foR+hRL9tkFGQWz9OQ1l7UAXj37Khmse1rK7IPARp7xt2e39XfyBc1zgDlxdzLKhoEmvpIbB+U=,iv:hziFeSYlPTMBIXNrrPT4D0NrOZi72hbDmXnaq/TgEIY=,tag:JrjVb9g86m8icwrkwt5Tfg==,type:str]
    version: 3.13.3
