apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-private-trackers
    namespace: media
type: Opaque
stringData:
    flood_api_key: ENC[AES256_GCM,data:MUeX7vu2nGBmYGKJEFNy23IS1jipr/MSLaFv+DbZ30k=,iv:klENRVUz8w10wfvK5EXDdROTWZYEanNpYCkcnw09THw=,tag:2Yczq3XciL1bUF4yjnUthQ==,type:str]
    rockethd_api_key: ENC[AES256_GCM,data:64sFgXJdI11ow7ljxpkxqfdWcCOcQkTleg47JqN1EW+6WS8c/H6gzRkxElLuWFoek6vbXmLAPg632XVoDgvb4jfl7gYPjaXE57aY6bU4SyOU+Gm7PQC/Ggcmp+DVKG0faZJB3w==,iv:xR/WG7qfjyOctob0H0+FONA6cKkUBo679q0+N4e2RiY=,tag:+GXqvuGf6IKdhpxcg95byw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbFpRWWVBYlYzcjlVYmdr
            c2ZZVEIwaUkvWnVlQ1ptU0VuZ3IvVW9UMGpRCjMrUVd3dTNxUGljYzBqeE1LSDZr
            TVVaWTZnZUg4S0NlTHNncFRUQzRXd1EKLS0tIEovaUpnNmpCWlJVZkw5UFNTWGlF
            S1U1UVlFM1g5TXJIaDYrT3pVSktGMUEKh0xtj4SekTXEis2GGCWQnD/2iPc3qs3d
            B0YAklwUJk41xL1D4VoNY5VatkxlVX7z/8dCZkNsn7+RdrSGmwMixg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YUhKK2lVRlpmb1Z3M3VK
            VU1CdHBmQUZoelJEaStJRjlGVUhUeWhwejB3CnA5enViUTRmYjFnTHp3ZGJUL2Vq
            QkVSMGRkamMwcWNxTklFMmJhNkRwTncKLS0tIFNuQlpIeEs0S1A1WUF4YzYyVGho
            aW5iQ3VrRkZ1SVNHRGcweDBUdTNkR2sKp5Ns1YaEGaDfk64eTawnc14617aPRSy/
            JyMfa0zTEUSvR31GofLcvy8q5QcxdQHEvEJXThyxtHh7BUhQET0AHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-22T21:02:12Z"
    mac: ENC[AES256_GCM,data:aCQZPIO29tbtGxgJZJJl9eNR/RquEP/Fm/3H/v0WQdyenBiQpbMtcOLs6qLQx1MvlwIPQKFQR8g5B0N8tQoAvDQzB4MvspeQSoKnKddbpRQ0QW6KUcd3w1KqBA1J+LX8ikqG8erIp5qAdXxpFvZ1NXEdpq/DjNL5zyv3Xuik24g=,iv:zsH3gkzYSRYc7xIYYnt+uU99agceqm+cpUx/T8ULSAI=,tag:VKHPnpGIKQmrrNPStYzh0w==,type:str]
    version: 3.13.1
