apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-private-trackers
    namespace: media
type: Opaque
stringData:
    flood_api_key: ENC[AES256_GCM,data:MUeX7vu2nGBmYGKJEFNy23IS1jipr/MSLaFv+DbZ30k=,iv:klENRVUz8w10wfvK5EXDdROTWZYEanNpYCkcnw09THw=,tag:2Yczq3XciL1bUF4yjnUthQ==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbFpRWWVBYlYzcjlVYmdr
            c2ZZVEIwaUkvWnVlQ1ptU0VuZ3IvVW9UMGpRCjMrUVd3dTNxUGljYzBqeE1LSDZr
            TVVaWTZnZUg4S0NlTHNncFRUQzRXd1EKLS0tIEovaUpnNmpCWlJVZkw5UFNTWGlF
            S1U1UVlFM1g5TXJIaDYrT3pVSktGMUEKh0xtj4SekTXEis2GGCWQnD/2iPc3qs3d
            B0YAklwUJk41xL1D4VoNY5VatkxlVX7z/8dCZkNsn7+RdrSGmwMixg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YUhKK2lVRlpmb1Z3M3VK
            VU1CdHBmQUZoelJEaStJRjlGVUhUeWhwejB3CnA5enViUTRmYjFnTHp3ZGJUL2Vq
            QkVSMGRkamMwcWNxTklFMmJhNkRwTncKLS0tIFNuQlpIeEs0S1A1WUF4YzYyVGho
            aW5iQ3VrRkZ1SVNHRGcweDBUdTNkR2sKp5Ns1YaEGaDfk64eTawnc14617aPRSy/
            JyMfa0zTEUSvR31GofLcvy8q5QcxdQHEvEJXThyxtHh7BUhQET0AHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T06:34:52Z"
    mac: ENC[AES256_GCM,data:ZFgqXjzIFF5LYa1rC6vrBSIf5WDBHE/zQZTFvYekt+4vhpSNvgAS2UQLVOb4IfpOfs9S4EUUHFzt92xVInCvXvGS+Jr0ztBF1LtZ4bnkczDrTMUQtS1s7IbgJ+qvx620Kiy1opWgcGcOISFFuwv8uE+MsmgetgcuqWDV1CUc9aE=,iv:KEHkhyAyX+qwUPEJp3sFu2fFlZL5eMRG/Id3ZK8u9Us=,tag:IutTxplubaLT8J6gMuFVog==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
