apiVersion: ENC[AES256_GCM,data:fZI=,iv:UQ5vICXKSZJOK9U7G2FqTcpImASrS77qbBkY0UtAKgM=,tag:bUDy76oDIgQtwYOO99yg4w==,type:str]
kind: ENC[AES256_GCM,data:i70Bqg2i,iv:JqlsW0geuML7gZKij98gUfvFNAX5HxqxW4zyqgMvwIM=,tag:lRkcODEcLNzt/Ci9WdZUfA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:DeKVNRHntNfA5LuxSg6a6Pc=,iv:oWymFPnVGZxmb8YBeALkiDF5rswd3NOtWcaY6n8yHdE=,tag:fysgHZEXhM0aFL5YG2FszQ==,type:str]
    namespace: ENC[AES256_GCM,data:fKU/DTs=,iv:pF2BUif/3wW/seUM+hkGidSe4kqRJd/4v1GTmS04eds=,tag:A9SXGhLjdCwMFv6vro7enw==,type:str]
stringData:
    secrets.yml: ENC[AES256_GCM,data:YT1duLTRRhJm6Bi0uxXzuocMqxPJ1XBFzOlG5PQqBKRtpX5nfzux5TBHY+0zUGJiHyPpwvqzpvxXoyYqxytMFp66SzZ3c7TDzP3DIFiOU2zPB0xaKtOsiGwshbtp0WWCk9VpNrnoyQT9+/43shZvO9zPvjMNJ6NBXc/kI6vFgeQzYtaS8glZAj2SlDaaF5NbLu+u+9WwinZa1EENK7QYIPda1ix+GLPV9O6k3O+F8j2SB8c8P/0+IqV0BjgGkntc3ObH5wFyBaB8oZ1AwPEpXarlMCmED+1ebQ==,iv:BGhyAUjUfQoP8to7ucZgaDYYl+PcmfvQbbhPFO1FVrs=,tag:GAp9j+fhNg+DRBSiPxwPbw==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTHZKZXdHNlFZcE5IVmxs
            TmxReVROSS9JNnp5Q0hDRjB0SzhWZFRrTFY4Ck5aM01JNDVIbmdDMGFtUkE0TW1G
            MGxHNjdla3Z3R3BsM2l0M3E3SVZIeDAKLS0tIHc4OWxaTE9rOWF0T2RheUMxTS9J
            ZldXVzhRdXBvZ0M3N2dMSEtHSHViancKOinkhF0GLWXciiVBxc/4JHN2KECGU+yW
            jdPawM2jFpjNfWmC5viDB+VlPZ/p8kKD4hNjnahUCNU+VyrjPRyD+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T15:13:03Z"
    mac: ENC[AES256_GCM,data:0fWu/echxNCs/RoHvRWTDysg+ajvSOQMWpgitFHPScqZav6vVQeCrJNAhiUS25lt8fI/mEBYq8NiNV2bSMeMa41DTawWOU/LynScgUC4UDDkcGu3/xNrPZ1inUa694P4ltSSvWxFFJtdkVwVWlHEq8ftUDzFBcqb7fMlW/os46I=,iv:DwZHNLhoGyEWiAGg+Dx/Ta1MN/PFsu46dFtHjPcs0EQ=,tag:lifru/yvjzxldr91lkkcwA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
