apiVersion: ENC[AES256_GCM,data:R2M=,iv:pJaNkAQpKvd8fzidhPsiu/Mue+7ZLwWqihEs+VHS/i8=,tag:MitUXh2NaXrof9DBt2/H9g==,type:str]
kind: ENC[AES256_GCM,data:jK2v1UTK,iv:v90CGbIAatOgWrCtIPBR99HWS8rmCU4GxrEcXbgNZ2k=,tag:23iTFVF6WLRx3wFoWk5rxQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:S9BQD0+vNL1WN1iK9Ld9eFY=,iv:uxDmrrZbsXlPUPG7O2XzzCPZHCnk4jHEcmGZ/9xs8KI=,tag:qMLSdPBOSWYB6oQ8EhTyzg==,type:str]
    namespace: ENC[AES256_GCM,data:hsWFw5Q=,iv:lUU62ULlM3iKg26Zde4MH2xjoI2DlTok6sSdOJ+maxM=,tag:Zy65bjl52Kxod2nLn95G+Q==,type:str]
stringData:
    secrets.yml: ENC[AES256_GCM,data:yS+A/mPhYjZOVUBJ8/pN9hbyhWue5D2O8uRbJnAk695h1W4MVtCApVrrf04knNjy5wGm18gP+wkE+QgvsJvC7O52gOJSMLC/zmjYpblZc4LEQOVoM1TtG4mLSIUMXz8deLP/nkPucnImJBgDIjC/kS4uTW0x1Kl9QKRZVUDnMZ6u5UUxvXHuCFYURrOwaIFfn1YAP+5sX/Q5f1oBaGf3ukSvfxbuV3Xl1JtzFG6HDoFXFV68zugko+QOQzm6ROh7XsVKQd4HH0w1fGgb5fRtWyLMdwS76eERqg==,iv:GqkVHGqZt3s0i7cWKovHe7T0Ty6rwhZ4U26aomtzotE=,tag:ULK4qYpKYZl/avnEpOabPg==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVkFJaUdYUzloYzlNR01i
            N3FsNHAwMGN6NjQ0dkZSVmZEclF5cWZWZG44CnpBc3VnY0l0WGRna2xyeS9BcUdD
            UXdmN3RadDBWaVc3bG9JYys3SXkyS1EKLS0tIHAyYTF5N3hRLzZXMzJPRDF5bWJq
            SmVBUWdzUVl6eHN4TzN0RVpiOE5IeTQKeu5NbYtlmaS6eFDHHggG0x5Yn24sN/l7
            qJY5c4vFucscrtEGQc+wUBYxX9jYK89GtmkAfa7aMNQuLEhxIkPyeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T14:38:13Z"
    mac: ENC[AES256_GCM,data:oXvoJzslz4nA2Nd1LldlZ7xo88cFlbgeHPpOHGf5vUBpJw0Eph6tmNML29pnqX+gugKRFqpd7sdxcjjn/6kJLznDn72si7t4h+kJSOIJskvvq2G8XNkm6eQJwWYyUk01c2CqyhD+os1xjmjegoNMlqv1A/P0Ya2thRkPP/mePQg=,iv:61nJidOVZZ0jMK9TEZhXbBS0X8eG+AH8fxgm5mfkViI=,tag:MsqNFX5qeETtotdjA0Caog==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
