apiVersion: ENC[AES256_GCM,data:l8s=,iv:urJ+cWHJo4Ae8vyG1SQ3rsayCoB2Qy4F4c6qybVnhN0=,tag:U0SvQPPIwPgBEMFgKhHQ1A==,type:str]
kind: ENC[AES256_GCM,data:OU2mVhAG,iv:Tff7sy1LXLBjOGliWtLWJ3BXSSoxhGVs1S1nxC7993k=,tag:YbrjzutwWvHorJUsFs4w8Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NmfEV6FhDnJsvvxR6gBfmUY=,iv:rQnfwX/dqMiShAKfjCBv0ithu74qJQ/FKXurmERnblc=,tag:SsOlFRruGnFBpkhLaOWz9g==,type:str]
    namespace: ENC[AES256_GCM,data:dY5JTOg=,iv:oWiflQhZWrNVgZzUKjohl0yUHGgImT0rK59qscTym5I=,tag:x1Mv4hWYPSKXQ7zgrBWc8Q==,type:str]
stringData:
    secrets.yml: ENC[AES256_GCM,data:UUiOlGJ4/iMjmEEJQ36kkDQQ6jymVRahjAN9s9+qZyX1i9O/1fDD7S4qP7bIgJSEMc90Ij1rFjejRQ4txpmzh+qWZp6x1v3826XPHR7ExbUwPGVpVj0kOavgK+oYu29s+qYH11lXUWYS1XuYzdoSJ/MDQeIoSjuBmsYhyvao+RurQ2xZnQeidmKjqeal/OVMbeqsJCe8tqtIJRSHFSDEi9ZJNManM3MdFQ==,iv:99Hkbvf0C3mHfv/oXFpW0k2eg6JuGe1Z+iHCdNNWcRc=,tag:2DVVSp4zjZwYw05dsNSEEw==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUjJra3dGbFFLNmdjK0g1
            dmdpTEZDLzNqQmEwMjVKME5Ib0YwSXRGRnprCkxOWmxna2k2Y0NOWjYyNlFsbEw5
            TzNTRWdLbS9OaklSVkJ5MlBOd0g3Z3cKLS0tIFpzQkd5UXNtYjZ3b0FkVVQySEdk
            YiticDlja1JqeHFnQmxQUDgxTjQ0U28KizWExqVyeJKP3NBu5O9MaLnRMV+2LpJg
            hEcNNmWnJ34jSQsInbYkujkTyfKctlQGuvjVxMbVxxQJSeyCLaUwwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T09:34:32Z"
    mac: ENC[AES256_GCM,data:b8lfv8Mfj5DAMBI10bDE3e6Dny6M9iYSmi4NzYAlcCyKUeTAPWvAQN7XYTBJ6VOy2MstyJGtfWYzYvTp7GkuJQp1KOZH1GvqtIYrrppnKIchv+8PrGtYyAJDctPifrcW08SbCCIkklKQXDhzThRp5Qk+uUGZZQ8guVyuuwu+4NM=,iv:Ky5i/cQ0Kh7WDb0073ZNWCTe31o3aLOlzHlkUn4A6dE=,tag:2sRB9TnV+mnDTynroi9TUw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
