apiVersion: v1
kind: Secret
metadata:
    name: ${s3_monitoring_credentials_secret_name}
    namespace: ${s3_namespace}
type: Opaque
stringData:
    accessKey: ENC[AES256_GCM,data:eSHYjz0vzYqnAXYYajub0tyGOoen76GDBNM+doCMig==,iv:2OADTKtYT8E75xJchicr1AxNcFyqpUtIaIUJiSRj8oU=,tag:MdueAomqQ30jvruNkqb54Q==,type:str]
    secretKey: ENC[AES256_GCM,data:djfBzP5a1tFGi8NskDuq40hUD803o7IzPHVRLftRUVIz9whxKDlc1/Y2+FfMUUjN6St1HdbP/pLxyG7ukeIrtQ==,iv:XTr0LAugvH0V5FA6IlNcdH/OLD81kHN65c0vAvkvHOo=,tag:it2aaGFmJHv/CZnH8ZX3jQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYmU0czdUNU92MUs0bTJU
            OENaNEpPNVJXNDZDMjMvZHIvbEF3cWpGNHlzCnN3NjVxL1AwcHNwMDRGZkpoZGdG
            ZEp4OWg2ZlkwMWQzenlSakRlNU9sREUKLS0tIFl1MnpzVGhiQkIrOWIzaG10N1pj
            bmpyVnhQek1SMnpTaXVTTU8vNHlBVEEKFHkW5T8VGGnExZi5ICrKm63Pg+QVMHVs
            hgfvIAMgrKf7EaXZOhdRRc9qKjcm2qtkitDSzlgJtbIZbxy5QHJSvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUE9jWklRMWVua2RuN3pV
            bkZndWNjQ0MxSGR3emlaT3JZc1FPMnIvTXp3ClY1Zm0zbWM0dVVHOXEzQktBYXhB
            Zm9zVTA3SzdiNDlnL0tzdndibmRCQm8KLS0tIHNXdCttOUF3Ulc4OG5MM3V4alRW
            d1RYdzFHU0lLTGE2NDdISlNNMmhUeUEKBcXM9TKNUve+VyR1XFXcJ49kOCe1cx3+
            8nXXm1hdMvuLz2LttQWmcg0zXqmwxKUjcbhCY42cFFnYHE5Yu3hZUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T09:14:52Z"
    mac: ENC[AES256_GCM,data:5oIA7fiblRodnhqfxJhjg1rCV9xuWFPvQlHzyembtZycMzqxHSoTu9sq23oDTpNO+F8yvD2ImdEwtR+kC5O40YxLLXh7j6pw0/MXubHKD3URZP6N2YiS+YfU7N98bzznIwTqTo72Hx7Sf7s7Euqz25UNu/xNTYw1ONXzUSw+iy4=,iv:a5k74Rrf3YgY5TJn8go6U3yyxLcAmqDXbBpafK8cvIM=,tag:dWxGZtran5v7EPzGapSA2A==,type:str]
    version: 3.13.1
