apiVersion: v1
kind: Secret
metadata:
    name: ${s3_root_secret_name}
    namespace: ${s3_namespace}
type: Opaque
stringData:
    rootUser: ENC[AES256_GCM,data:5EaCDprVnjeEGQ==,iv:EOA6FCYSEBVluNJS4c5VBslWUPNWVGXfxQnC4ocCViw=,tag:+2GcO6ViUhP0+LPALVAHjA==,type:str]
    rootPassword: ENC[AES256_GCM,data:oVUkHPQ4M7ScQWGQfCOqPzayzfnRJeLIG4lakApJh+9L+IgnzeJow4nh9OQe6IUNxZo5HfToc0vS8blFIAcZVw==,iv:6fGQAZHHD9pHYvs4hdKXI+SsrnrFQjJiQuUACFBVeXY=,tag:cOkDdHX7WlQd0THSg8b+WQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dFlvdVA4MUxZK0Y0N3g5
            RmJoQkE3S3hSWjRqTkJvdGNBZVg0Q2xOZ3dNCjI1K2N3ZW5OTTNpWDkxQ3d5eDha
            cWtZZmx3YUJmcEJqZmFzOTJOOTZzSGcKLS0tIDdVanM5UGRwZzQ1bTBkNmpKS2tT
            WFl1Nks3SUVRd29BcU53c0VWMCtXWDAKu9TyJ8iLI36sK7Wi6ciMgNb9LBa8Cw9O
            u5kCs6g4BVAVnuDA7q+DenymMYiT3AMfjLOPueXdmyEU2qzKw91ZuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WlhFZXFHS2NrdVpQcnJl
            U213ZHViZjM5V0tGejlGejZUckZrQ3Rkc244CmNpYjVwZ3BWR3NPdlhiaE9SRnBn
            WGwwS2I2M1RlZEtLNWpud1VYQXJnZGMKLS0tIDdtbkdDOUhKOTFnRWlBcXFDRnNJ
            OEhjcHExTEJEM25PNmtsTGxSZVdWdDAKUSuiAFu0bNdYm+rev5c7z2pe3TZGWzBn
            rMihEtPS4a+uwZ0tMXf6tK93krUZLBfIDGcefwRMSe9ajTlVL6fFQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T09:14:52Z"
    mac: ENC[AES256_GCM,data:1Zc1yzcHFEqspI7gPAkm/24TUOdWUoTX6/Pdhu+ZUF9H72bKItt91XXISQxKJazsOyEPHe6Lwd28zG+CCB4nAUaNEVsPrTjYEhSq7Z6l2UuC8IlptkMcZNh1Qm0pwSqHSSABUCoD0qF+ySsS/I+U4Si797xlZkcM9pG4AA3jQ/Q=,iv:r8td+MacyuNacPYEUTlK5wSQXx0yqndaOhxUqQY10VU=,tag:UhioFrl09Kg6t2cFBiypqQ==,type:str]
    version: 3.13.1
