apiVersion: v1
kind: Secret
metadata:
    name: selkies-desktop-auth
    namespace: cloud-desktop
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:SeFN1VpBg9L2/9YbSA+392IKr5+74jMJ,iv:MRRSzxy5N+Lk1C8+0RXGQ+bwonIxRwYOg+833NQKJYY=,tag:LYSBszwdbUsg+N+GMMd6Yw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VDRNOW5DeDlSOGJzSFp3
            QmtNbG1GTnBTbGFNU2gxT1hlMFUwelhtWlRVClJuT3JRUWIyV3BwMStaQXZZSExh
            b1ZRZWg3Si8yOE9QbWZkaDM5ZkdTVVkKLS0tIGxEeFpRNW81NXJ0enk0YWhTZ1pT
            RWpocGZKaXR1ajJIeHZ6Y1g2SjNDbDgKWgvbTe75iNWW7uJLKyka2QfQQ/t2Auqu
            Uc7pex1FFRamM95xIhBpj1Qzpp6YgxLcfoaRD4u2qx5tcjpMBB8lYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdjdpL3AvZWhTUGVFdDFK
            enRua0RHNCt2enV4ejI3UG5OQ0h5TTJsSkFBCm5Xejg1VWk4MlNkR3BwSXNvWWdD
            bW44bXZwZFczZnJVVVNIRTQ2VVdOTDAKLS0tIGNaWUZWL25Xby8yWGR3SGJwaU1U
            djJ0ZGM0b2N2WGZJNUpWSU55cjNSMUEKoZjFTAvUUTbKyB4vVDbDIdrU1Cu39ezB
            ehl/OzEyxrO6LkIbfcU13HMIaL2AKprL32KDRbz3i1g2pxmTCb0/pQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T10:17:48Z"
    mac: ENC[AES256_GCM,data:IklS/hkA/4DWSqnDcm03L+CNaVJbWsf4CGXZh5VLQUdWfmjjZmZr0NYfajZzEsSAGN0KLAELPQtc0ACtHQs3d6hPUNYKuGHvoERFWEJW3vi3UnUfQgitSkHOsCQ2zNZ6pMm2vwkrK+MrB+9Ns05WBvXnvTbuvaonMzutXpYnQbA=,iv:E193TFWA8NurLKpYGIFZdBbhyN+OoFd4fmeyFQjZ2iQ=,tag:SxiKPoZ3U7zYkWMUpdtKzw==,type:str]
    version: 3.13.3
