apiVersion: v1
kind: Secret
metadata:
    name: smb-accounts
    namespace: smb
    labels:
        app.kubernetes.io/name: smb
type: Opaque
stringData:
    ACCOUNT_printer: ENC[AES256_GCM,data:FsufDRGZzURjSRiFMRLc89X1aGrxrnS1gpiKoYV9ea97hm9q9Td4ljoRhc2e5UHX3PdYXQB5sHrG3+ehfNd831OTkwFh6yhQbfoKmatXJdpiR9BiATYoYPhMx6qjId7wgA==,iv:/bSPVZAYdmBCtIJFQ/93+Bvj8pWNpYbmNsIBlSd5fDk=,tag:rDXdnKZC916IpaUzZex7Eg==,type:str]
    UID_printer: ENC[AES256_GCM,data:nlBVow==,iv:K5J1esTolAxewitTWOw8kO9h5z6swcPOeWjexlypz8s=,tag:43nBZs54Tp9q8oRnIepfCg==,type:str]
    GROUPS_printer: ENC[AES256_GCM,data:bZd7RA==,iv:qIbAiqi8+Y8EaXvzwdvmWHhm3FcWRARu+8yobNGMmGE=,tag:VTKMInL68ZrPe1WxLwFr2w==,type:str]
    ACCOUNT_nextcloud: ENC[AES256_GCM,data:Zw2jDW9mJFwkDCGK/r+Db2hHIAGet+Fnd3OYw619LwmZb6vAtqQ2FWUXgLpThqwFibdNMUso3zA6DVxV6Ou8QKAfaNlVmeE/65il4192is7CXv2lStdmOxfu+IoUwCnPfnEy,iv:Td0UuUN62j1++OxfFMPt6o8IUg0ZA93jUiTUq9k2FDg=,tag:aqgaOFDXpEdCqDptdlAsaA==,type:str]
    UID_nextcloud: ENC[AES256_GCM,data:lEu7OA==,iv:jGhFD/4fb7Wa7xoO5pqJ1G+61QvZMsUwsu5jL96sF54=,tag:4hIGCaiK1f35wzSL4rmIAw==,type:str]
    GROUPS_nextcloud: ENC[AES256_GCM,data:2cNC+Q==,iv:QmL5xGOjXEXXf6x9YAEATzEAgoNGw6jKEHpF3YKKF80=,tag:ReknJQVmMIl5oJ69L3GLqA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4T3dKN3lyRTdlcEFJY3Fu
            T1dWVktvVkMzNzVQMllNeFhyeGNkV3J4ZFJJCmdldlBUNC9WelZuMTdTZU1OL3BE
            LzZoNW5zdVZ2MnNqSFlGaUJndWM5K1UKLS0tIE01MDVQUDJBVmJJYnZnaXkybUVa
            bnJKb2N2Zmw5dFVQazJIT0NYMVA5Y0EKD+bW1bl7mlGswHETF4SnBAetRNA/DMQN
            d0yI3ZjAzClYkwpHdLf33PnF9j+UWZdi+r2bDvSa5V1tLT1S+vLbIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUWhOOVFtQ2lPcmpvTThY
            TWpvN2VodlBUUkJQTjJDd0xjcFlNcmZBMG44ClpLcEQwSTd5MFJxQVRuS0REU3dS
            cUZ2Uk1DWFd6M0NKdjZFdU5HWHp2blEKLS0tIEltRVlSbm9sUlZFaFdRSTk4V0tK
            Z0cyaXp6VTdDQmVabUp6QnVSVDFMNTAK04E6OjcfWrZw3mVHhayn5TYyhdKluNki
            c7t5eQwHDFjJpLCqi4HZs0epwg4yXwMZ8ZK7ihWnNucdTEMsquhAvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T11:33:53Z"
    mac: ENC[AES256_GCM,data:XyyRXBJNMtlFySB1X80iw0D772a9CtHO8/gtpKAe82La82Ia0gKHsYR2+Y7IQ7/6s4GpU0nfkuLIDcBexk7Qw1HdL/pl6AOjg/7nWYbadOnbHXOgKE1x5GnGSUlFM6eNJrKrTYb26BOfGEZnw53vUTCWWjDgEOt3U7wmXxUWh6U=,iv:tpcXyLqMVMcduEndaepX/K/WIs6Ald6h39RcNJhr11E=,tag:M3kRhZXossT+EKR7v7RERQ==,type:str]
    version: 3.13.3
