apiVersion: v1
kind: Secret
metadata:
    name: stalwart-ldap-bind
    namespace: mail
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:mTjzLHAtVwobFQNXKWpG5npLs1ElERUdBb9Cum9I+g==,iv:rajIJKa3BuJHByEUg0bA3dG6k/iXXaWR4/QqVgvxyjo=,tag:eNMfUToJ/rklY7Be2AOeNQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Y2JHNkNGakpla25UUDBh
            QVlwRXFRaC9DenArODcyL2pRMHZubVFpeGlrCk9RYjJmZStDRW5CdWZUSFNCV0Zz
            YTJIMWhaSDIzTnNjclJOWUhqWUtwTzgKLS0tIElZcTNOdS9WVVAvNXVrTkZrSWow
            Vmlsa3ErODVJOU9ibHdLbS9uZmtiS3MKGNaRYJnTG4IpJC/nbdHuaiq5WvpLQ6nv
            lzS8zY8/HqMi2tQn5JwBt7uxXmzmVlhAqngPeoQyyzLMQQf6LZdrng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZ1FveHdxeDZQQUNtVm83
            ZVh0aUZCSGJPMjVwd3lOUllrUkJYTXUybHd3CjN2OFlHMlI0Yi8yRFphRE5PZXdp
            cm1uNEozME9lY0h1VHJiNHpNcHFHaGMKLS0tIE8vLzA1Y3VQWjFmNDE1YWVrY0pi
            Zm1XSWhidjlJZkwrd0FXMkpIWDU2dTgKaXtJba644dURL880IjqntUsNaRf/HHzE
            D78ItyyI4q3F7X9hJYBo5BifwHVrZ9hawJVowIQVV0p82RZ4drK+WQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T06:18:51Z"
    mac: ENC[AES256_GCM,data:pzfu+yVHNozbKITKanRBcbKmbuu1Hp3YtN+IiIMkc56n73fpFRstM23xTc939EGjlePUvS3ZnNPhYP7NrKM1PvzJMQWPUfCq2kkcYn4ln0oGlm4ka5CSIEbZ94agDwPm/Mxkp0Hj6sqRpH4BAPoyK8ub0LXIzJ3ld/YE0RaDmds=,iv:negJrYYL874Kj+bhBkQHvkREOO4xN2twJDG8o6j0pWU=,tag:nfi57NKgmbUcZtEQMtF0sQ==,type:str]
    version: 3.13.3
