apiVersion: v1
kind: Secret
metadata:
    name: stalwart-admin
    namespace: mail
type: Opaque
stringData:
    recoveryAdmin: ENC[AES256_GCM,data:OsKXytY7a+J1aRmU+ESnhSgwLZFZvhRX19e1zOtGazisawhFUIk=,iv:Fv4juk7W7GsUocHaWI+j4CJ5Cf18lxnIaVIbkqk357E=,tag:qSZg8BxwU8K/JwJREBWzGA==,type:str]
    password: ENC[AES256_GCM,data:+Iy4L0wZVZHeHReIrWdkuw9D5HvB7+WBxi3Y2vyzU/g=,iv:X+QBOI43+KbCzrxN2pK11bxUKp+jwE4kR3HBFPEtIOs=,tag:5G3icaJrFNpCKUK2vTOmdw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyd1NXQjNUVzloenNqVzQr
            Z3dMUzB4Y2NRSFc1N1c1Zkl2WWlUanFvS1N3CjdnNEdESVlkcTFGN1FVSnV5ajB1
            a3lBQ1gzVUFvQkM1QlF1bGZGSlZHUGcKLS0tIEFuSzIrdGpDb1c5dVhrV2hraU1Y
            Z21SV3NONUV2aUF2dERBNFdaWjVZVVEK9ct9qWCr3rgDPWIWbeqoJZZviT5bfgyw
            RNGB7q8cJcmLn8nUG9XKdgngVJ93n0uFjfbONX5rN4OmF/Bf1HAgDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScEdBTkdlRzY5NVlhU1VR
            TFdvdGtzTWlnWGxqZTRpUkl6bFpoL0tCZ2o4CnVWcE52NExDVUx2K0xMYzZPVmFl
            OERvaWNIaDBXd3lDb0lSRC9jME5BMWcKLS0tIGN2YjYyczJUclAxc2RLMTFxM2RN
            Q2RvUEo2dmhzT245ZXB5YStMY3MrNTgKEpow1/HKUWO7gJ0qALaUhIuDyFkCB/1Y
            JgiRN+X31qiklbFKmGBd7QUEy0uD8GG92nVjnHQLEOXu7CB5ESW23w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T23:09:37Z"
    mac: ENC[AES256_GCM,data:qaUnKfbm4bqnKiQLr3hcjo+tW84NeH9cB+rJMcFfqZnVrvRzrYUPmcGjWF/+Y+x8M/wEMNeUsTHeP40/kiPqzWfTFVc29v+E/fWVAt8WYRI2AjeyC+jGBKKdj1v6Z+X0dnjwsmoBf8uoOlevhS+imsk+nYqoH/EgC3ubP31HAQE=,iv:uRvM/KNaigmsZRcLtByrJ1SPBZIrUswbB8N8xru4w2Q=,tag:4Jbv838+f3c2fBD0DEx24Q==,type:str]
    version: 3.13.3
