apiVersion: v1
kind: Secret
metadata:
    name: stalwart-s3-credentials
    namespace: object-storage
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: mail
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: mail
type: Opaque
stringData:
    accessKey: ENC[AES256_GCM,data:7xUMoUHWQ4k=,iv:SdU4OiQVksSYc57ID+yFf15pAFjO+zgZE4pYqgGwL0I=,tag:b1EqEqGaO+A7UkqJIcDMfw==,type:str]
    secretKey: ENC[AES256_GCM,data:PjB7iIQsonyljvQ6uxychEI0yXC0NiSTi9r17FgXDv4DizML6TxOxg==,iv:9tCml5nH7K+v776ltV7JuuvN8aOKSm0z1B6oFQS1k2A=,tag:bL7WJL6fbPJqa2NzshW9Hw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWG9YcGx5d0tTOHlnN0FY
            WnFpZTV0T0RLZ2hIbGVtVGY5L2l3aVQvQlFBCjViVmNyKytjNUdYdTdnMVc2Smpa
            ZEN1VHFIcjNGWkFsc25oSzFZZ1lYUkUKLS0tIHlvNEVrNzBPQjZxNWEyWmNxbmhB
            UE85U2NpWndVczZYOEdnd0g3WG5sWFkKLqJ3hVVOgcg8qfuAYmGZmHltXNet1euo
            CZmAnwJcvrMzzTITm34BOHb12cJGPes39CQFpo4qubEHViSRA+a54w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubXovd1JwMURFNDY4ZWJJ
            ZWtEUmh3N21TWEhKekpxYXkxUlRBNEFBeG5nCm1WS0FjTFVCVUZ6YmczM0R0MVMx
            SythbGJDTXAzUTlad3IrcnM5Yk85YTQKLS0tIEIxSWFCSFFqc2k0dUh3cE53aXF1
            Q2dLOU9JVWZHcUtUYzBqWHRZQWoxTjAKCaM6mqiXl0WSA50IhoTWpSDPxJxRRf7u
            FLkByYPMUPoZ6nv/dX0SiLe2I7FqtSImvGMhy2gXrH89stXY9YJvlw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T22:33:16Z"
    mac: ENC[AES256_GCM,data:/vI7qqOM6nR0SiedE9ml08Gq+Y5xDWVvoIwxcwChqg5A8dSGYQs+MASPTxeZvC0s59ve+q0M5Ww8IUJO/DwGtKLecJ2htsoMVC04k8m+pE0+M2SMbDpkN8qHoQUX/vYP/Ym/sEhC3LZUlQLYgcIM8MBlyGvFpAgozvwp6BSskL4=,iv:tZseIdvvStByFcYLeH9wYZrbpDyrk/j5wetTANMjQQs=,tag:G/cfSLsU+MV4mpui9GgJWA==,type:str]
    version: 3.13.3
