apiVersion: v1
kind: Secret
metadata:
    name: stalwart-admin
    namespace: mail
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:wq9RUJW9a6/3HYFZgOkxvNLSnxSZ4fGY5PzLi8Q6E1o=,iv:j105ykzS7SPXUcPpImXPxiZKRcfsT3rKqhJg+p+IQxU=,tag:R4e0c5fptwSlsVzE1ugUDg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMUJkc01OVy9uc3N2QzE5
            KzdFTjdZbU1NNEd3TzdwNk8zdS90TW1TWVFzClRmeXhPT0VMN1dDT0d1eFJRL2Iv
            b2hVeHFQQmltV2JtM1IyYW1KODc3MlkKLS0tIHh6dmdjNHBHVUFHY25XVEQzU0M4
            ZEk2OFhJY3FqUFdPT0wwdTJvSE9ET3cKWiw0qf+Forw8hsbEYvfBo3EvckWUiyCt
            iYtMdwfLZVFisP40nr9ZWzaAKb88yAcr2sMNgGjkB/LdIYwnhKI5oQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSjJZVTZESzFWRWdTU2Rw
            SHhmemZ4YzBRNzMra2FzV3gveTJ2YVhCTEJRCjJCbHlzbVY2cjVtbGpNbEZNQm5L
            cE9oa2dDc09wSnJEYTBnaERMaFRtSEEKLS0tIFBkUlovYVZ0ZHRPc0RlZ3NXYm9x
            dTJtM1k4REt4Y2h0MUlJYldqOUtBVEUKkmop+3jxAbTYHxfjD2nwIH7/XHwPyG3i
            EXrpKjvkqpxTY+3KTCtwmBE2OFEpJHyxuaNvcscfloMb0Vu0TGVAPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T22:33:16Z"
    mac: ENC[AES256_GCM,data:6s3uLuc3GVHHo7XH/u4W2n3zRYZSb6SsZslpKWo0BnEkPdB9PCeplltmi8w9hPsyZ3uAjpVQ1eTIXhmCDWgvztQgdSo10HnGflqxp27RcBoOGfAF9uMt7DAFeAtZIXGApnNyoJTYDhQ38s5gTcdMbNLW7Oh08GrJ4M7/7drt+H0=,iv:A6aftBn/YCPUbohp32S6veitwtW9ki7WGunZuikSNqc=,tag:ehXA0DDRjbG0SU933xrrUQ==,type:str]
    version: 3.13.3
