apiVersion: v1
kind: Secret
metadata:
    name: stalwart-postgres-backup-credentials
    namespace: mail
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:gHhpj+b7O0bo+kNubt3NT5nguD0=,iv:pmKGJELAvPINOGbE9mSCriTlVoZYKiX6XQqbtlpWWGA=,tag:dAFhLIt+DIaCHgdU+e8DPg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:HRbKuUYQv8BHIy5IHA2OmpylGBDPFYmg7vbLpHekuZcNfrKfqr8I5A==,iv:eax5jCXXs1jn3t1X9TVpza+tnKm04201e1HNfIIOrJc=,tag:t7PBJpDfoomA/XIWZOMJlQ==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:kAcV+XNi3V6tChZnxlokIH8uvXkLkZP2tS4=,iv:LbNS19sPR4c1CCMadwBlax6DEMqJ//xpcuuM0OeA71Y=,tag:2kv2ZOyEam+UuxM1gH1ROA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UnphTmRtVUFHRlFieXZG
            RDRVRjJGOEk5UStvMWtUOVlmdTRyeGdrZ0VJCnNPTHp5YWtWbFBEVUxnb3B0d2tI
            bzhnckVnMEJvRWVURlhMYlJqaGxQMmsKLS0tIG9TYTBvNS9sZmg2OTdUU1A3SlhO
            QjJkWjV5bU5FaUtFMjVrUkloaGgyUGMKf4VHfiVwmX4X4qutjIiS+Ulj2Ad+01hC
            6bAW9HJCpvyERKSTy3TWWJ6KSJXR9765ThOhtqZQsxZ7zK4TFZG4JQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eUFqZHNpTmVoVWJoemxa
            S3BXVW5TWFpDUmdKWUx6MDNsK2lIYlZBNzFzCkpQbk5SZEpYaTBGQkYybmk5OHlh
            cENFa2h2SFhkOURZYnROekUxbXlyeU0KLS0tIHNZQlo3bjVEUyt1R3cxSTR3SjRF
            VnVROWNFU3ZFdVVyNGI5L2M1WlNOWUEK9A8t0fN32TvL/cQO+8ibfrIexCQHEz2T
            VXM56AVbl1VyQUQ2VSvTVWA5AwAn9QIKW37EXwe2rQoRGukjY8STGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T22:33:16Z"
    mac: ENC[AES256_GCM,data:YMvwOHkX+NsfEPiUJKzXRNdRUNWh99pJmIKot+tdMSTsXEBY9uKcTrk0jWB6M3EzrM45lcvVhJIjNL32UmYbW+UMdgkRR2DF/MRDa9p8n+QKHTh118VDUJg+yFoJ+T6539FcVgbSZU1ObKUA0z1XPeyEq/Uw0hgQXhsbeqMAHu8=,iv:ffjqV9DjsiNJxKksoteZ5Smxun57DRt9oYpeOy/jW0U=,tag:FpXJe4UniDu7PuwUzM28Og==,type:str]
    version: 3.13.3
