apiVersion: v1
kind: Secret
metadata:
    name: tempo-values
    namespace: monitoring
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:/b1EeOHeNMXIg7BiFnOMJADXPK/GKkLFTKMIz2jRJryPFyR8KHJtUfE0Anz9cg0yFDHyyjuWIeob43of7M5LB8/mPQuX3xvu8Gj9ahsjB1XLfUdJ6sPJEhHQlY+6lexz1xC4dcwYVsX26aNHhIVKkQVtwJTOSJiKrHx1,iv:W01PyeNyGXdy3X2t1TkE23dF6zdLozs28rj17bBNfIY=,tag:sGgoZ2S6lagm+3mxj4E3+w==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKOHphdGo4bTBTbU9HSTBx
            QXpXcGE3YkgvWkE5QUFOWi91dnBRVkdvUVEwCnB5anI1THJyRVAxeGRhTGxtVm45
            VlhseFhXcmFCaWFUVjBiWWVyQjEydEEKLS0tIFBYSUEzVGxIRU1DcHovTXhGZ0Qy
            YXFmVTgvMEdsQnNHSEVvQW54TmlyZnMKJggcIN/Ot3LlKieBr8SY/T7xbziDmGEw
            yguaoyFGst/nqaOPTociATeR4nNa2vA1tTYrDT1wmplOd4G+beoYFQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdkJyclRpZmRVQlA2OXpa
            U1ViTE1WOUIxTTBVRTRyMTUyenBubVFTMFY4CldXNjhTL0dhMFRsTEpKZmIxcHcr
            MGNDd1JMSnNiZzljbVlzY3BmWFp4OUEKLS0tIGRHR2pmUmhQYzA2TTNhZDA2VENE
            em8zbktDNGdUOG5rOUwwRkxQWUNGYkUKXMDeQNjq8NheX3xq884Otbw2im2cPbeQ
            x++yhUimOrjWTz+bOAQG82grlOosSNuStCelds1A3rSsAabF1jLUxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T07:11:57Z"
    mac: ENC[AES256_GCM,data:k9nDy75IJu4Js20yTCNSJ8YGTI9RriKAiMifA06/m2Auc4XtRCJcZczZ1Nh/N/HYTFPbJE+Wspdk2raQd6cezB/95HXUSchfZJ1A+WjqFt/jkSOUS1QUv5hRW6TtjC9o3td8LZEHOIzLTvVNC8KK/MOTAgzZ/Wf2D+fwfieibtY=,iv:vRHqNIR+mVxaN7GpxMTA9Ntd+sKsCRmKD7T+r0pO5Y8=,tag:lCORQgAkkSfT/TsQhXeQlw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
