apiVersion: v1
kind: Secret
metadata:
    name: tempo-values
    namespace: monitoring
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:kyMMWWRx6EaUxNtgrAw48/cnlJriytq1MRQA95Wq7boucbacb7CIzG1ZUZfNdUt2MHW+COAQ5ekaHUHNk3NCiRzOxEWP7OcbzifBQxkypzTgqVDOZKLJwGL4j5q40lvp/T1VRcklz/QZ1s78WUcVwrKLG5hEkSddoOEvt43zIV1yHykSXbefGmW43+Y4n95FEmQHONGhe4hHtnNI8bzZuwSFmWLHmxN/JIB8dxh+vXV7EHxNlVW8JytoZ581TyrkRIGbR010dDb8r46VMJ2eow==,iv:Z0Lij2LvkPN7OTWDnKOUrKVnYiIsMAtfHVFkMsQJZMg=,tag:Q805faL8feLgUU3f5bXrOQ==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdUhlVldCZlMzRDlvdGNV
            dFZjRzRUODVkL2dXUitCTjBMSTEzM1ZYSWt3CnVqdVdORXlPR1N0WS9FSjlhSmhj
            aTRtNi9ObEVnNFRhNGZ6WEZEQTVGb1kKLS0tIG1USGkxWVQ5YTlhWWZEbVdkWmJq
            RVpIWXBHTUxGc1c1eUlBVFp4ZW5HdkEKU8KngnodNAUKSpWQ3IdXRATfQkeQlF9Y
            uaMkUL87zfYmy8WdVOdCqppl1oyNEoUEdDgRHq1p+HF3NAZz2qTu8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T04:03:33Z"
    mac: ENC[AES256_GCM,data:DnkJWGIlxbSVgRoRw344XJVmeCwT3KHUm76ZXuI8FZ9pBvdVZIbGHs7RF9gR4cCIFWUB6UB+HEaODTefYWNdsdKxLjMHYWWgY6aVaXcbXbX4UpKRMRbBEhbNldIokeQgDEt+HyzVv5/0sZKWIBi/GAqqvg/Mi89IVmaoz3B03+E=,iv:/Hk7Q9RAv9mXt1nMCZO953Uw2bStEe2dlb+KPcQ982A=,tag:KKRPO38tf0tx/pSy2bvNQA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
