apiVersion: v1
kind: Secret
metadata:
    name: tf-game-ghcr-pull
    namespace: tf-game
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:2NQxTIAM7SRtVN3Oap3BtE5LLGj5SkJoNfa1UsOe7OJpSzzJxOcEazLyPPqLFMiGTS3Lq6RKvotqe4K8X6yeXgV9UE8zOu2vc+1sYfcPj2ddpBTZ9lzOhTIBkv8hTO7U5PWFmHOEHYOA0NYIzh3h590aofizqFKZcV0x0PO8NeR3VwAeET+zhDWIqMFR6ZU7pFuEFKvFnkvAUex9dAHGtSA8xjaKwljTa54byt2ozA86,iv:Ckw+WFXE1ZlN+7/yPxHrPrAqSwaXeKFgx+TBAat9FNs=,tag:r4UBLcQXasOYoIt8znXjXA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVmhHUmVCWkR0UGlLYnN3
            L1g2TEhaZGV3MkRNK0JwSHZ3WmdrTktoVmp3CkMzaDZxK0NpaTV4d0NQL3ZFU2lu
            NkRCTzBYdHZFRlRvWUtNNVpTN0RJeFkKLS0tIGd2N0oxcWlyMjExaDE1Z0I5eTAr
            elNwVlBxdXJuZlI2Sm1sKzRuWTYrVFkKSnEIiKYHwim4FhmIIg4npA4JGFMcuHMV
            q2li+ihKBF6yokptdqUU8oyOPiDSC9pqJ2KS7Lmp91/Gr+SCenmqnw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiN3pHY2lIQktXdVNrME1S
            WlIrZTV6MkNoU0VrY2E2RFVPQVdDN0x2WFZNClBiclh3VllsVGhSOVBNU3FON09a
            Z3BoRWFMcjUxdHpKQlQvbWZsMVNHMjAKLS0tIFlLeno5R3JBVGY0eTB5WlZHcHRS
            cDNabWJlUWpRTnlTdkpLaldDelVYcHMKwJZuwHD5R0TkMOa/QyY2TU38cxwh2CYC
            OH4NkOz6JnHTnyc/zZ044UOu7qloadnwGHUmZQu+GSs7G2/FGfAFjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T20:40:07Z"
    mac: ENC[AES256_GCM,data:S/3/c21NuWZo3N5Jsm+4inaapPy4e7YqN+2heUK0XqBChEdamTbtmLAyXfTcMtm3u3UqlzgnOZ/P9BEnBY3E7vIlR9v7p0i8/O3A2EyEX/NiqSSaueFi49BP6x6U1Jj0d++1Wl6BJin7cuKCJ0cXlZobxjOGk6KEnxYcc8b1EMA=,iv:OSRp8GmglN6JeeMMWcfGflJo+OeOoWeU6bdH23CDEfU=,tag:qCq4QH2qcrXckXCkThcvKQ==,type:str]
    version: 3.13.3
