apiVersion: v1
kind: Secret
metadata:
    name: tf-game-ghcr-pull
    namespace: tf-game
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:T1DNKuy8T2W1ZMIItKflIv0DQGqhJy91Xu8lG8mWPD1/02j46eBz3cOccpS3Towh8XlktDzSq/Mt8ZKpPuhP9SzJSvei8enA33aTbytwTuTDeKeKp0XQOhoZk8bnb5ZZPjf7jkY1AekBBk0vOA==,iv:3evhoIT9Tm78rWAT+mlxNxLmDFBOY/DPWn+itB8WZjQ=,tag:Ju+2BBSfAYYw65K4e2gWNA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQVNNM3VIdHdKT3d1bHFV
            UGZYNnhJT1l6S1BmbXhDUHJOamsrbkNzVjJvCjY2dHgyUVhBWVhCVXU1VW9OSTNV
            OHJYRkNpaE1UbkpuaUlObDRXTzRZcE0KLS0tIGU3bk8yQ0J2eE5RQXZpMENIbHYz
            dXhFVVM1MUovUGk4U3d3cHFCYWhObWMKdFYyfj+VLR+X2rWdXRyt+Bb8jbFuuLH/
            AocY3Zs/HRybdZa9so6RZUK/+XYi4PhWZD1FsqiRLuihsIGnKnJagw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSlVCb0MwSS9rYlM2eUdv
            aTVFejVFaDhZKzJyVlVMbHlTQVB5bGxzeDN3CnFON2pVbUZhRHVHQjVWQ2wxaHpT
            dmZGSTNscERuTG1XbG94ckhZbFhITVUKLS0tIHVWT3IrYVIwMk15TDlhaTZJZGtR
            K0hlTjh1R0thakx6blpIL1BHWmJPSUEKxDc/O3BDodhhFlBpIdUtq3OySf14xjrK
            iEOrcL8UUHIN8Zyc+XV3vdaBK7xXRKqx2HRzngJZPrix+3y/hsU9hQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T21:03:01Z"
    mac: ENC[AES256_GCM,data:9adDXxvCc/g6hJk5XG1i1TYb6/WPjRj4oiFAPudd/lU9J982e9DbTX+zlCQ9L1yRWuFpb1eBv8Qyq16xPGBVuL5d0zEuXk+ElJ3ezcMys2Um/4yojHZZ1w9jatx51s0WUP1SYcsLO+3qjBXbhgnUCpDtI8nHtNn+HU6T15bDaSk=,iv:ooLaDSkbR8rpF7dIMz4t2ooMGpZCTbWLPWcI3ikCD9E=,tag:SSqVtft0msM8IfJUQqDfJw==,type:str]
    version: 3.13.3
