apiVersion: v1
kind: Secret
metadata:
    name: twofauth
    namespace: twofauth
type: Opaque
stringData:
    app_key: ENC[AES256_GCM,data:6BYTDhQCtpOUAd9g6yqUj9IRnUqdHvV6E3kXlGDpVRs=,iv:leYKo9aY8zt4kMvV7Ln/eetYrjBeWyEW/gbGUk6O5YY=,tag:5a9dfMnrWmVmY/vTdOUNOQ==,type:str]
sops:
    age:
        - recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1aEpaM3pjZi92NE8ycWpa
            V3lBTUUvR3pXdFU3UGx3MWVoaWtQWnJlM2djCkZjdzNicGRJRU93RDAzYnE5YW83
            V3JPalFaRTBldnU2OGpGMTcvWDZkTUUKLS0tIGxkWDdLVG9URlAwclVLb3Z4a2hQ
            amhrcHdOdHA4OU9xTkRrVG5Ha3krbVkKiPmRrKZc5NVlIWIT35TcXtpqT21ipVOk
            T9PDu5mllQL0wdZrypg6yjxARKSbbTvpDhNd0ZdqCjbGqvEtrBiB7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T11:26:07Z"
    mac: ENC[AES256_GCM,data:vWrxb5wUvTa0BRo8OA/fRevPFpWNN+/gkMAoBRKDJC44aEJRIUbvYdMCbqCEIxeXuPUe8SzhGDTg/DvBlWmpHfXIhD7TWakcrhtahbEpoNs5ZYZfgCeyuvFd8OpWT6be7BCaZ7wOlkN/CivLD/Yp7AvejdENvitHJfeWvD1Kxe4=,iv:u5J3kHYAjkE3UBtoaXY8gmUCWXr+6g6SO6KUEcJpOBs=,tag:/C3NqGlD612E+ZfgJqQAuA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
