apiVersion: v1
kind: Secret
metadata:
    name: valheim-credentials
    namespace: valheim
stringData:
    #ENC[AES256_GCM,data:t9SKxjAnhr2gh9t38PQ2fSzcgNERVLAAtEvL8rHVaCpen/Fo3sZpXnW58BY+Iv1GqkuA9Mzi4OR508wWqmptsWBoUi9TiO0=,iv:SKGhkv5bQiNqdg9j16e5Tma/nBLMGEnTbkMgtS85TyM=,tag:Xp+j9Y4/BBmGDV1OWfYuiA==,type:comment]
    #ENC[AES256_GCM,data:BkPX2G2k3B+sbg5IBqLERfd41JKmwTcKn4DjgzH7oWCSiRSw4LtHeRAhuFerUx0KFbDOFCJE,iv:MgWiORo5b7QgkBzbV/46mqmDYiQ4eRB9fwC8f5Uz1zE=,tag:BcyCVyoBHuP7JXBmYbxReA==,type:comment]
    server_pass: ENC[AES256_GCM,data:fhfIsk9V2tBY8nI3Uq22X4M=,iv:GceB10ntx94dx8FDrK4oWXl/oJqU3q5kPiEjf7Ww3jo=,tag:YGF4xHhhL/MSQmHDiEKn4w==,type:str]
    #ENC[AES256_GCM,data:eepFzNwc5OYr1VeTotp81p3NFaiojgiFeTHeKEkJUgyi6ZekyTjJGmekrP7K0EP2LKkWj1HaPz5yVzi10/poqNbEqq7F/Q==,iv:kUKHKAQQQ/gQYFh/RNmjR4AttQq85vOkoRTxD1wc2jM=,tag:yA/SvQAGzEc/7eCorBN7yA==,type:comment]
    #ENC[AES256_GCM,data:yOsL/e2FfSDxwlF+smu7iviVJs60GQQOQ7EE2y891M1fnlE=,iv:BMXIGdyBrSQl8tDM2fMuxbW/Xu6ebzHy8z+SkWtM/c4=,tag:uceEVY0wFoRuUIAaybBMZw==,type:comment]
    public_host: ENC[AES256_GCM,data:7Yk7ja1TKrHTFTbaqZmUnWJ0cGV85v3yaNL7iQ==,iv:dneokFQ73iuBHfFYfntY45vP3aBfTlycgDz71XoXEWE=,tag:x9MONVriLt/GpZLSQEo5Hg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZHY4eTlrZFVtY01oT2hZ
            QlNIMmN1SGJMejNJQU45Z0ppd3psbTIzWHhFCnY1Ykd5NkI1UlFZY2ZYekpzaU5z
            T3ZaVzNxeWFJVFNtSDNiTG5scHY5QzQKLS0tIHozNHArZ2RrdENrQ3BwQUtEcFpQ
            a2FSZCtEUDJnVzZ2WmxGYkwrY0kvcXcKUUhLDFFZe2zeQ3zh0nn73yqn1elmwfg9
            i/yRV5jtQmgxvqUPJ/xE4ZcsepqMkZQXcL37JljDqcBiliMkCS5fSQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6R2pjWEdkc1IwQVN6K1dm
            eXVDY0tqRUZpRFp6Y01WNlRSYy9ZU1ZWM1ZrCnloNVlLdFR0U3ZEVlVFVlBpSW4w
            TDlwY3JRNGF0bDdkd2x6T204cHUrL0kKLS0tIER4dFcvY0hwTDdack83UVdYb1NF
            QTM0ZTJhNGw0TG1Qc0V4OUJHTmpVR3cKL0a3Zltjbz4brBZF4PYtzLWI2c8dSaUX
            oa75rs2pxr+ju+CuqNHv4UW8GwfN1CHwa0dxV9vya56I69vGW3H5JA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T20:23:25Z"
    mac: ENC[AES256_GCM,data:MfP2mAm539ZW4s3nhZcDEYJh/bN5HDqTosvGaBBqrDcpl2UloxqNq+L/qwhPNT9zeUOw8YIJVI2B+uilcWVHTzU6xxWWFSmIXxOtCLeKyY0hOUzw69+TzOWwKdiYEUMuGuuTVZMGEn7B9pK18FCmOENcPATlL/t7wm8Ub8p7Hpo=,iv:if3nRoM/KUjgFLoh5DjacVTjobhQC5JxlYRZKAofLGs=,tag:GLTpzbPDfzf/V25/6SsDCA==,type:str]
    version: 3.13.3
