apiVersion: v1
kind: Secret
metadata:
    name: valheim-backup-credentials
    namespace: valheim
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: backrest
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:pXYjjvg4wiaROT8cO/QTELeDKNHB06oIRvySrVqyaDw2YBAfXN/0mesGPaQ=,iv:mEoagFztYPTEVgqteJu29Ri+tj3rWdLLssDj/z8sY34=,tag:LebpJjcCaTFFRwYeUFFOPQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:L0b+YxVtGSJaHQCU8oWGm6zIPhw0hOWXSYP7zGpSKlbRlqWKNjD9YQKX7A==,iv:aWP9FZb++qN9ralKumcJjJ1/mf2Jlp2ul7JlwpMvwxM=,tag:9u57IRYu4j7rL9+ejyYMdQ==,type:str]
    #ENC[AES256_GCM,data:jDF7XqF2G2tC0oxQI969QlHkjssunZkjQ7arPemePfifLUZEuAz+41byjfnsa/50HyNdwairxCaLXBtCECAQK7H3bu4E9Q==,iv:d8NZaejPXqXWkpATcIFYva3WycXOwzs/NBW/i+fl818=,tag:Jr1NQ3+zW6mAhrvaJzZpug==,type:comment]
    #ENC[AES256_GCM,data:E7EqiOCHgmRxOEomB07nZk6OOvf1BuADCmyhuYokSi3n7XGxZqT9Hh2I/gbeFiNi96hpkiV5s+/d6O4=,iv:iy9GYCox3kSc7vzULg2YoYgNJeFBh4NESvAkTKt9hC4=,tag:APs2Gb2UYW90+WNod+31uA==,type:comment]
    #ENC[AES256_GCM,data:/NBCyB5uiFaE7j7azMzISLQ1s8EPLOXHkCLps8kRo87c8vZDo0UtpHoMUbf0fgPIAMp1n+L0TM5fUR+AWs7suko7,iv:ElMU+TYaPZSzKk42MkpcrgQ2HkEAMNX7cto7dDVUyyU=,tag:yqlbXw6ZP5N5u92RzXssew==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Q6Ozx04DoIjab80wMtAccypiTLw=,iv:/72HzfroROKnJiExo7kgPCCT8gEhUmfb31b10UgB+iU=,tag:OH6UAUvD9sUCJV+2+Uy7Sw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:oO3CFBkzbw8kQys5CVL1kWBbMypKSpzRFCACyfeS4t7mc4x9LA73VA==,iv:KVN5aAKNi3r0t5u85GSwiUfuFH6eP0ShZdzPK11flNM=,tag:4O4CWU3te4nJioGY1/Y01Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRkVvYmIwZGcyWTZ3cWZH
            UExLUXNLN21Fa1BGNWFkYmJ1VjJ4QVg1UDBBCjJ6VmxwWVZaUWpodXpBQzN4Q1hN
            Zkh5VHlUN1RKRFR3aGpxbWxBR2piMlkKLS0tIGhjS0k0NW1kbnBEeDhabWtROUpY
            aEpSL1dGVnB3L1RZWmhsTkRvVTlMVG8KrsFuyMwvTG0057d8z8vAuDl6anfz3J32
            aHJZs+r6F9nJ2G2tBIx5qI0KQAHPtAJWFf7ezb7qpo/F+WbTU05AcA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qms8fkrw8cn2pt0ekevqpx3ze86tg4axxv4mv3m72qs8s785h4esyhexdg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWT1BBQjNQaWVBQXBsREZr
            MHcwZzdUc2NyS2l1MHpjU2VNMUh6WmxLL2xNCmFuNDZKWm8zNGdCUlJCSzZnUGNu
            Zi8zbCt3K3JqM0xYMmR1dGZobjhrL3MKLS0tIEpNNkxjelVCU01zVGtMdUpjaXJ2
            ZTJVTHBtcHpNbXc2UzEycWljUW5pRHMKp1ZDYCTCBRJhDD8Ok7/DVAgpZie+rh4I
            xoH1EwKU8AVhDh3ngwbGSK6foim7bOspRoNZCGUtlbI16jpXY9/mAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158nt0t2syxf6nsehea43csvym5tcvyxwskhp5jrven3zjpu86acs63rzgy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T20:23:25Z"
    mac: ENC[AES256_GCM,data:TD1HUpMkqdmqn6sf1V6UCFZMiEiDevHn0NlxY5Jy+2F1XBYuqAXS+r3cCiqqwFJ+H0817XnIVaYpO3PlBUFLivR8mmCrG2y9GlC4dWsXTxskYtnpPQnJNTG2dZst5WyfuJ92lgB4fAWleGWn7mk5kpiZWMRdw9Id+DbCe7aEH1E=,iv:d1Xb5oEHpzrd74AVXdpIdZU01XVn8cgpnjLXW2/TDDQ=,tag:d1K//5x8v75F5QZ+fr+yvw==,type:str]
    version: 3.13.3
